### ISSUE TITLE
missing tag for 0.11.11

### ISSUE THREAD

**Issue by jab** [pallets/werkzeug#1002]
I noticed 0.11.11 was released to PyPI but is not showing up under https://github.com/pallets/werkzeug/releases - just thought I'd open this in case someone forgot to push the tag to github.

For anyone else interested, 0.11.11 release notes are here:
https://github.com/pallets/werkzeug/blob/d5396ed/CHANGES#L45-L57

**Comment by untitaker** [comment]
Should be fixed now, thanks!
