### ISSUE TITLE
useragents: Detecting Android crosswalk as ChromeOS

### ISSUE THREAD

**Issue by longfin** [pallets/werkzeug#1024]
## Environment
- OS: macOS (10.12)
- Python: 2.7.10
- Werkzeug: 0.11.11
- Flask: 0.10.1
## How to reproduce
- Check `request.user_agents.platform` when using [Crosswalk](https://crosswalk-project.org/) webview on android.
  - its `User-Agent` is `Mozilla/5.0 (Linux; Android 4.4.4; Google Nexus 7 2013 - 4.4.4 - API 19 - 1200x1920 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Crosswalk/21.51.546.7 Safari/537.36`
## Expected result
- `android`
## Actual result
- `chromeos`

**Comment by alexpantyukhin** [comment]
I believe the problem is that the `UserAgentParser` checks the platform not as separated word. https://github.com/pallets/werkzeug/blob/master/werkzeug/useragents.py#L81 .
