### ISSUE TITLE
Content-Length header should not be sent on 204 responses

### ISSUE THREAD

**Issue by jakul** [pallets/werkzeug#1025]
https://tools.ietf.org/html/rfc7230#section-3.3.2 states this:

```
A server MUST NOT send a Content-Length header field in any response
   with a status code of 1xx (Informational) or 204 (No Content).  A
   server MUST NOT send a Content-Length header field in any 2xx
   (Successful) response to a CONNECT request (Section 4.3.6 of
   [RFC7231]).
```

Werkzeug does send the content-length header for 1XX and 204 responses, and has done [since 2007](https://github.com/jakul/werkzeug/commit/85e43c12fd74375779d23c117594ea325b944d8c#diff-67ab56f47231589fb9c088d78b68854dR435).

**Comment by ThiefMaster** [comment]
098a689e8cbe39540ba361dba122069ba6200bd6

**Comment by zedrdave** [comment]
FYI (and for people desperately googling their problem): the unwanted Content-Length header currently makes Mac OS Safari throw a network error and fail, when a 204 is returned (e.g by calling a DELETE on a REST API).
