### ISSUE TITLE
Rename the console app to something more distinct.

### ISSUE THREAD

**Issue by romeojulietthotel** [pallets/werkzeug#1029]
I was working away on an app I named console and at some point as I progressed I discovered that werkzeug uses that name already. Maybe a better name would be /wzconsole or something like that since console is generic and common.

**Comment by untitaker** [comment]
We don't register a path called `console`. We only intercept requests if `?__debugger__=true` is part of the query string.

**Comment by romeojulietthotel** [comment]
Once I renamed my app the problem went away so my experience disagrees with your assertion.

**Comment by untitaker** [comment]
Ah, you're talking about modules, not request paths. In that case please provide a minimal reproducible example, as my *knowledge* says that Werkzeug's modules namespaced in the `werkzeug` package should not interfere with your app at all.

**Comment by romeojulietthotel** [comment]
I may have the terminology wrong. How I ran into this was I tried `localhost:5000/console` expecting to see a login page since my /console was for auth users only.  Note that there is no `?__debugger__=true`

**Comment by untitaker** [comment]
Sorry, I forgot we had that. You can do this to change this path:

    app.wsgi_app = werkzeug.debug.DebuggedApplication(app.wsgi_app, console_path="/my_custom_console_path")

Then you need to set `use_debugger=False` on your invocation of `app.run`, because you just set up the debugger yourself.

Alternatively you can `use_evalex=False` on `app.run`, but that will disable the entire debugger and only show plain tracebacks.

In principle we could set any reasonably unique name for the default path, at the same time it needs to be easily memorizable (since it's not linked anywhere).

**Comment by davidism** [comment]
Is this already documented? I don't think any code should change here.

**Comment by untitaker** [comment]
All parts of it are documented, i.e. `DebuggedApplication`, its params and `app.wsgi_app`. This usage pattern isn't. However, we could hint at wrapping the Flask app with `DebuggedApplication` when the user needs to pass params to it.

**Comment by davidism** [comment]
Re-file against Flask docs?

**Comment by untitaker** [comment]
Yup.

**Comment by romeojulietthotel** [comment]
Do I need to do something with this? File this against Flask docs? Your reply's not clear to me.

**Comment by untitaker** [comment]
I think Flask docs could be improved to document that DebuggedApplication could be set up explicitly. So yeah, I'd refile against Flask.
