### ISSUE TITLE
HTML text can vanish in the Werkzeug interactive debugger

### ISSUE THREAD

**Issue by alexwlchan** [pallets/werkzeug#1031]
(I feel like I might have raised this bug before, but I can’t find it if I have.)

If you’re using the interactive debugger and you type a command includes something that looks like an HTML tag, it gets treated as literal HTML text. This causes it to disappear once you’ve finished the command, which makes for an inconsistent history.

Here’s a simple repro:

![screen shot 2016-11-07 at 07 25 38](https://cloud.githubusercontent.com/assets/301220/20049525/6b86fc32-a4bb-11e6-984b-c713b4796d08.png)

The HTML tag should continue to be visible after executing your command.

Python/Werkzeug versions, although I know I’ve seen this on older versions too:

```console
$ python --version
Python 3.5.0

$ pip freeze | grep Werkzeug
Werkzeug==0.11.10
```

**Comment by alexwlchan** [comment]
If anybody fancies having a crack at this, I suspect the fix needs to go into https://github.com/pallets/werkzeug/blob/master/werkzeug/debug/shared/debugger.js

I made a similar change in #994, but my JavaScript-fu is insufficient to fix this bug. Although it’s possible to swap out the `&lt;` and `&gt;` entities in the printed text fairly easily, doing so will also corrupt the history, so pressing up arrow shows you the last command was `print('&lt;foo&gt;')`.

I suspect the answer is to go after the `appendTo(consoleNode);` and intercept whatever gets inserted there, but I haven’t been able to do so successfully.

**Comment by untitaker** [comment]
Confirmed.

**Comment by untitaker** [comment]
No I think this needs to be fixed serverside. The entire HTML output for the console is generated serverside, JS needs to trust serverside HTML.

**Comment by alexwlchan** [comment]
Ah, I saw the `<div class="output">[console ready]</div>` and assumed the display of the console was being handled client-side.

**Comment by alexpantyukhin** [comment]
I have made a server side fix for it. It seems to be working.

**Comment by untitaker** [comment]
@alexwlchan Can you confirm that #1032 works for you? It appears to fix the case I've been testing with, but maybe I've missed something.

**Comment by untitaker** [comment]
Also @alexpantyukhin thanks for getting on this!

**Comment by alexpantyukhin** [comment]
@untitaker You are welcome!

**Comment by alexwlchan** [comment]
Sorry for the delay in looking at this, the last few days have been tricky.

Fix works for me! Notes on my test setup below for posterity.

(Note to self: it really helps if you check out the branch the fix is on, not some random other branch.)

---

I assume there’s a way to access the Werkzeug debugger as a standalone module, but I don’t know how to do it; I always load it through Flask. So I spun up a fresh virtualenv, installed the patched Werkzeug version and Flask, then ran a tiny program that drops straight into the interactive debugger.

Then try running a few simple commands: `print('<foo>')`, `print('foo&bar')`, `print(1<2 and 3>4)`, check the output is as expected.

<details>
<summary>Environment setup</summary>

```console
$ python --version
Python 3.5.0
$ pip freeze
click==6.6
Flask==0.11.1
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
-e git+git@github.com:alexpantyukhin/werkzeug.git@f34b02bd37353a562a0a2fdc0cacfd60914f36c2#egg=Werkzeug-fix_debugger_console
wheel==0.24.0
```

</details>

<details>
<summary>Test program</summary>

```python
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from flask import Flask

app = Flask(__name__)

@app.route('/')
def index():
    assert False

app.run(debug=True)
```

</summary>

**Comment by untitaker** [comment]
I'm leaving this in master since the bugfix is neither security critical, nor is it visible in production (since the debugger is not in production), nor is this something that breaks normal debugger usage.
