### ISSUE TITLE
debug/shared folder has disappeared from conda builds between 0.11.8 and 0.11.9

### ISSUE THREAD

**Issue by rs2** [pallets/werkzeug#1040]
Compare https://repo.continuum.io/pkgs/free/win-32/werkzeug-0.11.8-py35_0.tar.bz2
to https://repo.continuum.io/pkgs/free/win-32/werkzeug-0.11.9-py35_0.tar.bz2

The side effect: unable to debug `flask` apps using 0.11.9 or newer.

**Comment by davidism** [comment]
You should report this to Conda, we don't manage those packages.

**Comment by rs2** [comment]
@davidism Thank you, and I know; I should have mentioned that all pypi packages _do_ have the `debug/shared` folder. All `conda` was supposed to do was to use `conda convert` to repackage it as a `bz2` tarball. Something went wrong on their end.
