### ISSUE TITLE
Url parameters are not converted in the order from the path

### ISSUE THREAD

**Issue by tshelburne** [pallets/werkzeug#1044]
I have a path of the form "/users/<user:user>/projects/<project:project>" which uses two custom converters, `UserConverter` and `ProjectConverter`. Internally, these load the user and project from the database, and `raise UserNotFound` or `raise ProjectNotFound` when the record is missing.

For my path above, if neither the user nor the project exist, I get a "404: Project not found" message. After digging, this is because the values are backed by a dictionary, and the values are converted in alphabetical order. If I rename my parameters in the following way, I received the expected "404: User not found" message: "/users/<user:a>/projects/<project:b>".

When I first started working on this, I looked for a better option since raising an error felt like the wrong approach, and didn't see one in the Flask / Werkzeug suggestions. That said, regardless of whether that is best practice, I think these converters should be executed in the order defined by the path, from left to right. Anyone who has named their parameters alphabetically in order to achieve this will be unaffected. I would feel differently if these functions were required to be purely functional, but this is Python and those assumptions can't be made / enforced.

**Comment by aenglander** [comment]
Starting work on this. I plan to finish during sprints.

**Comment by aenglander** [comment]
This is only an issue for Python versions before Python 3.6. As it would require sorting the dictionary after matching, which is moderately expensive, it was decided that we would not implement the support in older Python versions. If you need the functionality before Python 3.6, you can utilize the alphabetized attributes workaround specified above. Otherwise, you can upgrade to Python 3.6+.

**Comment by tshelburne** [comment]
Thanks for the update! I forgot this was even a thing.
