### ISSUE TITLE
How to use redis-cluster for caching?

### ISSUE THREAD

**Issue by ioshger0125** [pallets/werkzeug#1045]
Werkzeug used redis-py to connect to redis, but it seems not support redis-cluster while the redis-py-cluster supported.
Can you tell me how I can use redis-py-cluster or pyredis for caching with redis-cluster?
Thank you very much!

**Comment by wong2** [comment]
I don't think `Werkzeug` has anything to do with redis, are you looking for another repo?

**Comment by wong2** [comment]
[RedisCache](https://github.com/pallets/werkzeug/blob/master/werkzeug/contrib/cache.py#L514) is  a subclass of `BaseCache`, you can create your own caching class by subclassing `BaseCache` too
