### ISSUE TITLE
Headers.__delitem__ signature incompatible with ImmutableHeadersMixin.__delitem__

### ISSUE THREAD

**Issue by ambv** [pallets/werkzeug#1051]
[Mypy](https://github.com/python/mypy) recently introduced stricter checks for function signature compatibility (https://github.com/python/mypy/pull/2521). Since `werkzeug` is included in the typeshed library with typing stubs, it found an issue with the signatures of `__delitem__()` in datastructure.py. Consider:
```py3
class Headers(Mapping):
  def __delitem__(self, key, _index_operation=True): ...
```
vs.
```py3
class ImmutableHeadersMixin(object):
  def __delitem__(self, key): ...

class EnvironHeaders(ImmutableHeadersMixin, Headers): ...
```

Basically, it's invalid to replace `__delitem__()` accepting an optional kwarg with an implementation that doesn't.

**Comment by untitaker** [comment]
@ambv Am I correct that changing the signature of `ImmutableHeadersMixin.__delitem__` to accept arbitrary args would work?

**Comment by ambv** [comment]
Yes, that would work. `__delitem__()` in the *immutable* mixin is supposed to be a no-op so it's reasonable for it to accept (and ignore) arbitrary arguments.

To rephrase the problem for future reference:
* When you're using `Headers` directly, you can pass `_index_operation=True` to `__delitem__()`. Remember, the "user" of this functionality might be the class itself.
* `EnvironHeaders` is a subclass of `Headers` so it should accept `_index_operation=True`, too, but it doesn't because `ImmutableHeadersMixin` comes in first in the MRO.

**Comment by srittau** [comment]
It sounds to me that the correct fix would be to rename `Headers.__delitem__` and add a new `__delitem__` implementation that just calls the renamed method with default arguments.

**Comment by davidism** [comment]
Going with the simple solution by just adding `**kwargs` to `ImmutableHeadersMixin.__delitem__`.
