### ISSUE TITLE
Wrong order of base classes in wrappers.Response

### ISSUE THREAD

**Issue by ambv** [pallets/werkzeug#1052]
[Mypy](https://github.com/python/mypy) recently introduced stricter checks for function signature compatibility (https://github.com/python/mypy/pull/2521). Since `werkzeug` is included in the typeshed library with typing stubs, it found an issue with the order of Response base classes in wrappers.py. Consider:
```py3
class BaseResponse(object):
  def freeze(self): ...

class ETagResponseMixin(object):
  def freeze(self, no_etag=False): ...

class Response(BaseResponse, ETagResponseMixin, ResponseStreamMixin,
               CommonResponseDescriptorsMixin,
               WWWAuthenticateMixin):
  ...
```

Note that with this MRO of Response, the mixin's implementation of `freeze()` will never be used.

**Comment by edk0** [comment]
I had a quick look at typeshed and it seems it still lies about types in order to satisfy mypy. But the subclass order here is intended, and the inaccessibility of `ETagResponseMixin.freeze` via `Response` explicitly referred to in the documentation, so I don't think it's worth changing if the only problem it causes is upsetting mypy.

**Comment by amjltc295** [comment]
@edk0 Could you provide a bit more details about the intended subclass order here?
Why is the BaseResponse put first? Using base class as a mixin seems a bit confusing to me.
```
>>> Response.mro()
[<class 'werkzeug.wrappers.Response'>, <class 'werkzeug.wrappers.BaseResponse'>, <class 'werkzeug.wrappers.ETagResponseMixin'>, <class 'werkzeug.wrappers.ResponseStreamMixin'>, <class 'werkzeug.wrappers.CommonResponseDescriptorsMixin'>, <class 'werkzeug.wrappers.WWWAuthenticateMixin'>, <class 'object'>]
```

**Comment by edk0** [comment]
I believe the ordering is done like this so that ETag methods are accessible by default but without implicitly forcing ETag-ness on every `Response`.
