### ISSUE TITLE
`RedisCache.clear()` should not invoke `Redis_client.keys`

### ISSUE THREAD

**Issue by gdmello** [pallets/werkzeug#1069]
**Issue:**
`werkzeug.contrib.cache.RedisCache.clear()` invokes `Redis_client.keys(..)`
The `KEYS` command is not [recommended](https://redis.io/commands/keys) for production usage.

Python: 2.7.6
Werkzeug: Latest version

**Proposal:**
Update the `clear` method to use the recommended 'SCAN' command of redis.

If there is agreement on this feature - I can attempt a patch.

**Comment by lepture** [comment]
close it via https://github.com/pallets/werkzeug/issues/1249
