### ISSUE TITLE
dispaly pin code in console not required the `WERKZEUG_RUN_MAIN` env

### ISSUE THREAD

**Issue by dongweiming** [pallets/werkzeug#1073]
I use DebuggedApplication for my web server's interactive debugger. but i can't see the Debugger PIN code in console, because i'm not set the env `WERKZEUG_RUN_MAIN='true'`, It is implicit.

This make a little bit confused for me, I believe that to make the developers use a non-flask framework confused too. so i hope no longer verify [`WERKZEUG_RUN_MAIN == 'true'`](https://github.com/pallets/werkzeug/blob/master/werkzeug/debug/__init__.py#L251)

**Comment by davidism** [comment]
When the pin is requested, the middleware should be printing the pin to the terminal, and that's not dependent on that reloader env var. While you won't see the pin when starting the server, you should see it when you need it.
