### ISSUE TITLE
Change generate_password_hash to use stronger default than SHA-1

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1075]
I'm still not entirely clear if `pbkdf2:sha1` is vulnerable to the sha1 collision issue, but we should look into this. Changing the default to `pbkdf2:sha256` is probably fine regardless.

**Comment by davidism** [comment]
After some discussion, concluding that SHA-1 as used in PBKDF2 is not vulnerable now, nor is it likely to be any time soon. http://chat.stackoverflow.com/transcript/message/35836840#35836840

**Comment by untitaker** [comment]
I'm not convinced that one couldn't fabricate real data (given that, if you
found a collision with two input strings, you can append arbitrary data and
still have a collision) using this. I propose keeping this open either way,
even if no action is required for the next few years.
