### ISSUE TITLE
Fully deprecate werkzeug.script

### ISSUE THREAD

**Issue by untitaker** [pallets/werkzeug#1079]
werkzeug.script has been deprecated since 2011 and 0.12 now shows huge warnings, I think it's time to remove it.

**Comment by aaossa** [comment]
Can I take this? It looks like some of the example still use ‘from werkzeug import script‘. What should be use instead?

**Comment by untitaker** [comment]
Click is recommended.

**Comment by aaossa** [comment]
Where should I add it to requirements?

**Comment by ThiefMaster** [comment]
No, this would be about removing the module and - if it's referenced in the docs - mention `click` there instead. There is no need/reason to make click a hard requirement of werkzeug.

**Comment by untitaker** [comment]
I think Antonio is talking about the examples folder in the Werkzeug directory.
Since that one doesn't have a setup.py for each example, I think it's fine to
just not define the dependency anywhere. Perhaps a short notice in
examples/README would suffice.

**Comment by aaossa** [comment]
Yes, I'm sorry, I was talking about the examples, I didn't mention it. I'll work on this :grin:

**Comment by aaossa** [comment]
@untitaker I think this one can be closed now :ok_hand:
