### ISSUE TITLE
Set up appveyor

### ISSUE THREAD

**Issue by untitaker** [pallets/werkzeug#1082]
There have been a few bugs such as #1081 which could've been caught that way. Also currently the testsuite uses POSIX-specific syscalls.

**Comment by davidism** [comment]
This is set up in #1399, but for some reason the reloader tests are causing timeouts on Appveyor, but not locally. So the Appveyor webhook remains disabled until someone can investigate that.

**Comment by RonnyPfannschmidt** [comment]
would it be sensible to have the reloader tests be skipped as "xfail(run=False)" on appveyor so at least the other tests can run?

**Comment by davidism** [comment]
Hopefully the server / reloader tests can just be rewritten, because every time I try to dive back into them, I'm completely lost. They're very indirect.
