### ISSUE TITLE
Inheriting collections.structures.Mapping breaks backward compat

### ISSUE THREAD

**Issue by brmzkw** [pallets/werkzeug#1084]
My unittests stopped working since the upgrade to Werkzeug==0.12. I think this is due to a breaking change in the latest release of Werkzeug, but since the issue is kind of complex, it might not be Werkzeug's fault.

I'm using httmock to build a fake API response with `httmock.response()`. `httpmock.response` takes an arguments, `headers`, which is forwarded to `requests.structures.CaseInsensitivDict`.

* httmock call to CaseInsensitiveDict: https://github.com/patrys/httmock/blob/master/httmock.py#L51
* requests source code of CaseInsensitiveDict: https://github.com/kennethreitz/requests/blob/master/requests/structures.py#L18

In my case, `headers` is a `werkzeug.datastructures.Headers` object.

Since this [commit](https://github.com/pallets/werkzeug/commit/78c617b7cc9131296fed4e4b56445f809cb90d43#diff-0763fdcf376989cae2febde5212e7812R870), `werkzeug.datastructures.Headers` inherits the abstract base class `collections.Mapping`.

With Werkzeug 0.11.15:

```
>>> import requests
>>> import werkzeug
>>> print requests.structures.CaseInsensitiveDict(werkzeug.datastructures.Headers({'a': 1}))
{'a': 1}
```

With Werkzeug 0.12:

```
>>> import requests
>>> import werkzeug
>>> print requests.structures.CaseInsensitiveDict(werkzeug.datastructures.Headers({'a': 1}))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/t/local/lib/python2.7/site-packages/requests/structures.py", line 46, in __init__
    self.update(data, **kwargs)
  File "/tmp/t/lib/python2.7/_abcoll.py", line 566, in update
    self[key] = other[key]
  File "/tmp/t/local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 955, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
```

In both cases, casting the `werkzeug.datastructures.Headers` object to a `dict` before calling `requests.structurs.CaseInsensitiveDict` works.

Do you think it's Werkzeug's fault?

**Comment by untitaker** [comment]
Fixed in 0.12.1, sorry for the breakage
