### ISSUE TITLE
Enable access to the development server object via the application

### ISSUE THREAD

**Issue by Leonidaz0r** [pallets/werkzeug#1087]
I am using the development server in an application as a simple RPC interface, just exposed to localhost. I need to start and stop servers in my unit testing setup. The only way I found to stop a werkzeug development server is by making a custom route, which uses werkzeug.server.shutdown from environ and sending a request to that route. However it seems excessive to create a route just for this purpose.

I described my situation on StackOverflow for more background information(https://stackoverflow.com/questions/43017324/starting-and-stopping-flask-on-demand).

I looked into the code and it seems a simple change would make it possible to stop the server from anywhere. The server object is created here(https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L693):

```
def inner():
        try:
            fd = int(os.environ['WERKZEUG_SERVER_FD'])
        except (LookupError, ValueError):
            fd = None
        srv = make_server(hostname, port, application, threaded,
                          processes, request_handler,
                          passthrough_errors, ssl_context,
                          fd=fd)
        if fd is None:
            log_startup(srv.socket)
        srv.serve_forever()
```

Changing this to store srv as `application.srv` instead of a local variable (just changing two lines) would allow shutting down the server from anywhere in the code via its normal interface.

I would think this might also be useful to figure out other data about the server.

What do you think about this?

**Comment by parthgala** [comment]
+1. I have the same requirement. Is anyone looking at this?

**Comment by davidism** [comment]
See Werkzeug's treats for how we test with the server. Basically, use pytest-xprocess. Being able to shut down the server internally is already a hack, it's not a standard WSGI feature, I don't want to expand its use.
