### ISSUE TITLE
Parsing Content-Disposition header fails because of simple quotes

### ISSUE THREAD

**Issue by rslinckx** [pallets/werkzeug#1091]
I have the following Content-Disposition header:

    Content-Disposition: attachment; filename="Cours%20de%20l'oeuf%20jusqu'au%2024%20mars%202017.xlsx"

It fails to be parsed correctly using http.parse_options_header because the simple quotes are confusing the regexp. It worked correctly before the merge of pull request #933 fixing issue #932 which didn't include simple quotes in the regexp

Not sure how to fix this, though

**Comment by rslinckx** [comment]
@pszalanski do you have any idea ?

**Comment by davidism** [comment]
@untitaker knows more about this, but I don't think that's a valid use of quotes.

**Comment by rslinckx** [comment]
From what I understand, the only forbidden value is " (double quote) which must be escaped.

In any case this header was generated by latest chrome version with a file containing simple quote in its filename on the disk. Not something I can change easily

Also if there's only one simple quote in the file name (apostrophe for example), then it works as expected.

**Comment by davidism** [comment]
Why is Chrome generating an attachment header that's sent to your Werkzeug server? Not saying you're wrong, just curious.

**Comment by rslinckx** [comment]
It's a file upload using javascript, payload is in the body itself (not form encoded or multi part upload)

**Comment by marma** [comment]
The problem seem to be two-fold (if I read the RFC and regexp correctly): it tries to find encoding and language even though no '*' is present before the '=', and both encoding and language is captured as anything but whitespace ([^\s]) while RFC 5987 states otherwise.

    >>> _option_header_piece_re.match('; name=utf-8\'en\'test; filename="some_file.txt"').groups()
    ('name', 'utf-8', 'en', 'test')

Rearranging the regexp to look like below seem to work. At least for these two cases:

    _quoted_string_re = r'"[^"\\]*(?:\\.[^"\\]*)*"'
    _option_header_piece_re = re.compile(
        r';\s*(%s|[^\s;,=\*]+)\s*'
        r'(?:\*=\s*?(?:([^\s]+?)\'([^\s]*?)\'))?(?:=?)(%s|[^;,]+)?\s*' %
        (_quoted_string_re, _quoted_string_re))
    
    >>> _option_header_piece_re.match('; name=utf-8\'en\'\'test\'; filename="some_file.txt"').groups()
    ('name', None, None, "utf-8'en''test'")

    >>> _option_header_piece_re.match('; name*=utf-8\'en\'test; filename="some_file.txt"').groups()
    ('name', 'utf-8', 'en', 'test')
    
    >>> _option_header_piece_re.match('; name="\'test\'"; filename="some_file.txt"').groups()
    ('name', None, None, '"\'test\'"')

**Comment by marma** [comment]
Right, so the part about allowing double quotes in encoding and language doesn't actually make a difference if you correct the part about the asterisk. But if you just correct the quotes part then it works for quoted strings.
