### ISSUE TITLE
Documentation for 0.12.x missing on werkzeug.pocoo.org

### ISSUE THREAD

**Issue by klaplong** [pallets/werkzeug#1092]
There is, however, a link to it, which results in 404. I was trying to read the changelog, but had to come here.

**Comment by rajasimon** [comment]
Can't you able to access this page <code>[http://werkzeug.pocoo.org/docs/0.12/](http://werkzeug.pocoo.org/docs/0.12/)</code> ?

**Comment by klaplong** [comment]
Well, yeah, it appears to be fixed.
