### ISSUE TITLE
Abort with a response object no longer working

### ISSUE THREAD

**Issue by jakedt** [pallets/werkzeug#1098]
I used to use this pattern:

```python
resp = make_response('Message', 403, headers={})
abort(resp)
```

This no longer seems to work with the latest versions of Flask and Werkzeug. It appears that errors are always expected to be subclasses of `HTTPException` which define a `code` property, and the default `abort(` chain doesn't give you any way to set the code. For now my workaround is to create the `HTTPException`, set `.code` directly and then raise it.

**Comment by davidism** [comment]
I can't reproduce this issue. Your example produces a 403 response in both Werkzeug and Flask.

**Comment by damooo** [comment]
Facing same issue with 

```
Python 3.6.9
Flask 1.1.2
Werkzeug 1.0.1
```
