### ISSUE TITLE
Refactor memcached tests to be more general and thorough

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1101]
See #982, which prompted the discussion.

* We should remove the library-specific logic from the testsuite. Currently we have a try-except chain in `contrib.cache`, as well as the testsuite itself.
* All libraries should be tested. This requires a lot of new test environments, which needs to be expressed in tox without becoming too confusing.

**Comment by lepture** [comment]
close it via https://github.com/pallets/werkzeug/issues/1249
