### ISSUE TITLE
consistency with `werkzeug.datastructures.Range` and `werkzeug.http.parse_range_header`?

### ISSUE THREAD

**Issue by cosven** [pallets/werkzeug#1103]
As mentioned in [rfc 7233](https://tools.ietf.org/html/rfc7233)
>  A byte-range-spec is invalid if the last-byte-pos value is present
   and less than the first-byte-pos.
>
> DIGIT (decimal 0-9)
>
> ```
> byte-range-spec = first-byte-pos "-" [ last-byte-pos ]
> first-byte-pos  = 1*DIGIT
> last-byte-pos   = 1*DIGIT
> ```

```
In [101]: r = Range('bytes', [(0, 0)])

In [102]: r.to_header()
Out[102]: 'bytes=0--1'

In [103]: new_r = parse_range_header(r.to_header())

In [104]: print new_r
None
```

so, is `bytes=0--1` an invalid value?

**Comment by davidism** [comment]
Looks like it's invalid according to the spec you quoted. Similar to Python's `range`, the end value is not inclusive. Why do you have that specific range?

**Comment by cosven** [comment]
That specific range does not exists in real word.

I'm just curious about the parse result.
In my opinion, `Range('bytes', [(0, 0)])` should raise Error or return None but not return a `Range` object.
