### ISSUE TITLE
[Proposal] [ProxyFix] set num_proxies as an upper limit of proxies

### ISSUE THREAD

**Issue by hitigon** [pallets/werkzeug#1108]
Use case to be discussed:

- Server is behind proxies (e.g. LB), let's assume we only have one proxy here for simplicity.
- Basically, two types of clients talking with server:
  + clients behind its own proxies, sending Real IPs via X-Forwarded-For to the server. In this case, we have 2 IPs in the list. By setting num_proxies to 2, we can get the last IP in the list as a real IP.
  + clients directly talk with the server with Real IP. In this case, we can set num_proxies to 1.
- Obviously, we cannot make the App server to have both values to satisfy both cases.

In summary, if we want to handle both of cases, either always get the last IP in the list (regardless the setting of num_proxies) or we can dynamically change num_proxies (by reducing it when there is a mismatching between num_proxies and the length of IP list), basically make num_proxies as an upper limit.
```
    def get_remote_addr(self, forwarded_for, num_proxies=1):
        if num_proxies <= 0:
            return

        if len(forwarded_for) >= num_proxies:
            return forwarded_for[-num_proxies]
        elif num_proxies > 1 and self.next_ip_enabled:
            return self.get_remote_addr(forwarded_for, num_proxies - 1)
```

This is an example to modify `get_remote_addr`, having `num_proxies` as a param and have  `self.next_ip_enabled` as a flag.

Let me know what do you think, maybe this is not a common case, or there are security concerns.

Thanks.

**Comment by ThiefMaster** [comment]
I'm curious, is this a real use case? I don't see much value in anything but the very first loadbalancer adding X-Forwarded-For/X-Real-IP (and overwriting/discarding any such header already present, as it can't be trusted).

Either way, you MUST ensure that clients cannot send requests directly to your application unless you somehow ensure X-Forwarded-For gets stripped in that case.

**Comment by hitigon** [comment]
@ThiefMaster Yeah, I agree. whitelist is the best choice. Thanks!
