### ISSUE TITLE
IOError Broken pipe error

### ISSUE THREAD

**Issue by ettaka** [pallets/werkzeug#1110]
In Server Sent Events (SSE) a broken connection throws an IOError exception that is not handeled:

~~~
Error on request. A traceback is shown in server log:
Traceback (most recent call last):
  File "/home/eelis/bin/miniconda2/envs/mylly-python/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/home/eelis/bin/miniconda2/envs/mylly-python/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/home/eelis/bin/miniconda2/envs/mylly-python/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
~~~

I created a commit that removes the traceback and assumes that the IOError is possibly due to "a broken connection":

~~~diff
diff --git a/werkzeug/serving.py b/werkzeug/serving.py
index 65f777f..b423c9d 100644
--- a/werkzeug/serving.py
+++ b/werkzeug/serving.py
@@ -209,8 +209,6 @@ class WSGIRequestHandler(BaseHTTPRequestHandler, object):
             execute(self.server.app)
         except (socket.error, socket.timeout) as e:
             self.connection_dropped(e, environ)
-        except IOError:
-            self.server.log('error', 'IOError: possibly a broken connection.')
         except Exception:
             if self.server.passthrough_errors:
                 raise
~~~

**Comment by untitaker** [comment]
What's wrong with that behavior? Is this only about the bad/verbose output?

**Comment by ettaka** [comment]
@untitaker Thank you for your fast response! Yes, I may be too sensitive about it :) but I don't like seeing tracebacks in normal operation but rather see a human friendly notification instead. Tracebacks make me feel that there is something wrong with the code. This is of course a matter of taste and I can live with it but let me know how you decide. I'll open the pull request in case this is OK to you.

**Comment by JordanP** [comment]
@ettaka if you go forward with this, your except IOError statement should discriminate against errno so that it would log only if it's a "broken pipe IOError" and not any IOError.

**Comment by untitaker** [comment]
I agree. IOError seems a bit too broad

**Comment by ettaka** [comment]
@untitaker @JordanP Agreed.
I narrowed it down to broken pipe. Is it acceptable? See below:
diff --git a/werkzeug/serving.py b/werkzeug/serving.py
index b423c9d..2ad52ef 100644
--- a/werkzeug/serving.py
+++ b/werkzeug/serving.py
@@ -209,6 +209,10 @@ class WSGIRequestHandler(BaseHTTPRequestHandler, object):
             execute(self.server.app)
         except (socket.error, socket.timeout) as e:
             self.connection_dropped(e, environ)
+        except IOError, e:
+            import errno
+            if e.errno == errno.EPIPE:
+                self.server.log('error', 'IOError, Broken Pipe: possibly a broken connection.')
         except Exception:
             if self.server.passthrough_errors:
                 raise

**Comment by ettaka** [comment]
Sorry messed up. There should be else for other IOErrors...

**Comment by ettaka** [comment]
@untitaker @JordanP This should now work:
~~~diff
diff --git a/werkzeug/serving.py b/werkzeug/serving.py
index b423c9d..c8106de 100644
--- a/werkzeug/serving.py
+++ b/werkzeug/serving.py
@@ -209,6 +209,15 @@ class WSGIRequestHandler(BaseHTTPRequestHandler, object):
             execute(self.server.app)
         except (socket.error, socket.timeout) as e:
             self.connection_dropped(e, environ)
+        except IOError, e:
+            import errno
+            if e.errno == errno.EPIPE:
+                self.server.log('error', 'IOError, Broken Pipe: possibly a broken connection.')
+            else:
+                from werkzeug.debug.tbtools import get_current_traceback
+                traceback = get_current_traceback(ignore_system_exceptions=True)
+                self.server.log('error', 'IOError:\n%s',
+                        traceback.plaintext)
         except Exception:
             if self.server.passthrough_errors:
                 raise
~~~

**Comment by untitaker** [comment]
Please make a PR

**Comment by ThiefMaster** [comment]
And please don't keep the `import errno` local; move it to the top of the module instead where all the other imports are.
