### ISSUE TITLE
SERVER_SOFTWARE in environ for test client

### ISSUE THREAD

**Issue by jwg4** [pallets/werkzeug#1112]
Would it make sense for the test client Client to add the key SERVER_SOFTWARE to the request environment which it constructs, with a value of something like 'werkzeug test client/$WERKZEUG_VERSION'? Currently the Client sets up a bunch of default value for the environment, which can be overwritten by the creator of the Client object. These include SERVER_NAME, SERVER_PORT, SERVER_HOST, etc., but not SERVER_SOFTWARE. SERVER_SOFTWARE seems to be set by werkzeug itself, by gunicorn and gevent, etc.

Adding this key would make it possible for a request handler to do something with this value, which wouldn't break or have to be worked around, when tests are run using the test client. It would mean that application code which does something different, depending on which server it's run by could handle running as a test in the test client smoothly.

Happy to submit a patch (which would probably be pretty simple).

**Comment by untitaker** [comment]
Could you give a concrete example whete this could be useful?

On 25 April 2017 02:11:24 GMT+02:00, jwg4 <notifications@github.com> wrote:
>Would it make sense for the test client Client to add the key
>SERVER_SOFTWARE to the request environment which it constructs, with a
>value of something like 'werkzeug test client/$WERKZEUG_VERSION'?
>Currently the Client sets up a bunch of default value for the
>environment, which can be overwritten by the creator of the Client
>object. These include SERVER_NAME, SERVER_PORT, SERVER_HOST, etc., but
>not SERVER_SOFTWARE. SERVER_SOFTWARE seems to be set by werkzeug
>itself, by gunicorn and gevent, etc.
>
>Adding this key would make it possible for a request handler to do
>something with this value, which wouldn't break or have to be worked
>around, when tests are run using the test client. It would mean that
>application code which does something different, depending on which
>server it's run by could handle running as a test in the test client
>smoothly.
>
>Happy to submit a patch (which would probably be pretty simple).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/werkzeug/issues/1112

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jwg4** [comment]
Yes, when we deploy a HTTP API, we want to add a generic endpoint which does something like

```
def get_server_info(request):
    data = {
        'SERVER_SOFTWARE': request.environ['SERVER_SOFTWARE'],
        ...
    }
    ...
    return response(data)
```

The purpose of this is so that we can query our servers to identify exactly which web server versions, etc they are running on. We would like this code to work without modification when running unit tests.

**Comment by ThiefMaster** [comment]
Is `SERVER_SOFTWARE` actually a required environment value? If not you should probably use `.get()` there n - then your test code will work fine as long as it doesn't choke on a `None` (or whatever default you use)

**Comment by untitaker** [comment]
Tbh I think this stuff should be part of your own code.

**Comment by davidism** [comment]
Changing behavior based on what server is running seems like a bad pattern. Also, exposing the server software probably isn't safe. It's why you can disable it in Apache/Nginx.

**Comment by jwg4** [comment]
Fair enough.
