### ISSUE TITLE
When duplicate names are used in Cookie header, werkzeug uses the last one

### ISSUE THREAD

**Issue by dorfsmay** [pallets/werkzeug#1118]
Although not specified in the RFCs, it is a de facto standard in the case of duplicate keys, the first one is used, due to browser ordering cookies from most specific scope to most generic. Werkzeug works the other way around, and returns the value for the latest key rather than the first one.

**Comment by mitsuhiko** [comment]
Fixed in d4087a3072c8387d2d4dd57f988d051a2e202b25
