### ISSUE TITLE
Support for SameSite cookie property.

### ISSUE THREAD

**Issue by ngunderson** [pallets/werkzeug#1120]
SecureCookie and BaseResponse classes should be updated to allow users to pass "strict" or "lax" when setting a cookie. Read more about SameSite and its protection against CSRF [here](https://www.owasp.org/index.php/SameSite)

**Comment by runner4444** [comment]
There are two PRs open #1059  and #1046 , one of these should be merged.

**Comment by mitsuhiko** [comment]
This is implemented
