### ISSUE TITLE
Periods not allowed in converter arguments.

### ISSUE THREAD

**Issue by sirdodger** [pallets/werkzeug#1123]
A period is allowed in a route as per RFC1738:

Rule('/foo/my.path/', ...)

However, a period does not work inside, for example, an AnyConverter:

Rule('/foo/<any:bar, my.path>/', ...)

It seems like werkzeug.routing._converter_args_re is a little too strict.

**Comment by davidism** [comment]
The syntax would be `<any(bar, my.path):name>`, but yes, that doesn't work right now. Marking this as beginner friendly.

**Comment by dawran6** [comment]
I'm changing the `_converter_args_re` to be less strict. The current regex is:

```python
_converter_args_re = re.compile(r'''
    ((?P<name>\w+)\s*=\s*)?
    (?P<value>
        True|False|
        \d+.\d+|
        \d+.|
        \d+|
        \w+|
        [urUR]?(?P<stringval>"[^"]*?"|'[^']*')
    )\s*,
''', re.VERBOSE | re.UNICODE)
```

I'm changing this to:
```python
_converter_args_re = re.compile(r'''
    ((?P<name>\w+)\s*=\s*)?
    (?P<value>
        True|False|
        [a-zA-Z0-9_.]+|
        [urUR]?(?P<stringval>"[^"]*?"|'[^']*')
    )\s*,
''', re.VERBOSE | re.UNICODE)
```

This would allow none or more `.` character in the rule. Is this correct?
