### ISSUE TITLE
When WSGIRequestHandler catches socket.error it silences all other OSErrors in Python 3

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1127]
Reported at pallets/flask#1995. `WSGIRequestHander.run_wsgi` catches `socket.error` to silence client disconnects. In Python 2 this was fine, because `socket.error` was unique. In Python 3, `socket.error is OSError`, so any `OSError` or subclass (`IOError`, etc.) is also silenced.

Possible solution is to check if `e.errno` is a disconnect-related error and bubble the error up otherwise. Or catch a more specific error such as [`ConnectionError`](https://docs.python.org/3/library/exceptions.html#ConnectionError) in Python 3.

This only affects Werkzeug's dev server, other WSGI servers like Gunicorn do not exhibit this behavior.

**Comment by mitsuhiko** [comment]
I feel like we had this before. I thought we fixed this somewhere already.

**Comment by davidism** [comment]
It was reported against Flask and we discussed it there, but it's a bug against Werkzeug so I moved it here. Maybe that's what you're remembering? pallets/flask#1995

**Comment by aaossa** [comment]
Can I work on this? If so, any suggestion/advice to begin with that consideration?

**Comment by untitaker** [comment]
@aaossa I'm not sure what you mean with "that consideration". One possible approach to this issue is described in the OP

**Comment by aaossa** [comment]
With "that consideration" I meant the suggestion/advice I was asking for. I'll give it a try.

**Comment by aaossa** [comment]
I have a possible solution [here](https://github.com/aaossa/werkzeug/commit/35cecf481c1595add85d33829ea1f6e6538aeca0), should I create a test? @untitaker

**Comment by davidism** [comment]
I haven't looked at this in a while, but `type(e) is socket.error` is the same issue we're talking about here: it's not a distinct error on py3.

**Comment by aaossa** [comment]
I though that the problem was using `except (socket.error ...` because it uses `isinstance` instead of `type` and that caused the problems in error handling, because `isinstance` check subclasses and `type` does not.

**Comment by davidism** [comment]
`isinstance` is the same as `type is` in this case, because `socket.error = OSError`.

**Comment by aaossa** [comment]
Then maybe use something like:

```python
except socket.timeout, _:
    # ...
except socket.error, exc:
    print("Caught exception socket.error : " + str(exc))
```

and check the error code (using [`errno`](https://docs.python.org/3.6/library/errno.html)) like [this](https://stackoverflow.com/a/5161286/3281097) should work? I0m trying to find the errno for `socket.error`

**Comment by davidism** [comment]
Isn't that what I said at the top?
