### ISSUE TITLE
Set Content-Length when data passed to Response is a tuple

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1130]
See pallets/flask#1877. If the data is a `Collection`, it should be safe to calculate its length. Pass it to `set_data` and use `len(get_data())` to calculate the length.

Note that the header is still sent eventually, it's available on the receiving client, it's just not available on the object in Python.

**Comment by mitsuhiko** [comment]
Right now we only calculate the content length if data is set to a string or if a conditional response is created. If we want to change that we need to make the response attribute a descriptor.

**Comment by davidism** [comment]
Why do we only do it in those cases? In the linked issue, the response essentially *is* a string, but a tuple is used to add a line at the end, probably with the thought that it's better than doing the string concatenation. https://github.com/pallets/flask/pull/1262/files#diff-dc6f589d1b53806b6a6287c182b461b2R249 It's probably fine to just change Flask's `jsonify` to use `+ '\n'` instead, but calculating lengths in these cases still seems reasonable.

**Comment by mitsuhiko** [comment]
Because `response` is an attribute and not a property. Where would you calculate the length currently? We can change that but what if then people start appending stuff to the list? Then the content length will be wrong. (Responses are mutable)

**Comment by davidism** [comment]
I never thought of the use case where a user sets the response to a list and appends to it. I'm fine with leaving everything as-is in that case.

**Comment by davidism** [comment]
Although, a `tuple` can't be appended to, which is what's used by `jsonify`.

**Comment by mitsuhiko** [comment]
@davidism i don't understand though why we just don't make a string in flask. Should be cheaper appending a character to a string than to issue to `send()`s.

**Comment by davidism** [comment]
You're right, I'm going to fix it in Flask.
