### ISSUE TITLE
Groups of slashes in path should be normalized and redirected

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1132]
Originally reported at pallets/flask#1323.

`/x` and `//x` should route to the same location, possibly by redirecting. From the linked issue:

> On most operating systems, extra slashes resolve to one. URLs came from file system notation so it would seem that the two should respond in the same way.  
> 
> Apache removes duplicate slashes for [a good reason](https://issues.apache.org/jira/browse/NUTCH-1894).
> 
> Nginx has the [merge_slashes directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#merge_slashes), which is on by default.
> 
> [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.3) seems to imply you can't have multiple, contiguous slashes

Possible solution is to add a `collapse_slashes` option similar to `strict_slashes`. 

Possibly related to #491.

**Comment by davidism** [comment]
This should apply to defining rules (`//x` becomes `/x` internally) as well as matching incoming paths (`//x` redirects to `/x`).

**Comment by garlicbulb-puzhuo** [comment]
I am looking into this if this is still valid for ts-open.

**Comment by davidism** [comment]
This already has an open PR, sorry for the confusion
