### ISSUE TITLE
Werkzeug and socket.setdefaulttimeout incompatibility

### ISSUE THREAD

**Issue by fazalmajid** [pallets/werkzeug#1133]
One of my Flask servers was throwing errors in the middle of serving a 2.5MB file and aborting the response.

A stray test fixture was being imported that called `socket.setdefaulttimeout(5)`. As a side-effect this sets all new sockets to be non-blocking in Python's socketmodule. The machine in question was being slow with some context-switching latency, and the nginx reverse proxy was not reading from flask as fast as flask was sending data out, and at some point flask hit `EAGAIN` (which is synonymous with `EWOULDBLOCK`) when attempting to write to the socket, an error werkzeug doesn't handle:

```
2017-06-06 13:57:04 werkzeug INFO     127.0.0.1 - - [06/Jun/2017 13:57:04] "GET /cdc/wa/common.af157487.js HTTP/1.1" 200 -
2017-06-06 13:57:04 werkzeug ERROR    Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 196, in execute
    write(data)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in write
    self.wfile.write(data)
IOError: [Errno 11] Resource temporarily unavailable
```

The fix would be to catch the exception, run select() on the socket to wait until it is ready to write to, then resume the call. Or alternatively document the incompatibility.

**Comment by davidism** [comment]
Do not use the dev server in production.

**Comment by blaise-io** [comment]
I also have this issue, but during local development.

**Comment by jacquerie** [comment]
This seems familiar: it's the error diagnosed by @mihaibivol of which I talk about here: https://github.com/coleifer/micawber/issues/59#issuecomment-226430266

In fact, we were seeing that error in development when running with `DEBUG=True`, which made us use `gunicorn` in development as well.
