### ISSUE TITLE
RedisCache only accepts string keys

### ISSUE THREAD

**Issue by mcdallas** [pallets/werkzeug#1152]
Currently RedisCache only accepts string keys due to the 'key_prefix' parameter that gets concatenated to each key. Even SimpleCache accepts integer keys and redis itself even accepts sets as keys. 

I am using werkzeug 0.12.2 and Python 3.6.1

**Comment by davidism** [comment]
So what's your proposal? I don't want to drop the prefix, but converting arbitrary objects to string might not be correct.

**Comment by mcdallas** [comment]
Maybe add a check to see if the attempted key is a string and only then add the prefix.

**Comment by davidism** [comment]
How about if a prefix is defined, string keys are required, if it's none any key is allowed with the understanding that collisions are easier.

**Comment by mcdallas** [comment]
That works too. I can send a PR this weekend.

**Comment by davidism** [comment]
That would be really helpful, thanks!

**Comment by davidism** [comment]
The cache is deprecated, see #1249
