### ISSUE TITLE
Content-Type and Content-Length are set to empty string in test environment

### ISSUE THREAD

**Issue by f11r** [pallets/werkzeug#1159]
At the moment in the test environment the `Content-Type` and `Content-Length` headers are always set (see https://github.com/pallets/werkzeug/blob/40bfd13b4383512160a139aea3721c3746a4d7ae/werkzeug/test.py#L582), even if not provided by the user. This makes the following calls identical and stops anyone from testing a call without one of these headers:

~~~
resp = app_client.post('/v1.0/post_wrong_content_type', data=json.dumps({'some': 'data'}))
~~~
~~~
resp = app_client.post('/v1.0/post_wrong_content_type', data=json.dumps({'some': 'data'}), 
                       content_type='')
~~~

This seems very similar to #1049.

**Comment by mitsuhiko** [comment]
This is permitted by the WSGI spec:

> The following variables must be present, unless their value would be an empty string, in which case they may be omitted, except as otherwise noted below
>
> The contents of any Content-Type fields in the HTTP request. May be empty or absent.

We generally treat missing and set empty the same.
