### ISSUE TITLE
Reverse sorting backtraces in the debugger...

### ISSUE THREAD

**Issue by sean-** [pallets/werkzeug#116]
I can't think of the last time the top few frames of a backtrace were the interesting ones. In a terminal window, it makes sense to that the deepest frames are also the most interesting, and closest to your cursor at the bottom of the screen. On the web, however, that means that the most interesting frames are at the bottom of your browser window, which means scrolling.

It'd be EXCELLENT if the backtrace in werkzeug was reverse sorted so that the deepest frames are at the top of the page.

In an ideal world, I think this would be a tunable, something like:

WERKZEUG_BACKTRACE_ORDER = 'descending' # vs 'ascending'

Even if it wasn't a tunable, having it reversed by default makes more sense.

Thanks in advance. -sc

**Comment by davidism** [comment]
I'd rather not automatically scroll, but maybe clicking the error message at the top of the page will scroll to its counterpart at the end of the traceback.
