### ISSUE TITLE
MultiDict missing methods

### ISSUE THREAD

**Issue by brocef** [pallets/werkzeug#1160]
According to the MultiDict documentation [here](http://werkzeug.pocoo.org/docs/0.12/datastructures/#werkzeug.datastructures.MultiDict), there should be the following methods which are not defined in the current [wekzeug/datastructures.py](https://github.com/pallets/werkzeug/blob/master/werkzeug/datastructures.py) file:

- `items(*a, **kw)` <---This one actually exists, but with a different prototype
- `iteritems(multi=False)`
- `iterlists()`
- `iterlistvalues()`
- `itervalues()`
- `viewitems(*a, **kw)`
- `viewkeys(*a, **kw)`
- `viewlists(*a, **kw)`
- `viewlistvalues(*a, **kw)`
- `viewvalues(*a, **kw)`

Perhaps I'm overlooking something obvious, but there seems to be a discrepancy here.

**Comment by ThiefMaster** [comment]
https://github.com/pallets/werkzeug/blob/master/werkzeug/datastructures.py#L51 takes care of it.

**Comment by brocef** [comment]
Interesting... why do I get` AttributeError`s when trying to invoke those functions? Are these for Python 2 or 3 exclusively?

**Comment by ThiefMaster** [comment]
They only exist in Python 2. Just like the native collection objects, no iter* and view* methods exist in Python 3 (the default methods already return a view in Python 3)

**Comment by brocef** [comment]
Got it--thanks!
