### ISSUE TITLE
RedisCache.clear may return integer instead of boolean

### ISSUE THREAD

**Issue by spacewander** [pallets/werkzeug#1163]
I am using python 2.7.12 with :
```
redis==2.10.6
werkzeug==0.12.2
```

According to the documentation, `werkzeug.contrib.cache.RedisCache.clear` should return a boolean value to indicate `Whether the cache has been cleared`.
However, because `self._client.delete(*keys)` returns an integer as the number of keys removed, the actual returned value could be an integer. And since `clear` is not atomic, the returned number may be not equal to the `len(keys)`.

Maybe we could set `status` according to existence of `redis.exceptions.ResponseError`?
For example:
```python
status = True
try:
      self._client.delete(*keys)
except redis.exceptions.ResponseError:
      status = False
```

BTW, if there is nothing to clear, RedisCache.clear will return False. On the same occasion, FileSystemCache.clear will return True. The documentation about this occasion is not clear.

I could submit a patch if those behaviors are considered as bug.

**Comment by spacewander** [comment]
One more thing, `RedisCache.clear` should not use `keys` to get all keys.

Use `keys` in production is not recommended. Some people even suggest to rename `keys` command in production environment. I observed the mistake in a PHP background task before. The `keys` operation locked the Redis for more than 1 second, caused a great number of redis operation timeouts. I am not willing to see this happens again.

There is already an issue about replacing `keys` with `scan`(https://github.com/pallets/werkzeug/issues/1069), but there is not a related pull request yet.

**Comment by lepture** [comment]
close it via https://github.com/pallets/werkzeug/issues/1249
