### ISSUE TITLE
Built-in compression support for the Redis cache?

### ISSUE THREAD

**Issue by simenheg** [pallets/werkzeug#1170]
Hi. I’ve been pondering whether it would be good for the Redis cache to have built-in support for compression.

I imagine something similar to what [python-memcached](https://github.com/linsomniac/python-memcached/blob/master/memcache.py#L161) does could be done, where data with size above a user-specified limit is compressed and decompressed automatically on entry and retrieval.

Memcached has the advantage of being able to store an arbitrary 16-bit flag along with the data, so it’s easy to mark data that has been compressed. I’m not aware of a similar functionality in Redis, so I’m not sure what would be the best way to indicate which data has been compressed and not. Maybe the data could be prefixed with a bit flag when the compression feature is turned on.

Thoughts?

See also http://labs.octivi.com/how-we-cut-down-memory-usage-by-82/.

**Comment by lepture** [comment]
close it via https://github.com/pallets/werkzeug/issues/1249
