### ISSUE TITLE
FileStorage __init__ fails when backed by TemporaryFile

### ISSUE THREAD

**Issue by idoby** [pallets/werkzeug#1171]
When the upload is large and the stream is backed by a TemporaryFile, which is in turn backed by a _io.FileIO, __init__ fails here

`            if filename and filename[0] == s('<') and filename[-1] == s('>'):
`

because filename is an int (file descriptor number), which is not subscriptable. This is set by Python's `_io_FileIO___init___impl` function in `Modules/_io/fileio.c`.

Werkzeug 0.12.2, Python 3.6.2, macOS 10.12.6 (16G29)

**Comment by idoby** [comment]
Is this project still alive or should I ditch Werkzeug and Flask?

**Comment by ThiefMaster** [comment]
> Is this project still alive or should I ditch Werkzeug and Flask?

No need to be passive aggressive :)

And FYI, it's usually nice to include a minimal script to reproduce an issue. Or if that is too much work, at least the full traceback of the error.

**Comment by idoby** [comment]
Sorry, didn't meant to come off like that.

**Comment by untitaker** [comment]
@davidism Is there any reason why you deleted @idoby's comments?
