### ISSUE TITLE
Expect 100-continue always leads to HTTP/1.1 Continue: no control?

### ISSUE THREAD

**Issue by proycon** [pallets/werkzeug#1174]
I encounter the following problem, a file is being uploaded to my flask-based app. The client (curl in my test) first sends a Expect: 100-continue request before sending the full request body, a very sensible thing to do. However, werkzeug seems to immediately reply with a HTTP/1.1 100 Continue (I presume https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L150 is the culprit?) without allowing me any control over it. Whereas, at this point my app notes absence of authentication headers so replies with a 401, the actual body need not be sent and the 100 shouldn't have been sent. As I understand it, this is according to the HTTP Spec:

> The server MUST respond with a 417 (Expectation Failed) status if any of the expectations cannot be met or, if there are other problems with the request, some other 4xx status. 

Some communication between client and flask:

```
$ curl -v  -F "inputtemplate=InputWavFile" -F "file=@/nettmp/dlasrtest.wav" http://mhysa:8802/myproject/input/dlasr.wav
*   Trying 192.168.0.10...        
* TCP_NODELAY set                 
* Connected to mhysa (192.168.0.10) port 8802 (#0)                  
> POST /myproject/input/dlasr.wav HTTP/1.1                          
> Host: mhysa:8802                
> User-Agent: curl/7.55.1         
> Accept: */*                     
> Content-Length: 31161           
> Expect: 100-continue            
> Content-Type: multipart/form-data; boundary=------------------------13863bbaf000744c                                                  
>                                 
< HTTP/1.1 100 Continue           
* Send failure: Broken pipe       
* stopped the pause stream!       
* Closing connection 0         
```

Flask never explicitly reports the HTTP 100 in the server output, but does report the subsequent 401 I sent:

```
192.168.0.10 - - [13/Sep/2017 13:27:34] "POST /myproject/input/dlasr.wav HTTP/1.1" 401 -
```

I presume after the 401 the connection is broken, whilst the client is still trying to process the continue it got earlier, hence the broken pipe.

(Python 3.6, Werkzeug 0.12.2, Flask 0.12.2)

**Comment by mitsuhiko** [comment]
There is not much we can do here. First of all the 100-continue the werkzeug wsgi server handles and the implementation we have here is the only one that wsgi can really support. The issue you linked in the clam repo is actually the same thing in uwsgi as far as I can tell.

If you want a different behavior for this case then the PEP 333(3) would have to be extended. Right now replying with a 100-continue outright is the only recurse we have.
