### ISSUE TITLE
Confusing exception when creating RedisCache with null params

### ISSUE THREAD

**Issue by erjiang** [pallets/werkzeug#1179]
```
#!/usr/bin/env python                                                            

from werkzeug.contrib.cache import RedisCache

cache = RedisCache(host=None, password=None)                                     
                                                               
cache.get("foo")
```

Expected: some sort of redis.exceptions.RedisError, like redis.exceptions.ConnectionError

What happens: `AttributeError: 'NoneType' object has no attribute 'get'`

I think the error should be at least a little more relevant, not sure how the code even gets to the `cache.get` line.

**Comment by browniebroke** [comment]
What behaviour would you expect? Raise an exception if `host` is `None` when creating the `RedisCache` instance? I don't think we can do anything if the password is incorrectly set to `None`...
