### ISSUE TITLE
Upgrade JQuery from v1.11.3 (security)

### ISSUE THREAD

**Issue by avatarworf** [pallets/werkzeug#1181]
https://github.com/pallets/werkzeug/blob/master/werkzeug/debug/shared/jquery.js#L1

Running some Security software on our libraries shows that the werkzeug package has a security vulnerability (WS-2017-0195) simply because its using an old version of jquery.js v1.11.3

Anything post v3.0.0 should satisfy the vulnerability

- In v2.2.4 and previous, a lowercasing logic was used on the attribute names and was removed in v3.0.0. Because of this, boolean attributes whose names were not all lowercase cause infinite recursion, and will exceed the stack call limit.

**Comment by davidism** [comment]
We can upgrade it, but the debug middleware itself is a much larger security hole. Don't use it in production.

**Comment by CleoQc** [comment]
Addressed by https://github.com/pallets/werkzeug/pull/1390
