### ISSUE TITLE
FileSystemCache: new parameter `size_limit`

### ISSUE THREAD

**Issue by blixhavn** [pallets/werkzeug#1183]
In environments with limited disk space available for cache and variable element size, it might be too unpredictable to use the existing `threshold` parameter. I therefore suggest to introduce a `size_limit` parameter that will be used in the `_prune` function. Since calculating cache size can be an expensive operation, this should be maintained as a non-decaying cache element, to be updated on cache updates.

**Comment by blixhavn** [comment]
@davidism Any input here?

**Comment by lepture** [comment]
close it via https://github.com/pallets/werkzeug/issues/1249
