### ISSUE TITLE
Support Cache-Control extensions

### ISSUE THREAD

**Issue by mfr-itr** [pallets/werkzeug#1185]
I'm thinking specifically about https://bitsup.blogspot.fr/2016/05/cache-control-immutable.html.
Maybe add a dict str -> (str or None) which maps the extension name to the optional payload?

**Comment by jab** [comment]
@mitsuhiko and other maintainers, would you accept a PR implementing [Cache-Control: Immutable](https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/)?

**Comment by moi90** [comment]
Any progress on this? This would be valuable!

**Comment by davidism** [comment]
This is still marked experimental on MDN, I'm not sure I want to add that yet. Werkzeug already provides the tools to include whatever experimental options you want:

```python
# cache_control is also a dict
response.cache_control["immutable"] = False

# or add the property
from werkzeug.datastructures import ResponseCacheControl, cache_property

ResponseCacheControl.immutable = cache_property("immutable", None, bool)
```
