### ISSUE TITLE
responses without Content-Length always close the connection

### ISSUE THREAD

**Issue by nfelt** [pallets/werkzeug#1191]
WSGIRequestHandler from werkzeug.serving has the following lines of code:

https://github.com/pallets/werkzeug/blob/2f5268966428fcfdc76d2311864a7c43cf826c93/werkzeug/serving.py#L171-L173

Basically, when writing out any response, if the Content-Length header is missing, the request handler forcibly closes the connection.  There are several valid types of HTTP/1.1 responses that don't have to and often should not include a Content-Length header, but where it's unnecessarily wasteful to tear down the connection afterwards.

[Section 3.3.3 of the HTTP/1.1 RFC](https://tools.ietf.org/html/rfc7230#section-3.3.3) describes the process for determining the message length and lists these cases where Content-Length isn't needed or considered.

Specifically for Werkzeug, some relevant ones that could come up are:
- HEAD request responses
- 204 NO CONTENT responses
- 304 NOT MODIFIED responses
- Responses using Transfer-Encoding

Note that for 304 responses, Werkzeug's standard `get_wsgi_headers()` implementation will actually strip out an existing Content-Length header, making the out-of-box behavior that 304 responses always terminate the connection: https://github.com/pallets/werkzeug/blob/9f294937fe8c5cd1fe2d5ca04375dca82aad098a/werkzeug/wrappers.py#L1245-L1246

[Section 4.1 of the HTTP/1.1 Conditional Requests RFC](https://tools.ietf.org/html/rfc7232#section-4.1) implies that you SHOULD NOT include a Content-Length header with a 304 unless you're trying to prompt the browser to update cached metadata (which makes no sense in the case of Content-Length, really), so I think `get_wsgi_headers()` is showing reasonable behavior here.

A fix to this would be either to make WSGIRequestHandler smarter about when it forcibly closes the connection, or to put that behavior behind some user-controllable setting (or Response variable) so that it can be disabled if it's generating many needlessly closed connections.

**Comment by mitsuhiko** [comment]
This only affects the development server which does not support keep-alive anyways so that's not really something we need to fix. However more important `Transfer-Encoding` is not supported by the werkzeug server going out and a WSGI app is not permitted to emit it.

This leaves the 204/304/HEAD requests which I'm not sure about how HTTP keepalives work with it. I would need to investigate this. But closing this issue anyways because the internal server is not intended for these cases anyways.

**Comment by nfelt** [comment]
Thanks for the commit addressing this!  I realize that the serving logic is supposed to be primarily for development but it's been working well enough for our purposes, and it actually does support keep-alive - `WSGIRequestHandler` extends `BaseHTTPRequestHandler` which has a `protocol_version` class property, which defaults to `HTTP/1.0` for backwards compatibility, but if you set the property to `HTTP/1.1` then the connections do indeed stay alive.
