### ISSUE TITLE
unable to change the request.json value

### ISSUE THREAD

**Issue by ThirupathRao** [pallets/werkzeug#1194]
I created a request object  like
`request = LocalProxy(partial(_lookup_req_object, 'request'))`
But when I tried to modify the value of request.json as below
`request.json = { }`
It is throwing the following error.

<b>Python Version: 3.4.</b>
Flask Version: 0.10
werkzeug: 0.10

It used to work with python 2.7 and flask 0.9
Is there a way that I can get this working with python 3.4 ?

Thanks in advance.

**Comment by davidism** [comment]
It makes no sense to change `request.json`, that's a property of the incoming data.

**Comment by ThirupathRao** [comment]
Okay I understood.
But this used to work with python 2.7 and flask 0.9
But later it stopped working after upgrading to python 3.4 and flask 10

Is there any specific reason for this ?

**Comment by ThiefMaster** [comment]
It is a property returning dynamically generated data (it calls `request.get_json()`), that's the reason.

FYI, if you really want to editing it: `request.__dict__['json']` backs the cached property so if you assign to that it will probably work. But again, better to just not do it at all.

**Comment by ThirupathRao** [comment]
That Worked!!!
Thanks.

**Comment by davidism** [comment]
But really, don't do that.
