### ISSUE TITLE
Tests are failing on Travis

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1196]
`xprocess.ensure('redis_server', prepare)` fails. https://travis-ci.org/pallets/werkzeug/jobs/301622582

cc @untitaker

**Comment by untitaker** [comment]
https://github.com/pallets/werkzeug/commit/92c02d407e25db42fbff146b4ca9068c0c928453 should fix this.

**Comment by davidism** [comment]
There were some other issues with codecov and flake8. Waiting for the tests to finish.

**Comment by davidism** [comment]
And wheel no longer supports 2.6.

**Comment by davidism** [comment]
And yet `tox -e py26-normal` works on my machine.

**Comment by davidism** [comment]
Tox installs Watchdog, which installs PyYaml, which needs to build with wheel, which fails on 2.6. There appears to be no way to install wheel==0.29 in the tox virtualenv before the other deps are installed, it installs them all at once.

**Comment by davidism** [comment]
@RonnyPfannschmidt any suggestion (besides drop 2.6 support 😉), since you're active on Tox dev?

**Comment by untitaker** [comment]
I'd vote in favor of dropping 2.6, since the kind of companies who would still
be on 2.6 would probably also still use Werkzeug 0.8 or something like that.

**Comment by davidism** [comment]
See pallets/meta#24

**Comment by davidism** [comment]
Cache tests are still spotty and need to be restarted sometimes, but 2.6 and 3.3 are no longer tested. #1201
