### ISSUE TITLE
Docs: Multidict has_key(k) replaced with "in" - Python 3

### ISSUE THREAD

**Issue by naamancampbell** [pallets/werkzeug#1202]
Can the docs be updated to show Python 3 no longer supports has_key() for dicts?
http://werkzeug.pocoo.org/docs/0.12/datastructures/#werkzeug.datastructures.MultiDict
http://werkzeug.pocoo.org/docs/0.12/python3/

Source:
https://docs.python.org/3.1/whatsnew/3.0.html#builtins

**Comment by davidism** [comment]
`has_key` is there because the docs are built with Python 2 right now. As to that Python 3 page, it probably just needs to be removed at this point.

**Comment by mitsuhiko** [comment]
Going to close this issue because it's not really applicable.
