### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/werkzeug#1203]
Mostly want to discuss if we can push a release out (@davidism, @ThiefMaster)

The chunking stuff is becoming more of an issue now that more people use the fetch api which uses it by default for file uploads. We're running into that at sentry quite a bit now and master fixes that.

If you're fine with that I would make a post on the website documenting the changes and announcing that it breaks 2.6 and 3.3

**Comment by davidism** [comment]
Yes, I can release 0.13 tonight.

**Comment by ThiefMaster** [comment]
Any chance we can get in a fix for #1177 / #1091 as well (or if it's not trivial keep that for a 0.13.1)? I'm currently abroad and thus don't really have time to look into that... (also I'm not really familiar with this particular part of werkzeug)

**Comment by davidism** [comment]
I'm going to have to do this tomorrow morning, it got too late here. @ThiefMaster I'll look at those. Looks like someone in #1091 already did some digging in the regex. Regex 💔

**Comment by davidism** [comment]
Milestone is complete, I should be able to do this tonight.

**Comment by gabefair** [comment]
Thank you @davidism

**Comment by davidism** [comment]
I am writing the blog post right now, will go up soon.

**Comment by davidism** [comment]
https://www.palletsprojects.com/blog/werkzeug-013-released/
