### ISSUE TITLE
Werkzeug 0.13: request bodies not reaching app

### ISSUE THREAD

**Issue by rybesh** [pallets/werkzeug#1215]
I have a Flask application deployed using uwsgi behind nginx. After the upgrade to Werkzeug 0.13, request bodies were no longer being passed from nginx to my app (calls to `request.get_data()` returned `b''`). Downgrading to Werkzeug 0.12.2 fixed the issue.

Installed software versions:

python: 3.5.2-2ubuntu0~16.04.4
uwsgi: 2.0.12-5ubuntu3.1
uwsgi-plugin-python3: 2.0.12-5ubuntu3.1
nginx: 1.12.1-0+xenial0

uwsgi config:
```
[uwsgi]

plugins         = python3
chdir           = /srv/periodo
virtualenv      = /srv/periodo/venv
module          = periodo
callable        = app

# process-related settings
master          = true
processes       = 2
socket          = /var/www/periodo/uwsgi.sock
chown-socket    = www-data:www-data
chmod-socket    = 664

# clear environment on exit
vacuum          = true
```

relevant parts of nginx config:
```
upstream periodo_app {
    server unix:///var/www/periodo/uwsgi.sock;
}
server {
    listen              443 ssl;
    location / {
        uwsgi_pass  periodo_app;
        include  /etc/nginx/uwsgi_params;
    }
}
```

**Comment by davidism** [comment]
Does uWSGI or Nginx matter here? Do you get the body running the dev server? What is the body?

**Comment by rybesh** [comment]
It works fine with the dev server; this is only happening when running under uwsgi and nginx. The request that fails is PATCH request with content-type `application/json`. The PATCH handler looks like this:
```python
    def patch(self):
        try:
            patch_request_id = patching.create_request(
                patching.from_text(request.data), g.identity.id)
            database.commit()
            return None, 202, {
                'Location': api.url_for(PatchRequest, id=patch_request_id)
            }
        except patching.InvalidPatchError as e:
            return {'status': 400, 'message': str(e)}, 400
```
`request.data` is empty, same deal with `request.get_data()`.

**Comment by rybesh** [comment]
Also possibly relevant: I'm using this middleware to ensure that request bodies are consumed in their entirety so that uwsgi doesn't drop the connection:

https://github.com/periodo/periodo-server/blob/master/periodo/middleware.py

**Comment by davidism** [comment]
I'd really appreciate any help you can provide debugging this, since it is not a setup I can quickly create. If you have the time, a place to start would be using git bisect to find which commit affected this.

**Comment by rybesh** [comment]
I will have some time next week after Tuesday, so I will see what I can discover.

**Comment by davidism** [comment]
@rybesh I see that you recently still ran into this issue, but as you never added more details about the problem, there's not much I can do. You'll need to investigate this if you want it fixed.

**Comment by rybesh** [comment]
Yes, I started investigating it but didn't make much progress. I will return to it fairly soon however, as we would like to be able to upgrade to Flask 1.0. As soon as I have any further insight into the issue, I will post here.

**Comment by rybesh** [comment]
Running our app as an individual service under systemd ([as documented here](https://uwsgi-docs.readthedocs.io/en/latest/Systemd.html#one-service-per-app-in-systemd)) fixed this problem and we were able to upgrade to werkzeug 0.14.1.
