### ISSUE TITLE
Properly Detect Hashlib Algorithms Available [Python3]

### ISSUE THREAD

**Issue by Lvl4Sword** [pallets/werkzeug#1225]
- Describe what you expected to happen.

All algorithms available to actually be pulled

- If possible, include a minimal, complete, and verifiable example to help us identify the issue. This also helps check that the issue is not with your own code.

https://github.com/pallets/werkzeug/blob/master/werkzeug/security.py#L36 currently uses
```
algos = getattr(hashlib, 'algorithms', None)
```
which is None

This should instead be change to:
```
algos = getattr(hashlib, 'algorithms_available', None)
```
as verified in https://docs.python.org/3/library/hashlib.html#hashlib.algorithms_available

- Describe what actually happened. Include the full traceback if there was an exception.
```
algos = getattr(hashlib, 'algorithms', None)
print(type(algos))
<class 'NoneType'>
```

- List your Python and Werkzeug versions. If possible, check if this issue is already fixed in the repository.

Python version: Python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118] on linux
Wekzeug version: 0.13

Thank you!

**Comment by Lvl4Sword** [comment]
#1226 has been created for this.

**Comment by lepture** [comment]
Close it via https://github.com/pallets/werkzeug/pull/1282
