### ISSUE TITLE
Body of 412 responses not sent since ETag handling was added

### ISSUE THREAD

**Issue by lafrech** [pallets/werkzeug#1231]
On HTTP error, the response includes a message such as:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>413 Request Entity Too Large</title>
<h1>Request Entity Too Large</h1>
<p>The data value transmitted exceeds the capacity limit.</p>
```

Since Etag handling was added, 412 error response does not include this message anymore.

Below is the test script I used.

```python
#!/usr/bin/env python3

from werkzeug.exceptions import default_exceptions
from flask import Flask, abort


for http_exc in default_exceptions:

    app = Flask('test')
    client = app.test_client()

    @app.route('/')
    def test():
        abort(http_exc)

    response = client.get('/')
    assert response.status_code == http_exc

    if not response.get_data(as_text=True):
        raise ValueError('Missing data for HTTP error {}'.format(http_exc))
```

Feeding it to `git bisect` pointed me to https://github.com/pallets/werkzeug/commit/092e59a127de324517faa820e33b160372db8a85.

**Comment by mitsuhiko** [comment]
This is currently intentional because this is a side effect of how conditional requests are implemented.

**Comment by eruvanos** [comment]
Any update on this? I had to skip some requirements of a spec because of this.

**Comment by mitsuhiko** [comment]
I did not find a good way to fix this yet. The main issue is that from what I understand we must not send a response for precondition failed when triggered by an if-match.

**Comment by chenyosef-stratoscale** [comment]
+1.

By the way, the current behavior is not compatible with w3c https status code standard (https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) - which allow sending a body with 412 response code.

**Comment by ravidbro** [comment]
+1

**Comment by mitsuhiko** [comment]
We can just generally send bodies again :-/

**Comment by chenyosef-stratoscale** [comment]
@mitsuhiko Any ETA for that ?

**Comment by mitsuhiko** [comment]
Not atm. If someone sends a pr it can be faster.

**Comment by mitsuhiko** [comment]
I would just merge #1255. I'm not sure myself what's correct or not but since it broke people's stuff i would propose to undo this.

**Comment by davidism** [comment]
Yeah, I'm rebasing and adding a changelog now.

**Comment by mnowotka** [comment]
Hi,
I see this issue has been closed but this can;t be used because there is no official release that would include that change. Any chance to make a release (there wasn't any since Dec 2017)?
