### ISSUE TITLE
Add method for printing messages during server startup

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1234]
Werkzeug prints a couple lines when starting the server. Flask prints a bunch of extra information to the terminal from the run command, but has to check for the reloader and match the formatting. Instead, we should have a standard way to output messages during server startup. There should be support for style information and for not outputting on reload.

**Comment by oikake** [comment]
I can have a look at this. Are there any hints to start from? :)

**Comment by juped** [comment]
@mwizasimbeye11 and @teymour-aldridge will be working on this!

**Comment by davidism** [comment]
After working on the debugger and Flask runner for some other issues, I've decided this isn't useful enough to include at this time.
