### ISSUE TITLE
Add proxy fix support for x-forwarded-prefix

### ISSUE THREAD

**Issue by ilansh** [pallets/werkzeug#1237]
This header can be useful for apps where the root path is different behind proxy, for instance in my case using the traefik proxy - https://docs.traefik.io/basics/

**Comment by davidism** [comment]
If the proxy is stripping the prefix and adding this header, we're supposed to detect this header and add it to the URL before matching happens?

**Comment by davidism** [comment]
There are some other issues open about `ProxyFix` not supporting all the `Forwarded` headers (including the real `Forwarded` header). If you have time to create a PR that would be very helpful.

**Comment by ilansh** [comment]
No problem, I'll try to make some time for a new PR.

**Comment by ilansh** [comment]
As far as I understand, url matching is on the stripped urls (not adding the prefix from the header).  
Url building adds the prefix to the returned url.
