### ISSUE TITLE
Deprecate werkzeug.contrib.cache

### ISSUE THREAD

**Issue by lepture** [pallets/werkzeug#1249]
Werkzeug should definitely remove cache from itself. Werkzeug is designed for WSGI application. It seems cache has nothing to do with WSGI itself.

One certain decision in discussion [Remove unnecessary crud from werkzeug.contrib](https://github.com/pallets/werkzeug/issues/4) would be removing cache. We could release next version with a deprecated warning, and remove it totally in version 1.0.

There are lots of issues to solve, we need to focus on the important things. We can't make a good cache library within werkzeug.

Any feedbacks? @pallets/devteam-werkzeug

**Comment by lepture** [comment]
I'm closing issues related to cache.

@pallets/devteam-werkzeug please re-open it if you find the issue to be very important.

**Comment by lepture** [comment]
Flask-Caching has ported `werkzeug.contrib.cache`:

https://github.com/sh4nks/flask-caching/tree/master/flask_caching/backends

**Comment by davidism** [comment]
I'm going to disable the caching tests for now, it's causing too much uncertainty with other PRs.

**Comment by davidism** [comment]
The tests have been disabled, and instantiating a cache class shows a deprecation warning, "Werkzeug cache is deprecated as of version 0.15 and will be removed in 1.0."
