### ISSUE TITLE
Flask.test_client() methods should support files argument

### ISSUE THREAD

**Issue by aparamon** [pallets/werkzeug#1258]
Reincarnation of https://github.com/pallets/flask/issues/2645 , as suggested by @davidism .

Currently `Flask.test_client()` methods `get()`, `put()`, `post()` accept "data" argument but not "files" argument, which makes it incompatible with `requests`:
http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file

Making `Flask.test_client()` compatible with `requests` enables seamless transition between Flask unit and integration testing, e.g. via `pytest` fixtures.

A work-around via monkey-patching:
```python
orig_make_test_environ_builder = flask.testing.make_test_environ_builder
def make_test_environ_builder(*args, files=None, **kwargs):
    env = orig_make_test_environ_builder(*args, **kwargs)
    if files:
        env.files.update(files)
    return env
flask.testing.make_test_environ_builder = make_test_environ_builder
```

**Comment by davidism** [comment]
After some more thought, I'm going to close this for the same reason as #1376. All this would do is `data.update(files)`, it doesn't make anything about the format of the value easier, it just makes the code a little harder to reason about.

**Comment by dtracers** [comment]
I have a question about why this was closed?

I am trying to unit test file upload behavior in flask and am currently unable to get it to work at all.
Is there a solution for this for binary files?

https://stackoverflow.com/questions/56096412/requests-in-test-for-flask-app-is-has-no-files

**Comment by dtracers** [comment]
regardless of compatibility with requests input I need the files dict filled out for my test code which looks at files.  I have been unable to fill it out at all it is just always empty
