### ISSUE TITLE
redundancy

### ISSUE THREAD

**Issue by yangshuangjia123** [pallets/werkzeug#1261]
def application(*args):
            request = cls(args[-2])
            with request:
                return f(*args[:-2] + (request,))(*args[-2:])
        return update_wrapper(application, f)

args should be environ and start_response, and what *args[-2:] stands for?

**Comment by davidism** [comment]
You've left out part of the code, it appears to be a decorator, not the application itself. Where did you get that code?

**Comment by Derrreks** [comment]
this seems to be an old version of [`BaseRequest.application`](https://github.com/pallets/werkzeug/blob/master/werkzeug/wrappers.py#L281), but was changed a few months back in [this commit](https://github.com/pallets/werkzeug/commit/bffbd23c9a9667323010288b50d89f8982df9760)
