### ISSUE TITLE
Theming the werkzeug debugger ?

### ISSUE THREAD

**Issue by stuaxo** [pallets/werkzeug#1276]
Is there some info on themeing the werkzeug debugger?

![image](https://user-images.githubusercontent.com/179677/38509571-32544f30-3c1a-11e8-86d3-f1e762f46b67.png)

It would be nice to make the console stand out more (mockup just playing with web developer inspector tools).

I guess to make it really fun, the console could support the colourschemes from VTE.

**Comment by lepture** [comment]
It could be fun. But it will create a burden to maintain such thing. Instead, I would encourage you to create such a project by your own, and release it to PyPI.

**Comment by stuaxo** [comment]
It's in my list of things I don't have time to do properly.

What I should do is at least prototype up some possible improvements in case some else can find time to implement them.

**Comment by stuaxo** [comment]
Does the console part use some other library, or is it all just built in werkzeug ?
