### ISSUE TITLE
Multiple <path:...> allowed in rules

### ISSUE THREAD

**Issue by edk0** [pallets/werkzeug#1288]
I don't think there's a way multiple `<path:...>` elements could ever make sense.

As a simple illustration:
```python
ma = Map([Rule('/<path:a>/<path:b>', endpoint='blah')]).bind('localhost', '/')
d = {'a': 'x/y', 'b': 'y/z'}
print(d)
print(ma.match(ma.build('blah', d))[1])
```

Yields:
```
{'a': 'x/y', 'b': 'y/z'}
{'a': 'x', 'b': 'y/y/z'}
```

This can always happen if more than one element that accepts arbitrary data is present.

Pre-empting *all* the problems with ambiguity and `<path:...>` is hard, but this one is kind of straightforward.

**Comment by davidism** [comment]
I don't think I've seen anyone run into this. The match is valid, it's just that the rule is ambiguous. There can be multiple paths in a rule, they just can't be ambiguous.

```
/<path:a>/test/<path:b>
```

I'm not sure if it's worth checking for this.
