### ISSUE TITLE
FileStorage.save()'s performance depends on the amount of newlines in the file

### ISSUE THREAD

**Issue by bjrnio** [pallets/werkzeug#1292]
I ran some benchmarks with synthetic files of sizes ranging from 1MiB to 1GiB with and without newlines, and I found out a relationship between the time it takes FileStorage.save() to save a file to disk, and the file's amount of newline characters.

All testing was done on localhost and repeated three times. I did not to keep the actual milliseconds it took for each file to upload but I've drawn a graph that represents my results:

![Graph](https://user-images.githubusercontent.com/24278501/39749358-c760dba8-52b2-11e8-9dd3-fac0634ca3d1.png)

My testing reveals that a file of about 1GiB with +100M newlines takes +5min on average to save to disk, while the same size file with 0 newlines takes about 30s.

**My guess it's that it's shutil.copyfileobj()'s fault, but I'm not skilled enough to verify.**

_As a side note, I ran the same benchmarks against a Golang equivalent and it did not depend on the amount of newlines (Go 1.10.2 using io.Copy() to save a multipart.File to disk)._

**Comment by ThiefMaster** [comment]
I don't see how it would be related to newlines since this is all `copyfileobj` does:

```python
def copyfileobj(fsrc, fdst, length=16*1024):
    """copy data from file-like object fsrc to file-like object fdst"""
    while 1:
        buf = fsrc.read(length)
        if not buf:
            break
        fdst.write(buf)
```

Anyway, since `FileStorage.save()` does nothing relevant besides calling this function, I don't see how this is related to werkzeug unless it happens *only* with werkzeug but not when using `copyfileobj` directly.

**Comment by bjrnio** [comment]
I see, and after thorough thinking I realized my benchmarking was wrong, sorry 😅
