### ISSUE TITLE
What typically causes ValueError: Invalid accept_ranges value" in Werkzeug?

### ISSUE THREAD

**Issue by seanballais** [pallets/werkzeug#1295]
I'm trying to solve this [StackOverflow post](https://stackoverflow.com/questions/50320202/flask-static-files-return-500-error).

It got me wondering. In what cases would Werkzeug throw a `ValueError` related to invalid accept ranges? I read the source code but I am unable to connect the dots so I am left confused.

**Comment by davidism** [comment]
The traceback shown in the linked post shows the stack that led to that exception.
