### ISSUE TITLE
How about make a RegexConverter default?

### ISSUE THREAD

**Issue by qingyunha** [pallets/werkzeug#1305]
```python
class RegexConverter(BaseConverter):

    def __init__(self, map, regex):
        BaseConverter.__init__(self, map) 
        self.regex = regex

DEFAULT_CONVERTERS["regex"] = RegexConverter
```
so I do not need to write conveter for every  regex.

**Comment by ThiefMaster** [comment]
You can add this in your application if you need one. Adding custom converters on the url map is explicitly supported.

(Chances are good that you do not need one, and we do not want to encourage people to use raw regexps there.)

**Comment by qingyunha** [comment]
Thank you for your answer.
But I still have a question. Internally, it does use regexp. you need a regexp when writing a converter, so what's the difference here except the `to_python` and `to_vaule` interface. 
At least, I think that provides a regex converter is a convenience to some ad-hoc pattern
