### ISSUE TITLE
request.authorization encoding is latin1...

### ISSUE THREAD

**Issue by Flyguy** [pallets/werkzeug#1323]
How about a cyrillic logins or passwords ? :(

**Comment by ThiefMaster** [comment]
Sounds like charsets in http authorization are a clusterfuck: https://stackoverflow.com/q/7242316/298479
Anyway, if modern browsers support UTF8 there so should werkzeug.

**Comment by Flyguy** [comment]
That is. But the UTF-8 encoding is a standard de facto for the web.
I don't know about ALL browsers. But my firefox sent this as utf-8...
Also the code of RestSharp uses UTF-8 for this... https://github.com/restsharp/RestSharp/blob/develop/RestSharp/Authenticators/HttpBasicAuthenticator.cs

**Comment by Flyguy** [comment]
Anyway, latin1 so limited encoding...

**Comment by davidism** [comment]
The Werkzeug code was written well before the new spec that allows UTF-8 in the authorization header. If you'd like support for this sooner, I'd be happy to review a pull request.
