### ISSUE TITLE
[Critical] check_password_hash return true for empty string compare

### ISSUE THREAD

**Issue by dhruvinsh** [pallets/werkzeug#1326]
Not sure am i missing something or not, but empty string password check against check_password_hash 
 gives True.

```
>>> p = 'pbkdf2:sha256:50000$mMY9AjJW$e6607801621262f892cbb66f8f774aa8c865c11dda7776bbf1f4cc7ae5984842'
>>> from werkzeug.security import check_password_hash, generate_password_hash
>>> check_password_hash(p,'')
True
>>> check_password_hash(p,'a')
False
>>> check_password_hash(p,'')
True
>>> werkzeug.__version__
'0.14.1'
```

and it was devastating it was on a production server.

**Comment by ThiefMaster** [comment]
You know for sure that this particular hash was not created from an empty string?

**Comment by davidism** [comment]
Can't reproduce this. In the future, if you think you have found an active security issue, please report it responsibly in private to one of the maintainers or security@palletsprojects.com.

**Comment by dhruvinsh** [comment]
nope. it wasn't. it was actual password.

**Comment by dhruvinsh** [comment]
@davidism yeah you are right. My bad, should be more responsible. My sincere apology. 


By the way even I wasn’t able to regenerate the issue if i generate hash from scratch. One that stored on a database and published here, does accept empty string and actual password too.

**Comment by ThiefMaster** [comment]
Which Python version are you using?

**Comment by ThiefMaster** [comment]
I just checked again, and the hash you have in your initial post IS for an empty string:

```
>>> _hash_internal('pbkdf2:sha256', 'mMY9AjJW', '')
('e6607801621262f892cbb66f8f774aa8c865c11dda7776bbf1f4cc7ae5984842',
 'pbkdf2:sha256:50000')
```

As you can see, that's the same hash as in your initial post.

**Comment by dhruvinsh** [comment]
@ThiefMaster  thanks for investing your time. I really appreciate.

> Maybe it's a collision

yes you were absolutely right, due to loophole in a program, all the hash get updated with empty string. and same hash i posted does not accept actual password. 
Due to above it always get checked against database (in case of empty string) or ldap (in case of string) and that was causing the issue.
