### ISSUE TITLE
Add support for chunked responses on test server

### ISSUE THREAD

**Issue by brunoais** [pallets/werkzeug#1327]
I believe it would be a good addition to werkzeug's internal testing server if it were able to process chunked HTTP responses.
I already implemented the protocol not long ago and I believe I could contribute with such code.

**Comment by RonnyPfannschmidt** [comment]
the dev-server is very intentionally low powered and small in scope - even if such code is contributed - someone will have to maintain it

**Comment by brunoais** [comment]
Does that mean the answer is "no"?

**Comment by lepture** [comment]
@brunoais I think it is "no". But you can try to send a PR, we will review it.

**Comment by brunoais** [comment]
Alright, will try an update with the minimum needed to check what I have

**Comment by davidism** [comment]
Closing due to the reasons given in the linked PR. If you feel strongly that the dev server needs to send chunked responses and can explain why, I might reconsidder, but the PR had other issues anyway so a new one would need to be made.

**Comment by brunoais** [comment]
accepted
