### ISSUE TITLE
Base classes for werkzeug exceptions

### ISSUE THREAD

**Issue by Midnighter** [pallets/werkzeug#1331]
My use-case is specifically for ignoring errors passed on to sentry. It would be nice if a distinction could be introduced for 4xx and 5xx errors. What I mean is that at the moment all exceptions are children of `werkzeug.exceptions.HTTPException`. My suggestion is to introduce two children of that base class (maybe `HTTP4XXException` and `HTTP5XXException`) from which all the specific error classes inherit that would allow me to catch or ignore all corresponding errors at once.

**Comment by davidism** [comment]
It sounds reasonable at first, but we've had a lot of issues recently in Flask since fixing error handlers so that `Exception` actually handles *all* exceptions, and `HTTPException` handles *all* numbered exceptions. So I'm not sure that providing more opportunities for people to misunderstand these is good.

You should be able to achieve what you want with [`abc.ABCMeta.register`](https://docs.python.org/3/library/abc.html#abc.ABCMeta.register).

**Comment by Midnighter** [comment]
If I register `HTTP4xxException` on everyone of the corresponding werkzeug exceptions, I might as well type it out on the sentry ignore list. Basically, instead of writing:

```python
SENTRY_CONFIG = {
            'ignore_exceptions': [
                werkzeug.exceptions.BadRequest,
                werkzeug.exceptions.Unauthorized,
                werkzeug.exceptions.Forbidden,
                werkzeug.exceptions.NotFound,
                werkzeug.exceptions.MethodNotAllowed,
            ]
        }
```

I would like to say:

```python
SENTRY_CONFIG = {
            'ignore_exceptions': [
                werkzeug.exceptions.HTTP4xxException
            ]
        }
```

This wouldn't change anything about `HTTPException` still handling all numbered exceptions.

**Comment by davidism** [comment]
I understand that, but it doesn't seem like a big deal to me. It would make people think that adding an error handler for `HTTP4XXException` is a good (or at least possible) idea. Is there no way to ignore `HTTPExcpetion` then explicitly include `InternalServerError`?

**Comment by Midnighter** [comment]
Not that I know of but I can live with the disagreement.
