### ISSUE TITLE
RE: Shortly.py

### ISSUE THREAD

**Issue by silver2row** [pallets/werkzeug#1332]
Hello,

I just wanted to say that your shortly.py software works and it neat. Way to go, fellows/ladies.

Seth

P.S. End of issue. Oh and if you are just giving away examples, let me know. I would like to learn more.

**Comment by ThiefMaster** [comment]
Cool, but this is neither a bug nor a feature request so I'm going to close this issue.

BTW, if you plan to write an url shortener it's probably better to use Flask instead of Werkzeug directly.
