### ISSUE TITLE
Reloader not working in Flask Docker container

### ISSUE THREAD

**Issue by angadkalra** [pallets/werkzeug#1336]
I am running multiple docker containers (Node, Nginx, Flask, ElasticSearch) using a docker compose file. Whenever I change something in my flask files, flask outputs to terminal saying it detected the change, but then it never reloads. It just outputs this line and nothing else: 
"flask_1          |  * Detected change in '/var/flask/flaskr/api.py', reloading"

then all my api endpoints in flask don't work after.

**Comment by davidism** [comment]
You need to provide a Minimal, Complete, and Verifiable example demonstrating this, otherwise there's nothing we can do. I personally don't use Docker, so your best bet for a fix is investigating this and submitting a patch.

**Comment by davidism** [comment]
Anecdotally, I know there are plenty of Docker examples out there that *do* reload.
