### ISSUE TITLE
Send werkzeug default outputs to Apache2 error.log via WSGI

### ISSUE THREAD

**Issue by BioComSoftware** [pallets/werkzeug#1343]
This issue is also on [Stackoverflow](https://stackoverflow.com/questions/51823382/default-logging-lines-from-flask-app-route-decorator-not-sent-to-apache2-error). 

I cannot get the Flask default output (log lines seen when running an app via `flask run`, which I believe are generated by the `werkzeug` logger) sent via WSGI to Apache2's `error.log`.

`app.logging.<level>(message)` lines within the `app.py` code work fine, and are sent by WSGI to the Apache2 log. But, the default output (such as seen below) is NOT being sent.  

**Q: Is there a way to send the default (debug) output from flask, started ia WSGI and Apache2, to the Apache error.log?**

```
127.0.0.1 - - [13/Aug/2018 14:44:45] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [13/Aug/2018 14:44:45] "GET /static/css/selectize.css HTTP/1.1" 200 -
127.0.0.1 - - [13/Aug/2018 14:44:45] "GET /static/css/material.min.css HTTP/1.1" 200 -
127.0.0.1 - - [13/Aug/2018 14:44:46] "GET /static/css/style.css HTTP/1.1" 200 -
```

**Comment by ThiefMaster** [comment]
These log lines are from the dev server - in any other setup (ie in production) it's up to your webserver to log requests.

**Comment by BioComSoftware** [comment]
We're in a development environment. No way to send them through the sys.stdout used by WSGI?

**Comment by ThiefMaster** [comment]
Even if it's for development - if you use a real webserver, it's the web server's responsibility to log requests.

**Comment by BioComSoftware** [comment]
(Sorry for the change of comment. When I read your answer on Stack, I suddenly understood what you meant. Thanks again!)
