### ISSUE TITLE
GitHub releases are out of sync with PyPI

### ISSUE THREAD

**Issue by rsyring** [pallets/werkzeug#1347]
https://github.com/pallets/werkzeug/releases

Shows the latest release as 0.13 but PyPI shows the latest release as 0.14.1.

**Comment by davidism** [comment]
I guess GitHub changed their interface, because there's a little box that says "show 2 newer tags" that shows them.

**Comment by ThiefMaster** [comment]
tags != released; you need to manually create the release if you want it to show up nicely
