### ISSUE TITLE
MIMEAccept._value_matches and accept_XXX issue

### ISSUE THREAD

**Issue by alexey-ku77** [pallets/werkzeug#1348]
I consider MIMEAccept `accept_html`, `accept_xhtml` and `accept_json` properties **not applicable in real projects** in current implementation.
Current implementation makes accept_html to return True for application/json requests(xhr) and accept_json to return True for text/html requests in modern browsers.

DETAILS:
These properties rely on several checks for presence of mimetypes in accept header:

https://github.com/pallets/werkzeug/blob/778f482d1ac0c9e8e98f774d2595e9074e6984d7/werkzeug/datastructures.py#L1808-L1828

But `__contains__` method used for presence checks rely on MIMEAccept._value_matches method.
That method always return True when `*/*` is listed in accept mime types.
Problem is that `*/*` mimetype is used on common browsers.

Chrome: `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8`
Safari: `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`
Firefox: `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`

This make all 3 method to give True in different situations, which is wrong.

https://github.com/pallets/werkzeug/blob/778f482d1ac0c9e8e98f774d2595e9074e6984d7/werkzeug/datastructures.py#L1679-L1683
https://github.com/pallets/werkzeug/blob/778f482d1ac0c9e8e98f774d2595e9074e6984d7/werkzeug/datastructures.py#L1782-L1806

**Comment by davidism** [comment]
If we stop looking for `*/*` and that's the only thing a client sends, then we have the opposite problem: nothing appears accepted. If `text/html` and `application/json` are both accepted, the properties still don't help you decide which is *more* accepted. That's the job of `best_match()`.

It feels like the properties are meant as shortcuts for "if the client will accept this, I'm going to return it" as opposed to using `best_match()` for "I'll return what the client most wants".

Presumably when making JS requests to an API you know switches on `Accept`, you would send a header saying you specifically want JSON, as opposed to the browser's default catch-all. If a server was using the properties in that case, they would do `if accept_html return html else return json`.
