### ISSUE TITLE
uri_to_iri incorrectly handles %20

### ISSUE THREAD

**Issue by cziebuhr** [pallets/werkzeug#1356]
uri_to_iri incorrectly turns %20 in query string into ' ', which violates RFC 3987.
'+' and other percent encoding is handled correctly.
```
>>> from werkzeug.urls import uri_to_iri
>>> uri_to_iri('http://example.com/?arg=foo%20bar+baz%3dasdf')
'http://example.com/?arg=foo bar+baz%3dasdf'
```
Expected result: 'http://example.com/?arg=foo%20bar+baz%3dasdf'

In my setup, a 3rdparty library broke, because it insists that werkzeug.wrappers.Request.url doesn't contain spaces.

**Comment by davidism** [comment]
Reading RFC 3986 2.2, which is referred to by RFC 3987, ASCII space is not listed as a reserved character. Would you be specific about how the current implementation is not compliant with the RFC?

**Comment by cziebuhr** [comment]
It's not reserved, but also not unreserved. From RFC3987:
```
absolute-IRI   = scheme ":" ihier-part [ "?" iquery ]
iquery         = *( ipchar / iprivate / "/" / "?" )
ipchar         = iunreserved / pct-encoded / sub-delims / ":" / "@"
iunreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~" / ucschar
pct-encoded    = "%" HEXDIG HEXDIG
sub-delims     = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
iprivate       = %xE000-F8FF / %xF0000-FFFFD / %x100000-10FFFD
```

**Comment by davidism** [comment]
So because it's not unreserved, that means it should always be percent encoded?

**Comment by cziebuhr** [comment]
I assume so. At least I can't find a path through the ABNF where a space character is valid for the query part.

**Comment by davidism** [comment]
Can you take a look at @lepture's PR #1363? I had a comment about applying the same thing to `iri_to_uri`.

**Comment by cziebuhr** [comment]
I'm a bit confused how the 'unsafe' parameter works at all. e.g. 'foo%10bar' gets unquoted to 'foo\x10bar'. I assume that the whole range \x00-\x1f must also be considered unsafe.

**Comment by lepture** [comment]
@cziebuhr I think the current implementation of `uri_to_iri` is correct, but the `Request.url` should be in **URI** instead of **IRI**. Where did you get the error? What is your use case?

**Comment by cziebuhr** [comment]
I'm using authlib, which can use flask or django as backend. It accesses flask.request.url as common demoninator to form a non-dependant OAuth2Request object.

But I still think uri_to_iri needs some fixes. An IRI is an URI, where the unreserved character class is extended with UCS beyond U+007F. Nonprintable characters (U+0000 - U+001F) are not valid for both. I suggest changing url_unquote to always treat those characters as unsafe.
```
>>> uri_to_iri('http://example.com/foo=abc%0axyz')
'http://example.com/foo=abc\nxyz'
```

**Comment by lepture** [comment]
But IRI is not URI. I think Request.url should be URI instead of IRI, that is enough. @davidism what do you think?

BTW, I’ve added a workaround in Authlib: https://github.com/lepture/authlib/commit/d8ab09fb97169fc47070f48c2ede43348f1feff0

**Comment by davidism** [comment]
A URL is a URI, and IRI is a generalization of URI. The PR seemed fine and addressed the issue, I think it should be merged.

**Comment by cziebuhr** [comment]
```
>>> import rfc3987
>>> rfc3987.parse('http://example.com/foo=abc\nxyz', rule='IRI')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/rfc3987.py", line 462, in parse
    raise ValueError('%r is not a valid %r.' % (string, rule))
ValueError: 'http://example.com/foo=abc\nxyz' is not a valid 'IRI'.
>>> rfc3987.parse('http://example.com/foo=abc%0axyz', rule='IRI')
{'query': None, 'authority': 'example.com', 'path': '/foo=abc%0axyz', 'fragment': None, 'scheme': 'http'}
```
Same for URI
