### ISSUE TITLE
http version

### ISSUE THREAD

**Issue by zhangatao** [pallets/werkzeug#1362]
hello,i want know http version in werkzeug？

**Comment by ThiefMaster** [comment]
if you mean http instead of wsgi: you want something like uwsgi or gunicorn that speaks both http and wsgi.

**Comment by ThiefMaster** [comment]
It doesn't, it removes hop-by-hop headers which are not supposed to be forwarded. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

**Comment by zhangatao** [comment]
I have some questions. 1. Why are the headers of the request HTTP/1.1, but the headers of the response are HTTP/1.0?
2. Is there any other way to make the responding headers also follow HTTP/1.1, now I know that using nginx can make the responding headers comply with HTTP/1.1?

**Comment by ThiefMaster** [comment]
How are you accessing werkzeug? If you use the dev server, that one is probably http1.0-only. Use a real webserver if you want HTTP/1.0 or HTTP/2

**Comment by zhangatao** [comment]
太感谢了，我用flask开发服务，但是现在的服务是不稳定的。我需要用nginx做个代理了。

**Comment by zhangatao** [comment]
Thank you very much, I used flask to develop services, but the service is unstable now. I need to use nginx as a proxy.

**Comment by ThiefMaster** [comment]
Most important you need to use a real WSGI container like uwsgi or gunicorn and DO NOT use `flask run` or `app.run()` - those are not suitable for production.

**Comment by zhangatao** [comment]
Yes, big brother. I used gunicorn to wrap the flask service. But still not very stable.

**Comment by zhangatao** [comment]
Thank you very much
