### ISSUE TITLE
DeprecationWarnings importing ABCs from collection module

### ISSUE THREAD

**Issue by lucaswerkmeister** [pallets/werkzeug#1366]
When running tests of a Flask app, I’m seeing the following deprecation warnings from Werkzeug:
```
/usr/lib/python3.7/site-packages/werkzeug/datastructures.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working                                                                                                                                       
  from collections import Container, Iterable, MutableSet
/usr/lib/python3.7/site-packages/werkzeug/datastructures.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working                                                                                                                                       
  from collections import Container, Iterable, MutableSet
```
The abstract base classes imported here moved to the [`collections.abc`](https://docs.python.org/3/library/collections.abc.html) module in Python 3.3, and importing them from [`collections`](https://docs.python.org/3/library/collections.html) only works up to Python 3.7.

Does Werkzeug aim to support Python versions before 3.3, or can the import simply be changed unconditionally?

I’m on Python 3.7.0, Werkzeug 0.14.1.

**Comment by davidism** [comment]
#1351

**Comment by lucaswerkmeister** [comment]
Apologies, I have no idea why I didn’t find that issue when searching. (I did search, I promise! But apparently not well?)
