### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by agoldhammer** [pallets/werkzeug#1371]
The following error is noted when using Flask with Python 3.7:
/Users/agold/anaconda/envs/nooze/lib/python3.7/site-packages/werkzeug/datastructures.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Container, Iterable, MutableSet

**Comment by ThiefMaster** [comment]
Already fixed by #1367 but probably not in any release. Anyway, safe to ignore for now.
