### ISSUE TITLE
ImmutableMultiDict expansion breaks on Python 3.7.1

### ISSUE THREAD

**Issue by briancurtin** [pallets/werkzeug#1379]
I have a Flask app that broke during an upgrade from Python 3.7.0 to 3.7.1 and it appears to be around expansion of an `ImmutableMultiDict` (via `flask.request.args`). Our code was expecting a list of values for each query param key, but we're currently getting a single string (so iterating characters of a string instead of iterating items in the list).

I've been trying to track down a change in CPython that would have introduced something like this to figure out why, but haven't found anything yet and wanted to get some info out there in case others are seeing the same. If I find something there I'll report back.

The following code displays what we're seeing:

    from werkzeug import ImmutableMultiDict
    imd = ImmutableMultiDict({"key": ["value1", "value2"]})
    def fn(**kwargs):
        print(kwargs)

On 3.7.0 we had

    >>> fn(**imd)
    {'key': ['value1', 'value2']}

and with 3.7.1 we move to

    >>> fn(**imd)
    {'key': 'value1'}

With either version `imd.getlist("key")` properly returns `['value1', 'value2']`.

**Comment by davidism** [comment]
The only thing CPython could have changed was the implementation of `**kwargs` to unpack using `data.items()` instead of `dict.items(data)`. `MultiDict.items()` always returned the first value, so CPython must have previously been using `dict.items(data)

**Comment by briancurtin** [comment]
Thanks for the quick response! The alternative looks reasonable, and in fact, the point where we were doing this `**m` was probably not ideal anyway, so I may just refactor away from that sort of behavior entirely.

**Comment by dequis** [comment]
>The only thing CPython could have changed was the implementation of `**kwargs` to unpack using `data.items()` instead of `dict.items(data)`.

Yep, that change is https://github.com/python/cpython/pull/8624 and got backported to python 3.7.1 and 3.6.7

**Comment by km445** [comment]
If somebody was using url_for("my_route", **request.args) then the work-around could be url_for("my_route", **dict(request.args.lists())). It still generates a url with multiple parameters with same name, python 3.6.9+ included. Tested with Flask==1.1.1
