### ISSUE TITLE
Container, Iterable, MutableSet must be import from collections.abc

### ISSUE THREAD

**Issue by SaitoTsutomu** [pallets/werkzeug#1382]
At line 16 of datastructures.py.

asis: `from collections import Container, Iterable, MutableSet`
tobe: `from collections.abc import Container, Iterable, MutableSet`
or
```
try:
    from collections.abc import Container, Iterable, MutableSet
except:
    from collections import Container, Iterable, MutableSet  # for 2.7
```

Because, `from collections import Container, Iterable, MutableSet` is deprecated and deleted at python 3.8.

**Comment by davidism** [comment]
Duplicate of #1367
