### ISSUE TITLE
layout.html v0.14.1 license

### ISSUE THREAD

**Issue by Silviu-Caprar** [pallets/werkzeug#1385]
Hi,

Can you please specify which BSD applies on the file https://github.com/pallets/werkzeug/blob/0.14.1/examples/cupoftee/templates/layout.html ?
Is it the one from the LICENSE file or another ? Cause there is no version specified in the above file and from what I've noticed, there are other files, like https://github.com/pallets/werkzeug/blob/0.14.1/docs/werkzeugext.py which have an older bsd license.

Thank you

**Comment by davidism** [comment]
The same license as the rest of the project: BSD 3-Clause.
