### ISSUE TITLE
check_password_hash() fail

### ISSUE THREAD

**Issue by wlbentley** [pallets/werkzeug#1386]
MacOS 10.14.1.
Python 3.7.0
Werkzeug 0.14.1 installed with Pipenv, version 2018.7.1. 

### What I Expect to Happen
Working through Miguel Grinberg's [Flask Mega-Tutorial Part V](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-v-user-logins), where he demonstrates how to verify a hash using `check_password_hash`:
```
>>> from werkzeug.security import check_password_hash
>>> check_password_hash(hash, 'foobar')
True
>>> check_password_hash(hash, 'barfoo')
False
```

### What Actually Happens
Trying to follow along, an error is thrown:
```
Python 3.7.0 (default, Aug 17 2018, 21:14:48)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from werkzeug.security import check_password_hash
>>> check_password_hash(hash, 'foobar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/william/Virtualenvs/flask-mega-8I8MJhrT/lib/python3.7/site-packages/werkzeug/security.py", line 245, in check_password_hash
    if pwhash.count('$') < 2:
AttributeError: 'builtin_function_or_method' object has no attribute 'count'
>>>
```

An earlier example with `generate_password_hash` worked as expected:
```
>>> from werkzeug.security import generate_password_hash
>>> hash = generate_password_hash('foobar')
>>> hash
'pbkdf2:sha256:50000$vT9fkZM8$04dfa35c6476acf7e788a1b5b3c35e217c78dc04539d295f011f01f18cd2175f'
```

**Comment by davidism** [comment]
I can't reproduce this issue. You're using the name `hash`, which is already the name of a built-in function. It looks like you've inadvertently passed that function to `check_password_hash`, rather than a string.

**Comment by wlbentley** [comment]
My error: I had inadvertently left `hash` undefined when I ran `check_password_hash`. Works as expected now. Thank you for the help.
