### ISSUE TITLE
App stops serving requests after watchdog is installed

### ISSUE THREAD

**Issue by Forever-Young** [pallets/werkzeug#1388]
Without watchdog dev server (flask) works ok, but right after installing watchdog, it can't serve one request, just no answer.
No errors in the console, it loads all apps, reloads with watchdog.
How can I debug what's happening inside?

**Comment by grahamlyons** [comment]
@Forever-Young, could you provide a minimal example that someone can use to recreate this?

**Comment by eltonlaw** [comment]
Hi, I tried to recreate this. I setup a basic hello world Flask app and got a request from it. Then I installed and started watchdog and I didn't encounter any errors getting another request. What does your setup look like?

**Comment by Forever-Young** [comment]
I'll try to make minimal example soon. App is pretty big, in docker
container and so on.
