### ISSUE TITLE
Rewrite Test Client's Redirection Code

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/werkzeug#139]
The current redirection code in the test client is not perfect. First of all it's in violation of HTTP in so far as that it requires a special capitalization of the "Location" header but the bigger problem is that it uses an internal redirection client which makes subclassing harder than necessary.

**Comment by davidism** [comment]
There are still open issues about the test client redirect handling, but it looks like the ones mentioned here, subclassing and header capitalization, were handled in https://github.com/pallets/werkzeug/commit/4ca6e705a5c57f4ab2f2d16391c33b798962fc66.

**Comment by davidism** [comment]
#1402
