### ISSUE TITLE
Why does secure_filename() remove a leading underscore?

### ISSUE THREAD

**Issue by Siecje** [pallets/werkzeug#1398]
Why does `werkzeug.utils.secure_filename()` remove a leading underscore? Is it safe to add it back after?

```
>>> from werkzeug import utils
>>> utils.secure_filename('_why.py')
'why.py'
```

https://github.com/pallets/werkzeug/blob/d129d17066768238139b8f8a5d667d9a4f4d68db/tests/test_utils.py#L298

**Comment by davidism** [comment]
Seems to be for normalization purposes. You can do whatever you want to the filenames, but evaluating their security is up to you.
