### ISSUE TITLE
generate_etag raises TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by lafrech** [pallets/werkzeug#1408]
Using Python3.

`raw_data` can be arbitrary data, or the output of my view function (a Python `dict`).

```py
        ...
        data = json.dumps(raw_data, sort_keys=True)
        return generate_etag(data)
```

```
    ...
    return md5(data).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

This works:

```py
        ...
        data = json.dumps(raw_data, sort_keys=True)
        return generate_etag(bytes(data, 'utf-8'))
```

Should the same fix be applied in `generate_etag` that was [applied in hash_pin](https://github.com/pallets/werkzeug/commit/7111a5b6c95869024968dcdcfe370fb79fc5fb39)?

Or am I misunderstanding the usage of `generate_etag`?

**Comment by lafrech** [comment]
I just noticed there's another `generate_etag` implementation using [here](https://github.com/pallets/werkzeug/blob/4515c15d0126b7c913f7a0851b0e8e45c1c56b9c/werkzeug/wsgi.py#L744):

```py
    def generate_etag(self, mtime, file_size, real_filename):
        if not isinstance(real_filename, bytes):
            real_filename = real_filename.encode(get_filesystem_encoding())
        return 'wzsdm-%d-%s-%s' % (
            mktime(mtime.timetuple()),
            file_size,
            adler32(real_filename) & 0xffffffff
)
```

It uses a similar mechanism.

I guess unlike `hash_pin` we'd set `errors` to `'strict'`:

```py
def generate_etag(data):
    """Generate an etag for some data."""
    if isinstance(data, text_type):
        data = data.encode('utf-8', 'strict')
    return md5(data).hexdigest()
```

Should we use `to_native`, then?

```py
def generate_etag(data):
    """Generate an etag for some data."""
    return md5(to_native(data)).hexdigest()
```

**Comment by davidism** [comment]
Looking over this again, I'm not convinced this should change. I don't understand why you would do the example you showed where you return a manually generated etag. The etag should represent the stream of data being returned, which should be bytes. If you're using the standard `Response` wrapper, it already provides a correct way to do this:

```python
response = Response(json.dumps(data), content_type="application/json")
response.add_etag()
return response
```

**Comment by lafrech** [comment]
> The etag should represent the stream of data being returned, which should be bytes.

I don't claim any expertise, but AFAIU, the ETag can be anything.

https://en.wikipedia.org/wiki/HTTP_ETag

> Common methods of ETag generation include using a collision-resistant hash function of the resource's content, a hash of the last modification timestamp, or even just a revision number.

This said, if the user wants to specify a manual ETag, he does not need to use `generate_etag`.

If `generate_etag` is only meant to be called internally and if it is always fed bytes, then I guess it is fine to leave it as is.

In my framework, the ETag data is a Python `dict` so I have to convert it to bytes (`bytes(data, 'utf-8')`) before hashing it. Using my own `generate_etag` function is not an issue.
