### ISSUE TITLE
URL from pypi is invalid

### ISSUE THREAD

**Issue by ssbarnea** [pallets/werkzeug#1427]
If you go to https://pypi.org/project/Werkzeug/ and click homepage you get a 404 because homepage is https://www.palletsprojects.org/p/werkzeug/ instead https://github.com/pallets/werkzeug

**Comment by ThiefMaster** [comment]
Correct link is https://palletsprojects.com/p/werkzeug/ - PR will be appreciated! :)

**Comment by davidism** [comment]
Already fixed in master.
