### ISSUE TITLE
Response headers come back in alphabetical order A->Z->a->z

### ISSUE THREAD

**Issue by elitest** [pallets/werkzeug#1432]
Not sure if this is a flask issue or a werkzeug issue.
---

### Expected Behavior
With the code:

```python
@app.route('/')
def something():
        r = ''
        response = make_response(r)
        response.headers['header-a'] = 'something'
        response.headers['Header-c'] = 'something'
        response.headers['Header-b'] = 'something'
```
I believe the headers should be received by the client in the order that the program was written in:
```
header-a
Header-c
Header-b
```
### Actual Behavior
Instead they are received alphabetically from A->Z and then a->z.
```
Header-b
Header-c
header-a
```
### Environment

* Python version: 2.7.15+ on Linux
* Flask version: 1.0.2
* Werkzeug version: 0.14.1

I'm not sure there is a good reason that the headers should be re-ordered and there are multiple reasons that they shouldn't be re-ordered.

**Comment by ThiefMaster** [comment]
https://tools.ietf.org/html/rfc2616#section-4.2

> The order in which header fields with differing field names are
> received is not significant. However, it is "good practice" to send
> general-header fields first, followed by request-header or response-
> header fields, and ending with the entity-header fields.

So I don't think the order matters, especially for custom headers. I think you should mention the "multiple reasons" why header order should be preserved. Most likely we store them in a Python dict at some point, which are not ordered (before Python 3.7)

**Comment by davidism** [comment]
I can't reproduce your issue. `Headers` stores its values internally as a list, which is only appended to.

```pycon
>>> from werkzeug.datastructures import Headers                                                                                                                                                               
>>> h = Headers()                                                                                                                                                                                             
>>> h["header-a"] = "a"                                                                                                                                                                                       
>>> h["Header-c"] = "c"                                                                                                                                                                                        >>> h["Header-b"] = "b"                                                                                                                                                                                       
>>> h                                                                                                                                                                                                         
Headers([('header-a', 'a'), ('Header-c', 'c'), ('Header-b', 'b')])
>>> h.to_wsgi_list()                                                                                                                                                                                          
[('header-a', 'a'), ('Header-c', 'c'), ('Header-b', 'b')]
```
