### ISSUE TITLE
Expected behavior of the description in the exception traceback

### ISSUE THREAD

**Issue by kelvins** [pallets/werkzeug#1438]
I'm trying to create the following custom exception:

```python
from werkzeug.exceptions import BadRequest


class FieldsRequired(BadRequest):
    def get_description(self, environ=None):
        return "The following fields are required: {}".format(self.description)


if __name__ == "__main__":
    raise FieldsRequired("id, name")
```

But when the `FieldsRequired` exception is raised it shows the following traceback:

```bash
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    raise FieldsRequired("id, name")
__main__.FieldsRequired: 400 Bad Request: id, name
```

It only shows the `description` parameter passed to the `__init__`. As I understood it happens because it is calling the `self.description` instead of the `self.get_description()` in the [`__str__` method](https://github.com/pallets/werkzeug/blob/master/werkzeug/exceptions.py#L183).

Is this the expected behavior? Shouldn't it show the following traceback?

```bash
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    raise FieldsRequired("id, name")
__main__.FieldsRequired: 400 Bad Request: The following fields are required: id, name
```

I'm using Python 2.7.10 and Werkzeug 0.14.1.

**Comment by davidism** [comment]
Yes, the traceback message is different than the response message.
