### ISSUE TITLE
Sensitive Variable Support

### ISSUE THREAD

**Issue by kennethreitz** [pallets/werkzeug#145]
Thinking out loud here.

I saw Django's `sensitive_variables` feature for the first time today. Seems like a great idea.

https://docs.djangoproject.com/en/dev/howto/error-reporting/#sensitive_variables

@mitsuhiko any thoughts on adding support for this into werkzeug?

**Comment by davidism** [comment]
Sensitive variable markup in Django seems to be for two things: debug output and error logging / emails. Given that the debugger should only be run in development, and it can evaluate code, I don't think the added complexity is needed. And we don't log any data with exceptions, that would be something handled specifically by a project, and I don't think that's something that falls enough into Werkzeug's scope.
