### ISSUE TITLE
Wrong index when trusting IP addresses on X-Forwarded-For

### ISSUE THREAD

**Issue by MrBlaise** [pallets/werkzeug#1461]
https://github.com/pallets/werkzeug/blob/4bdffd1a0a018af2f690bb855145887d8fa36e75/werkzeug/middleware/proxy_fix.py#L163

I believe the code should read `return values[-trusted+1]`, because the client's IP should be the first untrusted IP from the right. If we have 3 proxies behind our app and we set x_for to 3, it will actually use the latest proxy's IP as REMOTE_ADDR instead of the user's.

**Comment by davidism** [comment]
Can you provide a reference for "the client's IP should be the first untrusted IP from the right".

**Comment by MrBlaise** [comment]
From here: http://nginx.org/en/docs/http/ngx_http_realip_module.html#real_ip_header

> If recursive search is enabled, the original client address that matches one of the trusted addresses is replaced by the last non-trusted address sent in the request header field.

But it also makes sense. If we trust 3 proxies than we know that the last 3 values will be the IP addresses of the proxies and the 4th must be the user. That is my understanding.

**Comment by davidism** [comment]
From Wikipedia:

> The general format of the field is:
> 
>     X-Forwarded-For: client, proxy1, proxy2
> 
> where the value is a comma+space separated list of IP addresses, the left-most being the original client, and each successive proxy that passed the request adding the IP address where it received the request from. In this example, the request passed through proxy1, proxy2, and then proxy3 (not shown in the header). proxy3 appears as remote address of the request.

**Comment by davidism** [comment]
The Wikipedia version matches my experience.

**Comment by davidism** [comment]
I'm not familiar with Nginx's realip module, but that appears to be a description of its behavior, not a description of the `X-Forwarded-` headers.

**Comment by MrBlaise** [comment]
Hmm, I am not sure what is happening then. I have an app behind Google Cloud Load Balancer, ESP (Cloud endpoints) and NGINX api-gateway. That is 3 proxies and my real IP is in the 4th position from the right. Might be a bug on Google's ESP then.

**Comment by davidism** [comment]
MDN docs also confirm the current version: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For.

The params are offsets to set the trust at. If you know the real ip is the last item, then set the count to 1 to get that value. But yes, I would follow up with your hosting provider.

**Comment by MrBlaise** [comment]
$proxy_add_x_forwarded_for in nginx appends the $remote_addr to the existing X-Forwarded-For header or if there is no existing header it will just use $remote_addr

First proxy -> If user tries to spoof with let's say 1.1.1.1 then the outcome will be `1.1.1.1, <REAL_USER_IP>`
Second proxy -> `1.1.1.1, <REAL_USER_IP>, <FIRST_PROXY_IP>`
Third proxy -> `1.1.1.1, <REAL_USER_IP>, <FIRST_PROXY_IP>, <SECOND_PROXY_IP>`

So yes you are right I am mistaken and something funky is going on.
