### ISSUE TITLE
Please release a version with the collections warnings fixed

### ISSUE THREAD

**Issue by allardhoeve** [pallets/werkzeug#1466]
Hi!

Could you please be so kind as to upload a new version with 759aa68 to pypi? It would be nice if we could stop getting warnings in flask apps 👍 

Thanks

**Comment by davidism** [comment]
Please follow this repo, our [blog](https://palletsprojects.com/blog/), or https://twitter.com/PalletsTeam for release announcements.

**Comment by allardhoeve** [comment]
Thanks for the response! Unfortunately, the links you provided tell me nothing about any roadmap or plans to release the software. So yes, I'll watch the Twitter stream, but it is not very informative. Is there a roadmap or discussion forum with more information about release plans?
