### ISSUE TITLE
[test client] New 0.15.0 test_client fails to fetch URL

### ISSUE THREAD

**Issue by dpgaspar** [pallets/werkzeug#1481]
Hi,

My tests began to fail when using 0.15.0.

I've got a routing rule: 

```
<Rule '/users/action/<name>/<pk>' (OPTIONS, HEAD, GET) -> UserDBModelView.action>
```

but test_client returns 404:

```
client = self.app.test_client()
rv = client.get('/users/action/resetmypassword/1', follow_redirects=True)
...
```
When using 0.14.1 the test succeeds

Can you help?

**Comment by strumgol** [comment]
Hi,
I think this linked with the redirection now returning a 308 code instead of 301 in version 0.15..
For us, it seems that redirect code 308 generate an error with request done with urllib2 while code 301 (returned in version 0.14) is handled with a redirection.

**Comment by dpgaspar** [comment]
No, I get a 404 not found

**Comment by davidism** [comment]
I cannot reproduce this issue as described. Be sure to include a minimal example demonstrating an issue when reporting it.

```python
from werkzeug.routing import Map, Rule
from werkzeug.wrappers import Request, Response
from werkzeug.test import Client

url_map = Map([Rule("/users/action/<name>/<pk>", endpoint="users.action")])


@Request.application
def app(request):
    adapter = url_map.bind_to_environ(request.environ)
    endpoint, view_args = adapter.match()
    return Response(endpoint)


c = Client(app, Response)
rv = c.get("/users/action/resetmypassword/1", follow_redirects=True)
assert rv.status_code == 200
```
