### ISSUE TITLE
Change to Unauthorized's argument order breaks existing code

### ISSUE THREAD

**Issue by jhgg** [pallets/werkzeug#1483]
In this commit: https://github.com/pallets/werkzeug/pull/1319/files#diff-43a63db82587e91732eda181306d76c7R240

The constructor of `Unauthorized` used to take the `description` as the first argument, but now takes `www_authenticate` as the first argument. This breaks backwards compatibility with all existing callers of `Unauthorized`. 

Would it be possible to change:
```py
def __init__(self, www_authenticate=None, description=None):
```

to
```py
def __init__(self, description=None, www_authenticate=None):
```

In 0.14.x, `abort(401, 'some error description')` now does a completely different thing in 0.15.0 - and that is a breaking change. 

`405 - MethodNotAllowed` also shares this special case... but that's 11 years old at this point :\

**Comment by lparet-yseop** [comment]
Same issue here.
It is an important breaking change, I have to fix the `Werkzeug` version to `0.14.1` in my `setup.py` by waiting a fix
Thanks for your help

**Comment by davidism** [comment]
I guess I was trying to be consistent with 405, but yeah, it makes more sense to leave description first.

**Comment by melon-ruet** [comment]
Got same issue at Werkzeug==1.0.1
