### ISSUE TITLE
Changes in ProxyFix are not documented

### ISSUE THREAD

**Issue by remilapeyre** [pallets/werkzeug#1484]
Hi, it seems to me that ProxyFix got changes that were not documented in 0.15. While the documentation give information about the module having changed, it's signature and behavior changed to. The new signature is:

```
ProxyFix(app, num_proxies=None, x_for=1, x_proto=0, x_host=0, x_port=0, x_prefix=0)
```

while the old ProxyFix had this behavior:

```
ProxyFix(app, num_proxies=None, x_for=1, x_proto=1, x_host=1, x_port=1, x_prefix=1)
```

As far as I can see, there is no warning in the documentation regarding the change in behavior and since this is not something that is tested with our unit tests, we did not caught it.

Is the change in behavior wanted?
Could we document it more clearly? Especially at https://werkzeug.palletsprojects.com/en/0.15.x/contrib/fixers/ wich only says:

> ## class werkzeug.contrib.fixers.ProxyFix(*args, **kwargs)
> 
> Deprecated since version 0.15: werkzeug.contrib.fixers.ProxyFix has moved to werkzeug.middleware.proxy_fix. This import will be removed in 1.0.

Would it be possible that importing from `contrib.fixers` give the old behavior and for the documentation and the error message give more details about this change?

Thanks a lot!

**Comment by davidism** [comment]
The signature of the previous version of `ProxyFix` from 0.14 is:

https://github.com/pallets/werkzeug/blob/f1d15a2c7f35dcde0e52787c9fdf9ea6f6405308/werkzeug/contrib/fixers.py#L120

The `x_` parameters are all new in 0.15.

**Comment by davidism** [comment]
The fact that you need to specify the count for each one is documented:

https://github.com/pallets/werkzeug/blob/129b3fa0041b874951ce89cbc0a7a6d6e8944414/src/werkzeug/middleware/proxy_fix.py#L38-L39

https://github.com/pallets/werkzeug/blob/129b3fa0041b874951ce89cbc0a7a6d6e8944414/src/werkzeug/middleware/proxy_fix.py#L62-L63

**Comment by remilapeyre** [comment]
Hi @davidism, thanks for the response. I did not see a mention that the default behavior changed though. There was a default behavior, there is still one but they differ. Can't we add a warning regarding this?

**Comment by rascalking** [comment]
Not for nothing, but by changing the default behavior, you're going to cause anything that's validating a signed http request (like Twilio webhooks) to suddenly decide that all of the signatures it's seeing are wrong.

**Comment by lybroman** [comment]
This change of default behaviour would affect the WA mentioned in [flask-restplus serve swagger over https](https://github.com/noirbizarre/flask-restplus/issues/227).
Now it would work with below code change:
`
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_port=1, x_prefix=1)
`

**Comment by davidism** [comment]
In most server setups, the default is probably what you want, or you might enable `x_host` as well. The various headers are set in various combinations by different platforms and proxies. It is dangerous to make a broad recommendation to set every value to 1, you must set the values according to your specific hosting setup.

**Comment by rascalking** [comment]
When working from a clean slate, absolutely.  But I think it might make sense to have the contrib wrapper that throws the deprecation warning supply defaults that match what the previous version of the class did.

Some context for why folks might be cranky about this, since this is what happened to me: a fresh pip install of the same project and code, where flask was pinned to 1.0.2, but werkzeug wasn't pinned, can result in a broken site.
