### ISSUE TITLE
werkzeug 0.15.0: mystery "generated" module when invoking coverage

### ISSUE THREAD

**Issue by asottile** [pallets/werkzeug#1487]
This seems to be a minimal reproduction:

(note I made a virtualenv one level up to avoid that being in the coverage output)

### `.coveragerc`

```ini
[run]
source = .
```

### `t.py`

```python
import flask

app = flask.Flask(__name__)

@app.route('/foo/<a>')
def hello(a):
    return 'world'


# pretend this is a test
with app.test_request_context():
    with app.test_client() as client:
        client.get(flask.url_for('hello', a='1'))
```

### runtime

```console
$ bash -xc 'coverage erase && coverage run t.py && coverage report && coverage xml'
+ coverage erase
+ coverage run t.py
+ coverage report
generated   NoSource: No source for code: '/tmp/t/generated'.
Aborting report output, consider using -i.
Name    Stmts   Miss  Cover
---------------------------
t.py        7      0   100%
+ coverage xml
No source for code: '/tmp/t/generated'.
Aborting report output, consider using -i.
```

### triage (?)

This appears to come from here: https://github.com/pallets/werkzeug/blob/86f7bdf6d7c005d3ab8be50226fe42edc1ce4f7c/src/werkzeug/routing.py#L1111

or, at least, that's the only instance of `'generated'` or `"generated"` in my site-packages -- so I may be guessing a bit here.

This is causing CI failures in https://github.com/asottile/git-code-debt

### workaround

A workaround appears to be setting this:

```ini
[run]
# ...
omit =
    *generated
```

in `.coveragerc`

though ideally I wouldn't have to exclude this 🤔

**Comment by davidism** [comment]
@edk0 I'm guessing this has something to do with the code generation for URL building. Can you take a look?

**Comment by davidism** [comment]
When `Rule` generates its build code, `CodeType.filename` is set to "generated". It should probably be set to `werkzeug.routing.__file__`.

https://github.com/pallets/werkzeug/blob/86f7bdf6d7c005d3ab8be50226fe42edc1ce4f7c/src/werkzeug/routing.py#L1102-L1115

**Comment by asottile** [comment]
I think `None` would also work (?)

**Comment by davidism** [comment]
@asottile I'll give that a try. Was about to write this whole thing, so I'll post anyway. :-)

---

For clarity, the code above is better as a dict:

```python
code_args = {
    "argcount": argcount,
    "nlocals": len(self.var),
    "stacksize": peak_stack + len(self.var),
    "flags": flags,
    "codestring": ops,
    "constants": tuple(self.consts),
    "names": (),
    "varnames": tuple(self.var),
    "filename": __file__,
    "name": "_build_unknown" if append_unknown else "_build",
    "firstlineno": 1,
    "lnotab": b"",
}
if not PY2:
    code_args["kwonlyargcount"] = 0
co = types.CodeType(**code_args)
```

I'm not really sure what the correct answer is. It's weird that this isn't causing the same error in Werkzeug's own coverage. How will coverage react if I tell it that the generated function is part of that module, what line do I say it starts on, what does it do when the `lnotab` table is empty, etc.?

**Comment by davidism** [comment]
`CodeType` doesn't work with keyword arguments. :-(

**Comment by asottile** [comment]
inspecting the coverage data I see two arcs, one from `(-1, 1)` and the other from `(1, -1)`, nonsense it seems

I think `werkzeug` itself avoids this due to:

https://github.com/pallets/werkzeug/blob/86f7bdf6d7c005d3ab8be50226fe42edc1ce4f7c/setup.cfg#L18-L22

Which avoids the "generated" file at `.`

**Comment by davidism** [comment]
Tests still pass with `None`, could you try patching that locally and see if it fixes your project's coverage?

**Comment by asottile** [comment]
woops, my suggestion was wrong, and I'm concerned about the test suite now 😨 

```
+ coverage run t.py
Traceback (most recent call last):
  File "t.py", line 3, in <module>
    app = flask.Flask(__name__)
  File "/tmp/venv/lib/python3.6/site-packages/flask/app.py", line 562, in __init__
    view_func=self.send_static_file
  File "/tmp/venv/lib/python3.6/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/flask/app.py", line 1216, in add_url_rule
    self.url_map.add(rule)
  File "/tmp/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1563, in add
    rule.bind(self)
  File "/tmp/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 710, in bind
    self.compile()
  File "/tmp/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 766, in compile
    self._build = self._compile_builder(False)
  File "/tmp/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1129, in _compile_builder
    return self.BuilderCompiler(self).compile(append_unknown)
  File "/tmp/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1120, in compile
    co = types.CodeType(*code_args)
TypeError: code() argument 10 must be str, not None
```

Setting it to `""` instead seems to work

**Comment by davidism** [comment]
:man_facepalming: I didn't actually set it to `None`.

**Comment by asottile** [comment]
It looks like `exec` uses `"<string>"` for that value:

```pycon
>>> s = 'print("hi")\ndef f(): pass\nprint(repr(f.__code__.co_filename))'
>>> exec(s)
hi
'<string>'
```

**Comment by davidism** [comment]
Yeah, I was looking at `compile` too. Does coverage skip those?

**Comment by asottile** [comment]
yep!

(this is in `coverage/control.py` in the released version I'm using, but here's the moved source):

https://github.com/nedbat/coveragepy/blob/28d223b4265242e08dac4bb016270dbc1b4482cb/coverage/inorout.py#L240-L245

**Comment by davidism** [comment]
Yeah, just found that, it skips empty or `<` prefix. Debating whether I should use something specific like "<werkzeug routing>" or just the empty string.

**Comment by asottile** [comment]
I'd go with `"<werkzeug routing>"`

**Comment by edk0** [comment]
(I got a new job, I'm trying to find the time to get back into this...) `<werkzeug routing>` seems right to me. I did that for the function name, so not doing it for the file seems like a bit of an oversight anyway.

**Comment by davidism** [comment]
No worries, I've already got a branch I'll PR later.
