### ISSUE TITLE
[0.15.1] itsdangerous rasies BadSignature when loading token using TimedJSONWebSignatureSerializer

### ISSUE THREAD

**Issue by iROCKBUNNY** [pallets/werkzeug#1489]
No such issue with Werkzeug==0.14.1

in: 

```
data = serial.loads(token)
```

rasies:

```
itsdangerous.exc.BadSignature: Signature b"*********" does not match
```

**Comment by davidism** [comment]
Werkzeug does not affect itsdangerous. Duplicate of https://github.com/pallets/itsdangerous/issues/120

**Comment by iROCKBUNNY** [comment]
Sorry, it turned out to be a decoder issue on my side. Just added `.decode('ascii')` to `serial.dump(json_data)` and saved my day!
