### ISSUE TITLE
reading request.form freezes untill file upload completes

### ISSUE THREAD

**Issue by robehickman** [pallets/werkzeug#1490]
I have a system which handles large file uploads which sends both the file and metadata (user and session token) as a multipart post request. The system needs to validate that the session is valid, and has to read the session token from the post data. But upon reading this, the handler function freezes until the file is finished uploading. This is a problem as the upload can take a non-trivial amount of time, during which the session token times out. (Session timeout is short as sessions hold an exclusive lock over uploads). 

I.e. doing:

request.form['session_token']

Causes the request to stall until the upload completes.

I'm not sure if this is because flask is unable to provide access to the parts of post data which have been received, or if my code is sending the file data before the metadata. Python module 'poster' is used on the client.

--- edit

Modifying the system to pass the session token in a get parameter fixes the problem, but I'd much rather pass it as post data if possible.

**Comment by davidism** [comment]
Use a cookie for that, headers are loaded before the request body.

**Comment by davidism** [comment]
There are also various issues and prs already open about form performance.
