### ISSUE TITLE
Why secure_filename() returns only ASCII string?

### ISSUE THREAD

**Issue by LeeInHaeng** [pallets/werkzeug#1505]
Can you please explain meaning of 'maximum portability' in 'The filename returned is an ASCII only string for maximum portability'?

I can find encoding way for utf-8 from 'http://www.voidcn.com/article/p-cxjdqemb-bpc.html'

**Comment by ThiefMaster** [comment]
Storing non-ascii filenames is a great way to end up with broken paths when moving between systems.
