### ISSUE TITLE
Test client render screenshot

### ISSUE THREAD

**Issue by simon-k** [pallets/werkzeug#1509]
I'm experimenting with BDD and python/flask. I've done it with .NET using PhantomJs or headless chrome as a browser client. 

My question is. It is possible during tests of a flask application using the werkzeug test client to generate screenshots of the application being tested? 

With PhantomJs it was really simple ```page.render('screenshot.png');```

**Comment by davidism** [comment]
This is not a goal of Werkzeug. The test client is not a browser, it doesn't render anything. There are other Python libraries similar to PhantomJS that you can use.
