### ISSUE TITLE
save_cookie args not serialized/hashed

### ISSUE THREAD

**Issue by gburt** [pallets/werkzeug#151]
Wouldn't it make sense to include most of the args to save_cookie (key, max_age, path, domain, secure, httponly) in the serialization so they can't be altered without invalidating the cookie?

**Comment by davidism** [comment]
Key is used for signing, it doesn't get transmitted with the payload. Token expiration is encoded in the payload. Max age, path, domain, secure, and httponly are properties of the cookie that the browser users, they don't get transmitted back with the cookie.
