### ISSUE TITLE
Module exec error when executing a directory directly and using reloader (Flask startup, debug=True)

### ISSUE THREAD

**Issue by CMLivingston** [pallets/werkzeug#1519]
Python can execute a directory directly if it contains a `__main__.py`, and this does not require `-m` module syntax. When running a flask app in debug mode and executing the script as a `__main__.py` in this fashion, the Werkzeug _reloader module treats the empty string returned from `sys.modules['__main__'].__package__` as an indication that we exec'd from a `-m` module exec, leading to the following "module not found" error:

```
$ python testdir
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
/usr/local/opt/python@2/bin/python2.7: No module named testdir
```

Example repro:

Flask==1.0.2
Werkzeug==0.15.2

`$ mkdir testdir` 
`$ touch testdir/__main__.py`

`testdir/__main__.py`:
```
from flask import Flask
 
app = Flask(__name__)
 
@app.route('/')
def hello_world():
    return 'Hello, world!'
 
if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0')
```

Execute the directory directly:
`$ python testdir`

One potential solution is to add an `elif` to https://github.com/pallets/werkzeug/blame/master/src/werkzeug/_reloader.py#L103 to check for whether `py_script` is a directory, and if so, simply `rv.append(py_script)` and drop through. I'm happy to contribute if something like this makes sense. My current workaround is to pin Werkzeug to <0.15.2.

**Comment by davidism** [comment]
Related to #1416, this is a case I didn't know about. That workaround sounds fine, I'd be happy to review a PR.

**Comment by davidism** [comment]
Looking into this more, this seems like a weird quirk of Python 2, and I'm not sure we need to support it. It works as expected in Python 3. Is there a reason you're not making a traditional package with `__init__` and using `-m`?

**Comment by CMLivingston** [comment]
I don't know if there's a specific reason off the top of my head. I'll need to dig into https://github.com/pantsbuild/pex (the project that this is affecting) further to determine whether `-m` __init__.py can work. I'll report back here.

**Comment by CMLivingston** [comment]
Confirming this use case works properly with Python 3, closing this.

**Comment by sanslash332** [comment]
@CMLivingston
Im continuing getting the error 
2019-11-25 16:25:12,303 - werkzeug - INFO - * Restarting with stat 
/home/sandl/.pyenv/versions/3.7.0/bin/python: No module named 

I'm using a __main__.py, and I start the project only with "python ."

python 3.7.0
flask 1.1.1
werkzeug 0.16.0

windows10 with ubuntu WSL

Is possible fix that?

So thanks you :3
