### ISSUE TITLE
invalidate_cached_property can unintentionally delete object attributes

### ISSUE THREAD

**Issue by mcyprian** [pallets/werkzeug#1547]
I have following class: 

```python
class Example(object):

    def __init__(self):
        self.foo = "Important data"
```
In case I pass standard attribute of the object to `invalidate_cached_property` it results in `foo` attribute being overwritten by no value object:

```python
In [1]: from script import Example

In [2]: from werkzeug.utils import invalidate_cached_property

In [3]: e = Example()

In [4]: e.foo
Out[4]: 'Important data'

In [5]: invalidate_cached_property(e, "foo")

In [6]: e.foo
Out[6]: no value
```

I believe that such thing can happen by mistake and `invalidate_cached_property` should be a noop for standard attributes. CC @singingwolfboy

**Comment by RonnyPfannschmidt** [comment]
i believe a warning should trigger as well, simply to make users aware of the issue,
else its easy to miss a typo when the code "works"
