### ISSUE TITLE
ProfilerMiddleware will overwrite .prof files with same filename

### ISSUE THREAD

**Issue by xietx1995** [pallets/werkzeug#1561]
If testing results of two requests are the same : 

- {method} - The request method; GET, POST, etc.
- {path} - The request path or ‘root’ should one not exist.
- {elapsed} - The elapsed time of the request.
- {time} - The time of the request.

Older .prof file will be overwritten with newer results.

**Comment by davidism** [comment]
That seems acceptable to me. You can pass a callablr to the filename parameter to further customize the file name.
