### ISSUE TITLE
suspicious first argument to super

### ISSUE THREAD

**Issue by jab** [pallets/werkzeug#1566]
The first line of `HTTPException.__init__()` is
https://github.com/pallets/werkzeug/blob/6e7c8bea0f307633e70d979fe0a89e046accc598/src/werkzeug/exceptions.py#L87

It is suspicious that this is not `super(HTTPException, ...)`. This should be changed if it is unintended or explained in a comment if it is.

**Comment by davidism** [comment]
`git blame` says that was me :sweat_smile: It's a typo, should be fixed.
