### ISSUE TITLE
Routing, 404 with specific script_name

### ISSUE THREAD

**Issue by fperucic** [pallets/werkzeug#1583]
All routes having the same prefix as the defined `script_name` will give a 404 response.

Here is an example:

https://www.example.com/public/public-user/password (public)
gives a 404 response, but if  root is changed to something like
https://www.example.com/portal/public-user/password (portal)
everything works as expected.

I noticed this issue in a Flask app when used with a custom `APPLICATION_ROOT` value. The 404 issue only occurs on routes who have the same starting prefix as the `APPLICATION_ROOT`

**Comment by davidism** [comment]
You need to use `DispatcherMiddleware`, or a WSGI server capable of managing the WSGI script name, `APPLICATION_ROOT` on its own does nothing for routing.
