### ISSUE TITLE
pip install stuck at collecting werkzeug

### ISSUE THREAD

**Issue by NotJohs** [pallets/werkzeug#1591]
[
<img width="719" alt="Screenshot 2019-06-25 at 09 27 16" src="https://user-images.githubusercontent.com/29008971/60082515-cbcb5880-972b-11e9-93f1-65aba00a59c7.png">
](url)

**Comment by ThiefMaster** [comment]
sounds like a problem accessing pypi.

**Comment by NotJohs** [comment]
@ThiefMaster 
Thanks a lot for your response, I really appreciate it. 
Finally, What can I do about this?

**Comment by ThiefMaster** [comment]
Wait. Or ask in #pypa on freenode. We just use PyPI and don't run it.

**Comment by NotJohs** [comment]
Alright.
Thanks a lot, I really appreciate it.
