### ISSUE TITLE
Reloader fails on setuptools script installed as an egg

### ISSUE THREAD

**Issue by pokoli** [pallets/werkzeug#1600]
We use werkzeug as router component of trytond. Everything worked on previous versions but since 0.15 (concretly after #1416 was merged), running the server from an package script and activating the reloader causes the following error: 

```
Traceback (most recent call last):
  File "/home/pokoli/.virtualenvs/kaialde/bin/trytond", line 4, in <module>
    __import__('pkg_resources').run_script('trytond==5.0.9', 'trytond')
  File "/home/pokoli/.virtualenvs/kaialde/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/pokoli/.virtualenvs/kaialde/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/home/pokoli/.virtualenvs/kaialde/lib/python3.7/site-packages/trytond-5.0.9-py3.7.egg/EGG-INFO/scripts/trytond", line 47, in <module>
    use_reloader=options.dev)
  File "/home/pokoli/.virtualenvs/kaialde/lib/python3.7/site-packages/werkzeug/serving.py", line 1007, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/home/pokoli/.virtualenvs/kaialde/lib/python3.7/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/home/pokoli/.virtualenvs/kaialde/lib/python3.7/site-packages/werkzeug/_reloader.py", line 159, in restart_with_reloader
    args = _get_args_for_reloading()
  File "/home/pokoli/.virtualenvs/kaialde/lib/python3.7/site-packages/werkzeug/_reloader.py", line 76, in _get_args_for_reloading
    if __main__.__package__ is None:
AttributeError: module '__main__' has no attribute '__package__'
```

**Comment by pokoli** [comment]
The issue is present on 0.15.x but not on 0.14.x
So we need a backport for it.

**Comment by davidism** [comment]
Could you be more specific about what you mean by "a package script"? I'm fine with the fix, but I want to understand under what circumstances `__main__` does not have a `__package__` attribute.

**Comment by pokoli** [comment]
@davidism I'm reproducing the issue when using [trytond declared as script on setup.py](http://hg.tryton.org/trytond/file/e3fe7c454ed6/setup.py#l90)

We have a package that depends on trytond, and the issue is reproducible by installing this package in editable mode (`python setup.py develop` or `pip -e .` ) on a virtualenv. I'm using python3.7

Here are my steps to reproduce it:

```
mkvirtualenv test 
hg clone https://hg.tryton.org/modules/stock -b 5.2
cd stock
python setup.py develop
trytond --dev
```

Please note that the --dev flag is required in order to activate the reloader, so the issue is not pressent without this flag. 

Let me know if this is enought or you need some additional information.

**Comment by davidism** [comment]
I'm sorry, that's a very complex project, I can't really dig through that. Can you provide a minimal example of just what's needed to reproduce the issue?

**Comment by davidism** [comment]
I could not reproduce this issue with the following sample project:

`setup.py`

```python
from setuptools import setup

setup(
    name="example",
    version="0.1.0",
    py_modules=["app"],
    scripts=["scripts/run-example.py"],
)
```

`scripts/run-example.py`:

```python
from werkzeug.serving import run_simple
from app import app

run_simple("localhost", 5000, app, use_reloader=True)
```

`app.py`:

```
from flask import Flask

app = Flask(__name__)

@app.route("/")
def index():
    return "Hello, World!"
```

**Comment by davidism** [comment]
This only occurs when you do `python setup.py develop`, not `pip install -e .`, because `develop` uses setuptools to do the install, and that results in eggs being installed. On the other hand, pip always installs packages unzipped.

I think setuptools maintainers are trying to move away from setuptools being the thing that manages the environment, in favor of pip, so you'll probably have a better compatibility experience in general by using `pip install -e .` going forward. That said, eggs should still be supported for now, so I'll merge the fix.

**Comment by pokoli** [comment]
Thanks!!
