### ISSUE TITLE
Assertion `arg->v.Name.ctx == Param || (arg->v.Name.ctx == Store && !toplevel)' failed (v15.3 and v15.4)

### ISSUE THREAD

**Issue by ruslan-gennadievich** [pallets/werkzeug#1603]
Python/symtable.c:1319: symtable_visit_params: Assertion `arg->v.Name.ctx == Param || (arg->v.Name.ctx == Store && !toplevel)' failed.
Aborted (core dumped)

https://github.com/pallets/flask/issues/3268

**Comment by davidism** [comment]
duplicate of #1553
