### ISSUE TITLE
Problem with setting path in set_cookie()

### ISSUE THREAD

**Issue by ldynia** [pallets/werkzeug#1604]
I'm having a problem setting path on my cookie with set_cookie() method on werkzeug/flask response. The documentation is straight forward.

```python
# This, sets cookie with default path='/'
response.set_cookie('access_token', 'my_token', domain='example.com')
```

However, when I set path parameter different than root ('/'), then cookie is not set.

```python
# This, doesn't set cookie
response.set_cookie('access_token', 'my_token', domain='example.com', path='/api')
```

Any idea why it fails to create cookie for cookies which path is different from root, and how to fix it?

**Comment by davidism** [comment]
I can't reproduce this issue. The following minimal example results in two cookies set, the "b" cookie only accessible from the "/b" route.

```python
from flask import Flask
from flask import request
from flask import Response

app = Flask(__name__)


@app.route("/")
def index():
    r = Response("Hello, World!")
    r.set_cookie("a", "a")
    r.set_cookie("b", "b", path="/b")
    return r


@app.route("/a")
def do_a():
    b = request.cookies.get("b", "not set")
    return b


@app.route("/b")
def do_b():
    b = request.cookies.get("b", "not set")
    return b
```
