### ISSUE TITLE
Inconsistent handling of newlines in Headers object

### ISSUE THREAD

**Issue by ngaya-ll** [pallets/werkzeug#1608]
Werkzeug's `Headers` object is inconsistent in its handling of newline characters.  These characters are allowed in the constructor but forbidden in the `add()` method.

**Steps to reproduce:**
```
>>> from werkzeug import Headers
>>> h1 = Headers([('X-Example', 'foo\r\n bar')])
>>> h2 = Headers()
>>> h2.add('X-Example', 'foo\r\n bar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../venv3/lib/python3.6/site-packages/werkzeug/datastructures.py", line 1166, in add
    self._validate_value(_value)
  File "/home/.../venv3/lib/python3.6/site-packages/werkzeug/datastructures.py", line 1173, in _validate_value
    raise ValueError('Detected newline in header value.  This is '
ValueError: Detected newline in header value.  This is a potential security problem
```

**Expected result:**
Both operations have the same result, whether a `ValueError` or success.

**Actual result:**
`Headers` constructor allows newlines while `Headers.add()` raises `ValueError`.

**Comment by pgjones** [comment]
It is possible to validate headers in the constructor as well; however the form parser has a [use case that requires them not to be validated](https://github.com/pallets/werkzeug/blob/0.16.x/tests/test_formparser.py#L484). I'm not certain if this is a required use case or if it can now be removed - hopefully someone more knowledgeable can comment.

**Comment by aeroaks** [comment]
Facing similar situation

**Comment by davidism** [comment]
@aeroaks the fact that you get this error isn't an issue. This issue is about making this behavior consistent, not fixing anything. If you're getting this error, you need to fix the values you're trying to put into the header, or address whatever's sending the bad headers.
