### ISSUE TITLE
SpooledTemporaryFile causes issues on SBCs in RAM usage and performance

### ISSUE THREAD

**Issue by mkirisame** [pallets/werkzeug#1624]
Hello and thanks for creating Werkzeug, I'd like to report a problem when using:
```python
f.save(s, buffer_size=16384)
f.close()
```
For the interested as background information: My device is an Odroid HC1 with gigabit ethernet and 2GB RAM, it handles file transfers easily at 83 MB/s over various network protocols, an SSD is attached to its SATA interface.

Observed behaviour:
The default configuration of Armbian (SBC version of Debian) is to have a tempfs for the /tmp directory. If my Flask server receives a POST request I call werkzeug.datastructures.FileStorage.save in order to write the received data to filesystem. However I noticed RAM filling up instead on large files and the download failing. The problem was as easily to identify as running ```df -h``` and seeing /tmp fill up to 100%, thus throwing an exception and terminating the upload prematurely. The performance was roughly 9MB/s

If I implement a server in vanilla python I lose all benefits of Flask and Werkzeug, but am able to write to the SSD directly at easily 30 MB/s. An implementation for HTTPS works with both obviously, but I really need the convenience of templates for designing the upload website and offer better security than basic webauth (i have a second version of the server that hashes the password as sha3-512 before sending).

Please tell me I made a mistake and that I can find a way to write data directly to my SSD instead of /tmp. The only loophole I found was changing the tempfile directory to SSD as well in the python code, but that will not stop Werkezug from writing the file first as SpooledTemporaryFile  and then as the final output file.

Server code:
```python
import os, ssl
from flask import Flask, request, redirect, url_for
from werkzeug import secure_filename

UPLOAD_FOLDER = '/home/ubuntu/shared/'
certfile = "/home/ubuntu/keys/fullchain.pem"
keyfile = "/home/ubuntu/keys/privkey.pem"
ecdh_curve = "secp384r1"
cipherlist = "ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-ECDSA-CHACHA20-POLY1305"

sslcontext = ssl.create_default_context(purpose=ssl.Purpose.CLIENT_AUTH)
sslcontext.options |= ssl.OP_NO_TLSv1
sslcontext.options |= ssl.OP_NO_TLSv1_1
sslcontext.protocol = ssl.PROTOCOL_TLSv1_2
sslcontext.set_ciphers(cipherlist)
sslcontext.set_ecdh_curve(ecdh_curve)
sslcontext.load_cert_chain(certfile, keyfile)

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

@app.route("/", methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        my_data = request.files.getlist('file')
        my_pass = request.form['password']
        if my_data and my_pass == 'CENSOREDPASSWORD':
            for file in my_data:
                my_handler(file)
            return redirect(url_for('index'))
    return """
    <!doctype html>
    <title>Upload new File</title>
    <h1>Upload new File</h1>
    <form action="" method=post enctype=multipart/form-data>
    <p><input type=file multiple name=file>
        <input type="password" name="password" value="">
        <input type=submit value=Upload>
    </form>
    <p>%s</p>
    """ % "<br>".join(os.listdir(app.config['UPLOAD_FOLDER'],))

def my_handler(f):
    filename = secure_filename(f.filename)
    f.save(os.path.join(app.config['UPLOAD_FOLDER'], filename), buffer_size=16384)
    f.close()

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=8000, ssl_context=sslcontext, threaded=True, debug=False)
```

**Comment by ThiefMaster** [comment]
Try setting `TMPDIR` to point to your SSD. SpooledTemporaryFile should [take this into account](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir).

**Comment by mkirisame** [comment]
> Try setting `TMPDIR` to point to your SSD. SpooledTemporaryFile should [take this into account](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir).

>Quote OP: "The only loophole I found was changing the tempfile directory to SSD as well in the python code, but that will not stop Werkezug from writing the file first as SpooledTemporaryFile and then as the final output file."

I've already discussed in the OP that this results in write amplification. All I see is the file written twice then.

**Comment by ThiefMaster** [comment]
https://github.com/pallets/werkzeug/blob/e197df1fa08aab6bd5d08605b16b42655f53072f/src/werkzeug/wrappers/base_request.py#L243-L270

You can override this by subclassing Flask to use a custom Request subclass. Instead of the [default](https://github.com/pallets/werkzeug/blob/e197df1fa08aab6bd5d08605b16b42655f53072f/src/werkzeug/formparser.py#L52-L61) one use a custom function that does whatever you like to do with the file.

However, this may be messy since you probably really don't want to the final destination of the file during upload before any access checks etc. have been performed.

**Comment by mkirisame** [comment]
I've only experimented with easy file-like wrappers like self.rfile around socket objects in vanilla python. Is this subclass where can I access the data before it enters SpooledTemporaryFile?

Messy is okay, since HTTPS and the auth ensure I create that mess. I don't want to be spoonfed or have someone do the work for me, but I thought Flask and Werzeug where to make things easier (which they do!), or I'm just a very average hobby coder.

**Comment by mkirisame** [comment]
Closed for what reason? I just want a fair explanation for a "wontfix". Fact is that files are being written twice for no obvious reason.
If the reply is me being a bad coder or making a mistake, I could live with that rather than awkward silence.
So please explain, what I am doing wrong?

**Comment by davidism** [comment]
Seems you've already been pointed in the right direction: if you have special circumstances that aren't supported by the default stream factory, it's possible to override the stream factory by overriding `Request._get_file_stream`.

**Comment by mkirisame** [comment]
That is not really an explanation why my system first has to write it to /tmp dir and later to the specified upload dir. But I won't force a reply or be a pest about it. Just a tad disappointed that POST doesn't seem to be implemented for files in GiB range, rather for strings of text. *shrug*

Consider me going silent now and have a good weekend.
