### ISSUE TITLE
UTF-8 Decode Error on Getting JSON

### ISSUE THREAD

**Issue by BtLutz** [pallets/werkzeug#1626]
Forgive me, this is the first issue I've opened.

I ran into an issue when Unicode characters are included in the POST body of a Request object upon calling request.get_json():

```
File "/usr/lib/python3.7/site-packages/flask/wrappers.py", line 157, in get_json
    rv = json.loads(data)
File "/usr/lib/python3.7/site-packages/flask/json.py", line 145, in loads
    s = s.decode(kwargs.pop('encoding', None) or 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 2849: invalid continuation byte
```

I have a feeling it's due to the code below in json.py:
```
if isinstance(s, bytes):
    # Needed for Python < 3.6
    encoding = detect_utf_encoding(s)
    s = s.decode(encoding)
```
You'll notice that the exception has a different line of code than the block below it. However, I tested the code block above from Werkzeug 0.15 in a Python interpreter and got the same result
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 9: invalid continuation byte
```

Python version is 3.7, Werkzeug version is whichever came with Flask 0.12.2.

**Comment by iwhiz** [comment]
Trying to reproduce the error. Could you please be more specific on your python version? Is it 3.7.2 or any other 3.7.X  ?

**Comment by davidism** [comment]
It sounds like you posted data in an encoding other than UTF, but you haven't provided enough information about how and what data you posted for us to tell. Per the JSON spec, JSON may only be encoded in UTF encodings, if you want to support others you need to provide your own wrapper.

If you have more information that points at a bug with UTF-8 handling, please post and I'll reopen.
