### ISSUE TITLE
when testing, cookie doesn't end up in environ in >= 0.15.2

### ISSUE THREAD

**Issue by lswainemoore** [pallets/werkzeug#1632]
I am using Flask and Flask-Testing, and attempting to set a cookie going into a request, like so:

`resp = self.client.get('/blah', headers={'Cookie': 'cookiename=cookieval')`

Prior to 0.15.2, the cookie will get passed through just fine, and is accessible on `request.headers` and `request.cookies`. On >= 0.15.2, `request.headers` no longer has the cookie and `request.cookies` is empty.

I stepped through, and I believe the line that causes the cookie to get dropped is `environ.pop("HTTP_COOKIE", None)` 

https://github.com/pallets/werkzeug/blob/d958822b5dfbc38e8192df368df162aa4bd7caf0/src/werkzeug/test.py#L198

which seems to have been introduced by https://github.com/pallets/werkzeug/issues/1491.

I'm not sure I follow the logic in that issue, but the line seems to have been intended to solve something unrelated (I'm not dealing with the `follow_redirects` kwarg), and is causing this behavior as a side-effect.

It's definitely not out of the question that I'm not setting the cookie right in the first place, and that it worked in < 0.15.2 was a happy accident. If that's the case, I'd love to know the better way to do it.

**Comment by lswainemoore** [comment]
Oh interesting. I'm now seeing the discussion on the PR itself: https://github.com/pallets/werkzeug/pull/1494.

Seems like the initial behavior was indeed not the best way to go about it.

One question: will `self.client. set_cookie` be ephemeral to the single request/test...that's a primary advantage of doing it the way I have been. If not, am I correct that I need to include `delete_cookie` as part of a teardown?

**Comment by davidism** [comment]
Each test should already construct it's own client, so there's no issue.
