### ISSUE TITLE
Add JSON PATCH support 

### ISSUE THREAD

**Issue by shawalli** [pallets/werkzeug#1641]
# Introduction

[RFC 6902](https://tools.ietf.org/html/rfc6902) documents the JSON PATCH media type, used during a PATCH method call<sup>1</sup>. The sole purpose of this media type is to describe the PATCH method operations in JSON format.

# Implementation

This functionality could be implemented much in the same way JSON is supported in `wrappers.json.JSONMixin` class. The `Mixin` class would therefore support implementations of:
* class-attribute `json_module`
* instance property `jsonpatch`
* instance property `is_jsonpatch`
* instance method `_get_data_for_jsonpatch`
* instance property `_cached_jsonpatch`
* instance method `get_jsonpatch`

The return value of `get_jsonpatch` would be of type `jsonpatch.JsonPatch` (found in the [jsonpatch](https://github.com/stefankoegl/python-json-patch) module).

# Note on JSONMixin Compatability

It should be noted that this media type should probably _not_ fall back to `json` in the event that this mixin is not used. For one, the functionality would need to be duplicated, to an extent. Because Mixins don't inherit from other Mixins, the `JSONMixin` would need to check for this media type and then load as JSON. In the event that both Mixins are used, there would be JSON data from `get_json` and JSON-PATCH data from `get_jsonpatch`. This isn't the end of the world, but it certainly isn't clear either.

# Footnotes
1 - This document may be thought of as a sibling to [RFC 7351](https://tools.ietf.org/html/rfc7351), the XML PATCH media type.

**Comment by shawalli** [comment]
I'm willing to add support for this functionality, but I wanted to make sure that it made sense and was a desired feature before beginning any real work on it.

**Comment by davidism** [comment]
Despite it being targeted at HTTP PATCH, being able to apply patches in a given format is pretty orthogonal to Werkzeug. I'm also hesitant because the RFC you've pointed to is a draft from 2013, and as far as I know there are no required semantics to PATCH requests, so I wouldn't want Werkzeug to suggest a standard where it shouldn't. It would be great to see this as an extension module, but I don't think it would belong directly in Werkzeug.
