### ISSUE TITLE
MIMEAccept.best_match() should return default if the only item is */*

### ISSUE THREAD

**Issue by anlutro** [pallets/werkzeug#1642]
Current behavior:

```
>>> from werkzeug.datastructures import MIMEAccept
>>> MIMEAccept([("*/*", 1)]).best_match(["text/plain", "text/html"], default="text/html")
'text/plain'
```

It seems like the first item in the `matches` list is always returned.

I argue that because the client accepts anything, the default is what should be considered rather than the item first in the list.

`*/*` as the Accept header is fairly common - for example, `curl` does it by default:

```
$ curl https://httpbin.org/headers
{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.64.0"
  }
}
```

**Comment by anlutro** [comment]
pardon me, I must have ran my test on an older version of the code, behaviour is actually as I'd expect right now!

**Comment by anlutro** [comment]
I originally thought this was an issue with the `Accept` class but it's actually the `MIMEAccept` class which has the faulty behavior, my bad.

**Comment by davidism** [comment]
The default is for no match. The matches list is in priority order. The catch all means take the highest priority match. If you need other behavior, either tell curl to ask for what you actually want, or add a special check for the catch all. I'm not convinced the behavior should change in the way described here.

**Comment by RonnyPfannschmidt** [comment]
It could be argued that when matching with equal weight the default should be chosen, practically this is a order issue the api user can easily make as a misstake

I wonder if under test it should warn if the default is not the first item in the list or if that is overreacting

**Comment by davidism** [comment]
At what point does the default stop? `*/*` makes some sense, but what if it's not the first item in the Accept header? Or what if `text/*` is used? `default` seems intended to match it's common use in other methods like `dict.get`. The following code might help with your specific case:

```python
accept = request.accept_mimetypes
if "*/*" in accept:
    return "text/plain"
return accept.best_match(["text/html", "text/plain"])
```
