### ISSUE TITLE
When the client disconnects, Werkzeug does not cancel streaming response that sends no data

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [pallets/werkzeug#1649]
### Steps to reproduce

1. Run the following program:
    ```python
    import time
    from werkzeug.wrappers import Request, Response

    @Request.application
    def app(request):
        def gen():
            while True:
                print('still running...')
                yield ''
                time.sleep(1)
        return Response(gen())

    if __name__ == '__main__':
        from werkzeug.serving import run_simple
        run_simple('localhost', 8000, app)
    ```
2. Open `http://localhost:8000` in the browser.
3. Close this browser tab.

### Expected result

"still running..." messages appear as long as the tab is open and stop once it's closed.

### Actual result

The messages keep appearing indefinitely.

### Version info

```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Werkzeug 0.15.6
```

**Comment by davidism** [comment]
This would be an issue with Python's http server, which Werkzeug subclasses. Does this happen with uwsgi or gunicorn? If not, I'm inclined to close this as won't fix because the dev server is not for production.

**Comment by Vlad-Shcherbina** [comment]
Same behavior with uwsgi.

Gunicorn kills the worker after 30 seconds, doesn't matter whether the client disconnected or not.
```
  -t INT, --timeout INT
                        Workers silent for more than this many seconds are
                        killed and restarted. [30]
```

**Comment by davidism** [comment]
Ok, I'm going to close this. Use gunicorn or another wsgi server that handles this behavior in production. I'm sure there's a timeout option for uwsgi and nginx as well.

**Comment by Vlad-Shcherbina** [comment]
No, gunicorn doesn't handle this. It kills the worker even if the client is still connected.

**Comment by davidism** [comment]
Ok, my point is basically that if the production servers don't handle this, the development server definitely won't. You possibly have something weird going on, because I haven't observed this behavior.
