### ISSUE TITLE
Add argon2 support to werkzeug.security._hash_internal

### ISSUE THREAD

**Issue by ye** [pallets/werkzeug#1652]
The newer and safer password hashing algorithm (than existing ones, PBKDF2 or bcrypt supported native by werkzeug.security._hash_internal) is [Argon2](https://github.com/P-H-C/phc-winner-argon2)

Is it possible to have add native support of Argon2 for password hashing in werkzeug? Thanks.

https://github.com/pallets/werkzeug/blob/master/src/werkzeug/security.py#L127

**Comment by davidism** [comment]
`generate_password_hash` supports any algorithm in the built-in `hashlib`. If hashlib supports Argon2, then `generate_password_hash` will.

**Comment by ye** [comment]
@davidism then why you baked in `PBKDF2`? And no, I don't want `passlib`

**Comment by davidism** [comment]
I had nothing to do with that, but presumably because it's widely used and brings compatibility with Django. It's also in `hashlib` as of Python 3.4. There is absolutely nothing wrong with using passlib, it comes with lots of useful functionality like upgrading hashes over time. It's you're decision whether you want to use it, but I don't plan on adding more complexity to Werkzeug's secondary utilities.

**Comment by ye** [comment]
>  I don't plan on adding more complexity to Werkzeug's secondary utilities.

That's fine. I can live with that.

> I had nothing to do with that, but presumably because it was widely used and brought compatibility with Django. It's also in hashlib as of Python 3.4.

Yes I can see that via `git blame`. "You" means `werkzeug`, not "you" personally @davidism :) In fact, I brought up the question partially because of this comment: https://github.com/pallets/werkzeug/pull/1226#issuecomment-354356625 I am fine with `werkzeug` delegates the hashing support to the official python's `hashlib`. But having PBKDF2 in the `if...else` logic in werkzeug and default the password hashing to be PBKDF2 seems a little odd given that hashlib supports blake2, but you don't have a block dedicated to blake2. Cryptographical hashing field evolves fast, long enough that one day we may hear that PBKDF2 is consider insecure.

>  There is absolutely nothing wrong with using passlib

I am not arguing that - it's just a preference and I don't want to add dependency modules if I don't have - having a module that supports many if not all hashing algorithms means it has a large dependency tree and I may not want to add huge amount irrelevant code as dependencies just to get argon2 support. 

Also the passlib's official repo is on Bitbucket, owned by Australian software company Atlasssian. Any serious security researcher and cryptographer would probably avoid doing that. I assume you are aware of https://www.nytimes.com/2018/12/06/world/australia/encryption-bill-nauru.html too, right?
