### ISSUE TITLE
Multiple headers with the same name gets replaced in test client

### ISSUE THREAD

**Issue by LukeMarlin** [pallets/werkzeug#1655]
`werkzeug.Headers` allows to add multiple headers with the same name:

    from werkzeug import Headers
    h = Headers()
    h.add("example", "value1")
    h.add("example", "value2")
    h.get_all("example")
    > ['value1', 'value2']

Trying to write a test case to gracefully prevent users from doing so with a custom header, I noticed that when using werkzeug's `TestClient` and issuing a `get`, the `request.headers` context only receive the latest value, not both.

It seems that this is due to https://github.com/pallets/werkzeug/blob/e7ba08f209477cb453f15113f9a4d527a6e81bfe/src/werkzeug/test.py#L743-L744

Should these be modified to preserve all values instead of replacing them?
I'd gladly change it if it makes sense.

**Comment by Junnplus** [comment]
I think you are right.

**Comment by davidism** [comment]
The problem is that `to_wsgi_list` is not really intended for creating the WSGI environ, it's for creating the header lines to write out in WSGI's `start_response`.

In the environ, there will be only one value for each header, which will be joined using the appropriate HTTP continuation.

**Comment by LukeMarlin** [comment]
@davidism Thank you for the answer.
However, I'm not sure what to think about it. Is there a possible fix? Is it desirable?
If you have some pointers, I might give it a try
