### ISSUE TITLE
release SameSite='None' fix from issue #1549

### ISSUE THREAD

**Issue by dlesco** [pallets/werkzeug#1660]
Several months ago, issue #1549 fixed the SameSite='None' problem.  However, it was never released, it's scheduled for 1.0.

Meanwhile, Chrome says their changing their security model in February, and they said other browser makers are doing the same:

https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

I need to start incorporating this into a web service.  Will 1.0, with this fix, be released very soon, or should this be backported to the 0.x series?

**Comment by davidism** [comment]
Please do not create these types of issues, they do not make the release process happen faster.

**Comment by dlesco** [comment]
For now, I can attempt putting the new version of dump_cookie function in my application, and try monkey-patching with `werkzeug.http.dump_cookie = dump_cookie`
