### ISSUE TITLE
werkzeug.FileStorage().save() saves an empty file

### ISSUE THREAD

**Issue by NimaBavari** [pallets/werkzeug#1666]
If we have
`file_storage = werkzeug.FileStorage()`
`file_storage.save()`
it will save an empty file. There is no solution anywhere online that I could find. Finally, after hours of debugging, I found a workaround:
`file_storage.stream.seek(0)`
`file_storage.save()`

**Comment by davidism** [comment]
Duplicate of #748
Duplicate of #207

This matches the behavior of Python in general. If you read from a file, you need to reset before you can read again. Additionally, some IO cannot be seeked, so this is not done automatically.

**Comment by Sahana-M** [comment]
Thank you this worked for me!!
