### ISSUE TITLE
HTTP desync attack follow up

### ISSUE THREAD

**Issue by Sytten** [pallets/werkzeug#1667]
Hi! We in the process of fixing the HTTP desync attack present in gunicorn (see the issue https://github.com/benoitc/gunicorn/issues/2176 and the PR https://github.com/benoitc/gunicorn/pull/2181).

We saw that the chunked processing in werkzeug might not be perfect, you expect that the environ `HTTP_TRANSFER_ENCODING` is only a string (like here https://github.com/pallets/werkzeug/blob/246e577e0c99ad1272dffddbfce8fd040a1699b8/src/werkzeug/wsgi.py), but it might be a string containing multiple TE separate by a `,`.

This might cause an HTTP desync attack if the client request is for example:
```
Content-Length: 5
Transfer-Encoding: chunked
Transfer-Encoding: identity
```

**Comment by davidism** [comment]
The development server is not intended for production, and offers no guarantee of security.

If you have a straightforward fix for this, prs welcome, otherwise I'll close this as out of scope.

**Comment by Sytten** [comment]
Not sure I understand, maybe I am mistaken buy you do use this method to check if the stream coming from the server is chunked or not. That's what I understood from https://github.com/pallets/flask/issues/367). You use it here: https://github.com/pallets/werkzeug/blob/246e577e0c99ad1272dffddbfce8fd040a1699b8/src/werkzeug/wsgi.py#L220
This might lead to problematic parsing if `wsgi.input_terminated` is set to to True but the TE is not parsed correctly as coming from the WSGI server.

**Comment by davidism** [comment]
I thought you were referring to the development server handling chunked encoding.

For security issues, please follow our [guidelines](https://github.com/pallets/werkzeug/security/policy) for responsible reporting.

**Comment by davidism** [comment]
Also, it's not clear that what you've pointed at is a security issue. All it's doing is saying "if the transfer encoding says its chunked, then there's no content lenght." For malformed TE, this just results in reading content length amount of bad data. But that method makes no guarantees about the format of data, only that it will read a set amount. And it won't allow infinite streams unless the server indicates that it will handle termination.

**Comment by Sytten** [comment]
I will send an email, I encourage you to read more about HTTP desync issues: https://portswigger.net/research/http-desync-attacks-request-smuggling-reborn
This is the base of this attack, to induce a desync between the processing of a proxy and the server.

**Comment by davidism** [comment]
Werkzeug is not a server though, it's an application. This security has to happen at the WSGI server, not the WSGI application.

**Comment by Sytten** [comment]
I would agree IF we didn't have the chunked processing passed down to the application. Since it's the case with the `wsgi.input_terminated`, this becomes a shared responsibility.

**Comment by davidism** [comment]
But that's exactly what `input_terminated` is used to signal. If the server advertises itself as properly terminating requests, then Werkzeug will allow streaming data. If it does not, then Werkzeug will read nothing. If the server is not actually terminating the request, that's an issue with the server, it's not something Werkzeug will do anything about.

**Comment by Sytten** [comment]
Fair enough I agree with that, I still think it's a bug that some server will pass a comma separated list in `HTTP_TRANSFER_ENCODING` while werkzeug expects a single string. The fix could be as simple as writing in the documentation that we expect a single string that must be `chunked` to handle the stream properly.

**Comment by mitsuhiko** [comment]
It’s completely unclear what a comma value would mean here so it seems fair to me to only detect chunking if there is a single value and it’s chunked. I don’t think this needs to be called out in the docs.

**Comment by Sytten** [comment]
Hummmm, that would mean a change in gunicorn...
