### ISSUE TITLE
`werkzeug.http.parse_accept_header` should parse Accept parameters

### ISSUE THREAD

**Issue by TMiguelT** [pallets/werkzeug#1679]
First of all, the [HTTP spec on the `Accept` header](https://tools.ietf.org/html/rfc7231#section-5.3.2) states that:

>  Each media-range might be followed by zero or more applicable media type parameters (e.g., charset), an optional "q" parameter for indicating a relative weight (Section 5.3.1), and then zero or more extension parameters.

Considering this, an `Accept` header like `Accept: application/vnd.api+json; charset=utf-8` is valid.

However, if you use `parse_accept_header` on such a header, the `charset` option will not be extracted:

```python
>>> from werkzeug.http import parse_accept_header
>>> from werkzeug.datastructures import MIMEAccept
>>> parse_accept_header('Accept: application/json; charset=utf-8')
Accept([('application/vnd.api+json; charset=utf-8', 1), ('Accept:', 1)])
>>> parse_accept_header('Accept: application/json; charset=utf-8', MIMEAccept)
MIMEAccept([('application/vnd.api+json; charset=utf-8', 1), ('Accept:', 1)])
```

This has implications for content negotiation, whereby your server supports `application/json` but the user includes a charset, meaning that it will neither match with the `best` property, nor `best_match` unless the charset also matches:
```python
>>> from werkzeug.http import parse_accept_header
>>> from werkzeug.datastructures import MIMEAccept
>>> acc = parse_accept_header('Accept: application/vnd.api+json; charset=utf-8', MIMEAccept)
>>> acc.best
'application/vnd.api+json; charset=utf-8'
>>> acc.best_match(['application/json'])
```
(this last invocation returns `None`)

I notice that `parse_options_header` does work correctly for this header, but this would need to be applied to each `Accept` in the list of types:

```python
>>> from werkzeug.http import parse_options_header
>>> parse_options_header('application/json; charset=utf-8')
('application/vnd.api+json', {'charset': 'utf-8'})
```

**Comment by TMiguelT** [comment]
I'm happy to write a PR for this, by the way. I just want confirmation that this is in scope for werkzeug.

**Comment by aenglander** [comment]
First off, which version of Werkzeug are you using. I cannot get the same responses from the provided code snippets.

Second, it appears you are mixing apples and oranges hear. Parsing the header and getting a match are very different. In that manner, `parse_options_header` and `parse_accept_header` are very similar although they are intended to be different. Matching, as far as I can ascertain from re-reading the spec is working as expected. Your accept statement provides one type with a `charset` option. It does not allow for a type without the `charset` of `utf-8`. Therfore, it will not match a type without the a `charset` of `utf-8`. If you were to provided a `utf-8`
 `charset` for in matching `acc.best_match(['application/json;charset=utf-8']` or an option without a `charset`  ` parse_accept_header('Accept: application/json, application/json; charset=utf-8', MIMEAccept)`, you would get a match.

It would appear from the spec that If you want to treat character sets out side of content types, you should use the `Accept-Charset` header: [https://tools.ietf.org/html/rfc7231#section-5.3.3](https://tools.ietf.org/html/rfc7231#section-5.3.3).

**Comment by TMiguelT** [comment]
I get this on all versions of Werkzeug, but I just tested it on `0.16.0` and got the same results.

I think you might be right though. If the client is asking for `charset=utf-8`, then it means it will only accept `application/json` if it has this charset, meaning that a literal match is still appropriate. I'm further convinced because, using `format=flowed` as an example, the [spec](https://tools.ietf.org/html/rfc7231#section-5.3.2) says:

>  For example,
      `Accept: text/*, text/plain, text/plain;format=flowed, */*`
   have the following precedence:
     1.  text/plain;format=flowed
     2.  text/plain
     3.  text/*
     4.  */*

**Comment by TMiguelT** [comment]
But, having said that, I can see a common use-case where we're we are hosting a server that supports `application/json`, and is happy to reply with any unicode encoding, specified either with `charset=` in `Accept`, or with `Accept-Charset`. 

If we use Werkzeug's `best_match` to determine if there was a valid `Accept` header, our server will *always* `406 Not Acceptable`, when in fact we would much rather Werkzeug treats `application/json;charset=utf-8` equivalently to:
```
Accept: application/json
Accept-Charset: utf-8
```

But yes, I guess I'm more talking about matching mimetypes rather than parsing headers here. But I still think there's a need that Werkzeug doesn't fulfil.

**Comment by aenglander** [comment]
So, werkzeug is properly implementation of the specification as I read it. The specification portion you're pointing out is that the most specific match should win. You must get more specific in the match not less specific. Dropping the extension when matching would make it less specific. By the logic you proposed and the specification that applies, the following request
```http:
HTTP 1.1 GET /
Accept: application/json;charset=utf-8
```
could match properly to `application/json` for MIME type and `latin1` for Character Set as any character set passed would pass the check thanks to the lack of an `Accept-Charset` header. The spec says:
> A request without any Accept-Charset header field implies that the  user agent will accept any charset in response.

I get that it doesn't seem to make sense; but, it would appear that you need to specify all the possible supported character sets using the `charset` extension if you want to support the amazingly valid use case according to the specification. Each header is processed separately and has to be to satisfy the specification.
