### ISSUE TITLE
Found a security issue

### ISSUE THREAD

**Issue by ZeddYu** [pallets/werkzeug#1681]
Found a security issue. How can I report it?

**Comment by jab** [comment]
https://github.com/pallets/werkzeug/security/policy

**Comment by ZeddYu** [comment]
> https://github.com/pallets/werkzeug/security/policy

I have sent an email. But no one replied. @jab

**Comment by jab** [comment]
Thanks @ZeddYu, when did you send it?

I don't currently get these emails but I'm sure some of the other maintainers do, and someone should get back to you soon to acknowledge receipt.

We're grateful for your submission.

**Comment by RonnyPfannschmidt** [comment]
@ZeddYu it may be a little bit, when you did send it it was late night in europe, and late sunday evening in the us, now its just early monday morning in the eu

**Comment by ThiefMaster** [comment]
Thanks for the report, I can confirm that we received it.

BTW, the dev server isn't meant to be used in production, so the impact of the issue you reported seems *very* limited to me - so at least based on my understanding of the problem I think it would actually be OK to open a normal public issue about it here on GitHub

**Comment by ZeddYu** [comment]
@ThiefMaster But werkzeug, in general, is widely used in production. This is the result of my discussion with my partner.  Golang have a similiar issue and they also fix it.

**Comment by ThiefMaster** [comment]
Werkzeug (the WSGI framework) is very much production-ready and widely used as you say. But the builtin dev server has never been and will never be meant for production. Anyone using it in production is doing something which we clearly discourage...

The docs actually mention this:

> The development server is not intended to be used on production systems. It was designed especially for development purposes and performs poorly under high load. For deployment setups have a look at the Application Deployment pages.

**Comment by ZeddYu** [comment]
@ThiefMaster  Fine. But if werkzeug is not used in production env, in other words, it doesn't have any security issues. Is this right? Or What kind of issue do you think is a security issue? Just a simple discussion.

**Comment by ThiefMaster** [comment]
What I'm saying is that **this particular part** (the builtin **development** web server) of werkzeug is **not suitable for production**. The werkzeug **WSGI framework** is of course suitable for production.

**Comment by ZeddYu** [comment]
All right. I see. Thanks for your patience. :P
