### ISSUE TITLE
Sort order is not stable in Accept class

### ISSUE THREAD

**Issue by lincolnq** [pallets/werkzeug#1686]
```py
    from werkzeug.datastructures import LanguageAccept
    from werkzeug.http import parse_accept_header

    a = parse_accept_header("en-US,fr-FR", LanguageAccept)
    assert a.best == "en-US"  # fails, it returns fr-FR
```

I expected the order to be preserved. 

RFC 3282 describes desired behavior for Accept-Language: "If no Q values are given, the language-ranges are given in priority order, with the leftmost language-range being the most preferred language; this is an extension to the HTTP/1.1 rules, but matches current practice."

Looking at the source code, the Accept class is reverse-sorting the input list by specificity, then quality, then name; I think it should not sort by name and instead should preserve the given order.

**Comment by zgoda** [comment]
According to current standard which is [RFC 7231](https://www.rfc-editor.org/rfc/rfc7231.html#section-5.3.5) I'd rather expect a list in case of equal preference matches. There is a note there describing this exact case.

**Comment by pgjones** [comment]
See #1701 - I also think the parsed order should be preserved.
