### ISSUE TITLE
POST request freezes up and crashes when Content-Length and no body

### ISSUE THREAD

**Issue by dpatz** [pallets/werkzeug#1703]
For some reason, I occasionally receive requests from the browser with a `Content-Length` set but with no body. When this happens the request just freezes (and eventually, on my server, gunicorn kills it). Is there something I can do or a setting I can change to prevent this from happening?

Here is a simple app with the same problem:
```
from flask import Flask, request


app = Flask(__name__)


@app.route('/', methods=['POST'])
def hello_world():
    print(request.json)
    return 'Hello World!'


if __name__ == '__main__':
    app.run(debug=True)
```

This POST request will break it:
`curl -X POST -H "Content-Length: 94" -H "Content-Type: application/json; charset=utf-8" http://localhost:5000`

**Comment by pgjones** [comment]
Presumably Gunicorn times the request out and kills it? If so I think this is the correct action - the browser has promised a body but not yet sent it, the server should therefore wait a limited amount of time until till the browser sends the body or if not close the connection.

**Comment by davidism** [comment]
Yeah, this isn't something Werkzeug can do anything about, it has to happen at the server level.

**Comment by dpatz** [comment]
Yeah, that was my assumption too. I was more wondering if there is anything I can do at the library/application level to put some kind of timeout on it and handle the exception myself.

**Comment by pgjones** [comment]
This is something that the WSGI server is responsible for handling - [this](http://docs.gunicorn.org/en/stable/settings.html#worker-abort) and [this](http://docs.gunicorn.org/en/stable/settings.html#timeout) may be useful to you.

**Comment by dpatz** [comment]
Thanks, it looks like it was actually raising a `SystemExit` exception. So I should be able to just wrap `request.json` and handle it that way.
