### ISSUE TITLE
make_conditional(..., accept_ranges=True) respond range request with 200 OK

### ISSUE THREAD

**Issue by Kontinuation** [pallets/werkzeug#1704]
## Description

`make_conditional(request_or_environ, accept_ranges=True)` responds range requests with `206 Partial Content` when the request does not fetch the entire content, which is fine; when the range specified in the request covers the entire content, the server respond with `200 OK`, which may cause various problems.

## Expected Behavior

Server should respond with `206 Partial Content` in case of a successful range request, regardless of whether the requested range covers the entire content or not. Responding with `200 OK` indicates that the server has ignored the range header, thus client might consider that the server does not support range requests, which is not feasible when `accept_ranges` was specified as `True`.

## Impact

HTML5 video playbacks on old versions of safari (<= 12) does not work due to this problem, since safari has been strict in checking the status code of range requests. Request with `Range: bytes=0-` was responded with `200 OK` where `206 Partial Content` was expected. After patching the `ETagResponseMixin._process_range_request()` method to make it always respond with `206 Partial Content`, the video playback worked properly.

## Behavior of other webservers

* Web Servers: Both Nginx/1.14.0 and Apache/2.4.29 respond `Range: bytes=0-` with `206 Partial Content`.
* Object Stores: Both Amazon S3 and Baidu's BOS respond `Range: bytes=0-` with `206 Partial Content`.

## Possible Solution

Maybe we could remove the special treatment for the `content_length != complete_length` case in  `_process_range_request` method defined in `werkzeug/wrappers/etag.py`. I am not familiar with the codebase so I'd like to wait for professionals to come up with a correct fix.

**Comment by davidism** [comment]
Is this the same as #410? I don't have a Mac, but if always responding 206 to range requests solves the issue, that sounds acceptable to me.

**Comment by davidism** [comment]
The RFC does seem to support this interpretation. https://tools.ietf.org/html/rfc7233#section-3.1

> If ... the specified range(s) are valid and satisfiable (as defined in Section 2.1), the server SHOULD send a 206 (Partial Content) response...

It doesn't say anything about returning a normal 200 response if the range covers the entire contents.

**Comment by pgjones** [comment]
I think it should change to 206 as well, this [from here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests), 
> In case of no support of range requests, the 200 OK status is sent back from a server.

is what convinces me. I'll draw up a PR.

**Comment by pgjones** [comment]
Interestingly the implementation is intentionally [returning 200](https://github.com/pallets/werkzeug/commit/0a23c94a352649655e2b1691c9008dd8082e752d#diff-67ab56f47231589fb9c088d78b68854dR1471), maybe @magne4000 could say why?

**Comment by davidism** [comment]
I tried to reproduce this issue, but no one I give it to can make it happen on Safari. I'm willing to merge this since you report it did fix the issue, and it seems like a good fix regardless, but it would be nice to get a reproducible example.

**Comment by magne4000** [comment]
Hum, if the RFC doesn't specify anything regarding the 200 response, that would have been an interpretation on my side. I think this particular condition can safely be removed
