### ISSUE TITLE
fallback:<coding> error handler documented, but not present

### ISSUE THREAD

**Issue by ThomasWaldmann** [pallets/werkzeug#1706]
See there https://werkzeug.palletsprojects.com/en/0.16.x/unicode/#error-handling for:
```
There is additional error handling available which is a Werkzeug extension
to the regular codec error handling which is called fallback.
Often you want to use utf-8 but support latin1 as legacy encoding too
if decoding failed. For this case you can use the fallback error handling.

For example you can specify 'fallback:iso-8859-15' to tell Werkzeug it
should try with iso-8859-15 if utf-8 failed. If this decoding fails too (which
should not happen for most legacy charsets such as iso-8859-15) the error
is silently ignored as if the error handling was ignore.
```

Actual behavior:

```
>>> werkzeug.url_unquote('%fcbel', errors='fallback:iso-8859-1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "werkzeug/urls.py", line 610, in url_unquote
    rv = rv.decode(charset, errors)
  File "/home/user/.pyenv/versions/2.7.15/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
LookupError: unknown error handler name 'fallback:iso-8859-1'

>>> werkzeug.__version__
'0.15.6'
```

**Comment by davidism** [comment]
As far as I can remember that has never been a feature. I can't recall anything removing it either. It may have been removed before then, in which case these docs are just incorrect and need to be updated.

**Comment by ThomasWaldmann** [comment]
Well, as it has been documented, it has been a feature. :-)

But due to lots of unicode-related refactoring, it seems it got lost somehow and noone except some MoinMoin admins / users noticed.

**Comment by ThomasWaldmann** [comment]
btw, there is `codecs.register_error()` - maybe that just should be used?

**Comment by davidism** [comment]
Looks like the code that supported such "fallback" encodings was removed in 2013: f5a657a65a1bcc1eaec22b972398dfcb0c2185d3. Looks like MoinMoin is vendoring Werkzeug, so it must have had a very old version until recently, or you must have only just now run into a URL that had a decoding error. I don't plan to add this fallback back in, so it would probably be better to identify why your project is receiving/has this inconsistent data and address it there.

**Comment by ThomasWaldmann** [comment]
No, we did not vendor at that old version.

But only users who got iso-8859-1 content in their event-log somehow triggered the exception.
