### ISSUE TITLE
Version 0.16.1 removed top level imports before planned?

### ISSUE THREAD

**Issue by jameswilliams1** [pallets/werkzeug#1710]
I've been having issues with django-extensions after doing an update today and I finally found the issue is that Werkzeug has dropped some top level imports that were deprecated (but scheduled for removal in 1.0.0) in the move from 0.16.0->0.16.1. In this case `from werkzeug import DebuggedApplication` now doesn't work.

Now I get using this is deprecated, but if you're following semantic versioning then a move of 0.0.1 shouldn't change behaviour like this as other packages are now broken. When doing this import the warning gives 
```
DeprecationWarning: The import 'werkzeug.DebuggedApplication' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.debug import DebuggedApplication' instead.
```
so I think this sudden change may have caught a few people off guard who thought they had time before they needed to switch.

**Comment by davidism** [comment]
If you got a warning then that's not an error. I can't reproduce this issue, `from werkzeug import DebuggedApplication` still returns `DebuggedApplication` (but with the warning) in 0.16.1.
