### ISSUE TITLE
Adding watchdog dependency breaks file watching on Windows

### ISSUE THREAD

**Issue by TheIncorrigible1** [pallets/werkzeug#1716]
I've tested this on Win7 Ent & Win10 Pro 1909.  Adding `Werkzeug[watchdog]` breaks Flask's reloader entirely.  I figured this is the best place for the issue since this is where I found documentation on the matter.  The `stat` reloader works as expected.

Versions:
* py 3.6 & 3.8
* watchdog-0.9.0 (tried 0.10.1 as well)
* flask-1.1.1
* werkzeug-0.16.1 (tried 1.0.0 here, too)

A quick repro:

```bash
pip install flask werkzeug[watchdog]
```

*app.py*

```python
import flask
def create_app():
    return flask.Flask('test')
```

```bash
SET "FLASK_ENV=development"
flask run
```

Uninstall `watchdog` immediately remediates the issue as it falls back to `stat`.  I've attempted launching flask with both the entry `flask.exe` and `python -m flask run` (both from a virtual environment).

**Comment by davidism** [comment]
I can't reproduce this issue. Please provide a traceback.

**Comment by TheIncorrigible1** [comment]
It appears my comment edits weren't saved.  This happens specifically while trying to watch the static folder using an environment variable:

```bash
SET "FLASK_RUN_EXTRA_FILES=static/"
```

**Comment by davidism** [comment]
We were unable to reproduce this on Windows, Linux, or Mac.
