### ISSUE TITLE
Adhoc ssl subject altName

### ISSUE THREAD

**Issue by mrichar1** [pallets/werkzeug#1720]
Recent versions of Chrome seem to be dislike certificates that are missing or have unusual subjectAltName fields, giving the error:

> This server could not prove that it is <name> its security certificate is from [missing_subjectAltName]

Looking at the code in `generate_adhoc_ssl_pair` it seems to have the subjectAltName hard-coded to `*`:

https://github.com/pallets/werkzeug/blob/master/src/werkzeug/serving.py#L538

Would it make more sense for this to match the value of the  `cn` parameter (which will be `*` if unset anyway) ?

**Comment by davidism** [comment]
I don't know much about TLS, so I'm not going to be able to answer your question of if it would make more sense? Would it make more sense? Please make a PR if you think it would.

For the record, I don't see this in Chromium or Firefox, things work fine considering it's self-signed so it will always be untrusted no matter what.

I'd recommend [mkcert](https://github.com/FiloSottile/mkcert) if you want consistent and correct local development certs.

**Comment by davidism** [comment]
Closing as I'm not clear what the correct behavior here is (if it's incorrect at all).
