### ISSUE TITLE
werkzeug fails to import secure_filename within Docker

### ISSUE THREAD

**Issue by ideaman924** [pallets/werkzeug#1724]
I have a Flask application that depends on `flask-uploads`, which in turn depends on `werkzeug`. When I run my Flask application outside of Docker it runs fine. However, if I use Docker Compose to build my application, the following error occurs:

```
Traceback (most recent call last):
  File "db_setup.py", line 1, in <module>
    from app import db
  File "/usr/src/app/app.py", line 6, in <module>
    from flask_uploads import UploadSet, configure_uploads
  File "/usr/local/lib/python3.8/site-packages/flask_uploads.py", line 26, in <module>
    from werkzeug import secure_filename, FileStorage
ImportError: cannot import name 'secure_filename' from 'werkzeug' (/usr/local/lib/python3.8/site-packages/werkzeug/__init__.py)
```

Any idea what is going on? This only happens within Docker, so I think it may be an environment problem. Thanks in advance!

**Comment by ideaman924** [comment]
Sorry, just realized it's a problem on `flask-uploads` end! If anybody has the same issue follow this pull request: https://github.com/maxcountryman/flask-uploads/pull/28

Sorry about the bad bug report!

**Comment by xariskef** [comment]
install an old version werkzeug, works for me

pip install werkzueg==0.15

**Comment by Joskam** [comment]
> install an old version werkzeug, works for me
> 
> pip install werkzueg==

This works but you need to correct the typo.     It should be  werkzeug==0.15
