### ISSUE TITLE
Change in 1.0.0 to add pathlib support for `.save()` breaks usage of `io.BytesIO`

### ISSUE THREAD

**Issue by acaos** [pallets/werkzeug#1733]
## Versions

* Python 3.7
* Werkzeug 1.0.0 (from PyPI)

## Report

The addition of pathlib support to `.save()` from #1654 breaks the the ability to pass `io.BytesIO` objects to `.save()`.

Previous behavior: Saving to an `io.BytesIO` object worked as expected.
Behavior in 1.0.0: An exception is thrown in `fspath()`.

```
  File "/app/main.py", line 310, in extract_metadata
    files['metadata'].save(metadata_io)
  File "/app/.venv/lib/python3.7/site-packages/werkzeug/datastructures.py", line 3061, in save
    dst = fspath(dst)
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO
```

**Comment by Vermeille** [comment]
Exact same issue here. Thumbed up.

**Comment by Vermeille** [comment]
For now I'm using this workaround

```python
# until https://github.com/pallets/werkzeug/issues/1733 is fixed
buf = io.BytesIO()
#request.files['photo'].save(buf)
from shutil import copyfileobj
copyfileobj(request.files['photo'].stream, buf, 16384)
```

**Comment by davidism** [comment]
Looks like we need to do some shuffling with the order we check the types and do the conversion, in order to continue to support file-like objects. Scheduled for 1.0.1, PRs welcome if anyone can work on a fix.
