### ISSUE TITLE
Outdated documentation of SharedDataMiddleware

### ISSUE THREAD

**Issue by magula** [pallets/werkzeug#1735]
It seems that `SharedDataMiddleware` was moved to `middleware.shared_data`, but its documentation still says

```
    """A WSGI middleware that provides static content for development
    environments or simple server setups. Usage is quite simple::
        import os
        from werkzeug.wsgi import SharedDataMiddleware
[...]
    """
```
and the [tutorial](https://werkzeug.palletsprojects.com/en/1.0.x/tutorial/?highlight=shareddatamiddleware#step-2-the-base-structure) still says
`from werkzeug.wsgi import SharedDataMiddleware`.

**Comment by davidism** [comment]
I'm happy to consider a PR against the 1.0.x branch that address these docs.

**Comment by magula** [comment]
Splendid, I've created a pull request, see #1736.
