### ISSUE TITLE
_dump_date year conversion doesn't zfill(4)

### ISSUE THREAD

**Issue by nicolary** [pallets/werkzeug#1739]
I have some dates that have a year before year 1000 and the _dump_date function doesn't represent them as zero filled to 4 so parsing the output with '%a, %d %b %Y %H:%M:%S %Z' throws an exception.

```
index b428ceeb..d233d0f2 100644
--- a/src/werkzeug/http.py
+++ b/src/werkzeug/http.py
@@ -882,7 +882,7 @@ def _dump_date(d, delim):
             "Dec",
         )[d.tm_mon - 1],
         delim,
-        str(d.tm_year),
+        str(d.tm_year).zfill(4),
         d.tm_hour,
         d.tm_min,
         d.tm_sec,
```

**Comment by davidism** [comment]
I'm not clear why dates prior to 1000 are relevant in an HTTP context. Can you explain why you need Werkzeug's `http_date` for this?

**Comment by nicolary** [comment]
_dump_date is used as the default datetime and date encoding function in Flask's JSONEncoder class:

https://github.com/pallets/flask/blob/master/src/flask/json/__init__.py

**Comment by davidism** [comment]
Since you have specialized data, you should probably be using a better representation than HTTP dates anyway. I'd recommend overriding `app.json_encoder`, or using something like Marshmallow to serialize your data first. I guess I'm fine with a PR, it just doesn't seem very relevant to typical HTTP date use cases.

**Comment by nicolary** [comment]
I did override it. I figured I'd mention it in case you wanted to apply the included patch - it mitigates this python issue https://bugs.python.org/issue13305 in this case.

Since the function is being used for common date encoding in Flask maybe they should rethink the http_date use in their default encoder...

Thanks for the response.

**Comment by nicolary** [comment]
I did override it. I figured I'd mention it in case you wanted to apply the included patch - it mitigates this python issue https://bugs.python.org/issue13305 in this case.

Since the function is being used for common date encoding in Flask maybe they should rethink the http_date use in their default encoder...

Thanks for the response.
