### ISSUE TITLE
Server is slow on IPV6 networks

### ISSUE THREAD

**Issue by galeej** [pallets/werkzeug#1750]
Hi,

The server runs extremely slowly on ipv6.

While this was addressed in the documentation, none of them seem to work for us.

Has this been resolved?

We are using 0.16.1

**Comment by ThiefMaster** [comment]
I doubt this is a werkzeug issue...

**Comment by galeej** [comment]
Would you be able to suggest a methodology of checking this?  I am running a flask server which uses werkzeug.

**Comment by galeej** [comment]
We have two modems (one which has 5G and one which does not).

The flask program runs very fast on the one without 5G and runs extremely slowly on the one which does.

My hypothesis is that this is due to Werkzeug and the IPV6 issue.  Does that make sense?

**Comment by ThiefMaster** [comment]
just fyi, the builtin werkzeug server is NOT SUITABLE for production usage.. and since you access it over 5g it sounds a bit like you are using it in production

**Comment by galeej** [comment]
we dont use it for production usage.

**Comment by davidism** [comment]
The HTTP server is provided by Python's [`http.server`[(https://docs.python.org/3/library/http.server.html) module, all Werkzeug is doing is wrapping that to create a WSGI environ for the request and call the application. Any performance issues are unlikely to be due to something Werkzeug controls.

**Comment by galeej** [comment]
Thanks for the clarification.
