### ISSUE TITLE
Should HTTPExceptions subclass Response?

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1751]
Came across the following comment in the docs about Werkzeug's exceptions:

> Because of Python 2.4 compatibility those do not extend from the response objects but only from the python exception class.

Further back, the comment used to read "Python 2.3/2.4 compatibility".

I'm trying to find what this compatibility was. Was it that 2.3 introduced a new requirement going forward? Or that a requirement was lifted but we needed to remain compatible with 2.4 at the time? We haven't supported 2.4 in ages, and are dropping 2 completely at this point, so I'm at least removing this comment.

Would there be any benefit to making `HTTPException` a subclass of `Response` at this point? Maybe someone can try it out and see what happens.

**Comment by pgjones** [comment]
The compatibility issue may be [this change](https://docs.python.org/2/whatsnew/2.5.html#pep-352-exceptions-as-new-style-classes).

I'd actually much prefer the opposite to occur i.e. that exceptions aren't capable of being WSGI responses. This is a pain in an ASGI sense as the WSGI response is not relevant.

**Comment by davidism** [comment]
Going to close this. We might do something about it while extracting behavior to `sansio`, but I don't think we need to keep this specific issue open.
