### ISSUE TITLE
Use traceback module instead of custom wrapper

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1753]
Now that we're dropping Python < 3.6, we probably don't need the wrappers in `werkzeug.debug.tbtools` anymore. Investigate what we can replace with the built-in [`traceback`](https://docs.python.org/3/library/traceback.html) module. It's unlikely we can remove everything, but from what I remember from implementing nested traceback handling, there is quite a lot of overlap.

**Comment by teymour-aldridge** [comment]
I'm going to try my hand at this.
