### ISSUE TITLE
deprecate utils.format_string

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1756]
It appears to do exactly what `string.Template` does.

**Comment by northernSage** [comment]
I would be glad to help with this.

**Comment by davidism** [comment]
You're welcome to work on issues, no need to ask first. The deprecation warning should be something like `'format_string' is deprecated and will be removed in 2.1. Use 'string.Template' instead.` There's a few places the function is used internally which should be replaced with `string.Template`, as well as the implementation itself.

**Comment by northernSage** [comment]
Okay, I will get to it and write a PR in the next few days.
