### ISSUE TITLE
deprecate posixemulation

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1759]
It's called out as "not a public interface" in the docstring, and looks like it was only there to support `contrib.sessions`, which has moved to `secure-cookie` now. Move it there if it's still needed, remove it here.

**Comment by northernSage** [comment]
I'll write a PR for this soon

**Comment by davidism** [comment]
Also need to make a secure-cookie 0.1.1 release with this included.

**Comment by northernSage** [comment]
> Also need to make a secure-cookie 0.1.1 release with this included.

Okay, Will look into pallets/secure-cookie#12 in the next few days as soon as I get the chance
