### ISSUE TITLE
remove get_filesystem_encoding after dropping Python 3.6

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1760]
I *think* this is a non-issue in Python >= 3.6 ~because of [PEP 529](https://www.python.org/dev/peps/pep-0529/)~, but I haven't had time to look thoroughly. It would be helpful if someone could write up some research on whether it's still relevant.

**Comment by gmelodie** [comment]
So there are mainly two things that `get_filesystem_encoding` checks:
1. Whether or not the system is a "buggy" unicode filesystem, i.e. linux or bsd system **and** the result of `sys.getfilesystemencoding` is `None` ([which can't be anymore](https://docs.python.org/3/library/sys.html#sys.getfilesystemencoding) so this check should no longer make sense)
2. Whether or not `sys.getfilesystemencoding` is ASCII

In theory `has_likely_buggy_unicode_filesystem` should no longer be needed as `sys.getfilesystemencoding` will never return `None`, but according to the [python docs](https://docs.python.org/3/library/sys.html#sys.getfilesystemencoding):
> On Unix, the encoding is the locale encoding.

And according to [the werkzeug docs]():
> several bug reports against Werkzeug have shown that the value of sys.getfilesystemencoding() cannot be trusted under traditional UNIX systems. The usual problems come from misconfigured systems, where LANG and similar environment variables are not set

So I *think* we shouldn't be able to safely remove `get_filesystem_encoding`. This is all theoretical thinking based on docs as I am unsure about how to create tests for this.

**Comment by davidism** [comment]
Great writeup, thank you. It sounds like we can at least clean this up a bit, even if we can't remove it yet. The comment in the Werkzeug docs is pretty vague, were you able to find any of the issues it referred to?

**Comment by gmelodie** [comment]
[Here](https://github.com/pallets/werkzeug/search?q=getfilesystemencoding&type=Issues)'s what comes up searching for `getfilesystem` on the repo. From these, #689 and #635 seem to be relevant and have been fixed by #674, which implements the `get_filesystem_encoding`. I think we could try and create some tests for this and see exactly what can be removed from the code without issues. I'm not sure about how to implement these tests for different architectures though, but it should be fun :)

**Comment by davidism** [comment]
To follow up on this, it looks like Werkzeug's `get_filesystem_encoding` uses the same logic as PEP 538 and PEP 540: on Linux, if the encoding is not available or is "C", use "UTF-8" instead. Once we drop Python 3.6 support, probably in 2.1, we can remove these functions.
