### ISSUE TITLE
refactor live server tests

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#1762]
These tests cause false positive test failures constantly. People get confused when their PRs randomly fail, and I have to drop in and re-run the failed worker, sometimes multiple times before it takes. The most flaky tests are those that use the reloader. They often time out because something weird went wrong while starting the process, and so the CI worker spins for 10 minutes or whatever the timeout is. Even when they work, these tests are *slow*, running tox locally takes forever because of them.

Part of the problem with fixing that is that the implementation is a nightmare. Once you untangle it (and that's not trivial), it's apparent that there was a lot of clever problem solving going on, but it got out of hand. We need to simplify this in order to make any headway. Unfortunately, it's been a while since the last time I dove in, but I'll try to outline how it currently works.

1. The `dev_server` fixture produces a function that takes a string of Python code, writes the default `run_simple` kwargs (localhost and a unique port) and the source to a temporary file, and patches that into `sys.path`.
2. It imports the new module and reads off the kwargs to figure out if the test source changed the host or set up TLS.
3. It uses `xprocess` to *run `conftest.py` as a Python module*. The argument on the command line is the temp dir to add to the path. It patches the reloader to log loops, adds a middleware to get the inner pid when the reloader is active, then calls `run_simple` with the kwargs from the imported module.
4. Some tests make a request and examine the response. Others read the log file from `xprocess`. Reloader tests wait for either the reloader loop or the inner pid to change, or both. This is exposed through the object the `dev_server` function returns to the test.
5. Finally, special care has to be taken to kill the process group (and it's different on Windows, of course), since xprocess doesn't kill the reloader correctly on its own.

Here are some general ideas / order for refactoring:

1. Create a `test_apps` directory and extract the various strings of code to Python files.
2. Consolidate them to a minimum set needed for tests, since there's probably a lot of overlap or minor unnecessary differences.
3. Put the `test_apps` directory on the path instead of dealing with temporary directories.
4. Create a `test_apps/run.py` file to be the entry point for `xprocess.ensure`.
5. Expose a common API for making a request to the server, rather than manually setting up `HTTPConnection` in every test.
6. Drop requests and use `http.client` everywhere (need to deal with unix socket).
7. Simplify how we test the reloader. I have no idea how yet.

This still ends up somewhat circuitous, but hopefully easier to visualize at least. Maybe we'll see an even better solution as we start refactoring.

**Comment by kbanc** [comment]
@aenglander are you still working on this? If not I'd like to give it a go.

**Comment by davidism** [comment]
@kbanc it's fine for you to start on this,
