### ISSUE TITLE
High memory consumption uploading a file

### ISSUE THREAD

**Issue by robbitara** [pallets/werkzeug#1771]
I have already read every issue about this, especially #1041 that seems the most similar to my case.
This is what I do:
```python
class Uploadd(Resource):

    def post(self):
        
        filename = request.headers['X-Content-Name']

        with open('/home/roberto/upload/' + filename, 'ab') as file:
            file.write(request.stream.read()) 

        return "OK"
    
    def get(self):
        return "GOOD"
```
Basically I send a file splitted in chunks (20 MB each) from the browser with ES8 fetches.
In the request body I put the chunk and I set the content type to 'application/octet-stream'.
Server side I do what you can see above, and what happens is that my memory buffer / cache grows exactly by the size of the file I upload. And this is bad, because uploading more than 2/3 files would fill the available memory. 
Here is a [video demostration](https://youtu.be/vAawXdx0trk) of the issue.

**Comment by jab** [comment]
Please use StackOverflow for questions about your own code. e.g. https://stackoverflow.com/questions/36875258/copying-one-files-contents-to-another-in-python looks relevant to what you're trying to do.

**Comment by robbitara** [comment]
@jab I don't think that this is an issue regarding my own code only.
Because just by making this:
`data = request.data`
or this:
`data = request.stream.read()`

The content of the file that I'm sending is all cached in memory.
The link that you attached is not related to this issue in any way.
What I am experiencing is very similar to [this issue](https://github.com/pallets/flask/issues/2086).
Is there any explanation of this?

**Comment by jab** [comment]
Your code `data = request.stream.read()` literally means “read the entire contents of the stream into memory, and store it in the “data” variable. The SO link shows how to avoid that by reading a chunk at a time (passing an into to the `read(...)` call for max bytes to read) as well as higher-level ways to do it using `copyfileobj` and `sendfile`. If you have any further questions, please post to SO.
