### ISSUE TITLE
ModuleNotFoundError with mod_wsgi

### ISSUE THREAD

**Issue by nikosft** [pallets/werkzeug#1776]
In Ubuntu 18.04, although my script was executed correctly using the command line, when using apache2 and mod_wsgi I was receiving the following error:

`ModuleNotFoundError: No module named 'werkzeug'`

It turns our that pip installs modules locally for each user and I had to install the module using this command

`sudo -H pip install Werkzeug`

Does this seem correct? If yes may be a note should be added in `https://github.com/pallets/werkzeug/blob/master/docs/deployment/mod_wsgi.rst`

**Comment by davidism** [comment]
No, absolutely never use `sudo pip`. Create a virtualenv and install to it. Configure mod_wsgi to use that env. See mod_wsgi docs for details.
