### ISSUE TITLE
Support X-Forwarded-*

### ISSUE THREAD

**Issue by danny0838** [pallets/werkzeug#1777]
Currently `get_current_url` ignores the `X-Forwarded-Proto` even if set by the reverse proxy, causing `request.url` to have wrong scheme if the client requests `https` while the backend application is served under `http`.

This can be fixed by replacing `environ["wsgi.url_scheme"]` to use `X-Forwarded-Proto` in precedence for `get_current_url`:
https://github.com/pallets/werkzeug/blob/237b35a63631fda0fe80eb51dccdfe8a2f50d304/src/werkzeug/wsgi.py#L71

For reference: [Bottle](https://bottlepy.org/docs/dev/_modules/bottle.html#BaseRequest.urlparts)'s support for X-Forwarded-Proto.

Similarly, `X-Forwarded-Host` can be used in precedence of `HTTP_HOST`.

**Comment by davidism** [comment]
Use the ProxyFix middleware.

**Comment by danny0838** [comment]
@davidism Thank you and sorry for not having noticed about this. Is there also support for [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded)?
