### ISSUE TITLE
SameSite option document is not updated

### ISSUE THREAD

**Issue by seanxlliu** [pallets/werkzeug#1779]
On the flask [document page](https://flask.palletsprojects.com/en/1.1.x/security/#set-cookie-options), it writes,

_SameSite restricts how cookies are sent with requests from external sites. Can be set to 'Lax' (recommended) or 'Strict'. Lax prevents sending cookies with CSRF-prone requests from external sites, such as submitting a form. Strict prevents sending cookies with all external requests, including following regular links._

However, it has supported `'None'` as a valid value.

**Comment by davidism** [comment]
It will be updated the next time the Flask docs are rebuilt.
