### ISSUE TITLE
REQUEST_URI should preserve the query string

### ISSUE THREAD

**Issue by fmang** [pallets/werkzeug#1781]
REQUEST_URI was introduced by #1419: https://github.com/pallets/werkzeug/pull/1419/commits/7162f432417c5c0c25827eaa7367dfda7ee56d9c

Currently, Werkzeug strips the query string. While REQUEST_URI is not a standard variable, I believe the consensus is to include the query string. According to https://github.com/pallets/werkzeug/issues/766#issuecomment-441495490 that should have be the case for Werkzeug too.

That applies to RAW_URI too.

It’s an edge case, but ideally empty query strings like in `/?` should be preserved too and not simplified to `/`.

**Comment by davidism** [comment]
I can't reproduce this issue. I ran the following example and got the full unquoted path and query.

```python
from pprint import pformat
from werkzeug import Request, Response, run_simple

@Request.application
def app(request):
    return Response(pformat(request.environ))

if __name__ == "__main__":
    run_simple("localhost", 5000, app)
```

Navigating to `http://localhost:5000/a%2fb?a=%2f`, `REQUEST_URI` was `/a%2fb?a=%2f`.

**Comment by davidism** [comment]
#1782 shows that this is about the test client, not the dev server.

**Comment by kx-chen** [comment]
Working on this.
