### ISSUE TITLE
Mod_wsgi and Apache

### ISSUE THREAD

**Issue by Pablo-Marina** [pallets/werkzeug#1783]
Hello:

I'm having problems installing mod_wsgi on Apache. The idea is to include a file called mod_wsgi.so in apache/modules/ but all I find on the Internet are mod_wsgi folders containing several stuff but not a single one with .so extension. So happens with the "pip" command.
So any ideas of what should I do?
Thank you!

**Comment by ThiefMaster** [comment]
This is out of the scope of werkzeug. You usually use your distribution's package manager to install the `mod_wsgi` module for apache.

PS: If you don't have any specific requirement on mod_wsgi, it'd probably be easier to use uwsgi or gunicorn.
