### ISSUE TITLE
Problem installing mod_wsgi on Apache

### ISSUE THREAD

**Issue by Pablo-Marina** [pallets/werkzeug#1784]
Hello:

I'm having problems installing mod_wsgi on Apache. The idea is to include a file called mod_wsgi.so in apache/modules/ but all I find on the Internet are mod_wsgi folders containing several stuff but not a single one with .so extension. So happens with the "pip" command.
So any ideas of what should I do?
Thank you!

**Comment by ThiefMaster** [comment]
Please do not open duplicate issues. #1783
