### ISSUE TITLE
get_json function returning None when force equal to true is used

### ISSUE THREAD

**Issue by duducp** [pallets/werkzeug#1789]
Hello,

When I use `get_json(silent=True, force=True)` and there is no value in the request body, the function returns me with a _None_.

Wouldn't the correct be an empty dictionary since I'm saying that _force_ is true?

A possible correction could be as follows:
https://github.com/pallets/werkzeug/compare/master...duducp:patch-1

**Comment by ThiefMaster** [comment]
why? null / None seems more sensible to me than an empty dict. not all json payloads are dicts.
