### ISSUE TITLE
Content-Type routes

### ISSUE THREAD

**Issue by Avamander** [pallets/werkzeug#1794]
Given that quite a few people build APIs using Flask, I think it would be nice to have a built-in way to create routes per content-type. 

For example:
```
@app.route("/new", methods=["GET"])
def new():
    return render_template("form.html")

@app.route("/new", methods=["POST"], content-types=["application/json"])
def new_json():
    # do stuff with JSON
    return some_json

@app.route("/new", methods=["POST"], content-types=["application/html"])
def new_html():
    # do stuff with browser form
    return some_page
```

Could this be added to base Flask or should everyone really implement this functionality using some other (library's) decorator?

**Comment by davidism** [comment]
The routing is already complicated enough. This adds another dimension of complexity to deciding which route to match or build, as well as for humans to understand the routing table they've defined. Incorrect content type is presumably a 400 error, not 404, so it's not strictly related to routing either.

Also, your example is wrong, you'd want to accept both `application/x-www-form-urlencoded` and `application/form-data` to accept form data, which seems fairly verbose for little payoff.

What form the data is sent in doesn't really seem like it should change what an endpoint does, and I think the much better API design is to accept one form of data and stick with it, letting the API return 400 for bad data. If you do want to accept multiple types, you probably want some way to normalize that data before working with it, at which point having different routes doesn't really help anyway.

This seems better suited to an API extension, or a dispatching view similar to Flask's `MethodView` class.

**Comment by Avamander** [comment]
> Also, your example is wrong, you'd want to accept both application/x-www-form-urlencoded and application/form-data to accept form data, which seems fairly verbose for little payoff.

Yeah, you're correct, I fixed that for future reference.

**Comment by Avamander** [comment]
> What form the data is sent in doesn't really seem like it should change what an endpoint does, and I think the much better API design is to accept one form of data and stick with it,

Well, I can think of cases where POST forms have CSRF protection and JSON endpoints have different authentication.

**Comment by Avamander** [comment]
> Incorrect content type is presumably a 400 error, not 404, so it's not strictly related to routing either.

This is correct, but theoretically Flask could handle this case by first looking up path, then method, then content-type?

Thank you for replying though!
