### ISSUE TITLE
Using Response.from_app updating the request "body" object also updates flask.request.json object

### ISSUE THREAD

**Issue by rwuebker** [pallets/werkzeug#1795]
Hello,

Using the following:
python 3.6.8
connexion[swagger-ui]==2.7.0
flask==1.0.4
werkzeug==1.0.1

If I use the Response.from_app method and I modify the body object inside my handler, it also updates the flask.request.json object. This is only for swagger 2.

If I use a swagger 3 file, this does not happen.

I created a repo to demonstrate this:
https://github.com/rwuebker/flask-swagger-connexion-issue

Steps to reproduce:
1. clone the repo above
2. pip install -r requirements.txt
3. run "python app.py:"
4. notice the final assertion error

Thanks for taking a look!

**Comment by davidism** [comment]
I appreciate that you've made an example to reproduce your issue, but there is too much non-Werkzeug code that I'm not familiar with for me to step through and debug. You indicate that `from_app` is the issue, but it's not clear why, as opposed to an issue with Connexion or something else in Werkzeug. *Maybe* this is related to #1698?

Closing for now as it's not clear what issue is being reported.
