### ISSUE TITLE
Allow BaseRequest subclasses to override empty argument value

### ISSUE THREAD

**Issue by jayaddison** [pallets/werkzeug#1799]
As part of a [Flask](https://github.com/pallets/flask) application I have encountered a possibly rare use case where I'd like to supply a query-string parameter name, but provide no value for it.

It's essentially an indicator from the client to the host that the client's interested in a certain field/item, but doesn't want to specify any value for it (which in Pythonic, I think translates most closely to a `None` representation).

The specific handling I'm looking for is that a URI with the query-string `?foo=1&bar=&baz` should parse to a Python dict-like `{'foo': '1', 'bar': '', 'baz': None}`, although that's my particular use case and others may have different requirements.

Although deployed implementations have a tendency to define the 'real world' rules, I've confirmed against the current URI RFC ([RFC 3986](https://tools.ietf.org/html/rfc3986)) that it should be valid for a query string to contain parameters without corresponding `=` attachments (whether the right-hand-side is empty or not).

I looked into subclassing Flask's [`Request`](https://github.com/pallets/flask/blob/master/src/flask/wrappers.py#L20) class, but it looks like query-string handling is one level lower in the stack, here in `werkzeug`.

**Comment by davidism** [comment]
Hmm, this is interesting to consider what the value of `bar=` vs `baz` is, but I don't think this level of customization is needed in Werkzeug. You can already override the `Request.args` property and decode `self.query_string` manually if you need something different. Adding obscure customization points like this isn't the direction I want to take right now.

**Comment by jayaddison** [comment]
Thanks for the thoughtful feedback @davidism; and yep, I've confirmed locally that overriding `Request.args` (for either the flask or werkzeug request classes) works well; I'll go with that approach for now.

I definitely appreciate that simplicitly is a relief for everyone's software complexity (and mental) burdens.

It's plaintive of me, but for what it's worth: small feature flags like [strict_slashes](https://github.com/pallets/werkzeug/blob/fa6781dfbf73288c63fe885c2220536fb46f7c35/docs/routing.rst#rule-format) have saved me from headaches and uphill battles in the past

I see the `empty_value` option as existing in similar territory -- disabled and quietly ignored for most, but with the capability to brighten a developer's day relative to the prospect of initiating organization-wide library updates.
