### ISSUE TITLE
limit the input length of a request to that specified in Content-Length.

### ISSUE THREAD

**Issue by posativ** [pallets/werkzeug#181]
I am not that familiar with WSGI details, but the [dulwich](https://www.samba.org/~jelmer/dulwich/apidocs/) sample `git-http-backend` has a Middleware that fixes non-conforming WSGI servers by limiting the input length of a request to that specified in Content-Length.

I am not sure wether this is an issue of werkzeug, but I first did not use this Middleware and the `git push` never finished (though the push was successful, but git did not returned to shell). As I wrapped the application through `LimitedInputFilter` the push terminated correctly.

I am talking about https://github.com/jelmer/dulwich/blob/master/dulwich/web.py#L197 and I am using werkzeug's run_simple as development server.

**Comment by untitaker** [comment]
From the WSGI spec:

>The server is not required to read past the client's specified Content-Length , and is allowed to simulate an end-of-file condition if the application attempts to read past that point. The application should not attempt to read more data than is specified by the CONTENT_LENGTH variable. 

The wording is confusing, but the last statement is pretty clear.

**Comment by alexpantyukhin** [comment]
But actually `get_input_stream` uses the `LimitedStream` which doesn't read more then `CONTENT_LENGTH` bytes number https://github.com/pallets/werkzeug/blob/master/werkzeug/wsgi.py#L980

**Comment by davidism** [comment]
Appears to be addressed.
