### ISSUE TITLE
Debugger icons license/attribution

### ISSUE THREAD

**Issue by ofawx** [pallets/werkzeug#1813]
The icons **console.png** and **source.png**  in the debugger **[werkzeug/src/werkzeug/debug/shared/](https://github.com/pallets/werkzeug/tree/master/src/werkzeug/debug/shared)** appear to come from the [Silk icon set](http://www.famfamfam.com/lab/icons/silk/), from the icons _application_xp_terminal_ and _page_code_ respectively, which are CC BY 2.5/3.0 licensed.

I can't find any attribution for these in this project, and am not of the view that their inclusion is particularly compatible with the BSD 3-clause license that it is distributed under.

I'm rather new to OSS and its licensing intricacies but thought this was worth raising. I see solving this in two steps:

1. Provide attribution for whatever icons are used, Silk currently.
2. Switch the icons out for a more BSD-compatible equivalent, probably MIT. I would be happy to find an appropriate alternative and raise a PR, if you agree with all of the above.

**Comment by davidism** [comment]
I don't really see the licenses as incompatible, so unless you're the author and have more specific insight, I'm fine with just adding the license next to the files. I'm also open to replacing them with something in the public domain that does not require a license, or original icons contributed under our license.

**Comment by teymour-aldridge** [comment]
I'm not a lawyer and this isn't legal advice, but I'd argue that the BSD 3-Clause license only applies to the distribution of "code" in "source or binary forms" so I'd suggest that images don't count as being included under the license (though you could argue that they're binary files).

**Comment by obfusk** [comment]
IANAL either but I'm fairly certain the licenses are not incompatible (maybe if the images were directly embedded in the source code - thus creating a combined work - but I don't see how either license would restrict distributing code and "data" together).

I think that adding the required attribution for the icons should solve this.

**Comment by teymour-aldridge** [comment]
I know approximately 0 about law. Attribution sounds like a good move 😄
