### ISSUE TITLE
Append trailing slash to URL broken

### ISSUE THREAD

**Issue by oztourer** [pallets/werkzeug#1842]
There is a bug in utils.py function append_slash_redirect() for the case where a URL is missing a trailing slash. Before adding the slash the current code removes any existing slash. It unfortunately also removes the leading slash, causing the URL to become relative instead of absolute.

Line 542 currently uses strip('/') but should use rstrip: 

    `new_path = environ["PATH_INFO"].rstrip("/") + "/"`

**Comment by davidism** [comment]
Duplicate of #1538

**Comment by davidism** [comment]
Addressed in #2338
