### ISSUE TITLE
bug: @cached_property property can be set

### ISSUE THREAD

**Issue by danrobinson88** [pallets/werkzeug#1858]
See code example:

```python
from werkzeug.utils import cached_property    

class A(): 
      @cached_property 
      def foo(self): 
           return 3 

a = A()
a.foo = 2
```
This should raise an exception

**Comment by kx-chen** [comment]
One of the tests for `cached_property` checks for this exact use case. https://github.com/pallets/werkzeug/blob/f3f9d983b80e8d3ff0597ec1a57e4a96c3c99192/tests/test_utils.py#L86

What's the difference between that test case and this?

**Comment by ThiefMaster** [comment]
Also what's the problem with it? Getting it returns the cached value or runs the method to compute the value. Setting it will set the "cached" value explicitly. Seems logical to me.
