### ISSUE TITLE
send_file: allow filename for inline content-disposition 

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/werkzeug#1869]
`send_file` should support `attachment_filename` even for content-disposition inline.

Including a filename with inline files makes perfect sense e.g. when serving images users may want to "rightclick -> save as".
To avoid breaking API changes I would recommend keeping `attachment_filename` for it, but sending a content-disposition:inline header in case `as_attachment` is false. Alternatively we could deprecate `attachment_filename` in favor of a new `client_filename`, where the old kwarg would not add an inline disposition while the new one would.

This depends on #1850 since it moves `send_file` from Flask to werkzeug.

**Comment by davidism** [comment]
Since this is essentially a fresh start, we can just rename it `client_filename` with the behavior described. Flask's `send_file` will still exist as it has to get various Flask-specific data, so it can do the deprecation there.

**Comment by davidism** [comment]
`download_name` seems like a clearer description of what the parameter does.
