### ISSUE TITLE
Accept needs a strict mode check to exclude * matches

### ISSUE THREAD

**Issue by mortoray** [pallets/werkzeug#1895]
The `Accept` type needs a strict mode checking to exclude the * types from matching.

For example, given the header `image/png,image/svg+xml,image/*;q=0.8,video/*;q=0.8,*/*;q=0.5` a strict check for `image/webp` should fail. Currently the find, best_match, and `in` tests return a match.

This is motivated by browsers that are essentially lying about what they accept with *'s.

For WebP, the standard says the `image/webp` should  be listed explicitly in the header. But `Accept` right now has no function that would do that check.

**Comment by mortoray** [comment]
I'm not saying they are doing the wrong thing, I'd also agree that's the correct interpretation of those headers. Alas, the way the browsers are working is not helpful. They always add wildcards to the accept lists even if they can't handle the type. For example, in that above accept stirng the "image/*" implies WebP, but that browser (Safari) does not support them. It's unlikely it can support all image formats as it claims, and certainly not he */* as the final match.

They do at least report a q < 1 when they don't support something.

For WebP the convention is to explicitly add "image/webp" to the list so it can be detected. I'm asking for a function that would do this type of explicit matching.

At the moment I use the `quality` function, and if the value is < 1 assume it's not supported. Perhaps this is the solution.

**Comment by davidism** [comment]
It's unfortunate that browsers are reporting incorrect values. However, as pointed out, the current implementation is also correct. As I don't completely understand the issue and am not clear how the proposed API should be implemented, I'm going to close this. Your workaround sounds acceptable for now.
