### ISSUE TITLE
Timezone in request's date properties

### ISSUE THREAD

**Issue by kam193** [pallets/werkzeug#1900]
HTTP-date are always in UTC [[RFC]](https://tools.ietf.org/html/rfc7231#section-7.1.1.1), however Werkzeug return dates from headers as naive `datetime` objects [[code - parser]](https://github.com/pallets/werkzeug/blob/ed7bdd1402d948a3a3cf5a29ffca152b651617a9/src/werkzeug/http.py#L800), [[code - properties]](https://github.com/pallets/werkzeug/blob/6868ede8ba4e1f883952154ba68883efac0021a0/src/werkzeug/wrappers/etag.py#L53). 

I propose to add timezone info as UTC for each date (by default or as optional behavior).

Currently, when we want to compare date from request (e.g. `if_modified_since`) we need to either add timezone to date from request or force second part of comparison to be naive. However, RFC strictly defined which timezone has HTTP-date, so I think it would be naturally to add it for objects.

**Comment by pgjones** [comment]
I think this makes sense, especially as Werkzeug has dropped Python 2. My view would be to change it to be UTC timezone by default and note the potential breakage in the changelog. I defer to @davidism for a decision though.

**Comment by davidism** [comment]
I'm ok with doing this, something similar is being done in ItsDangerous 2.0.

**Comment by davidism** [comment]
Python 3.3 added a bunch of stuff that lets us basically replace all our implementation: `email.utils.parsedate_to_datetime`, `formatdate`, and `format_datetime`. Also, `werkzeug.http.cookie_date` appears entirely unnecessary now, nothing in any specs I found says that cookie dates need "-" as the delimiter, they use the same HTTP date as everywhere else. Also also, we were passing along "weekday" as "millisenconds" to `datetime`, which was giving a value of 0-6 milliseconds for any given day.
