### ISSUE TITLE
Werkzeug stores cookies values with the same name in-order, but should take domain into account

### ISSUE THREAD

**Issue by sdwvit** [pallets/werkzeug#1908]
https://github.com/pallets/werkzeug/blob/master/src/werkzeug/http.py#L1057
```
 The same key can be provided multiple times, the values are stored
    in-order. The default :class:`MultiDict` will have the first value
    first, and all values can be retrieved with
    :meth:`MultiDict.getlist`.
```

However, if you check the specification (and how browser handle it):
https://tools.ietf.org/html/rfc6265
```
 Although cookies are serialized linearly in the Cookie header,
   servers SHOULD NOT rely upon the serialization order.  In particular,
   if the Cookie header contains two cookies with the same name (e.g.,
   that were set with different Path or Domain attributes), servers
   SHOULD NOT rely upon the order in which these cookies appear in the
   header.
```

To replicate, have 2 flask-based websites with auth. Given they are on different domains: `a.b.com` `b.com` with a common part `b.com`, authorize on b.com and then try to authorize on a.b.com and do logged-in only request on a.b.com. It fails with authorization error. The short explanation is: flask uses werkzeug's base_request and receives auth cookie via request.cookies['session'], which calls parse_cookie [here](https://github.com/pallets/werkzeug/blob/09a248649069780b4adfb910fb69f6fb304f2ea3/src/werkzeug/wrappers/base_request.py#L519)

Expected behavior: it works by the latest rfc spec.

Environment:

- Python version: 3.6
- Werkzeug version: current

**Comment by davidism** [comment]
I'm sorry, I don't understand this request. Werkzeug just decodes the cookies sent to it by the client. If your browser is sending cookies for domains you didn't expect, that seems like either an issue with the browser (unlikely) or your expectation.

As far as I can tell Werkzeug is compliant with the spec. If it receives two values, it will parse two values, but that doesn't imply that that order can be relied on, just like what you quoted says.

**Comment by sdwvit** [comment]
@davidism hey, thank you and sorry for confusion. I believe it may be a bug in flask, rather than in werkzeug.

**Comment by davidism** [comment]
It's not in Flask or Werkzeug. Browsers send the appropriate cookies with each request, but those sent values have no domain information at that point. It's only when you're setting cookies that you can control the domain. You'll need to debug how your project is set up.

**Comment by sdwvit** [comment]
@davidism yep, after sleeping on it I decided to check which order chrome sends cookies. And it sends more generic cookie first 🤦
