### ISSUE TITLE
Reloader removes venv's site-packages

### ISSUE THREAD

**Issue by flying-sheep** [pallets/werkzeug#1914]
I have dash installed in a venv. Dash uses Flask behind the scenes.

Running the following minimal Dash app in debug mode crashes:

```py
import dash
import dash_html_components as h

app = dash.Dash(__name__)
app.layout = h.Div(['Hi'])
app.run_server(debug=True)
```

```pytb
 Warning: This is a development server. Do not use app.run_server
 in production, use a production WSGI server like gunicorn instead.

 * Serving Flask app "scratch" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "~/Library/Application Support/JetBrains/PyCharm2020.2/scratches/scratch.py", line 1, in <module>
    import dash
ModuleNotFoundError: No module named 'dash'
```

Environment:

- Python version: 3.8.5
- Werkzeug version: 1.0.1

**Comment by jab** [comment]
Based on your bug report, this looks like a problem with your environment. This issue tracker is for problems in Werkzeug. Please use StackOverflow for help with problems like this.

**Comment by flying-sheep** [comment]
I have 10 years of Python experience. Might be that you're right, but usually I open issues for a reason.

**Comment by flying-sheep** [comment]
So can you please reopen this?

**Comment by davidism** [comment]
I can't reproduce this issue as described. The code provided starts the server with the reloader successfully. A sample Flask app using `app.run()`, and a sample Werkzeug app using `run_simple` also worked. This suggests that there's an issue with your environment which you'll need to identify and debug on your own. Sorry we can't help more with that.
