### ISSUE TITLE
scrypt support in `generate_password_hash`/`check_password_hash`

### ISSUE THREAD

**Issue by homeworkprod** [pallets/werkzeug#1917]
Starting with Python 3.6, [scrypt](https://en.wikipedia.org/wiki/Scrypt) ([RFC 7914](https://tools.ietf.org/html/rfc7914.html)) is available in the standard library as [`hashlib.scrypt`](https://docs.python.org/3/library/hashlib.html#hashlib.scrypt). As it is a more recent, arguably "safer" alternative to PBKDF2, it would be splendid to be able to use it for password hashes as well.

Due to it's nature, it is not available via `hashlib.new('scrypt', …)` and, thus, would require extra support in Werkzeug, [similar to PBKDF2](https://github.com/pallets/werkzeug/blob/ef545f0d0bf28cbad02066b4cb7471bea50a93ee/src/werkzeug/security.py#L133).

Since Werkzeug requires at least v3.6 of Python anyway, older versions need not be handled.

I couldn't dig up any previous discussions about it. Has this been considered and evaluated before?

**Comment by davidism** [comment]
If you need extended hashing support, use Passlib.

**Comment by homeworkprod** [comment]
Fair enough.

For the record, I suggested adding support for it *because* it would not introduce a new dependency and spare users from having to install Passlib while still getting easy access to a "modern" PBKDF (as bcrypt isn't available without an additional dependency).

**Comment by davidism** [comment]
I'm not referring to a new dependency when I refer to "added complexity". Just adding more paths for special cases in `generate_password_hash` is more complexity on its own. For most applications, `generate_password_hash` will be just fine. For anyone considering upgrading their security from there, they'll want to use Passlib anyway for all the other features it provides.

**Comment by homeworkprod** [comment]
> I'm not referring to a new dependency when I say "adding support". Just adding more paths for special cases in generate_password_hash is more complexity to support.

I had read it that way, and I agree. Thank you for clarifying nevertheless.

**Comment by MartinThoma** [comment]
I haven't heard about passlib before so I looked them up

* [Source](https://foss.heptapod.net/python-libs/passlib): last commit is less then a week ago; 14 contributors
* [PyPI](https://pypi.org/project/passlib)
* [Eli Collins](https://www.linkedin.com/in/eli-collins-4b619545/): Main developer
* [StackOverflow](https://stackoverflow.com/questions/tagged/passlib): 39 questions

Although there are other contributors, there seem not to be that many.

**Comment by davidism** [comment]
https://github.com/pallets/werkzeug/issues/2654
