### ISSUE TITLE
Empty fragment ignored by redirect/iri_to_uri

### ISSUE THREAD

**Issue by phryk** [pallets/werkzeug#1921]
```
import werkzeug
werkzeug.urls.iri_to_uri('#')
```

This should have returned `#`, but instead returns an empty string.
This is a problem because fragment identifiers are preserved across redirects unless the location redirected to
contains `#`, which for me then leads to previous double opt-in modals being shown after a form is submitted.

My current workaround for this is redirecting to `#_`.

Environment:

- Python version: 3.7.8
- Werkzeug version: 1.0.0

**Comment by davidism** [comment]
The `url_parse` and `url_split` functions are used to implement `iri_to_uri`. These functions are copies of Python's `urllib.parse.urlparse` and `urlunparse` (for historical reasons) and are intended to have the same behavior. In particular, `urlparse` on an empty fragment returns an empty value, and `urlunparse` on an empty value does not produce an empty fragment.

I don't think we should change this. Your workaround seems fine, or you can intercept the response returned by `redirect` and add a fragment:

```python
response = redirect("#")
response.location = f"{response.location}#"
return response
```

I don't know about your specific app, but something seems weird about redirecting to the same location. If you're using AJAX, you don't need to return a redirect, and can also remove an existing fragment once the response is successful, using the same mechanism you're using to add fragments for modal navigation in the first place.
