### ISSUE TITLE
HTTP Utilities docs refers to old cStringIO module.

### ISSUE THREAD

**Issue by vlade11115** [pallets/werkzeug#1926]
HTTP Utilities docs code sample for Form Data Parsing https://werkzeug.palletsprojects.com/en/1.0.x/http/#module-werkzeug.formparser refers to `cStringIO` module. This module is gone in [Python 3](https://docs.python.org/3.0/whatsnew/3.0.html#text-vs-data-instead-of-unicode-vs-8-bit)
`from cStringIO import StringIO`
Should be changed to `from io import StringIO`
May I create PR to fix this?
According to [contributing guidelines](https://github.com/pallets/werkzeug/blob/master/CONTRIBUTING.rst#submitting-patches) `If there is not an open issue for what you want to submit, prefer opening one for discussion before working on a PR.` This is why I create issue, not PR.

**Comment by davidism** [comment]
Fairly sure it needs to be `BytesIO` (and the data needs to be a `b""` string), but yes, a PR would be great, thanks.
