### ISSUE TITLE
[current default branch] werkzeug always raises a warning on import

### ISSUE THREAD

**Issue by asottile** [pallets/werkzeug#1933]
```console
$ python -Werror -c 'import werkzeug'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/werkzeug/src/werkzeug/__init__.py", line 2, in <module>
    from .test import Client
  File "/tmp/werkzeug/src/werkzeug/test.py", line 46, in <module>
    from .utils import get_content_type
  File "/tmp/werkzeug/src/werkzeug/utils.py", line 303, in <module>
    html = HTMLBuilder("html")
  File "/tmp/werkzeug/src/werkzeug/utils.py", line 234, in __init__
    warnings.warn(
DeprecationWarning: 'utils.HTMLBuilder' is deprecated and will be removed in 2.1.
```

Environment:

- Python version:
  ```console
  $ python --version --version
  Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
  [GCC 9.3.0]
  ```

- Werkzeug version: d7eebd2054842334804e74ec7ad465bc78d7b2e6

This appears to be caused by #1772

**Comment by davidism** [comment]
I'm not sure what's going on here. If you run `pytest` or `tox -e py38` locally, they both succeed, but it's failing in CI here and in Flask.

**Comment by davidism** [comment]
I think what you're saying is that regardless of the weird test failure, it shouldn't be raising a warning on import. That seems reasonable, I'll remove the warning from `HTMLBuilder.__init__` and leave the warning on its other methods.

**Comment by asottile** [comment]
@davidism because the warning happens really early pytest doesn't catch it (until 6.1 where the warning system was reworked)
