### ISSUE TITLE
werkzeug.datastructures.Headers interface is not dict-like

### ISSUE THREAD

**Issue by ergoithz** [pallets/werkzeug#1946]
Documentation says (https://werkzeug.palletsprojects.com/en/master/datastructures/#werkzeug.datastructures.Headers):
> An object that stores some headers. It has a dict-like interface but is ordered and can store the same keys multiple times.

but that assertion is misleading, since looking at the code

https://github.com/pallets/werkzeug/blob/d05ee59d18b895bf204431a501bf6621f3077d5c/src/werkzeug/datastructures.py#L1165-L1167

`Headers.__iter__` returns a list of items (key-value tuples) instead of the keys, rendering it not dict-like.

As this is a quirk already causing trouble to people but fixing it would be API breaking, at least this quirk should be noted on the documentation (and maybe replacing dict-like mentions with the more generic mapping interface).

**Comment by davidism** [comment]
Please submit your suggested PR.
