### ISSUE TITLE
werkzeug.Response.add_etag docstring is not clear enough!

### ISSUE THREAD

**Issue by DarkSuniuM** [pallets/werkzeug#1948]
Hello there,
This is not a bug, It's related to documentation, I found `Response.set_etag` and `Response.add_etag` docs a little confusing!

0. Open a Python console
0. Import `werkzeug.Response`
0. Run `help(werkzeug.Response.set_etag)`
0. Run `help(werkzeug.Response.add_etag)`

I expected the `werkzeug.Response.add_etag` docstring be more specific about using the `werkzeug.Response.get_data`.

Environment:

- Python version: 3.8.6
- Werkzeug version: 2.0.0.dev

**Comment by davidism** [comment]
Seems clear to me, and the suggested fix didn't make this clearer, so I'm going to close this.

**Comment by DarkSuniuM** [comment]
@davidism The key element is the "Based on" part, The way I see it, both `set_etag` and `add_etag`, can add or set etag on the response, but one of them takes an argument which is the actual etag, while the otherone does the etag calculation based on the `response.get_data`, regardless of the etag you may wanna set!
just having them as `set` and `add` does not clarify that one of them gets calculated automatically
