### ISSUE TITLE
Why not add import for JSONMixin

### ISSUE THREAD

**Issue by purplemysticx** [pallets/werkzeug#1959]
Environment:

- Python version: 3.8.6
- Werkzeug version: 1.0.1

Add `from .json import JSONMixin` to `werkzeug/wrappers/__init__.py`, right?

**Comment by davidism** [comment]
I've got something planned about this, but it involves a larger change than just adding this import. I don't think it's particularly important to have a shortcut import for this (or most things), so I'm going to close this.
