### ISSUE TITLE
reload via kqueue on BSD

### ISSUE THREAD

**Issue by dannybr** [pallets/werkzeug#1966]
can kqueue/stat be optional?

on bsd systems kqueue does not work for NFS based files.
in my case the solution was to remove watchdog.py which triggerd the use of kqueue instead of stat

**Comment by davidism** [comment]
Watchdog is an optional dependency. If you don't install Watchdog, the slower, built-in stat reloader will be used. If you need watchdog for other reasons, you can also pass `reloader_type="stat"` to `run_simple`.

**Comment by dannybr** [comment]
thanks for a very quick response!
and it works now!
great!!
thanks again,
	danny
