### ISSUE TITLE
Command history (arrow keys) breaks while debugging when reloader is enabled

### ISSUE THREAD

**Issue by susodapop** [pallets/werkzeug#1968]
## Issue Description 
If the reloader is enabled, command history doesn't work while using `pdb` in Windows.

## Steps to Reproduce

I've reproduced this on three Windows 10 Pro machines.

0. In a fresh virtualenv install `werkzeug`.
1. Copy the simple usage example from the [README](https://github.com/pallets/werkzeug/blob/master/README.rst)
2. Enable the reloader with `use_reloader=True` and insert a `breakpoint()` in the `application` function.
3. Run the code and visit `localhost:4000` in your browser. Then return to the command prompt. `pdb` is now active.
4. Type `x=10` and press enter
5. Press the up arrow. The command  `x=10` does not appear on the current line.
6. Kill the server with `ctrl+c` and set `use_reloader=False`
7. Repeat steps 3,4, and 5. The command  `x=10` will appear again on the current line.

On MacOS you will see `x=10` reappear. On Windows, nothing appears.

I tested in cmd.exe, powershell, and the new windows terminal. It behaves the same with `stat` and `watchdog`.  I observed it for ~12 months but only dug into today. I found [this SO page](https://stackoverflow.com/questions/1241453/why-do-windows-consoles-lose-command-line-history-up-arrow-after-a-time) that observes the same behavior unrelated to werkzeug. Does anyone else see this? I've disabled the reloader entirely to workaround it.

### Code for this example
```
from werkzeug.wrappers import Request, Response

@Request.application
def application(request):
    breakpoint()
    return Response('Hello, World!')

if __name__ == '__main__':
    from werkzeug.serving import run_simple
    run_simple('localhost', 4000, application,
        use_reloader=True)
```
## Expected Behavior

On MacOS, command history works as expected while using the interactive debugger. I can use the up and down arrows to cycle through past commands.

Environment:

- Python version: 3.8.3
- Werkzeug version: 1.0.1

**Comment by davidism** [comment]
There is absolutely no way I'm going to be able to investigate this, and it sounds like it's only tangentially related to Werkzeug. Seems you've found the much simpler workaround: disable the reloader when using a debugger, which is probably good practice regardless. Happy to consider a fix if you want to look into it, but I probably won't keep this open long term.

**Comment by susodapop** [comment]
I understand completely. I opened this issue on the off-chance there was an obvious fix I missed. And for other google searchers down the line. Thanks for your great work!
