### ISSUE TITLE
Add a hybrid mode to MultiDict

### ISSUE THREAD

**Issue by Diaoul** [pallets/werkzeug#197]
AFAIK, currently you can either convert a MultiDict to a dict of lists or a dict of single values.
An hybrid conversion would be great so that single values keep their values while repeated values are shown as lists.

Currently, this can be done with the Python `cgi` module and its [form.getvalue method](http://docs.python.org/library/cgi.html#higher-level-interface)

```
m = MultiDict([('a', 'b'), ('a', 'c'), ('e', 'f')])
m.to_something()
{'a': ['b', 'c'], 'e': 'f'}
```

Or even better, to avoid confusion, being able to specify a list of exceptions to return as lists:

```
m.to_dict(as_list=['a'])
{'a': ['b', 'c'], 'e': 'f'}
m.to_dict(as_list=['e'])
{'a': 'b', 'e': ['f']}
```

In general, the developer know that such field of a form can return multiple values, type conversion at the early stages like that could be very useful.

FYI: I'm currently porting an app using the `cgi` module to `flask` and `request.form` is a `MultiDict`. I'd rather not to have to write a helper function to convert the `MultiDict`. All this to be able to use [pyextdirect](https://github.com/Diaoul/pyextdirect) with a few lines of code.

**Comment by vitriol** [comment]
I'm sure there was a good reason to having the multidict return only 1 value even though a key holds several, but I'm afraid I can't think of it.

Consider writing an API that accepts both form-data and json data requests. I have no way of easily converting the multidict to it's json equivalent, that is exactly what has been requested above:

<pre> {'a': ['b', 'c'], 'e': 'f'} </pre>

So now I have to go through hoops to convert it into a simple dictionary that only has lists where lists are needed. This seems like an awkward thing to do. Any chance we can reconsider this?

**Comment by mitsuhiko** [comment]
@vitriol the whole problem is already malformed. What you are trying to do there is just dangerous.  Don't do that :)
