### ISSUE TITLE
User agents not being detected

### ISSUE THREAD

**Issue by JavaScriptDude** [pallets/werkzeug#1971]
While using your utility to parse user agents for calls to my site, I have a few that don't get parsed correctly:

Version not getting parsed on the following user agents:

* `Mozilla/5.0 (Linux; Android 10; motorola edge) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.101 Mobile Safari/537.36`
* `Mozilla/5.0 (Linux; Android 10; motorola edge) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.81 Mobile Safari/537.36`
* `Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.1.4322)`

Detected as 'mozilla' but is actually msie v11:

* `Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko`

**Comment by jcorvino** [comment]
See my comments on issue [#1923](https://github.com/pallets/werkzeug/issues/1923)

We should probably merge these 2 issues since they share the same root problem.

**Comment by davidism** [comment]
Happy to consider a PR that updates the matching rules.

**Comment by Saif807380** [comment]
I'd like to work on this.
