### ISSUE TITLE
LocalProxy is callable() when it is not

### ISSUE THREAD

**Issue by mfrlin** [pallets/werkzeug#1979]
I am using `current_user` from `flask_login` library which is a `LocalProxy` it seems. `current_user` proxies to my User object. I pass `current_user` to GraphQL library which executes this code:

```
...
if callable(value):
    return value(info, **args)
...
```
`callable(value)` returns True but when it gets called my User object is used which is not callable and the code explodes.

Here is a reproducible example:
```
>>> l = Local()
>>> u = l('user')
>>> l.user = "martin"
>>> type(u)
<class 'werkzeug.local.LocalProxy'>
>>> callable(u)
True
>>> u()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/martin/.cache/pypoetry/virtualenvs/at-backend-Jyw7lpcG-py3.8/lib/python3.8/site-packages/werkzeug/local.py", line 375, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
TypeError: 'str' object is not callable
```

Environment:

- Python version: 3.8
- Werkzeug version: 1.0.1

**Comment by davidism** [comment]
Due to the way proxying works, the proxy object will look like it implements every special method, not just `__call__`.  There is no way around this. If you need to work with the object itself, use `proxy._get_current_object()`.
