### ISSUE TITLE
ask flask app to shutdown without request context

### ISSUE THREAD

**Issue by hemna** [pallets/werkzeug#1999]
I am trying to use flask app as a docker healthcheck url mechanism.   I have my own signal handler
that looks for CTRL-C to shutdown all of my app's threads, but this seems to prevent flask from ever
exiting.   I need a programatic way to ask the flask app to shutdown from inside a signal handler
that is used for CTRL-C so all of my threads and flask can gracefully exit.

**Comment by davidism** [comment]
The reloader adds a signal handler for `SIGTERM` that calls `sys.exit()`. If you replace it with your own signal handler, you still need to do what it was doing.

https://github.com/pallets/werkzeug/blob/2190a45fa550030caf64c5403873502a555f8c89/src/werkzeug/_reloader.py#L411
