### ISSUE TITLE
Review Accept.best_match and MIMEAccept._value_matches

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/werkzeug#20]
There was a bug in there and the fix was the switching of two arguments. However it should be ensured that this was the only bug and that it now works as expected. Unfortunately it's slightly underdocumented there.

**Comment by anlutro** [comment]
I'm not sure if this should be a separate issue or not, so I'll just post it here for now.

It seems to me that with a request that has the header `Accept: */*` (which is the default for curl, for example), `best_match` should return the default instead of the first element in the list.

**Comment by davidism** [comment]
#1507 and #1574 have improved how `LanguageAccept` and `MIMEAccept` matching works. Please open a new issue if there's something specific that's not working.
