### ISSUE TITLE
werkzeug logger does not report to external logging handler correctly

### ISSUE THREAD

**Issue by qwofford** [pallets/werkzeug#2002]
I am trying to add my own application's logging handler to werkzeug's log. It mostly works, but is missing some string substitution variables.

Ordinarily, this is the output I see with DEBUG turned on:

```
* Running on http://127.0.0.1:5054/ (Press CTRL+C to quit)"
```

However, if I add my handler to the werkzeug logger in the following way:

```
handler = logging.FileHandler('mylogpath')
log.addHandler(handler)
...
werk_log = logging.getLogger('werkzeug')
werk_log.addHandler(handler)
...
```

...my log only captures this:

```
* Running on %s://%s:%d/ (Press CTRL+C to quit)
```

I expected that my logger would capture the werkzeug logs verbatim.

Environment:

- Python version: 3.7.6
- Werkzeug version: 1.0.1

**Comment by davidism** [comment]
I can't reproduce this issue. The following code produced the expected output in a log file:

```python
import logging

from werkzeug import Request, Response, run_simple

logger = logging.getLogger("werkzeug")
handler = logging.FileHandler("server.log")
logger.addHandler(handler)

@Request.application
def app(request):
    return Response("Hello, World!")

run_simple("localhost", 5000, app)
```

```
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
```
Unrelated to the issue, if you're redirecting the Werkzeug development server logs to a file, it's generally an indication that you're trying to use the development server in production. Do not use the development server in production, use a production WSGI server.
