### ISSUE TITLE
change ident_func RuntimeError to DeprecationWarning

### ISSUE THREAD

**Issue by epandurski** [pallets/werkzeug#2034]
I am not sure if this is a problem with werkzeug 2.0b1, or just Flask not declaring its dependency correctly, and installing werkzug 2.0b1 instead of a compatible version (1.x). The effect is that I get `RuntimeError: The __ident_func__ should not be used in Python 3.7+ as a ContextVar is used.` in all my tests (they worked fine before 2.0b1).

You can see the failed build here:
https://app.circleci.com/pipelines/github/epandurski/flask_signalbus/421/workflows/de9e9d0f-4346-48b0-979a-250e01400056/jobs/755

Here is the package that I am trying to build: https://github.com/epandurski/flask_signalbus
It uses Flask-SQLAlchemy. I guess that ```self.session = self.create_scoped_session(session_options)``` is the source of the problem, but I have not looked at it thoroughly.

Environment:

- Python version: 3.9.1
- Werkzeug version: 2.0b1

**Comment by davidism** [comment]
Changed the title to reflect the change that should happen in Werkzeug.

**Comment by epandurski** [comment]
I do not think that the problem is the version of pip/setuptools. Here is the setup() function of the package that has Flask-SQLAlchemy as a dependency. The build bot installs the most recent python docker image.

```
setup(
    name='Flask-SignalBus',
    version='0.5.6',
    url='https://github.com/epandurski/flask_signalbus',
    license='MIT',
    author='Evgeni Pandurski',
    author_email='epandurski@gmail.com',
    description='A Flask-SQLAlchemy extension for atomically sending messages (signals) over a message bus',
    long_description=__doc__,
    packages=['flask_signalbus'],
    zip_safe=True,
    platforms='any',
    setup_requires=pytest_runner,
    install_requires=[
        'Flask-SQLAlchemy>=1.0',
        'marshmallow-sqlalchemy>=0.22.0',
    ],
    tests_require=[
        'pytest~=4.6',
        'pytest-cov~=2.7',
        'mock~=2.0',
    ],
    classifiers=[
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
    ]
)
```

**Comment by ThiefMaster** [comment]
The problem is that your setup installs prereleases. `python setup.py test` and letting it fetch dependencies via `tests_require` instead of using `pip` to install them seems to use super legacy workflows - for example, I see it building eggs instead of wheels, and installing prereleases...

**Comment by davidism** [comment]
Using setuptools for any commands except builds is deprecated by setuptools, so `setup.py test`, `install`, `develop` etc. You're now discovering why: none of those support the majority of the metadata that PyPI/wheels/pip uses. You need to use `pip` to install packages, and should use `pytest`directly to run tests.

**Comment by epandurski** [comment]
Thanks for pointing this out. This behavior is kind of useful, though -- an early alarm for upcoming problems :)
