### ISSUE TITLE
2.0 upgrade notes

### ISSUE THREAD

**Issue by pokoli** [pallets/werkzeug#2035]
I've seen that the first release candidate was uploaded to Pypi but I was unable to find any release notes.
I see there are some incompatbile changes and some functions have been removed (our test suite is failing because wsgi_to_bytes has been removed). 

Is there any upgrade notes available so we can adapt our library to work with the upcoming new version? 
Is there any planned date for the release of the final version? 

Please let me know if there is any better place to post such questions.

**Comment by davidism** [comment]
https://werkzeug.palletsprojects.com/en/master/changes/#version-2-0-0
