### ISSUE TITLE
Add multipart part headers to  fields

### ISSUE THREAD

**Issue by iakum** [pallets/werkzeug#2049]
Hi everybody,

in a project I use flask which uses werkzeug behind the scenes. In this project I support multipart requests, where one part is JSON and the other XML, for example:

``` python
for _, part in flask.request.files.items():
	if part.content_type == "application/json":
		# do something
	elif part.content_type in ("application/xml", "text/xml"):
	       # do something
```

This code works fine with the following request:

```
--boundary
Content-Type: application/json
Content-Disposition: form-data; name="a"; filename="x"

{
    "a": 1
}

--boundary
Content-Type: application/xml
Content-Disposition: form-data; name="b"; filename="y"

<?xml version="1.0" encoding="ISO-8859-1"?>
<a>
	<b/>
</a>
--boundary--
```

As you can see, I'm not interested into the filenames. But if the filesnames are not set, the formparser parses the parts as "fields" (see [here](https://github.com/pallets/werkzeug/blob/06cf78c66f9ca3448d5c112e3829cb778c1198f5/src/werkzeug/formparser.py#L459)). In this case, I can't access the headers as with files. 

Potential solution

```python
for part in flask.request.form.items():
	if part.content_type == "application/json":
		# do something
	elif part.content_type in ("application/xml", "text/xml"):
	       # do something
```

Request:

```
--boundary
Content-Type: application/json
Content-Disposition: form-data; name="a"

{
    "a": 1
}

--boundary
Content-Type: application/xml
Content-Disposition: form-data; name="b"

<?xml version="1.0" encoding="ISO-8859-1"?>
<a>
	<b/>
</a>
--boundary--
```

Because ImmutableMultiDict is used, I'm not sure if this can be done in a non-breaking change.

**Comment by davidism** [comment]
I don't plan to change this, see https://github.com/pallets/werkzeug/issues/1848#issuecomment-712532762. If you need to support custom behavior, you'll need to implement custom code.

**Comment by iakum** [comment]
Thanks a lot!
