### ISSUE TITLE
Could you keep raw headers in request object？

### ISSUE THREAD

**Issue by zhaoye** [pallets/werkzeug#2063]
I want to get raw header name from request using flask.

e.g.
Request header name t ,but in flask request it is upper case T.

if there is a property named raw_headers, then i can get the real header name.

```python
from flask import request

request.raw_headers
```

**Comment by davidism** [comment]
The WSGI environ (based on CGI) passes all headers as upper case with underscores. We do not have the information needed to do this.

**Comment by zhaoye** [comment]
Got it. Thanks.

**Comment by pgjones** [comment]
ASGI keeps the raw headers - so Quart may be useful to you. They are in the `request.scope.headers`

**Comment by ThiefMaster** [comment]
I'm curious what the usecase for accessing the raw headers is....

**Comment by zhaoye** [comment]
> I'm curious what the usecase for accessing the raw headers is....

It's a testing tool. Record mobile app requests ..
