### ISSUE TITLE
Debugger's library detection doesn't work with symlinks

### ISSUE THREAD

**Issue by brondsem** [pallets/werkzeug#2072]
The debugger's stacktrace nicely colors lines differently if they come from your own code vs library code.  However, this doesn't work correctly if the library path (virtualenv) is a symlink.

I am not 100% sure how to replicate this simply because my environment is part of a fairly complex build system.  But `sysconfig.get_paths()` returns paths like `/var/local/venv/...` and that is a symlink to `/other/path/venv/`

Environment:

- Python version: 3.7
- Werkzeug version: 1.0.1

**Comment by davidism** [comment]
Happy to consider a PR.
