### ISSUE TITLE
Werkzeug development server with reloader crashes on Windows with some ffi imports

### ISSUE THREAD

**Issue by ColdHeat** [pallets/werkzeug#2076]
I am working on a [module](https://github.com/ColdHeat/pybluemonday) that makes use of Golang and FFI. However using it in Windows and Flask with the development server with reloading enabled results in a silent crash in the development server. 

Notice in the following that the first `flask run` command exits silently, but it succeeds if you disable the reloader:
```
PS C:\Users\IEUser\Downloads> $env:FLASK_DEBUG=1
PS C:\Users\IEUser\Downloads> flask run
 * Environment: development
 * Debug mode: on
 * Restarting with stat
PS C:\Users\IEUser\Downloads> flask run --no-reload
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

I traced this down to the the subprocess call in the [`restart_with_reloader`](https://github.com/pallets/werkzeug/blob/c4d85cb9e0e78c2d5786baad649100d42526c399/src/werkzeug/_reloader.py#L248) function. For some reason this subprocess call will return a 1 exit code with no stdout or stderr. 

I tested this out by using the following script:

```python
from flask import Flask

from pybluemonday import UGCPolicy

def sanitize_html(html):
    SANITIZER = UGCPolicy()
    return SANITIZER.sanitize(html)

def create_app():
    app = Flask(__name__)

    @app.route('/')
    def hello_world():
        print("test")
        return sanitize_html('<script>alert(1)</script><h1>asdf</h1>')

    return app

if __name__ == "__main__":
    app = create_app()
    app.run(debug=True, threaded=True, host="127.0.0.1", port=5000)
```

However if you modify `close_fds` to be True (the default value), 

```diff
diff --git a/src/werkzeug/_reloader.py b/src/werkzeug/_reloader.py
index ab0966b8..3d8b34e5 100644
--- a/src/werkzeug/_reloader.py
+++ b/src/werkzeug/_reloader.py
@@ -245,7 +245,7 @@ class ReloaderLoop:
             args = _get_args_for_reloading()
             new_environ = os.environ.copy()
             new_environ["WERKZEUG_RUN_MAIN"] = "true"
-            exit_code = subprocess.call(args, env=new_environ, close_fds=False)
+            exit_code = subprocess.call(args, env=new_environ, close_fds=True)
 
             if exit_code != 3:
                 return exit_code
```

the development server and its reloader will work:

```
PS C:\Users\IEUser\Downloads> flask run
 * Environment: development
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 902-880-760
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
test
127.0.0.1 - - [02/Apr/2021 01:03:03] "[37mGET / HTTP/1.1[0m" 200 -
```

It's worth noting that the `close_fds` default on Windows was changed from False to True in Python 3.7. 

I don't really understand why this happens and the [commit that introduced it](https://github.com/pallets/werkzeug/commit/d9e7736de41e7cbf5de70a15e28449b4dd4adab0) is quite old so I'm not completely sure if this is the correct fix but I don't see what could be wrong with the module code because it works perfectly outside of the Windows/Flask development server. 

Happy to make a PR to make the close_fds value flip to True on Windows but be False otherwise if it's the right fix. 

Here are working wheels for Windows for the pybluemonday library if you want to run the above script. 
[win.zip](https://github.com/pallets/werkzeug/files/6248464/win.zip)

Environment:

- Python version: 3.7.9
- Werkzeug version: 1.0.1

**Comment by ColdHeat** [comment]
It seems like adding any kind of stdout to subprocess.call lets it work (i.e. `stdout=subprocess.PIPE` or `capture_stdout=True`).

Also it seems this problem somewhat exists in other projects as well: https://github.com/ipython/ipython/blob/86d24741188b0cedd78ab080d498e775ed0e5272/IPython/utils/_process_common.py#L72

**Comment by davidism** [comment]
Why is this an issue with Werkzeug and not with go ffi, Python subprocess, or pybluemonday? All we're doing is reusing the socket file descriptor, which is a valid use case for the code we're using. Beyond that, I know nothing about any of the systems involved to attempt to debug or fix it.

**Comment by ColdHeat** [comment]
`flask run` works because it ran in production mode which disabled the reloader.

The issue could definitely be somewhere else but in my very initial testing no other server that I could run crashed. It was only flask and only on this specific situation so I figured it's a good place to start before I dig heavily into the other harder to debug areas. I also couldn't get similar kinds of crashes if I removed Flask/Werkzeug. 

But now that you mention it and I better understand the issue I tried to test out other servers with reload capabilities. Very few servers both support Windows and reload capabilities. 

Uvicorn worked (with minor changes to the above script to get the app factory out):
```
uvicorn.exe "app:app" --interface wsgi --reload --port 5555

[32mINFO[0m:     Uvicorn running on [1mhttp://127.0.0.1:5555[0m (Press CTRL+C to quit)
[32mINFO[0m:     Started reloader process [[36m[1m8544[0m] using [36m[1mstatreload[0m
[32mINFO[0m:     Started server process [[36m988[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     ASGI 'lifespan' protocol appears unsupported.
[32mINFO[0m:     Application startup complete.
test3
[32mINFO[0m:     127.0.0.1:51811 - "[1mGET / HTTP/1.1[0m" [32m200 OK[0m
[33mWARNING[0m:  StatReload detected file change in 'app.py'. Reloading...
[32mINFO[0m:     Started server process [[36m6448[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     ASGI 'lifespan' protocol appears unsupported.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Finished server process [[36m6448[0m]
[32mINFO[0m:     Stopping reloader process [[36m[1m8544[0m]

```

[reloadex](https://pypi.org/project/reloadex/) also worked:

```
PS C:\Users\IEUser\Downloads> ^C
PS C:\Users\IEUser\Downloads> reloadex.exe .\app.py
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
```

I completely understand that this library is probably not heavily used and does some very specific Windows calls. It was just difficult to find a server other than Werkzeug that supported the right behavior. 

I also understand how difficult Windows as a development target is I'm more curious about what's wrong than really pushing for a fix. 

I don't fully understand what the fd passing is doing in Windows but if I can narrow down the issue deeper I can report it wherever it makes more sense.

**Comment by ColdHeat** [comment]
With `go version go1.15.11 windows/amd64` and the following testing code, the Go code seems to work in a similar test condition.

```
import subprocess
import os
import threading

def bluemonday():
	new_environ = os.environ.copy()
	new_environ["WERKZEUG_RUN_MAIN"] = "true"

	subprocess.call(["./bluemonday.exe"], env=new_environ, close_fds=False)

t = threading.Thread(target=bluemonday, args=())
t.setDaemon(True)
t.start()
t.join()
```

bluemonday exe and testing script provided here:
[Archive.zip](https://github.com/pallets/werkzeug/files/6250590/Archive.zip)

**Comment by ColdHeat** [comment]
If it's useful, the following is the code where uvicorn does its reloading:
https://github.com/encode/uvicorn/blob/bf1c64e2c141971c546671c7dc91b8ccf0afeb7d/uvicorn/supervisors/basereload.py#L33-L66
https://github.com/encode/uvicorn/blob/bf1c64e2c141971c546671c7dc91b8ccf0afeb7d/uvicorn/subprocess.py#L9-L38

**Comment by davidism** [comment]
Closing, I don't know how I can address this and there hasn't been further updates.

**Comment by ColdHeat** [comment]
You can emulate uvicorn's approach for reloading using multiprocessing instead of subprocess.call. 

Replacing [this function](https://github.com/pallets/werkzeug/blob/af160e0b6b7ddd81c22f1652c728ff5ac72d5c74/src/werkzeug/_reloader.py#L239-L251) with something similar to [this](https://github.com/encode/uvicorn/blob/bf1c64e2c141971c546671c7dc91b8ccf0afeb7d/uvicorn/supervisors/basereload.py#L33-L66) and [this](https://github.com/encode/uvicorn/blob/bf1c64e2c141971c546671c7dc91b8ccf0afeb7d/uvicorn/subprocess.py#L9-L38). 

I recognize that it's probably not worth the effort but I actually think it would improve the speed of the reloader. uvicorn's reloader is much faster in my experience.
