### ISSUE TITLE
It would be handy to include a hashids function for converting numbers into strings

### ISSUE THREAD

**Issue by nickjj** [pallets/werkzeug#2077]
Currently there's the https://github.com/davidaurelio/hashids-python library which lets you pass in a number and get back a string. It's a few hundred lines of code and has no dependencies.

It would be kind of nice to have this baked into werkzeug especially since we have functions like `secure_filename`. Generating a hashid is a pretty reasonable way to create a non-reversible string out of a number.

This comes in quite handy for dealing with file uploads. For example, it wouldn't be a good idea in most cases to use `current_user.id` as an avatar filename because it leaks the user's ID. But if you run hashid on it, it would transform something like `123` into  `Mj3`, and as long as you use the same salt you'll get the same output with the same input.

Now you could say just use the hashids library which is fair enough, but werkzeug has a number of other things like a user agent parser which also has dedicated libraries. Likewise there's the generate hash functions too. Seems like you're not too opposed to adding arbitrary functions that are useful in most apps.

**Comment by davidism** [comment]
Thanks for the suggestion, it's an interesting library. However, I do not plan to add this. As you say, users can install and use it if needed, us reimplementing it in Werkzeug doesn't simplify things but adds more maintenance work that's unrelated to WSGI.

We want to get rid of our custom user agent parser, it causes endless issues and is better served by a dedicated library. `secure_filename` is needed for sanitizing user input, which is a direct security concern of web applications. Similar for password hashes, although if I was designing things today I'd point users to passlib instead.
