### ISSUE TITLE
Chunked response support for werkzeug.serving

### ISSUE THREAD

**Issue by rawler** [pallets/werkzeug#2090]
This is a new attempt to solve #1327, with a slightly different approach, and for a specific reason; explicit failures.

Right now, if a generator-driven response fails mid-stream, the error-handler may or may not add some error-description to the end of stream, before closing connection. A client will typically not distinguish this from a successful completed request. Unless the response is carefully inspected, the crash will go on undetected. In the worst case, for opaque response content, or when running with `passthrough_errors`, the response may be truncated in a way that cannot be detected by the client.

For HTTP-clients, such as Python stdlib, using `Transfer-Encoding: chunked` activates automatic detection of truncated response (`http.client.IncompleteRead` is thrown). Given that any HTTP/1.1-supporting client is mandated to support chunking, this should be a justifiable change in behavior.

**Comment by davidism** [comment]
https://github.com/pallets/werkzeug/pull/1328#issuecomment-446373040
