### ISSUE TITLE
Improve documentation for "Shutting Down The Server"

### ISSUE THREAD

**Issue by mike239x** [pallets/werkzeug#2092]
After spending a while trying to find how to stop a running server, I only found out that there is [this hacky way](https://werkzeug.palletsprojects.com/en/1.0.x/serving/#shutting-down-the-server) to do it, which sure does not look like a good solution - but then I found [this comment](https://github.com/pallets/werkzeug/issues/1752#issuecomment-655600254) on the issue regarding the same topic, which says
> we also provide the much less well known make_server function

and also contains a nice example on how to use it to create, start, and then stop a server.

I would like to have that in the documentation part on "Shutting Down The Server", because IMHO that is what people want when they search for stopping the server, but instead they only see that hacky solution. I want this page to see some improvement.

**Comment by davidism** [comment]
closed by #2146
