### ISSUE TITLE
2.0.0rc5 cannot iterate over CombinedMultiDict keys

### ISSUE THREAD

**Issue by andreymal** [pallets/werkzeug#2105]
Today I upgraded my Flask project to 2.0 for testing purposes, and Flask-WTF broke in some situations. After a little debugging I found out that it caused by CombinedMultiDict. Since this behavior change is not mentioned in the 2.0.0 changelog, I assume this is a bug.

If I understand git log correctly, it's caused by this change: https://github.com/pallets/werkzeug/commit/3ed73015106f61ca979ae30eb9d76edee7f2055d#diff-143c70ac9c8b70912211bd835f0c9dceb28ccaf02ea065da4a0e3d643bc7686dL1503

```python
from werkzeug.datastructures import CombinedMultiDict, MultiDict
c = CombinedMultiDict([MultiDict([('foo', 'bar')])])
for k in c: print(k)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: iter() returned non-iterator of type 'set'
```

**Comment by davidism** [comment]
You can `pip install git+https://github.com/pallets/werkzeug` to get this change until I make another release candidate.
