### ISSUE TITLE
Make @cached_property generic over the value

### ISSUE THREAD

**Issue by srittau** [pallets/werkzeug#2113]
Currently the following code will infer type `Any` for `Foo().bar`, although it should infer type `str`:

```python
from werkzeug.utils import cached_property

class Foo:
    @cached_property
    def bar(self) -> str:
        return ""

reveal_type(Foo().bar)
```

Making `class cached_property` generic over the value solves this problem and corrects the type of a few fields like `Request.base_url`. I have a PR ready for this that actually removes a few instances of `# type: ignore` in werkzeug code (although it adds two new ones.)

**Comment by srittau** [comment]
I opened #2117. It's my understanding that any performance issues with `Generic` should only affect the startup times, unless classes are created on the fly, since `cached_property` instances are only initiated on startup.

**Comment by davidism** [comment]
You're right, I wasn't thinking about when `cached_property` was created, so it should be safe in this case.
