### ISSUE TITLE
Stronger typing for `request.headers.get` method

### ISSUE THREAD

**Issue by pcorpet** [pallets/werkzeug#2128]
Since v2 and the typing stubs, the `get` method of the `Headers` data structure always returns a `Optional[str]`. However in some cases we can know statically that it will return a `str`. Indeed when a default string parameter is given, then the function always return a `str`.

Here's a preview of my code before v2:

```py
auth_token = flask.request.headers.get('Authorization', '').replace('Bearer ', '')
```
Now that `werkzeug` is typed, the `.replace` will raise an typing error when analyzed with `mypy`.

```
error: Item "None" of "Optional[str]" has no attribute "replace"
```

I can fix it like this:
```py
auth_token = typing.cast(str, flask.request.headers.get('Authorization', '')).replace('Bearer ', '')
```
or even like this
```py
auth_header = flask.request.headers.get('Authorization', '')
if auth_header:
  auth_token = auth_header.replace('Bearer ', '')
else:
  auth_token = ''
```

But I feel like all of those patches shouldn't be required. I'll send a type fix.

**Comment by ThiefMaster** [comment]
I guess we need an `@overload` definition for `get` and similar methods... like here: https://github.com/python/typeshed/blob/a7302dc6cb9527ba8cb014327e29c035d991550f/stdlib/typing.pyi#L443-L446
