### ISSUE TITLE
Werkzeug, Flask app Working outside of request context error

### ISSUE THREAD

**Issue by mouadennasri** [pallets/werkzeug#2132]
Environment:

- Python version: 3.7
- Werkzeug version: 2.0.0

```
cli_1  |   File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 544, in _get_current_object
cli_1  |     return self.__local()  # type: ignore
cli_1  |   File "/usr/local/lib/python3.7/site-packages/flask/globals.py", line 37, in _lookup_req_object
cli_1  |     raise RuntimeError(_request_ctx_err_msg)
cli_1  | RuntimeError: Working outside of request context.
```
I was using the `Werkzeug==1.0.1` in my Flask app, today it was upgraded to version 2.0.0 and the pod went down, the app couldn't start, the reason was the issue above, 
I quickly did a downgrade to `Werkzeug==1.0.1` all good but using the newer version cause this problem

**Comment by pgjones** [comment]
There is insufficient information here for us to figure this out. Could you provide a code snippet that reproduces the problem?
