### ISSUE TITLE
Testing framework Client.get() / Client.head() non-standard behavior

### ISSUE THREAD

**Issue by franklx** [pallets/werkzeug#214]
This [Bug report](https://github.com/jfinkels/flask-restless/issues/98) involves the Werkzeug testing framework.

I think that the get()/head() methods should serialize data payload and append it to the request url.
A kwarg can be added for preserving the non-standard behavior (it should be useful in some cases).

If you agree with my thinking I will work on a patch for both code and documentation.

Thank you in advance.

**Comment by untitaker** [comment]
@franklx Sorry for letting this pass unreviewed. Generally Werkzeug tries to follow the relevant RFCs, but in this case, I'd argue that sending a payload with the GET request is **an instruction by the user to violate these RFCs**. Therefore I'd suggest that Werkzeug should spit out a warning if the user tries to pass data with a GET request.

**Comment by davidism** [comment]
This is a very old issue, so not sure when this was addressed, but `EnvironBuilder` and `Client` do nothing to the data based on the method.

```python
from werkzeug.test import Client
from werkzeug.wrappers import Request, Response


@Request.application
def app(request):
    return Response(request.get_data())


client = Client(app, Response)
response = client.get("/", data={"foo": "bar"})
print(response.get_data())
```

**Comment by untitaker** [comment]
Yeah just mentioning it because it was the suggestion in the OP

**Comment by davidism** [comment]
I took a look at [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3) and only the TRACE method is defined as "MUST NOT send a message body". GET and HEAD both say "A payload within a GET request message has no defined semantics".

Requests sends on the body without warning, Firefox `fetch` throws an error.

**Comment by untitaker** [comment]
It's practically useless and I would assume that people only do it errorneously when trying to send a querystring. I guess [my former comment](https://github.com/pallets/werkzeug/issues/214#issuecomment-71381615) was wrong though.

I think we can close this issue since this is just bikeshedding then
