### ISSUE TITLE
Document that werkzeug.server.shutdown is deprecated

### ISSUE THREAD

**Issue by davewsmith** [pallets/werkzeug#2146]
https://github.com/pallets/werkzeug/pull/1873 adds a runtime notice that the current server shutdown method is deprecated, but does not also add a deprecation note in the 'Shutting Down The Server' section of `docs/serving.rst`.

Noting what the approved method going forward is would be nice, but it's not clear from https://github.com/pallets/werkzeug/issues/1752 that there's agreement.

This is an odd issue, since it comes up by way of Flask. I have several local tools that spin up web interfaces to monitor some temporary process, and have found a `/quit` route to be quite convenient. Happy to submit an Issue in the flask project, if that's appropriate here.

**Comment by davidism** [comment]
See #1752 for deprecation.
