### ISSUE TITLE
downloading from send_file unpacks gzipped files

### ISSUE THREAD

**Issue by filak** [pallets/werkzeug#2149]
The gzipped files returned with
````
return send_file( fpath, as_attachment=True ) 
````
are being downloaded unpacked. The file are saved as \*.gz but its content is plaintext.

This does not happen with 
Flask==1.1.2
werkzeug==1.0.1

Environment:
- Python version: 3.7.1
- Flask version: 2.0.1

**Comment by AbdealiJK** [comment]
I have the same issue.
I found that doing:
```bash
curl -X GET http://myurl.com/files/1 --output /tmp/test.tar.gz
```
works fine, and the filesize is ~10kb
But when I do:
```python
import requests
resp = requests.request('GET', url='http://myurl.com/files/1')
with open('/tmp/test.tar.gz', 'wb') as f:
    f.write(resp.content)
```
The file size is ~100kb

I am using the following very simple call in my flask API:
```python
import io
from flask import send_file

send_file(
    io.BytesIO(open('/src/test.tar.gz', 'rb').read()),
    download_name='test.tar.gz',
    as_attachment=True,
)
```

**Comment by filak** [comment]
Yes, @AbdealiJK - downloading with curl is OK - ie. 

        curl -O "http://127.0.0.1:5000/download/whatever.gz"

**Comment by davidism** [comment]
Hey all, not sure if you saw my comment above, but anyone is welcome to submit a PR to fix this.

> So maybe send_file should only set Content-Encoding if as_attachment is False?

**Comment by filak** [comment]
I can confirm that the suggested change works as expected:

          #if encoding is not None:
          if encoding is not None and not as_attachment:
              headers.set("Content-Encoding", encoding)

**Comment by shivamv300** [comment]
@davidism I have create a PR with the suggested changes:
https://github.com/pallets/werkzeug/pull/2161
Could you please review it?
