### ISSUE TITLE
test.Client.resolve_redirect keeps previous RAW_URI and REQUEST_URI

### ISSUE THREAD

**Issue by mrcljx** [pallets/werkzeug#2151]
When `follow_redirects=True` is used, the second request will have an updated path, but the `environ` will not clear the synthesized `REQUEST_URI` and `RAW_URI` values from the previous request.

Example (using Flask):

    app = flask.Flask("test")

    @app.route("/e1")
    def endpoint():
        return flask.redirect("/e2")

    @app.route("/e2")
    def endpoint_destination():
        rv = {k: flask.request.environ[k] for k in ["PATH_INFO", "REQUEST_URI", "RAW_URI"]}
        return flask.jsonify(rv)

    client = app.test_client()
    rv = client.get("/e1", follow_redirects=True)
    assert rv.json == {
        "PATH_INFO": "/e2",
        "REQUEST_URI": "/e2",
        "RAW_URI": "/e2",
    }

Expectation:

    Expected :{'PATH_INFO': '/e2', 'RAW_URI': '/e2', 'REQUEST_URI': '/e2'}
    Actual   :{'PATH_INFO': '/e2', 'RAW_URI': '/e1', 'REQUEST_URI': '/e1'}

Environment:

- Python version: 3.6
- Werkzeug version: 2.0.1

---

I did only start to see this with 2.x. I think the fix might be as easy as doing the following in `resolve_redirect`:

```diff 
- builder = EnvironBuilder.from_environ(response.request.environ, query_string=qs)
+ builder = EnvironBuilder.from_environ(response.request.environ, path=path, query_string=qs)
```

**Comment by davidism** [comment]
So the actual issue is that `EnvironBuilder` stores both the original `request_uri`, as well as the `path` after some processing, but the redirect code only rewrites the path. That said, your proposed solution still looks good.
