### ISSUE TITLE
FileStorage perhaps has incorrect typing metadata

### ISSUE THREAD

**Issue by hughsie** [pallets/werkzeug#2155]
Describe how to replicate the bug.

    from flask import request
    # snip some app-specific logic...
    fileitem = request.files["file"]
    blob = fileitem.read()

and then:

    mypy test.py
    test.py:3: error: "FileStorage" has no attribute "read"

Environment:

- Python version: 3.9.5
- Flask version: 2.0.1

**Comment by 4sfaloth** [comment]
I'm also experiencing this. Just to be clear @davidism are you saying `werkzeug` has its metadata correctly set, and that this is a bug/limitation in `mypy` itself?

**Comment by davidism** [comment]
Looks like I didn't define the `__getattr__` method in the `datastructures.pyi` file, so the type system isn't picking it up (it doesn't look at the source if there's a pyi file). Happy to consider a PR that fixes the pyi file.
