### ISSUE TITLE
werkzeug double-encodes redirects when processing merge_slashes

### ISSUE THREAD

**Issue by tomprince** [pallets/werkzeug#2157]
```python
from werkzeug.routing import Rule, Map

routes = Map([
    Rule("/merge/<some>/path"),
])

def get_redirect_location(path):
    try:
        routes.bind("test.host").match(path)
    except Exception as e:
        return e.get_response({}).headers['location']
    else:
        raise ValueError("no redirect")

def test_merge_slashes():
    assert get_redirect_location("/merge/%//path") == 'http://test.host/merge/%25/path'
```

It looks like `Rule.match` uses `Rule.build` to generate the new path [here](https://github.com/pallets/werkzeug/blob/2.0.1/src/werkzeug/routing.py#L943), which is already urlencoded. But then `MapAdapter.match` encodes the resulting path again [here](https://github.com/pallets/werkzeug/blob/2.0.1/src/werkzeug/routing.py#L1963-L1969).

Environment:

- Python version: 3.9.5
- Werkzeug version: 2.0.1

**Comment by cAtaman** [comment]
I just opened #2193 which should fix this
