### ISSUE TITLE
cannot import name 'ContextVar' from 'werkzeug.local'

### ISSUE THREAD

**Issue by AnkS4** [pallets/werkzeug#2163]
`from flask import Flask, jsonify, request
`

```
$ python app.py 
Traceback (most recent call last):
  File "/vagrant/APIs/alpha/app.py", line 1, in <module>
    from flask import Flask, jsonify, request
  File "/usr/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 19, in <module>
    from werkzeug.local import ContextVar
ImportError: cannot import name 'ContextVar' from 'werkzeug.local' (/home/vagrant/.local/lib/python3.9/site-packages/werkzeug/local.py)
```

Environment:

- Python version: Python 3.9.5
- Werkzeug version: werkzeug 2.0.1-1

**Comment by davidism** [comment]
I can't reproduce this issue with the information given.

**Comment by myanalysis** [comment]
i am getting the same erro.  just appeared. i don't think i changed anything?

  File "/Users/benson/PycharmProjects/myprelim/v_env/lib/python3.9/site-packages/dash/dash.py", line 20, in <module>
    import flask
  File "/Users/benson/PycharmProjects/myprelim/v_env/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
    from .app import Flask as Flask
  File "/Users/benson/PycharmProjects/myprelim/v_env/lib/python3.9/site-packages/flask/app.py", line 19, in <module>
    from werkzeug.local import ContextVar
ImportError: cannot import name 'ContextVar' from 'werkzeug.local' (/Users/benson/PycharmProjects/myprelim/v_env/lib/python3.9/site-packages/werkzeug/local.py)

**Comment by davidism** [comment]
A note to anyone stumbling across this and deciding to thumbs down my comment: I still can't reproduce it, and we can't fix something we can't reproduce. If you have this issue, open a new issue with a minimal reproducible example (that goes beyond what is present in this issue, since it's not sufficient for me to reproduce as written).

Here is what I did based on the information provided:

```
$ python3.9 -m venv venv
$ . ./venv/bin/activate
(venv) $ pip install flask
(venv) $ python
>>> from flask import Flask
```

**Comment by myanalysis** [comment]
I have no idea why the error just appeared out of the blue but it looks like updatings to werkzeug 2.0.1 has solved te issue for me. good luck.

**Comment by Maruf-S** [comment]
> 
> 
> i am getting the same erro. just appeared. i don't think i changed anything?
> 
> ```
>   File "/Users/benson/PycharmProjects/myprelim/v_env/lib/python3.9/site-packages/dash/dash.py", line 20, in <module>
>     import flask
>   File "/Users/benson/PycharmProjects/myprelim/v_env/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
>     from .app import Flask as Flask
>   File "/Users/benson/PycharmProjects/myprelim/v_env/lib/python3.9/site-packages/flask/app.py", line 19, in <module>
>     from werkzeug.local import ContextVar
> ImportError: cannot import name 'ContextVar' from 'werkzeug.local' (/Users/benson/PycharmProjects/myprelim/v_env/lib/python3.9/site-packages/werkzeug/local.py)
> ```

installing flask 1.0.0 fixed the issue for me

**Comment by hhp-the-maestro** [comment]
> > i am getting the same erro. just appeared. i don't think i changed anything?
> > ```
> >   File "/Users/benson/PycharmProjects/myprelim/v_env/lib/python3.9/site-packages/dash/dash.py", line 20, in <module>
> >     import flask
> >   File "/Users/benson/PycharmProjects/myprelim/v_env/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
> >     from .app import Flask as Flask
> >   File "/Users/benson/PycharmProjects/myprelim/v_env/lib/python3.9/site-packages/flask/app.py", line 19, in <module>
> >     from werkzeug.local import ContextVar
> > ImportError: cannot import name 'ContextVar' from 'werkzeug.local' (/Users/benson/PycharmProjects/myprelim/v_env/lib/python3.9/site-packages/werkzeug/local.py)
> > ```
> 
> installing flask 1.0.0 fixed the issue for me



> `from flask import Flask, jsonify, request `
> 
> ```
> $ python app.py 
> Traceback (most recent call last):
>   File "/vagrant/APIs/alpha/app.py", line 1, in <module>
>     from flask import Flask, jsonify, request
>   File "/usr/lib/python3.9/site-packages/flask/__init__.py", line 7, in <module>
>     from .app import Flask as Flask
>   File "/usr/lib/python3.9/site-packages/flask/app.py", line 19, in <module>
>     from werkzeug.local import ContextVar
> ImportError: cannot import name 'ContextVar' from 'werkzeug.local' (/home/vagrant/.local/lib/python3.9/site-packages/werkzeug/local.py)
> ```
> 
> Environment:
> 
>     * Python version: Python 3.9.5
> pip install werkzeug==2.0 , that would solve the issue

**Comment by hhp-the-maestro** [comment]
> A note to anyone stumbling across this and deciding to thumbs down my comment: I still can't reproduce it, and we can't fix something we can't reproduce. If you have this issue, open a new issue with a minimal reproducible example (that goes beyond what is present in this issue, since it's not sufficient for me to reproduce as written).
> 
> Here is what I did based on the information provided:
> 
> ```
> $ python3.9 -m venv venv
> $ . ./venv/bin/activate
> (venv) $ pip install flask
> (venv) $ python
> >>> from flask import Flask, jsonify, request
> ```
> 
> I did not get the provided error.

**its a kind of incomplete update of werkzeug module from 2.0 to 2.0.1,if you install the latest version of werkzeug, then you will encounter the problem**

**Comment by davidism** [comment]
I tried with the latest version, works fine, so that's not correct.

**Comment by hhp-the-maestro** [comment]
no there are 

> I tried installing 2.0.0 then 2.0.1, works fine, so that's not correct.

no there are a lot of things missing in 2.0.1, i just went through between those two in detail to check what would be the problem, where i found some of the missing things like attribute not found for (send from directory) and cannot import  name ContextVar from (locals.py). so i went through werkzeug repo src on pallets github,  where i found everything which was missing. so i just tried to downgrade to 2.0,  and ran flask and got the green light, I don't know whether my solution is correct, but it did fix my issue, as the issue explained by others suits well to the problem of mine , so i concluded that the solution could be the same of just "pip install werkzeug==2.0', thats it, Other than this i don't wanna argue about correct or not , coz you know that better than me. its a kind of help to the open src community .
