### ISSUE TITLE
"ImportError: cannot import name'secure_filename' from'werkzeug'" when importing the flask_uploads package

### ISSUE THREAD

**Issue by scopelin** [pallets/werkzeug#2168]
Environment:

- Python version: 3.9
- Werkzeug version: 2.0.1

To fix add the following two lines to werkzeug\__init__.py

from .utils import secure_filename
from .datastructures import FileStorage

**Comment by ThiefMaster** [comment]
That's nothing to be fixed in werkzeug: https://github.com/pallets/werkzeug/pull/1640/files

But considering the (lack of) activity in flask-uploads (see https://pypi.org/project/Flask-Uploads/#history) you might be better off not using it at all.
