### ISSUE TITLE
Missing braces in f-string at tutorial.rst

### ISSUE THREAD

**Issue by mhihasan** [pallets/werkzeug#2178]
Environment:

- Python version: 3.9.5
- Werkzeug version: 2.0.1

**Comment by ThiefMaster** [comment]
Some details would be helpful... I'm sure you wouldn't like to go over every f-string in that file either to look for a needle in a haystack.

**Comment by ThiefMaster** [comment]
Just for the future, you do not need to open an issue for minor fixes like this. Just open a PR straight away.
