### ISSUE TITLE
```werkzeug.posixemulation``` can not be installed

### ISSUE THREAD

**Issue by mohammed-almaqdy** [pallets/werkzeug#2182]
after installing werkzeug successfully that was required in odoo14 I face an issue with installing posixemulation with the commend 
```pip3 install werkzeug.posixemulation``` the showed issue was 
```
ERROR: Could not find a version that satisfies the requirement werkzeug.posixemulation (from versions: none)
ERROR: No matching distribution found for werkzeug.posixemulation
```
I try that with the newest version of werkzeug but it shows the above issue and retry it with 0.16.0, 0.11.15 as shows in some solution in stack over view for cases like this but don,t solve the issue can any one help me here , thanks in advance 

- Python version: 3.8.10
- Ubuntu 20.04

**Comment by davidism** [comment]
That's not an installable package, it's old code that was removed.
