### ISSUE TITLE
to_dict method on CombinedMultiDict doesn't give combined result for overlapping keys

### ISSUE THREAD

**Issue by GuidoTournois** [pallets/werkzeug#2189]
Whenever I call `to_dict(flat=False)` on a `CombinedMultiDict`, obtained from combining two MultiDicts with overlapping keys, only the values of the last MultiDict are returned. 

```python
# altered from documentation to make keys overlapping.
from werkzeug.datastructures import CombinedMultiDict, MultiDict
post = MultiDict([('foo', 'bar'),('foo', 'bar2')])
get = MultiDict([('foo', 'bar3')])
combined = CombinedMultiDict([get, post])
combined.getlist('foo')
>> ['bar3', 'bar', 'bar2']
combined.to_dict(flat=False)
>> {'foo': ['bar3']}
```

From a class that intends to combine two MultiDicts, I expect the result from one of its methods to be a combined result.
Environment:
- Python version: 3.6.8
- Werkzeug version: 1.0.1

**Comment by cAtaman** [comment]
Hi @GuidoTournois

I'd suggest you go through the docstrings of the `to_dict` function [here](https://github.com/pallets/werkzeug/blob/1.0.x/src/werkzeug/datastructures.py#L1597-L1606). The functionality you want could be easily be gotten with `to_dict(flat=True)`

**Comment by GuidoTournois** [comment]
Hi Chima,

Thanks for your reply and thanks for picking up the issue so quickly.

Cheers,

Guido


Op zo 25 jul. 2021 om 16:07 schreef Chima Ataman ***@***.***>:
