### ISSUE TITLE
Reporting Security Issues

### ISSUE THREAD

**Issue by Creastery** [pallets/werkzeug#2190]
Hi Pallets Team,

I tried contacting security@palletsprojects.com and via direct message on Twitter over the past week, but unfortunately did not receive any response. 

Can a security team member from your team please check the inbox? Thanks :)

**Comment by davidism** [comment]
I did respond. Yes, we have your report and will work on it.

**Comment by Creastery** [comment]
That's weird... I didn't receive anything on my end somehow. 
Thanks for letting me know, and do feel free to let me know if you have any questions!
