### ISSUE TITLE
max_age in send_file should enforce integer

### ISSUE THREAD

**Issue by Yoshi325** [pallets/werkzeug#2230]
## Description

Currently any value passed into `send_file` for the `max_age` ends up as the value of `max-age` within the `Cache-Control` header. The type hints specify that either an integer or a callable that takes a string and returns an integer. However, since these are just hints (and not strong typing) they are not enforced. 

The specification for that value states that it must be an integer (not for example a float). So I think it is a bug that Werkzeug does not atleast attempt to enforce the value being an int with an attempt at conversion on: https://github.com/pallets/werkzeug/blob/3c5d3c9bd0d9ce64590f0af8997a38f3823b368d/src/werkzeug/utils.py#L784

## Replication:

Call `send_file` with the `max_age` argument value of: `1.0`, and observe that `1.0` is the value that comes out in the header.

## Expectation:

When a convertible value is passed, an integer is what ends up in the header.

## Environment:

- Python version: 3.8.2
- Werkzeug version: 0.16.1

**Comment by davidism** [comment]
Python in general does not do runtime type checking. I don't plan to change that for this case.

**Comment by Yoshi325** [comment]
I understand that Python itself does not do this. 

But in order to stay in-line with the specification for Cache-Control's max-age value, I think it would provide a better user experience to attempt to align it. Right now, this can create unexpected behavior downstream with no warning. 

If not enforcement, would you be open to me putting up a PR to atleast give a warning of some sort that the resulting value it out of spec?

**Comment by Yoshi325** [comment]
For what it is worth, Django does something similar to what I was suggesting: https://github.com/django/django/blob/68b8eda78864b78d1b8b2529ec119ec440f8458a/django/utils/cache.py#L76

**Comment by baronfel** [comment]
Another note (appeal to spec authority incoming): the spec for [max-age](https://httpwg.org/specs/rfc7234.html#cache-request-directive.max-age) says that the value _must_ be a [delta-seconds](https://httpwg.org/specs/rfc7234.html#delta-seconds), which has the following definition:

> The delta-seconds rule specifies a non-negative integer, representing time in seconds.

so without enforcing that, werkzeug is in danger of being out of spec based on user input.

**Comment by davidism** [comment]
Werkzeug isn't in danger of being out of spec. A program that decides to pass an invalid value is out of spec, but in general we/Python don't validate/coerce every value that's passed through to http. I don't plan to change this at this time.

**Comment by baronfel** [comment]
Would it be more appropriate for flask, as a framework built on top of werkzeug, to do this validation for the user?
