### ISSUE TITLE
New reloader mode

### ISSUE THREAD

**Issue by ZAurele** [pallets/werkzeug#2233]
The reloader is awesome however depending on the IDE configuration you could end up having a project that reload automatically because the IDE will changes the files mtime.

I suggest adding a reloader type, that use the file size instead of the mtime, I've tried and it works like a charm.

```py
class SizeReloaderLoop(ReloaderLoop):
    name = "size"

    def __enter__(self) -> ReloaderLoop:
        self.sizes: t.Dict[str, float] = {}
        return super().__enter__()
        
   def run_step(self) -> None:
        for name in chain(_find_stat_paths(self.extra_files, self.exclude_patterns)):
            try:
                size = os.stat(name).st_size
            except OSError:
                continue

            old_size = self.sizes.get(name)

            if old_size is None:
                self.sizes[name] = size
                continue

            if size > old_size:
                self.trigger_reload(name)
```

**Comment by davidism** [comment]
I don't plan to maintain more reloaders at this point, it's hard enough with the current behaviors. You can add this to the reloader loops in your project if you'd like to use it:

```
from werkzeug._reloader import reloader_loops

reloader_loops["size"] = SizeReloaderLoop
```

Then you can do `run_simple(..., reloader_type="size")`.

Note that this is all internal, so it's the user's responsibility to pin versions and adapt to changes.

**Comment by ThiefMaster** [comment]
If you IDE touches files that haven't been modified, I'd report that as a bug in the IDE.

**Comment by ThiefMaster** [comment]
BTW, your size reloader has a bug - it should be `!=` and not `>` since removing something from a file is certainly a reason to trigger a reload.

**Comment by ZAurele** [comment]
> BTW, your size reloader has a bug - it should be `!=` and not `>` since removing something from a file is certainly a reason to trigger a reload.

Indeed, many thanks to both of you, perfect and quick answers !
