### ISSUE TITLE
Missing import for MultiDict

### ISSUE THREAD

**Issue by marty331** [pallets/werkzeug#2259]
ImportError for MultiDict 

Import werkzeug v-2.1.0.dev0 and try to utilize the MultiDict class

MultiDict should import without error.

Environment:

- Python version: 3.10
- Werkzeug version: 2.1.0.dev0

**Comment by davidism** [comment]
I can't reproduce this issue. Importing MultiDict works.

**Comment by marty331** [comment]
@davidism 
Please check version 2.1.0.dev0
