### ISSUE TITLE
Erro router when use nginx

### ISSUE THREAD

**Issue by jeisonmp** [pallets/werkzeug#2264]
I am use a nginx router to do proxy reverse to /dash interface, but when I access an error arrive. I don't know why I when I test in without nginx all happen ok.

![image](https://user-images.githubusercontent.com/9480995/137824703-6e671e7e-3731-45fa-9807-466316411a34.png)

Environment:

- Python version: v3
- Werkzeug version: I am using dash 2.0.0 version.

and...

![image](https://user-images.githubusercontent.com/9480995/137825907-343401b4-e298-4125-9412-6a98363bf405.png)

My code start with...

`
app = dash.Dash(__name__, suppress_callback_exceptions=True, routes_pathname_prefix="/dash/")

server = app.server
`

**Comment by davidism** [comment]
Sorry, we can't help with this type of question on the issue tracker. You also haven't provided any details about your configuration or code. We also can't help with Dash, as it is is a separate project. If you have a specific issue (not question) with Werkzeug, please narrow it down to a minimal reproducible example.
