### ISSUE TITLE
send_from_directory can't  continue send large file

### ISSUE THREAD

**Issue by R8KwEwN2hvrhY** [pallets/werkzeug#2266]
I have a file over 40G, if break off on download,idm can't continue download from server,but if rate of progress is low it will continue,about 50% the download would't work.

hope send_from_directory work with large file

Environment:

- Python version:Python 3.9.6
- Flask version: 2.0.1

**Comment by friendtasy** [comment]
i try to  use chrome download to test,i found that the download will resumed few minutes，maybe the idm feel time out~~~~~~
