### ISSUE TITLE
Enhance Application Dispatcher to accept regex mount keys in place of prefixes

### ISSUE THREAD

**Issue by zevdg** [pallets/werkzeug#2288]
# Feature Request
[werkzeug.middleware.dispatcher.DispatcherMiddleware](https://werkzeug.palletsprojects.com/en/2.0.x/middleware/dispatcher/?highlight=dispatcher%20middleware) is a great way to route requests between different WSGI applications.  This is particularly useful when handling routing in an application that uses different frameworks for different routes. Unfortunately, prefix-only routing makes it difficult to fully recreate the routing rules of many applications in a framework-agnostic way. If regexes were supported, it would be possible to migrate routings from pretty much any framework to DispatcherMiddleware losslessly.  This would be particularly useful in automating incremental migrations from any python web framework to another.

## My particular use case
I'm specifically interested in migrating routing configurations from App Engine's app.yaml handlers (a different framework agnostic router) to DispatcherMiddleware (both framework and platform agnostic) en-mass.  A hypethetical lossless app.yaml -> DispatcherMiddleware translator would help applications migrate from App Engine to cloud run (or any other platform that doesn't support app.yaml).  Importantly, this tool would be useful for any application, no matter which framework (or frameworks) are in use.

## Example
convert
```
handlers:
- url: /.*/foo
  script: django.app
- url: /.*/bar
  script: flask.app
```
to an equivalent DispatcherMiddleware mount config, like

```
app = DispatcherMiddleware(serve_frontend, {
    re.compile('/.*/foo'): django.app,
    re.compile('/.*/bar'): flask.app,
})
```

Would Werkzeug be interested in a contribution to add this feature?

Why now?
With the [recent release](https://cloud.google.com/blog/products/serverless/support-for-app-engine-services-in-second-generation-runtimes) of the [App Engine APIs in python3](https://cloud.google.com/appengine/docs/standard/python3/services/access), we expect to see many apps migrating from python27 to python3 which no longer supports WSGI app routing in app.yaml.

**Comment by davidism** [comment]
I would not want to expose regexes directly, but perhaps Werkzeug's router could be used. Happy to review a PR if you want to investigate this further.

**Comment by zevdg** [comment]
If you just want to keep regexes out the API, the key could be a matcher function instead, like

```
djangoRoutes = re.compile('/.*/foo')
flaskRoutes = re.compile('/.*/foo')

app = DispatcherMiddleware(serve_frontend, {
    lambda path: djangoRoutes.fullmatch(path): 'django.app',
    lambda path: flaskRoutes.fullmatch(path): 'flask.app',
})
```

I'm not quite sure if that's what you meant by "not exposing regexes directly"

**Comment by davidism** [comment]
I meant I don't want people writing regexes, since that's not how they interact with routing in Werkzeug/Flask. I want them to use the routing system if we're going to add more routing logic.

**Comment by zevdg** [comment]
Aaah, I get you now. Makes sense.  I'll dig into the Werkzeug routing primitives and look for a clean way to compose them with DispatcherMiddleware.

> Your regexes examples don't match a prefix, they match the whole path.

Yes, that's certainly one of the implicit requirements here.  To give a real example, people have existing routes like `/.*\.(js|css)` that are expected to match `/foo.js` but not `/foo.js.map`.

**Comment by davidism** [comment]
After thinking about this more, I don't think I want to add this amount of complexity to `DispatcherMiddleware`. It has a single purpose right now of dispatching to `/` separated subpaths. It's not clear how to extend that to using the full routing system, which deals with full paths not prefixes.

I think it would be better for GAE to provide a WSGI middleware that is specific to their routing scheme. Perhaps it can use Werkzeug utilities, perhaps it doesn't need to. I'm not sure if I'd add it to Werkzeug or not at that point, since typically we want users to rely on an HTTP server like Nginx or Apache to dispatch to different applications running independently.
