### ISSUE TITLE
Better qs-manipulation APIs on BaseURL

### ISSUE THREAD

**Issue by xmo-odoo** [pallets/werkzeug#2297]
The `werkzeug.urls` APIs are pretty awesome for both low and high-level uses, `URL` is especially nice for both parsing/manipulating URls and neatly creating them.

The one black mark here is that while extracting a querystring is really well supported (`URL.decode_query`), resetting one less so, and *updating* one is especially not-nice:

- resetting requires an explicit call to `url_encode` for serialization, which is OK but a bit verbose:
  ```python
  return url_parse(input).replace(query=url_encode(params))
  ```
- updating can not be performed as an expression as it requires extracting, processing, then re-setting the query:
  ```python
  url = url_parse(input)
  qs = url.decode_query()
  qs[key] = value
  return url.replace(query=url_encode(qs))
  ```

Every time this feels ugly and frustrating. Since `BaseURL` already has a bunch of convenience helpers for existing (simpler) use-cases, maybe it could have them for this as well? e.g. `set_query(d=None, /, **kw)` and `update_query(d=None, /, **kw)` which could take care of that internally?

The one thing which is a bit unclear, given querystrings have `MultiDict` semantics, is how to handle key conflicts (for updates, but also potentially for replacements if the method would accept both an optional base mapping and kwargs).

I think *replacement* semantics would make more sense as default, even though that is not the behaviour of `MultiDict.update` (and I don't think it has any method to do that as part of its interface?). Though for `set` at least it could also accept *either* a (multi)dict or kwargs but not both.

**Comment by davidism** [comment]
Werkzeug was originally written for Python 2, and used Python's `urlparse` module. When Python 3 support was added, it instead tried to backport Python 3's `urllib.parse` module to support both strings and bytes for 2/3 compat. Werkzeug's `urls` module is mostly not our own code, but a copy of the API from Python's builtin `urllib.parse` module, with whatever behavior it had at the time.

The history of this makes maintaining it more difficult, as it's hard to dive in and understand the correct behavior, or understand how/why it differs from Python's implementation. My long term goal is to remove as much of this module as possible and go back to using `urllib.parse` directly. Therefore, I don't plan to change how most of it works any further, including the `URL` and `BytesURL` classes.

**Comment by xmo-odoo** [comment]
> Werkzeug's urls module is mostly not our own code, but a copy of the API from Python's builtin urllib.parse module, with whatever behavior it had at the time.

That doesn't really jibe with the actual modules, `werkzeug.urls` has a much better (and more expansive) API than `urllib.parse`, very much including everything mentioned in this post. As far as I can see (and in my experience) `werkzeug.urls` is closer to "`urllib.parse` but good" than "outdated `urllib.parse`".

**Comment by davidism** [comment]
It has some other functions, which I won't get rid of, but the vast, vast majority of it was intended to be a compat layer when we were maintaining support for Python 2 and 3, not a separate API.

**Comment by davidism** [comment]
If the functions in `werkzeug.urls` were implemented as wrappers around `urllib.parse`, rather than complete reimplementations, I'd be more open to adding extra behavior. As a maintainer and user, I want to understand what extra behaviors are happening, versus unintended different behavior from divergent implementations.

I'm not opposed to, for example, having a `url_parse` function that does `urllib.parse.urlparse` then returns our own enhanced `ParseResult` with extra behavior. But I first want to get to the point that the functions are actually wrappers around `urllib.parse`.
