### ISSUE TITLE
Debugger fails to log tracebacks reliably

### ISSUE THREAD

**Issue by joostpjotr** [pallets/werkzeug#2299]
I'm using the Flask development server (Werkzeug 2.0.1, Python 3.7.12) in a Kubernetes-based container using Skaffold. When an unhandled exception occurs the browser displays the HTML traceback, but the traceback does not (immediately) appear in the log output. This is inconvenient when working on APIs, because then the HTML traceback is often not easily accessible.

I suspect that when running the Flask development server directly from a terminal the output is unbuffered (or line-buffered). But that when running in a Kubernetes-based container the output is buffered. The traceback seems then to get stuck in that buffer till the next request is logged.

The traceback is [written to the error output](https://github.com/pallets/werkzeug/blob/f663609dd665e835982872d9088d0f3ab64ced75/src/werkzeug/debug/__init__.py#L351) using:

```python
            traceback.log(environ["wsgi.errors"])
```

It would seem that an `environ["wsgi.errors"].flush()` directly after could fix this issue. Or maybe a call to `flush()` after finishing the request at a higher level.

As a workaround, setting the `PYTHONUNBUFFERED` environment variable when running the server does make the tracebacks appear right away.

**Comment by davidism** [comment]
I don't think it's Werkzeug's (or any library's) job to flush the output stream every time something is written. If you have stdout set up to not output as expected, then it sounds like you should also have Python set up to understand that, which is what `PYTHONUNBUFFERED` is for.
