### ISSUE TITLE
Difference in watched .zip files between stat and watchdog reloaders

### ISSUE THREAD

**Issue by HairyFotr** [pallets/werkzeug#2300]
I've noticed that after enabling the watchdog reloader, my Flask application reloaded after each zip file upload. This did not happen with the stat reloader.

After some looking, I've narrowed the issue down to these lines:
https://github.com/pallets/werkzeug/blob/3b79230cfd99c8e64d14d4abd655bc1d39398a87/src/werkzeug/_reloader.py#L68-L69
https://github.com/pallets/werkzeug/blob/3b79230cfd99c8e64d14d4abd655bc1d39398a87/src/werkzeug/_reloader.py#L85
https://github.com/pallets/werkzeug/blob/3b79230cfd99c8e64d14d4abd655bc1d39398a87/src/werkzeug/_reloader.py#L312

`StatReloaderLoop` calls `_find_stat_paths`, which includes `.py` and `.pyc` by default, while WatchdogReloaderLoop also includes all `.zip` files. However, `_find_stat_paths` does mention zip files on the path in a comment, which are likely the exact list of zip files that need to be watched.

I solved my specific Flask app issue by excluding the upload folder from the reloader, but maybe this difference between the reloaders is worth addressing.

Environment:

- Python version: 3.9.5
- Werkzeug version: 2.0.2

**Comment by davidism** [comment]
Uploaded files should not go in the static folder. For flask, they should go in the instance folder, which is not part of the watched files. This is not related to zip files, there's nothing specific Werkzeug should change.
