### ISSUE TITLE
Add ProxyFix cloudflare support.

### ISSUE THREAD

**Issue by GotPythonized** [pallets/werkzeug#2315]
Sorry, French speaking here (I used Deepl to translate).

When we use: "X-Forwarded-For" with Cloudflare proxies, it is the addresses of this one that appear as REMOTE_ADDR. 
EX:
'HTTP_CDN_LOOP': 'cloudflare',
HTTP_CF_CONNECTING_IP': '51.161.81.xx', 
'HTTP_X_FORWARDED_FOR': '172.70.110.67', < Cloudflare IP
'HTTP_X_REAL_IP': '172.70.110.67', < Cloudflare IP
'REMOTE_ADDR': '172.70.110.67', < Cloudflare IP

While if we use: "CF-Connecting-IP", it is the correct IP addresses that appear.

'HTTP_CDN_LOOP': 'cloudflare',
'HTTP_CF_CONNECTING_IP': '51.161.81.xx', 
'HTTP_X_FORWARDED_FOR': '172.70.178.173', < Cloudflare IP
'HTTP_X_REAL_IP': '172.70.178.173', < Cloudflare IP
'REMOTE_ADDR': '51.161.81.xx',< Good

Translated with www.DeepL.com/Translator (free version)

I fixed it like that:

```
class ProxyFix:
    def __init__(..., x_cdn_loop:int = 1)
        ...
        self.x_cdn_loop = x_cdn_loop
    def __call__(...):
        ...
        if environ_get("HTTP_CDN_LOOP") == "cloudflare" and (self.x_cdn_loop == 1):
            remote_addr = self._get_real_value(self.x_for, environ_get("HTTP_CF_CONNECTING_IP"))
        else:
            remote_addr = self._get_real_value(self.x_for, environ_get("HTTP_X_FORWARDED_FOR"))

        if remote_addr:
            environ["REMOTE_ADDR"] = remote_addr

        # x_for = self._get_real_value(self.x_for, environ_get("HTTP_X_FORWARDED_FOR"))
        # if x_for:
        #    environ["REMOTE_ADDR"] = x_for
```

**Comment by ThiefMaster** [comment]
Why is cloudflare not providing standard headers?

**Comment by davidism** [comment]
I don't plan to add any service-specific support to Werkzeug. This would be appropriate as an extension package to provide a Cloudflare WSGI middleware.
