### ISSUE TITLE
Werkzeug v1 EOL and security backports policy?

### ISSUE THREAD

**Issue by n1ngu** [pallets/werkzeug#2316]
After https://github.com/pallets/werkzeug/pull/1913 and https://github.com/pallets/werkzeug/pull/2150 I am curious about
- what is the project policy for backporting security features to the Werkzeug v1 series
- whether it should be made explicit that it reached an EOL right after v2 was released if that is so

Thank you.

**Comment by davidism** [comment]
We support only the latest 2.x.y version, and may port security fixes back to 2.x-1. V1 is not supported.
