### ISSUE TITLE
Form parser ignoring Content-Type charset

### ISSUE THREAD

**Issue by insmo** [pallets/werkzeug#233]
Given a form value like "Kjær", encoded with `windows-1254` encoding,
is decoded as UTF-8 by the werkzeug form parser. In Python
request.form['name'] will return u'Kj\ufffdr', rather than u'Kj\xe6r'.

The BaseRequest class defines the default charset as UTF-8. However,
even though a charset is specified as in the Content-Type header,
werkzeug will use this default charset when parsing urlencoded form
data.

I will argue that two mistakes are made by the werkzeug form parser;

1) The default charset is set to utf-8. While section 3.7.1 in the
HTTP spec says "When no explicit charset parameter is provided by the
sender, media subtypes of the "text" type are defined to have a
default charset value of "ISO-8859-1" when received via HTTP." [1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7.1).

2) The charset parameter is not respected [2](http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.4).

I would like to get a confirmation that my assumptions here are correct, before I spend time on implementing a patch for the issue. (@kennethreitz, @mitsuhiko)

curl --data "name=Kj%E6r" -H "Content-Type:
application/x-www-form-urlencoded; charset=windows-1254"
http://localhost:5000/

**Comment by ultrabug** [comment]
I'm surprised that nobody else thought this issue is quite important when dealing with non UTF-8 url encoders.

I'm also affected by this behavior. Are we missing something @untitaker please ? How could we help more to get this issue some love ?

Thanks

**Comment by untitaker** [comment]
When I set the label I didn't really look into this issue, as I would expect that a fix would break backwards compat, so preserving it for a major version seemed like a good idea.

RFC 2616 has been superseded. We have to check whether the issues from the OP still are violations of the standard.

>1) The default charset is set to utf-8. 

I am pretty sure that the current charset default is now correct, although somebody should verify this independently.

>2) The charset parameter is not respected

This is still a bug.

**Comment by untitaker** [comment]
Also, yeah, I am glad to accept PRs on this, but the submitter should do extensive research on the relevant RFCs themselves.

**Comment by ultrabug** [comment]
Thanks for your quick answer @untitaker. I can't guarantee to have the right amount of time for this but at least this issue has a direction for resolution.

Cheers

**Comment by pasitolonen** [comment]
I've been struggling with this same issue (UTF-8 vs. ISO-8859-1) for a while. In my case, another server sends for example a value with %C4 to my application and it is always converted to u'\ufffd by Flask, no matter what. And after that, every decode/encode fails.

**Comment by davidism** [comment]
This is intentional: https://github.com/pallets/werkzeug/issues/909#issuecomment-365578698. We cannot trust a user-supplied codec because Python has no way to tell us if a codec name is a standard text encoding or a Python-specific / custom registered codec (for example, "zip"). If you're willing to take that risk, you can mix in `contrib.wrappers.DynamicCharsetRequestMixin` to your `Request` class, or do something similar with your own list of good codecs.
