### ISSUE TITLE
werkzeug shouldn't try to interpret HTTP_TRANSER_ENCODING

### ISSUE THREAD

**Issue by DenisKuplyakov** [pallets/werkzeug#2346]
[PR 1198](https://github.com/pallets/werkzeug/pull/1198) has broken wsgi protocol. [PEP 3333](https://www.python.org/dev/peps/pep-3333/) states that:

> However, because WSGI servers and applications do not communicate via HTTP, what [RFC 2616](http://tools.ietf.org/html/rfc2616.html) calls ["hop-by-hop" headers](http://tools.ietf.org/html/rfc2616.html#section-13.5.1) do not apply to WSGI internal communications. **WSGI applications must not** generate any "hop-by-hop" headers, attempt to use HTTP features that would require them to generate such headers, or **rely on the content of any incoming "hop-by-hop" headers in the environ dictionary**.

Transfer-Encoding is a hop-by-hop header [as stated in RFC2616](https://www.ietf.org/rfc/rfc2616.txt#:~:text=Authorization%0A%20%20%20%20%20%20%2D%20TE%0A%20%20%20%20%20%20%2D%20Trailers%0A%20%20%20%20%20%20%2D-,Transfer%2DEncoding,-%2D%20Upgrade%0A%0A%20%20%20All%20other) so it should be ignored.

As stated by PEP3333 handling of hop-by-hop should be done on WSGI servers side (like uwsgi):

> WSGI servers must handle any supported inbound "hop-by-hop" headers on their own, such as by decoding any inbound Transfer-Encoding, including chunked encoding if applicable.

> Similarly, a server may re-encode or transport-encode an application's response, but **the application** should use a suitable content encoding on its own, and **must not apply a transport encoding**.

By the moment a try of werkzeug to handle chunked Transfer-Encoding leads to the problems on nginx+uwsgi+werkzeug stack. Nginx eliminates chunked Transfer-Encoding and sends prepared body to uwsgi, but leaves HTTP_TRANSFER_ENCODING untouched. That conforms with PEP3333 which states:
> The environ dictionary is required to contain these CGI environment variables, as defined by the Common Gateway Interface specification [[2]](https://www.python.org/dev/peps/pep-3333/#id7)

Common Gateway Interface specification states that HTTP_* stuff is forwarded unmodified:
> Meta-variables with names beginning with 'HTTP_' contain values read from the client request header fields, if the protocol used is HTTP. The HTTP header field name is converted to upper case, has all occurrences of "-" replaced with "_" and has 'HTTP_' prepended to give the meta-variable name. The header data can be presented as sent by the client, or can be rewritten in ways which do not change its semantics. 

So, to summarize the problem is following:
1. nginx eliminates chunked encoding from body
2. nginx sets CONTENT_LENGTH
3. nginx sends prepared body to uwsgi and HTTP_TRANSFER_ENCODING unmodified
4. uwsgi doesn't try to parse HTTP_TRANFER_ENCODING as body is prepared and CONTENT_LENGTH is set 
5. werkzeug [here](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/wsgi.py#L161) tries to get CONTENT_LENGTH, goes [here](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/wsgi.py#L129), see that chunked is in Transfer-Encoding and return None CONTENT_LENGTH despite that it is already set by nginx
6. werkzeug goes [here](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/wsgi.py#L172) and returns empty body

I have attached docker-compose project that reproduces behavior described above:
1. unpack project
2. docker-compose up --build
3. cat request | nc localhost 8080
4. see environ, wsgi.input, request.data and request.stream in service logs:
```
app_1    | {'CONTENT_LENGTH': '6',  <----
app_1    |  'CONTENT_TYPE': 'text/plain',
app_1    |  'DOCUMENT_ROOT': '/etc/nginx/html',
app_1    |  'HTTP_ACCEPT': '*/*',
app_1    |  'HTTP_CONTENT_TYPE': 'text/plain',
app_1    |  'HTTP_HOST': 'localhost:8080',
app_1    |  'HTTP_TRANSFER_ENCODING': 'chunked',  <----
app_1    |  'PATH_INFO': '/',
app_1    |  'QUERY_STRING': '',
app_1    |  'REMOTE_ADDR': '127.0.0.1',
app_1    |  'REMOTE_PORT': '40204',
app_1    |  'REQUEST_METHOD': 'POST',
app_1    |  'REQUEST_SCHEME': 'http',
app_1    |  'REQUEST_URI': '/',
app_1    |  'SERVER_NAME': '',
app_1    |  'SERVER_PORT': '8080',
app_1    |  'SERVER_PROTOCOL': 'HTTP/1.1',
app_1    |  'uwsgi.node': b'denisnotebook',
app_1    |  'uwsgi.version': b'2.0.20',
app_1    |  'werkzeug.request': <Request 'http://localhost:8080/' [POST]>,
app_1    |  'wsgi.errors': <_io.TextIOWrapper name=2 mode='w' encoding='ANSI_X3.4-1968'>,
app_1    |  'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
app_1    |  'wsgi.input': <uwsgi._Input object at 0x7f50d3b90370>,
nginx_1  | 127.0.0.1 - - [04/Mar/2022:09:33:09 +0000] "POST / HTTP/1.1" 200 18 "-" "-"
app_1    |  'wsgi.multiprocess': False,
app_1    |  'wsgi.multithread': False,
app_1    |  'wsgi.run_once': False,
app_1    |  'wsgi.url_scheme': 'http',
app_1    |  'wsgi.version': (1, 0)}
app_1    | wsgi.input b'foobar'  <----
app_1    | request.data b''  <----
app_1    | request.stream b''  <----

```
5. The screenshot shows the data that uwsgi receives. You can see there is no chunks lengths in request body. Data was captured by tcpdump and visualized via wireshark.

![tcpdump_of_uwsgi](https://user-images.githubusercontent.com/3333218/156739019-76079a90-e8fa-4da0-8608-5c6f053661ee.png)

[compose_project_for_werkzeug.zip](https://github.com/pallets/werkzeug/files/8184705/compose_project_for_werkzeug.zip)

Environment:
- Python version: 3.8.5
- Werkzeug version: 2.0.3

PS. Even if you try to handle values in Transfer-Encoding, such code 
```
if environ.get("HTTP_TRANSFER_ENCODING", "") == "chunked":
```
is broken as Transfer-Encoding may be a list of multiple specifiers, like: `Transfer-Encoding: gzip, chunked`. But I hope this code will be removed completely from werkzeug or moved to some optional behavior as a solution of this issue.

**Comment by DenisKuplyakov** [comment]
I should mention that I thought at first that it is nginx bug to not remove HTTP_TRANSFER_ENCODING from the data passed to uwsgi. Here is the [ticket in nginx bug tracker](https://trac.nginx.org/nginx/ticket/2328). But as I mentioned above that behavior conforms with PEP3333

**Comment by davidism** [comment]
If you're dechunking input in nginx, then you should also configure nginx to unset the header that says that the input is chunked.

**Comment by DenisKuplyakov** [comment]
> If you're dechunking input in nginx, then you should also configure nginx to unset the header that says that the input is chunked. The content-length header should not be set when transfer-encoding is set, as they specify the length of the body in different ways.

@davidism You make decisions based on HTTP protocol, but werkzeug actually implements WSGI protocol, which differs in handling of transfer encoding stuff. I have proven this in the issue description by providing links to the PEP3333. Which of my arguments in issue description you consider wrong?

Werkzeug actually doesn't implement WSGI correctly now. And moreover it retranslates empty body to the application without any warning or error, which leads to hidden errors.

**Comment by davidism** [comment]
If the transfer encoding is chunked, then this is a streaming request. WSGI has insufficient ability to handle streaming requests safely on its own, which is why the defacto `wsgi.input_terminated` standard was introduced by the original author of Werkzeug, and adopted by many WSGI servers. If the request looks like it is streaming (has no length, or is chunked), then the only thing the application can do is rely on the server to terminate the body appropriately, otherwise the stream could continue forever. If a WSGI server implements terminating responses safely, then it must set the `wsgi.input_terminated` environ to indicate to the application that it is safe to read without knowing the length. Unfortunately, https://github.com/unbit/uwsgi/issues/1428 is still open, so uWSGI doesn't handle this. Again, if you're handling it by unchunking in Nginx, then you need to communicate that it is no longer chunked.

**Comment by DenisKuplyakov** [comment]
I think, that if we add additional features above the standard, they should be backward compatible. Or we can't anymore say that werkzeug correctly implements WSGI/PEP3333. Due to this I propose to leave additional stuff like `wsgi.input_terminated` out of our discussion and talk about vanilla WSGI.

I prove in the issue description that by the moment support of vanilla WSGI is broken as:
1. hop-by-hop headers must be ignored (PEP3333), but they don't
2. HTTP_TRANSFER_ENCODING must be passed "as is" (CGI spec refered by PEP3333), but current implementation expects it to be modified

About uwsgi: @unbit [says](https://github.com/unbit/uwsgi/issues/1428#issuecomment-270605092) the same that I wrote in the issue description:
> Chunked transfer IS supported by uWSGI, it is not supported by the WSGI standard. The PEP3333 does not cover it, and instead you always need a Content-Length. You are expecting your WSGI layer to automatically manage it, but it is a violation of the standard. In uWSGI we prefer to not enforce ad-hoc behaviour where a standard is expected, by adding specific features in the uwsgi module in the best possible way.

PS. Can I ask you to send me a link to `wsgi.input_terminated` specification?

**Comment by davidism** [comment]
We're not breaking anything, you're _sending invalid headers_. Unset the transfer-encoding header, or don't dechunk the content ahead of time, and you won't run into this issue. If you send both a content length and transfer-encoding: chunked header, you have set up an ambiguous situation. So you either send the correct data, or you use a WSGI server that can safely handle streaming responses.

**Comment by davidism** [comment]
Here's the spec: https://gist.github.com/mitsuhiko/5721547

To summarize: If the stream looks like it doesn't have a content length that can be trusted, the only safe thing a WSGI application can do is not trust it. The way the WSGI server can indicate that the streaming response can be trusted is to set `wsgi.input_terminated`'.

Gunicorn supports it:https://github.com/benoitc/gunicorn/issues/1653, mod_wsgi supports it, and Waitress supports it. I'm not sure what others do, but among the common servers, uWSGI is the only outlier. Note that you can also "support" it by terminating streaming early, which is what you seem to be trying to do, but if you do that _you need to make sure the resulting headers and data are consistent_.

**Comment by DenisKuplyakov** [comment]
> We're not breaking anything, you're _sending invalid headers_. Unset the transfer-encoding header, or don't dechunk the content ahead of time, and you won't run into this issue.

The behaviour of nginx+uwsgi by the moment completely conforms with PEP 3333. I will repeat the text again:

> The environ dictionary is required to contain these CGI environment variables, as defined by the Common Gateway Interface specification [[2]](https://www.python.org/dev/peps/pep-3333/#id7)

Common Gateway Interface specification states that HTTP_* stuff is forwarded unmodified:

> Meta-variables with names beginning with 'HTTP_' contain values read from the client request header fields, if the protocol used is HTTP. The HTTP header field name is converted to upper case, has all occurrences of "-" replaced with "" and has 'HTTP' prepended to give the meta-variable name. **The header data** can be presented **as sent by the client**, or can be rewritten in ways which **do not change its semantics**.

---

> If you send both a content length and transfer-encoding: chunked header, you have set up an ambiguous situation. 

That's wrong as PEP3333 clearly says that:

> **WSGI applications must not** generate any "hop-by-hop" headers, attempt to use HTTP features that would require them to generate such headers, or **rely on the content of any incoming "hop-by-hop" headers in the environ dictionary**.

The current Werkzeug implementation obviosly relies on content of Transfer-Encoding, which is hop-by-hop header.

I think, you confuse between WSGI and HTTP. For HTTP existence of both `Content-Type` and `Transfer-Encoding: chunked` is considered impossible. And HTTP spec clearly says that client MUST ignore `Content-Type` if `Transfer-Encoding: chunked`.

But we are speaking about WSGI now. And WSGI spec requires a server to pass HTTP_* stuff unmodified to application and application MUST ignore contents of any hop-by-hop headers.

---

I have tested nginx+uwsgi+Falcon 3.0.1 and it behaves correctly and according to WSGI spec.

The project is the same as attached, but falcon is installed in Dockerfile and contents of app.py are replaced by:
```python
import falcon

class Resource:
    def on_post(self, req, resp):
        print(req.stream.read())
        resp.media = 'finished'

application = falcon.App()
application.add_route('/', Resource())
```

Here is log output, which is correct:
```
app_1    | b'foobar'
```

I will test django tomorrow.

**Comment by mitsuhiko** [comment]
I am not entirely sure what you are asking for. WSGI has a known deficiency that it's unclear what to do with chunked requests at all. Before the introduction of `wsgi.input_terminated` where was absolutely no way to handle it. The only way that was supported by PEP 333 was to not use any chunked requests at all. We tried to improve on this situation by opening a door at all to support it.

There is a pretty straightforward workaround in your situation anyways which is to remove `HTTP_TRANSFER_ENCODING` in a middleware or elsewhere. The only alternative option is to roll back any support for chunked requests which would also break your setup.

**Comment by DenisKuplyakov** [comment]
> WSGI has a known deficiency that it's unclear what to do with chunked requests at all. Before the introduction of wsgi.input_terminated where was absolutely no way to handle it. The only way that was supported by PEP 333 was to not use any chunked requests at all.

I can't agree with you. That is clear and strictly defined in spec. WSGI says that server MUST set CONTENT_LENGTH with [semantics defined by CGI spec](https://datatracker.ietf.org/doc/html/draft-coar-cgi-v11-03#section-4.1.2):

> The server MUST set this meta-variable if the request is accompanied by a message-body entity. The CONTENT_LENGTH value must reflect the length of the message-body **after the server has removed any transfer-codings or content-codings**.

So this implies that server has no way but to read the whole request before using WSGI interface to access application in a case chunked transfer encoding is used. It's clear and that is the way, but not the perfect way (that's why you go with `wsgi.input_terminated` stuff).

Also I should note that server MUST support chunked Transfer-Encoding as of [Section 3.6.1 of HTTP1.1](https://datatracker.ietf.org/doc/html/rfc2616#section-3.6.1):

> All HTTP/1.1 applications MUST be able to receive and decode the "chunked" transfer-coding, and MUST ignore chunk-extension extensions they do not understand.

---

> The only alternative option is to roll back any support for chunked requests which would also break your setup.

For me by the moment implementation of `wsgi.input_terminated` looks as not wsgi-compatible without changes to the server. So I think there are two options:
1. you can hide all the `wsgi.input_terminated` stuff by some configuration option, which is turned off by default. That way werkzeug "out of the box" will be WSGI conforming;
2. or you can stop declare Werkzeug as WSGI conforming.

---

I have looked throight the spec on `wsgi.input_terminated` and have a couple of comments, as it looks like werkzeug doesn't implement your own spec.

`wsgi.input_terminated` spec says:
> WSGI servers have two options to providing the input stream:
> 1. Provide wsgi.input as socket file unchanged. This means that **wsgi.input_terminated** is set to False or **not added to the WSGI environ at all**. In that case the **WSGI application is required to look at the CONTENT_LENGTH** and only read up to that point. Applications in that case are required to count up the bytes received and comparing it against the content length. If less than CONTENT_LENGTH is received the application must respond to this in order to not accidentally assume a regular end of the stream has been reached.

In my case werkzeug doesn't look. It returns empty input.

Also `wsgi.input_terminated` spec says:
> Until that however is the case clients will need to support the worst case which is that flag not being set in which case they are required to work within the vague wording of the original specification.

So, why when the flag is not set by uwsgi I got a broken application with empty input with behavior that not conforms with WSGI?
