### ISSUE TITLE
ImportError: cannot import name 'BaseRequest' from 'werkzeug.wrappers'

### ISSUE THREAD

**Issue by kannanprasanna** [pallets/werkzeug#2360]
After the latest release 2.1.0, all dependent flask builds/tests are failing due to the below error 
ImportError: cannot import name 'BaseRequest' from 'werkzeug.wrappers'

Flask and other dependent projects use Werkzeug>=2.0 in their requirements.txt and any programs importing Flask and running a test are failing.

Environment:

- Python version: 3.8.8
- Werkzeug version: 2.1.0

**Comment by davidism** [comment]
The various base classes were previously deprecated, as they were consolidated into the `Request` class, and are now removed. https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0

> Request and response mixins have all been merged into the `Request` and `Response` classes.
