### ISSUE TITLE
WERKZEUG_SERVER_FD key error

### ISSUE THREAD

**Issue by Pavithrajas** [pallets/werkzeug#2361]
Environment:

- Python version: 3.8
- Werkzeug version: 2.1.0
- Flask version: 2.1.0 

Issue: I was able to run my flask application without any problem before a couple of days. But suddenly with the above versions in my ubuntu machine, it started throwing me a key error for `WERKZEUG_SERVER_FD` in "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 1047. 

Is there anything, I have to do to fix this problem explicitly? 
Why did this become a problem all of a sudden?

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided.

**Comment by Pavithrajas** [comment]
I am trying to run this flask application : https://github.com/ArunKumarJain/mock-server/blob/master/mockserver.py

which gives me the following stack trace: 

>  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 1047, in run_simple
    fd = int(os.environ["WERKZEUG_SERVER_FD"])
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'WERKZEUG_SERVER_FD'

**Comment by jeroen92** [comment]
I'm also hitting this error when starting Werkzeug 2.1.0 and having the`WERKZEUG_RUN_MAIN` envvar set to `true`. Removing this envvar fixes it. I'd like to have it set though in order to suppress logging like
``` * Serving Flask app 'app.helpers.auth' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off```

**Comment by davidism** [comment]
Something you're using is setting `WERKZEUG_RUN_MAIN`, an environment variable used internally during server/reloader setup. This is incorrect. In other cases of this that I've found, the intention seems to be to hide startup messages from the development server. This is not safe. The messages intentionally warn about running a development server. You'll need to report this issue to the library doing this, not Werkzeug.
