### ISSUE TITLE
cannot stop flask app programmaticaly with werkzeug 2.1.0 

### ISSUE THREAD

**Issue by vetonyx** [pallets/werkzeug#2363]
piece of code that handle shutdown route in flask app

func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()

request.environ.get('werkzeug.server.shutdown') returns None
this makes us freeze werkzeug version to previous in our project

- Python version: 3.8.10
- Werkzeug version: 2.1.0

**Comment by davidism** [comment]
See https://github.com/pallets/werkzeug/issues/1752 for reasons why the `shutdown` function was removed. The documentation shows one way to manage processes using `multiprocessing` instead.

This was previously deprecated, and is now removed.

2.0.0:

> Deprecate the `environ["werkzeug.server.shutdown"]` function that is available when running the development server. [#1752](https://github.com/pallets/werkzeug/issues/1752)

2.1.0:

> Remove previously deprecated code. [#2276](https://github.com/pallets/werkzeug/pull/2276)
> * Remove the non-standard shutdown function from the WSGI environ when running the development server. See the docs for alternatives.

Using this function while it was deprecated showed a warning in the terminal explaining that it would be removed.

**Comment by banesullivan** [comment]
While this works for a multithreaded server, it doesn't work for a multiprocess server:

```py
import requests
import threading

from werkzeug import Response, Request
from werkzeug.serving import make_server


@Request.application
def app(request):
    return Response("howdy",  200)


class Server(threading.Thread):
    def __init__(self, port=5005, *args, **kwargs):
        
        self.port = port
        # NOTE THE processes=5
        self.srv = make_server("localhost", port, app, processes=5)
        
        threading.Thread.__init__(self, daemon=True, target=self.srv.serve_forever)
        
        self.start()
        
    def shutdown(self):
        self.srv.shutdown()
        self.join()

    def get(self):
        return requests.get(f'http://localhost:{self.port}/').text
        

t = Server()
print(t.get())

t.shutdown()  # <- hangs on the shutdown call

print(t.get())
```

**Comment by banesullivan** [comment]
Change to `self.srv = make_server("localhost", port, app, threaded=True)` and this works like a charm though
