### ISSUE TITLE
Werkzeug 2.1.0 fails with `WERKZEUG_SERVER_FD` error

### ISSUE THREAD

**Issue by sfuerte** [pallets/werkzeug#2368]
Upgrading to 2.1.0 leads to the following error:
```
"message": "Starting REST API"
"message": "'WERKZEUG_SERVER_FD'", 
"exc_info": "Traceback (most recent call last):
  File \"/opt/cisco/nni/nniAgent.py\", line 1678, in run
  api.run()
  File \"/opt/cisco/nni/rest_api/nniRestApi.py\", line 135, in run
  self.app.run(host=self.host, port=self.port, debug=self.debug)
  File \"/usr/local/lib/python3.9/dist-packages/connexion/apps/flask_app.py\", line 104, in run
  self.app.run(self.host, port=self.port, debug=self.debug, **options)
  File \"/usr/local/lib/python3.9/dist-packages/flask/app.py\", line 920, in run
  run_simple(t.cast(str, host), port, self, **options)
  File \"/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py\", line 1047, in run_simple
  fd = int(os.environ[\"WERKZEUG_SERVER_FD\"])
  File \"/usr/lib/python3.9/os.py\", line 679, in __getitem__
  raise KeyError(key) from None
  KeyError: 'WERKZEUG_SERVER_FD'"
"message": "SHUTDOWN"
```

Environment:

```sh
$ lsb_release -d
Description:	Debian GNU/Linux 11 (bullseye)

$ python3 --version
Python 3.9.2

# selected packages
$ pip3 list
Package               Version
--------------------- --------------
connexion             2.13.0
Flask                 2.1.0
Werkzeug              2.1.0
```

Workaround:

freezing Werkzeug @ 2.0.3 in `requirements.txt` (which we didn't have before as don't use it directly but it's rather a prerequisite of `connexion` and `Flask`)
```
Werkzeug==2.0.3
```

**Comment by davidism** [comment]
Looks like connexion is messing with the dev server internals in a way that tricks it into thinking it's running in the reloader when it's not. Since it's not actually running in the reloader, certain things that it expects aren't set up correctly. You'll need to report this to connexion.

**Comment by RobbeSneyders** [comment]
@davidism could you point me to where connexion is messing with the dev server internals? I'm having a hard time reproducing the issue.

**Comment by davidism** [comment]
Yeah, I had a look and can't reproduce this either. If anyone is setting `WERKZEUG_RUN_MAIN` manually for some reason, that's what would mess with it.

**Comment by sfuerte** [comment]
@davidism, thanks for the hint. Apparently, it was set in systemd service file, removing that solved the issue.
```
# required to disable Flask debugging banner: "Serving Flask app (lazy loading) ..."
Environment="WERKZEUG_RUN_MAIN=true"
```

**Comment by davidism** [comment]
The fact that you're running this in systemd indicates a severe security issue with that application. Do not run the development server in production. It is not intended to be secure, stable, or efficient. The fact that you have to set an internal variable just to disable this message should be a strong indicator that you're doing something incorrect.

**Comment by sfuerte** [comment]
Thanks for the info. Will review what was done there :)
