### ISSUE TITLE
`secure_filename` drops non-ASCII characters

### ISSUE THREAD

**Issue by Furkas91** [pallets/werkzeug#2376]
`secure_filename` doesn't work with Cyrillic characters in filenames. `secure_filename("фото.jpg")` results in "jpg" not "фото.jpg".

Environment:

- Python version: 3.7
- Werkzeug version: 2.1.1

**Comment by davidism** [comment]
From the fuction's docs:

> The filename returned is an ASCII only string for maximum portability. The function might return an empty filename.

It normalizes Unicode characters using NFKD, then drops any characters that can't be encoded to ASCII. NFKD splits combined characters, which allows dropping the combining characters while keeping the underlying "ASCII compatible" character, but that only works for certain characters.

@ThiefMaster Do you think we should remove the "ASCII only" step?

**Comment by ademaro** [comment]
Yes, I confirm that this is a big problem. If the file name consists only of Cyrillic characters (not ascii characters), only the file extension is returned. You could at least replace all those characters with an underscore, which would end up with something like: `_.jpg`

Or remove the line `filename = filename.encode("ascii", "ignore").decode("ascii")` from secure_filename function.

**Comment by ThiefMaster** [comment]
What I usually do is transliterating non-ascii chars to ascii versions: https://github.com/indico/indico/blob/master/indico/util/fs.py#L34-L53 - like this I pretty much always get a decent filename without non-ascii crap in it. But I don't think this can be done in a satisfactory way without additional dependencies.

I absolutely would **not** want non-ascii characters in my file names on disk, but maybe a fallback kwarg to ensure a non-empty result could be a good option...

**Comment by ademaro** [comment]
I agree that storing non-ascii file names is a bad idea (I save them later with something like this: https://pypi.org/project/python-slugify/).

It is just not clear how to control this now (there are many dependencies in other packages and it breaks them with non-acsii characters)
