### ISSUE TITLE
Two identical POST requests in flask lead to a method not allowed error in the second request. Issue traced back to Werkzeug 2.1

### ISSUE THREAD

**Issue by ImreC** [pallets/werkzeug#2380]
Calling the same endpoint twice with a post request leads to:
```
127.0.0.1 - - [05/Apr/2022 17:41:14] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [05/Apr/2022 17:41:14] "{}POST / HTTP/1.1" 405 -
```

Minimal repo here: https://github.com/ImreC/werkzeug-flask-bug. Running this creates a single endpoint which accepts method POST. Calling this endpoint with no body works fine. Calling it with any body (f.e. `{}`) works fine the first time, but returns a 405 Method not allowed error the second time. With Werkzeug 2.0.3 this behavior does not occur.

Environment:

- Python version: 3.8 (also tested on 3.10)
- Werkzeug version: 2.1.1 (also confirmed in 2.1.0)

**Comment by davidism** [comment]
If you post data, your view needs to read that data. Werkzeug's development server is not capable of draining this. In 2.1, HTTP/1.1 mode, with keep-alive behavior, was enabled by default, which means a request that doesn't actually read the input sent with it gets prepended to the start of the next request.

Production servers do not have this issue. If you read the data in the request, the development server will not have this issue.

The development server is a wrapper around Python's `http.server`, a bug can be reported to them if you think it should be fixed there.

**Comment by ImreC** [comment]
Ok, this will be easily resolved. Thanks for clarifying! Was very confusing behavior without knowing what was going on
