### ISSUE TITLE
Unable to build werkzeug

### ISSUE THREAD

**Issue by seemantk** [pallets/werkzeug#2384]
Hello, in Funtoo Linux we have this package available to users.  We have been getting reports (and confirm the same) of the following error:

```
  File "/var/tmp/portage/dev-python/werkzeug-2.1.1/work/Werkzeug-2.1.1/src/werkzeug/serving.py", line 39
    def __getattr__(self, name: str) -> t.Any:
                              ^
SyntaxError: invalid syntax
```

The python version in use is 3.7

**Comment by davidism** [comment]
I can't reproduce the issue with the information provided.

**Comment by seemantk** [comment]
What further information may I furnish?
