### ISSUE TITLE
Still unable to build werkzeug

### ISSUE THREAD

**Issue by seemantk** [pallets/werkzeug#2385]
I opened #2384 to report this. But instead of _asking for more information_ the ticket was summarily closed, which doesn't feel like a friendly experience at all.

I've attached the full build log.  If there's other information needed to help y'all debug this, please let me know so that I can provide it!

**Comment by seemantk** [comment]
[build.log](https://github.com/pallets/werkzeug/files/8456040/build.log)

**Comment by davidism** [comment]
You said you were running Python 3.7, but very clearly in the logs I see Python2_7. Fix your build process, it's using a version of Python that has passed end of life.
