### ISSUE TITLE
Closing the client connection prior to any response

### ISSUE THREAD

**Issue by dsoprea** [pallets/werkzeug#2389]
I have some application-level security measures. I'd like to just kill the client connection if we suspect that the current request is suspicious rather than returning a proper response. To produce an ambiguous response to the client that seeks to avoid an outright acknowledgement that they found a webserver. What about being able to call a function right when the incoming connection is accepted and the header bytes are first read? I've tried to just close the request stream from a before_request function or close the response stream in a after_request function, but the former has no effect and the latter will just close the socket after already having written the status and headers.

I did a heavy number of searches into both the lifecycles of Flask and Werkzeug, but didn't turn up anything. It seems like no one has ever asked the connection-abort question before.

It seems like I should be able to catch where the start_response callback is called by Flask and either write my own or intercept it and return my own no-op write function so that the client connection is effectively never acted on, but this requires more research. I couldn't seem to find anywhere in Flask or Werkzeug that actually calls start_response or anything that might refer to this by an alternate name before I ran out of time to look.

I'm posting this here as well as having posted it in SO several days ago since I wasn't seeing any activity.

Reference: https://stackoverflow.com/q/71825516/706421
Reference: https://github.com/pallets/werkzeug/blob/c7ae2fea4fb229ffd71187c2b665874c91b96277/src/werkzeug/serving.py#L250

**Comment by ThiefMaster** [comment]
Considering that the built-in server is neither intended nor suitable for production usage, I don't see why this is needed there.

**Comment by dsoprea** [comment]
We're using uWSGI, but Werkzeug is assembling the HTTP response.

**Comment by davidism** [comment]
This is not possible at the WSGI application layer. You'd need a custom HTTP server with this capability.

**Comment by davidism** [comment]
You need an alternative for Nginx.

**Comment by dsoprea** [comment]
Can you clarify what would happen if I just went into Werkzeug and got it to not return anything? It seems like a very practical and achievable measure, but you seem to be convinced that it still wouldn't break/sabotage the transaction.

**Comment by dsoprea** [comment]
I suggested that this would be an acceptable alternative if there could not otherwise be a direct impact on the connection itself. I'm just trying to be disruptive to the caller.

**Comment by davidism** [comment]
You can't "not return anything" from the WSGI application layer, that doesn't mean anything. The spec does not work that way. You're talking about something at the HTTP layer, which is not what Werkzeug is.

**Comment by dsoprea** [comment]
I mean, I was hoping for single, enthusiastic response. But, I appreciate
your many "succinct" responses all the same. Thank you for your work on the
project.

**Comment by davidism** [comment]
I'm sorry I did not reply in a way that suited your expectations of what a reply is. Regardless of the format or length, my response would have been the same, so I'm not sure what the point of you saying that is. Note that my response is "no that's not possible" four different ways, since you kept insisting it was possible rather than believing me.
