### ISSUE TITLE
refactor WSGI assumptions out of `http.py` and `wsgi.py` functions

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#2408]
Our goal is to be able to process headers and request information from both WSGI and ASGI, which use different data structures. Similar to the `sansio.Request` refactor, make a `sansio.http` module that has implementations of the various HTTP methods (and possibly "WSGI" methods) that takes the exact values it needs instead of an environ. Then change the top-level `http` module to call these methods with values from the environ. Later, we might add an `asgi` implementation to similarly call them with an asgi context instead.

**Comment by davidism** [comment]
This can be divided up into many tasks, we can work on one or a few functions at a time.

**Comment by HundredVisionsGuy** [comment]
@rrahkola and I are working on this.

**Comment by rrahkola** [comment]
Yep!
