### ISSUE TITLE
move parsing methods that return data structure objects into the objects

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#2409]
Many functions in `http` are header parsing that returns an object from `datastructures`. Move the parsing code into the classes themselves, and deprecate the old functions.

For example, `parse_cache_control_header` should instead be a classmethod `CacheControl.parse_header()`.

There may also be some functions that convert an object to a header value, those should also be in the object.

**Comment by DailyDreaming** [comment]
This sounds like something I can handle.

**Comment by davidism** [comment]
After some discussion with @pgjones, we think splitting datastructures and moving parsing functions next to relevant classes will be a better reorganization. Going to close this for now, I'll think about that larger refactor later.
