### ISSUE TITLE
redirect from a POST can cause METHOD_NOT_ALLOWED

### ISSUE THREAD

**Issue by jwag956** [pallets/werkzeug#2416]
In 2.1.0 (not in 2.0.3) I am getting METHOD_NOT_ALLOWED upon redirects from an initial POST request. This is using Werkzeugs built-in WSGI server. The long and short is that in the WGI environ dict the REQUEST_METHOD somehow gets set to the CONTENTS of the posted form that caused the redirect. From PyCharm debugging from werkzeug::routing.py:

`REQUEST_METHOD='csrf_token=Ijg0NWUwZTM4OGY5YzI4MjRkODg0Yjk1YjA1Y2ViZmFmZDM3N2Y0Mjki.YnQbIw.1tat_eO7-PXILGefdESfOfAOKJM&name=sfactor&submit=DeleteGET'`

POST a form, and as part of initial processing of that form (I have it in a decorator) perform a redirect(<endpoint>). I am doing this using a browser (Chrome). Chrome developer tools don't show anything odd at all - correct 301, correct Location header.

Hmm - just a thought - since I am calling redirect() from a decorator, I haven't actually read in/accessed the entire request - is there some way that the request socket isn't being cleared when short-circuiting a request (out on a limb here!). Note that in the above example - the proper REQUEST_METHOD 'GET' is at the end of the line.

Environment:

- Python version:3.8
- Werkzeug version:2.1.0

**Comment by davidism** [comment]
Upgrade to 2.1.2.

**Comment by jwag956** [comment]
Darn - thought I was all up to date. Yup - all fixed... sorry for the trouble.
