### ISSUE TITLE
html.escape() partially double-escapes Markup (keeps <> but reescapes &)

### ISSUE THREAD

**Issue by lucaswerkmeister** [pallets/werkzeug#2419]
```python
>>> html.escape(markupsafe.Markup('<b>&lt;</b>'))
Markup('<b>&amp;lt;</b>')
```

This incomplete “cooperation” with `html.escape()` seems undesirable. I noticed it when using `abort()`:

```python
from flask import Flask, Markup, abort

app = Flask(__name__)

@app.route('/')
def index():
    markup = Markup(r'<b>{}</b>').format('<')
    abort(400, markup)
```

This produces:

```html
<!doctype html>
<html lang=en>
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p><b>&amp;lt;</b></p>
```

> <p><b>&amp;lt;</b></p>

This turns out to be because Werkzeug’s `HTTPException.get_description()` calls `html.escape()` on the description, which leaves the `<>` as they are, but turns the already-escaped `&lt;` into `&amp;lt;`.

Environment:

- Python version: 3.10.4
- MarkupSafe version: 2.1.1

**Comment by davidism** [comment]
I'm just going to add MarkupSafe as a dependency to Werkzeug as well. No reason to use `html.escape` here when everyone use Flask (a large majority of the Werkzeug users) will already have MarkupSafe installed.

**Comment by davidism** [comment]
The problem is that `html.escape` uses `str.replace`, and doesn't (shouldn't) know anything about MarkupSafe. Meanwhile, MarkupSafe has to treat any plain strings passed to its methods as requiring escaping, it has no way to know they come from `html.escape`.

**Comment by lucaswerkmeister** [comment]
Thanks! Sounds like a sensible solution to me.
