### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by apinanyogaratnam** [pallets/werkzeug#2424]
When making requests with a boolean argument, the logic of parsing types do not work well with boolean types.
Passing in an argument as `?boolean=False`, the request argument will return True because it is not empty instead of
having the desired boolean value passed as the argument.

Send a request to an endpoint with an argument as boolean=false

current parsing code:
```
boolean_argument = request.args.get('boolean', type=bool)
```

`boolean_argument` will equate to True because it is not an empty string.

This happens because of the following method:
[code](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/datastructures.py#L265)

Expected `boolean_argument` to be False instead of True

Environment:

- Python version: 3.10.4
- Werkzeug version: 2.1.2

**Comment by davidism** [comment]
Please fix the title of this issue.

**Comment by davidism** [comment]
In html, bools (checkboxes) do not work this way. They either send "on" if checked, or don't send anything. You would check `key in request.args` for a bool. Or write a custom converter if you expect some other values.
