### ISSUE TITLE
Performance issue for some data handling in MultipartDecoder

### ISSUE THREAD

**Issue by zhangchunlin** [pallets/werkzeug#2430]
When using werkzeug handling file upload, werkzeug use FormDataParser and MultipartDecoder, in here: https://github.com/pallets/werkzeug/blob/edef71c243e1e1396092f7b5f82ddad6c6f766cf/src/werkzeug/sansio/multipart.py#L187 , if for some part of data, the var data_length is always 0, that will always generate a 'werkzeug.sansio.multipart.NeedData', so the source code will run  self.buffer.find(b"--",...) ( https://github.com/pallets/werkzeug/blob/edef71c243e1e1396092f7b5f82ddad6c6f766cf/src/werkzeug/sansio/multipart.py#L182 ) again and again, which will take longer and longer time(I think it is O(n²)), in the end the upload of file will take much longer time than other most of the files.

Generate a file, which will having a b'\r' in a bound of MultipartDecoder.buffer, and all the data after there is no "\r".
Example of this kind of file:
```
def test52():
    with open("uploadfile.dat","wb") as f:
        def _gen():
            yield b"\r"
            for i in range(30000000):
                yield b"1234567890"
        for i in _gen():
            f.write(i)

if __name__ == '__main__':
    test52()
```
Then upload this file with werkzeug: werkzeug.formparser.parse_form_data() , it will reproduce the issue

Need to handle file quickly, but actually very slow

Environment:

- Python version:3.6.5
- Werkzeug version: latest: edef71c243e1e1396092f7b5f82ddad6c6f766cf

There is a workaround, here( https://github.com/pallets/werkzeug/blob/edef71c243e1e1396092f7b5f82ddad6c6f766cf/src/werkzeug/formparser.py#L348 ) ,  buffer_size: int = 64 * 1024, that's too small, to handle several hundrers of MBytes of data, that will run too many times, if this buffer_size can be given by user, for example user give: 16 * 1024 * 1024, that will reduce the time a lot.

**Comment by davidism** [comment]
@pgjones could you take a look at this?

**Comment by pgjones** [comment]
I think I'll need some more information here. The parser will still consume the buffer whilst looking for the next boundary, so I don't think there is any n^2 growth. I'm also unsure if this applies as the example given is invalid multipart data and hence should result in a failed parse.

**Comment by zhangchunlin** [comment]
Because every time parser search for the next boundary, it need to traverse all the data, the traverse time is decided by the data length, suppose buffer size is n, the traverse time is about to connec with: n+2n+3n+4n+5n... mn = (1+2+3...+m)n = (m * (m + 1) / 2)*n, so it is m^2 growth.

**Comment by pgjones** [comment]
I think #2441 fixes this.
