### ISSUE TITLE
About CNNVD-202205-4094

### ISSUE THREAD

**Issue by 1170301013** [pallets/werkzeug#2431]
This cve is invalid, if you're running the dev server in production you have bigger security issues. The dev server is never intended to be run in production. The cve is also misattributed, it is about Python's http.server.

That said, upgrade Werkzeug

_Originally posted by @davidism in https://github.com/pallets/werkzeug/issues/2420#issuecomment-1137369788_

**Comment by 1170301013** [comment]
Is that means, upgrade werkzeug is neccssary? Or it's realy invalid

**Comment by davidism** [comment]
Both

**Comment by 1170301013** [comment]
Yeah, thanks. But i'm still using py2.7 , it's diffcult for me to update dependencies all.

**Comment by davidism** [comment]
You have bigger problems then. Work on upgrading to Python 3.8 or later as soon as possible.

**Comment by 1170301013** [comment]
That can't be decided by me, only the whole team, it's a terrible thing and will take a long time for us to update.
Thanks for your idea and time~
