### ISSUE TITLE
Add a size parameter to send_file

### ISSUE THREAD

**Issue by rejoc** [pallets/werkzeug#2438]
add a size parameter with default value of None to send_file

in send_file, size is calculated based on the different files "structures". 
But in some cases, like passing a mongodb fs (GridOut) file, the size is not calculated. There may be other cases like that where the caller can get the actual size of the file prior than calling send_file and pass the actual value.

This value could be used instead of calculating it if not None or simply as a default value to initialize the size variable.

This is the first step before asking for the same feature in Flask ;-)

**Comment by davidism** [comment]
Don't ask for it in Flask, it's implemented here.

If you know the size of the file, do the following:

```python
response = send_file(...)
response.headers.set("Content-Length", size)
return response
```

Or just let it stream, there's nothing wrong with that either.

I don't plan to add more options to `send_file` at this point, it's already a very complex set of arguments.

**Comment by rejoc** [comment]
Thanks. Much better!
