### ISSUE TITLE
random net::ERR_INVALID_HTTP_RESPONSE 200 loading javascript and other static files

### ISSUE THREAD

**Issue by Calabashmc** [pallets/werkzeug#2445]
Using Flask 2.11 with Werkzeug 2.11 with any browser that utilises Chromium (tested with 103.0.5060.53 (Official Build) (64-bit) via Chrome, Vivaldi, and Chromium browsers).  Issue does not affect Firefox.

When running built in server for development on local machine the browser will often not fetch some static files. Refreshing the page multiple times can sometimes manage to get all static files loaded but typically some will while others do not.

Examples of this are javascript files do not load, fonts, and less often images.  

Some examples on one load I got this
localhost/:950 
 GET http://localhost:5000/static/trix-main/dist/trix.js net::ERR_INVALID_HTTP_RESPONSE
localhost/:951 
 GET http://localhost:5000/static/trix-main/dist/new_image_upload.js net::ERR_INVALID_HTTP_RESPONSE

after a refresh all was good.
Then another refresh I got this
GET http://localhost:5000/static/sash/assets/plugins/bootstrap/css/bootstrap.min.css net::ERR_INVALID_HTTP_RESPONSE
icons.css:1          GET http://localhost:5000/static/sash/assets/iconfonts/feather/feather.css net::ERR_INVALID_HTTP_RESPONSE
localhost/:951          GET http://localhost:5000/static/trix-main/dist/new_image_upload.js net::ERR_INVALID_HTTP_RESPONSE
localhost/:938          GET http://localhost:5000/static/js/ticket.js net::ERR_INVALID_HTTP_RESPONSE
localhost/:421          GET http://localhost:5000/static/sm4sb/images/priority/p4.png net::ERR_INVALID_HTTP_RESPONSE

so sometimes no errors and other times a random assortment of static files won't load.

All of these are loaded from HTML files using` url_for. For example
`<script src="{{url_for('static', filename='js/ticket.js')}}"></script>
or
``<img src="{{url_for('static', filename='/sm4sb/images/sm4sb.png')}}" alt="sm4sb">
`

Environment:

- Python version: 3.10.4
- Werkzeug version: 2.1.1

**Comment by davidism** [comment]
Update to Werkzeug 2.1.2.
