### ISSUE TITLE
Surprising behavior when overriding a cached property

### ISSUE THREAD

**Issue by hexagonrecursion** [pallets/werkzeug#2452]
Currently overriding a cached property in a subclass causes to surprising behavior because the parent and the child use the same key to store the value of the property:

```py3
from werkzeug.utils import cached_property


class Parent:
    @cached_property
    def foo(self):
        return 1


class Child(Parent):
    @cached_property
    def foo(self):
        return 20 + super().foo

    def bar(self):
        return 300 + super().foo


a = Child()
a.foo
assert a.bar() == 321  # BUG: should be 301

b = Child()
b.bar()
assert b.foo == 1  # BUG: should be 21
```

Environment:

- Python version: 3.8.12
- Werkzeug version: 2.0.1

**Comment by hexagonrecursion** [comment]
I think I know how to fix this: #2453

**Comment by davidism** [comment]
> because the parent and the child use the same key to store the value

This is technically true, but it's obscuring what the actual issue you have is. You're expecting a descriptor accessed through `super()` to be accessed with the paren't classes namespace. That's not how `super` works though, the whole point is that it looks up something on the parent then executes it with `self` set to the current object.

I don't think this is a necessary thing to fix, given the added complexity of the proposed solution. For all our use cases involving `cached_property`, we do not need to have a different value on the parent than the child. It's also not clear that the current implementation is wrong, it's just not what you need for your use case.

If you need the behavior described in this issue, it seems appropriate at that point to write an implementation that is specific to your use case.

**Comment by hexagonrecursion** [comment]
What makes this surprising is that this works as expected for `@property`

```py3
class Parent:
    @property
    def foo(self):
        return 1


class Child(Parent):
    @property
    def foo(self):
        return 20 + super().foo

    def bar(self):
        return 300 + super().foo


a = Child()
a.foo
assert a.bar() == 301

b = Child()
b.bar()
assert b.foo == 21
```

How about a PR documenting this gotcha and proposing a workaround?
