### ISSUE TITLE
ImportError: cannot import name "parse rule' from 'werkzeug.routing'

### ISSUE THREAD

**Issue by MuNeNICK** [pallets/werkzeug#2464]
I developed an application with Flask and got the following error. 

```
File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 14, in <module>
from werkzeug. routing import parse rule
ImportError: cannot import name
"parse rule' from 'werkzeug.routing'(/usr/local/lib/python3.9/site-packages/werkzeug/routing/__init__.py)
```

However, when I downgraded the werkzeug version to 2.1.2, the error did not occur.

Environment:

- Python version:3.9
- Flask version:2.0.1 and 2.1.3
- Werkzeug version:2.2.0

**Comment by ThiefMaster** [comment]
`parse_rule` was marked as internal, and due to changes in 2.2 (most likely in https://github.com/pallets/werkzeug/pull/2433) it no longer exists as a global function.

PS: Did you type that error message manually? It does NOT look like something copy-pasted.

**Comment by bruntonspall** [comment]
It looks like the flask_login package was using parse_rule, it's just broken in a bit of my code as well.

This looks to have been opened here: https://github.com/maxcountryman/flask-login/issues/686 but since the import error is thrown from WerkZeug, people may come here first.

**Comment by bbnil** [comment]
also affects flask-restx
https://github.com/python-restx/flask-restx/issues/460
