### ISSUE TITLE
Werkzeug 2.2.0 tries to import Container from collections on Python 3.10 and fails with ImportError

### ISSUE THREAD

**Issue by dstromberg** [pallets/werkzeug#2475]
The tail end of the traceback looks like:
  File "/usr/local/lib/python3.10/site-packages/werkzeug/datastructures.py", line 16, in <module>
    from collections import Container, Iterable, MutableSet
ImportError: cannot import name 'Container' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

I believe this is why (for some meanings of "why") :
/usr/local/cpython-2.5/bin/python (2.5.6) bad  
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: cannot import name Container
/usr/local/cpython-2.6/bin/python (2.6.9) good 
/usr/local/cpython-2.7/bin/python (2.7.16) good 
/usr/local/cpython-3.0/bin/python (3.0.1) good 
/usr/local/cpython-3.1/bin/python (3.1.5) good 
/usr/local/cpython-3.2/bin/python (3.2.5) good 
/usr/local/cpython-3.3/bin/python (3.3.7) good 
/usr/local/cpython-3.4/bin/python (3.4.8) good 
/usr/local/cpython-3.5/bin/python (3.5.5) good 
/usr/local/cpython-3.6/bin/python (3.6.13) good 
/usr/local/cpython-3.7/bin/python (3.7.0) good -c:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
/usr/local/cpython-3.8/bin/python (3.8.0) good <string>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
/usr/local/cpython-3.9/bin/python (3.9.0) good <string>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
/usr/local/cpython-3.10/bin/python (3.10.0) bad  
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: cannot import name 'Container' from 'collections' (/usr/local/cpython-3.10/lib/python3.10/collections/__init__.py)

Thanks for the cool tool.

**Comment by davidism** [comment]
I can't reproduce the issue with the information provided. I can import `werkzeug.datastructures` from Werkzeug 2.2.0 installed in a fresh Python 3.10 virtualenv. Be sure to include a minimal reproducible example when reporting an issue.

```
$ python3.10 -m venv venv
$ . ./venv/bin/activate
(venv) $ pip install "Werkzeug==2.2.0"
(venv) $ python3.10 -W error
>>> from werkzeug.datastructures import MultiDict
# no error
```
