### ISSUE TITLE
branch rule cannot be matched to URL without trailing slash

### ISSUE THREAD

**Issue by standag** [pallets/werkzeug#2478]
Similar to this [bug](https://github.com/pallets/werkzeug/issues/2467), the new router cause incompatibility with the old version (2.1.2). For rules that contain a trailing slash (e.g. `/path6/`), the current version (2.2.x) returns NotFound for a URL that doesn't end with a trailing slash (e.g. `/path6`). 

In versions <=2.1.2, there was a possibility to define a branch rule for `/path6/`. This rule was successfully matched also for URL without the trailing slash "https://domain/path5" in case there wasn't the same leaf rule "/path6".

Updated test that failed:

```python
def test_strict_slashes_leaves_dont_consume():
    # See issue #1074
    map = r.Map(
        [
            r.Rule("/path6/", endpoint="branch"),
        ],
        strict_slashes=False,
    )

    adapter = map.bind("example.org", "/")

    assert adapter.match("/path6", method="GET") == ("branch", {}).  # stop work in versions 2.2.x
 ```

According to documentation, this probably isn't a use-case for switch `strict_slashes` but it breaks our code, maybe some mention in the changelog.

> Rules that end with a slash are “branches”, others are “leaves”. If strict_slashes is enabled (the default), visiting a branch URL without a trailing slash will redirect to the URL with a slash appended. [source](https://werkzeug.palletsprojects.com/en/2.2.x/routing/?highlight=strict_slashes#rule-format)

Environment:

- Python version: 3.9.13
- Werkzeug version: >2.2.0

**Comment by pgjones** [comment]
I think you are reporting #1074, although I think you desire the opposite behavior. Could you confirm if I've understood you correctly?

**Comment by davidism** [comment]
I am having a hard time understanding the issue you're reporting. Can you please update the title and code example to explain _exactly_ the behavior you expect? Most of the example seems irrelevant to what you're discussing.

**Comment by davidism** [comment]
I can't find the exact reference, but I'm pretty sure what you're trying to describe is, as you point out, not intended to be supported. I know something in the docs or a previous issue mentions that it would not be correct for a trailing slash to be appended, as it breaks something about good URL design.

**Comment by davidism** [comment]
Please reduce the code in your example to only demonstrate the exact issue you are having.

**Comment by davidism** [comment]
OK, I guess I'm not explaining this well. Write a minimal, reproducible example, showing the error you're getting and what you expect instead. `assert` on its own doesn't convey what's going on.

**Comment by pgjones** [comment]
I am a little confused as the snippet posted works exactly as the documentation you've quoted suggests. Do you consider this a bug? Or is the issue that the bug fix and change in behavior isn't clear from the changelog?

**Comment by standag** [comment]
I updated dependencies in our project and ran into problems with our internal services that cannot reach us because missing trailing slash. When I read the documentation, I didn't consider this as a bug but an undocumented fix of behavior.

> Do you consider this a bug?

No.

> Or is the issue that the bug fix and change in behavior isn't clear from the changelog?

Yes.

**Comment by pgjones** [comment]
See also #2479
