### ISSUE TITLE
The 2.2.x matcher no longer supports regexes that can match a slash.

### ISSUE THREAD

**Issue by bblommers** [pallets/werkzeug#2491]
With release 2.2.x, the matcher no longer supports regexes that can match a slash.

An example test case:

```
def test_regex_that_captures_multiple_slashes():
    map_ = r.Map(
        [
            r.Rule(r"/<regex('[^/:]+'):initial_part>/<regex('[^:]+'):remainder>", endpoint="regex"),
        ],
        converters={"regex": RegexConverter},
    )
    adapter = map_.bind("localhost")
    assert adapter.match("/asdfsa/sth") == ("regex", {'initial_part': 'asdfsa', 'remainder': 'sth'})
    assert adapter.match("/asdfsa/sth/qwer") == ("regex", {'initial_part': 'asdfsa', 'remainder': 'sth/qwer'})
    assert adapter.match("/asdfsa/sth/qwer/asdf") == ("regex", {'initial_part': 'asdfsa', 'remainder': 'sth/qwer/asdf'})
```

This behaviour was supported in earlier versions.

Note that, on main, the matcher currently hangs when matching against this regex - that bug is fixed with #2489.
Running this test against the branch that contains the fix results in a NoMatch() for the second and third assertions.

Environment:

- Python version: 3.x
- Werkzeug version: 2.2.x

**Comment by pgjones** [comment]
Is your regex converter marked as `part_isolating = False`?

**Comment by bblommers** [comment]
Thanks for the hint @pgjones - setting that attribute fixed it indeed.

**Comment by davidism** [comment]
Note that the `regex` converter is not provided by Werkzeug. You should report an issue to the library providing that converter. Also note that setting `part_isolating` opts out of the faster router implementation, so it should only be set if a converter actually needs to match `/`.
