### ISSUE TITLE
Werkzeug and http both add a Date header for files served statically.

### ISSUE THREAD

**Issue by andyDoucette** [pallets/werkzeug#2500]
I ran into some warnings from nginx that my Flask server was generating duplicate Date headers, so I investigated.

Here's how to reproduce the situation:

app.py
```
from flask import Flask

app = Flask(__name__)

@app.route("/hello")
def hello_world():
    return "Hello from a flask route!"
```

static/hello
```
Hello from static world.
```

`$flask run`

From another terminal run:
```
[root@vis cli]$ curl -v 'http://127.0.0.1:5000/hello'
*   Trying 127.0.0.1:5000...
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> GET /hello HTTP/1.1
> Host: 127.0.0.1:5000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: Werkzeug/2.2.2 Python/3.10.4
< Date: Wed, 10 Aug 2022 08:05:18 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 25
< Connection: close
< 
* Closing connection 0
Hello from a flask route!
[root@vis cli]$ curl -v 'http://127.0.0.1:5000/static/hello'
*   Trying 127.0.0.1:5000...
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> GET /static/hello HTTP/1.1
> Host: 127.0.0.1:5000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: Werkzeug/2.2.2 Python/3.10.4
< Date: Wed, 10 Aug 2022 08:05:22 GMT
< Content-Disposition: inline; filename=hello
< Content-Type: application/octet-stream
< Content-Length: 25
< Last-Modified: Wed, 10 Aug 2022 08:00:56 GMT
< Cache-Control: no-cache
< Date: Wed, 10 Aug 2022 08:05:22 GMT
< Connection: close
< 
Hello from static world.
* Closing connection 0
```

The -v turns on curl's verbose mode so that the request and response headers are printed.

Note how the headers of the static route have two Date fields, whereas the headers of the dynamic route only have one.

I dove into this some more and it seems that here's what is happening:

The http package always adds the date header, regardless of if it's a dynamic or static route.
/usr/lib/python3.10/http/server.py:493
`        self.send_header('Date', self.date_time_string())`

The werkzeug package adds it again for a static request:
/usr/local/lib/python3.10/dist-packages/werkzeug/wrappers/response.py:802
`                self.headers["Date"] = http_date()`

Obviously we should be doubling up on headers, right?  What do you believe is the best fix for this?

**Comment by andyDoucette** [comment]
Werkzeug==2.2.2

**Comment by davidism** [comment]
Don't use the development server in production. This isn't actually an error, and the fix would add a lot of complexity to the server handler.

**Comment by andyDoucette** [comment]
This is not the correct behavior!  Any server, wether it's a develop;ment
server or production server, should be correct.  I'm not sure that making
sure there's only one copy of each header is "a lot of complexity".
Deduping things in python is usually a one-liner.  Can you explain why it's
a difficult thing to fix?  Even if it was difficult, are you really going
to accept not doing the right thing just so you can close out a ticket?  At
least leave it open and invite people to make pull requests if it bothers
them too.  Heck, I'd be happy to try and fix it if I had a sense that the
fix would be merged.

**Comment by ThiefMaster** [comment]
AFAIK some HTTP headers MAY occur more than once. So it's not as simple as deduplicating ALL headers...

**Comment by andyDoucette** [comment]
Since it's an extra header, it seems possible that fixing this problem might actually make the code simpler (for example if there's always 1-2 Date headers, taking out the extra one could make it 1 all the time by DELETING code.)  What am I missing?

**Comment by andyDoucette** [comment]
Ok, but maybe just checking to see if it's there before adding it?  Or if we're confident that in a given case there's always a duplicatoin just not adding it the second time in that case?

**Comment by andyDoucette** [comment]
All of these are between -1 to +2 lines of code.  Not "a lot of complexity.'

**Comment by davidism** [comment]
Report to Python that their http.server should not set the Date header if one is already set. We're a simple wrapper around that.

**Comment by andyDoucette** [comment]
Or, what's the point of setting the Date header if http will take care of it for us?
