### ISSUE TITLE
Support for K8S Ingress Header `X-Original-Forwarded-For`

### ISSUE THREAD

**Issue by lovexuan** [pallets/werkzeug#2501]
Let's say there is a network topology: Client (IP: 1.2.3.4) -> Nginx Reverse Proxy(IP: 5.6.7.8) -> K8S Ingress -> K8S Service -> Flask Pods

Nginx Reverse Proxy will set `X-Forwarded-For: 1.2.3.4`, it's fine. But when request arrival K8S Ingress, it will set `X-Original-Forwarded-For: 1.2.3.4`, then set `X-Forwarded-For: 5.6.7.8`. Just paste a related issue at ingress-nginx: [X-FORWARDED-FOR and X-ORIGINAL-FORWARDED-FOR](https://github.com/kubernetes/ingress-nginx/issues/5970)

For me, I just write a custom function to solve it, but I think it should be resolved at werkzeug level, just simple check `X-Original-Forwarded-For` at `Request.access_route`, such as:

```
    @cached_property
    def access_route(self) -> t.List[str]:
        """If a forwarded header exists this is a list of all ip addresses
        from the client ip to the last proxy server.
        """
        if "X-Original-Forwarded-For" in self.headers:
            # Maybe we should also combine X-Original-Forwarded-For and X-Forwarded-For
            return self.list_storage_class(
                parse_list_header(self.headers["X-Original-Forwarded-For"])
            )
        if "X-Forwarded-For" in self.headers:
            return self.list_storage_class(
                parse_list_header(self.headers["X-Forwarded-For"])
            )
        elif self.remote_addr is not None:
            return self.list_storage_class([self.remote_addr])
        return self.list_storage_class()
```

For now, I can't think of any harm if we doing so. What's your idea?

**Comment by RonnyPfannschmidt** [comment]
Typically the place for this is middleware which is configured for deployment

Else insufficiency protected apps will put malicious headers into consideration
