### ISSUE TITLE
NotFound exception should be imported in routing/__init__.py

### ISSUE THREAD

**Issue by ankush** [pallets/werkzeug#2502]
`from werkzeug.routing import NotFound` fails after https://github.com/pallets/werkzeug/pull/2433

There's a simple fix:

``` diff
- from werkzeug.routing import NotFound
+ from werkzeug.exceptions import NotFound
```

But in the spirit of https://github.com/pallets/werkzeug/pull/2446 `NotFound` should also be added to `routing/__init__.py` ?

**Comment by pgjones** [comment]
No, it is not part of the routing but rather an exception.
