### ISSUE TITLE
Hide Server Version on Werkzeug

### ISSUE THREAD

**Issue by vinayhegde-drip** [pallets/werkzeug#2507]
**Environment:**
- Python version: 3.10.6
- Werkzeug version: 2.2.2

Hi team, running the above Werkzeug version that I wanted to hide similar to setting `server_tokens off` [for NGinx](https://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens). Below is a sample code snippet having the Werkzeug output

```ruby
vinayhegde ~ $ curl -v localhost:5001/ping
*   Trying 127.0.0.1:5001...
* Connected to localhost (127.0.0.1) port 5001 (#0)
> GET /ping HTTP/1.1
> Host: localhost:5001
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: Werkzeug/2.2.2 Python/3.10.6
< Date: Thu, 08 Sep 2022 11:54:34 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 2
< Connection: close
<
* Closing connection 0
Ok
```

Found an [equivalent Superset page](https://stackoverflow.com/questions/62995414/how-to-hide-server-software-version-werkzeug-python-from-superset-response-h) but none so for the **Werkzeug** app itself. Searching [Werkzeug's Stackoverflow](https://stackoverflow.com/search?q=%5Bwerkzeug%5D+server+version) didn't help either

Could you kindly help how to hide this?

**Comment by davidism** [comment]
I don't plan to add this. There's no reason to hide it, the development server is only for development, not production, so there should be no issue with showing it.

**Comment by vinayhegde-drip** [comment]
_> I don't plan to add this. There's no reason to hide it, the development server is only for development, not production, so there should be no issue with showing it._

ok in that case, what could be a workaround to continue using Werkzeug for production?

**Comment by davidism** [comment]
Werkzeug is fine to use anywhere. It's the development server that should not be deployed in production. https://werkzeug.palletsprojects.com/en/2.2.x/deployment/
