### ISSUE TITLE
Reopen 2430: performance issue for some data handling in MultipartDecoder

### ISSUE THREAD

**Issue by zhangchunlin** [pallets/werkzeug#2511]
Detail please check issue #2430

I generate a 100 MBytes file with script in #2430, the test data of upload time:
- werkzeug 2.2.2: 33s
- werkzeug 2.0.2: 31s
So it is even a little worse after the change.

Environment:

- Python version:Python 3.9.7
- Werkzeug version:2.2.2

**Comment by davidism** [comment]
Please make a new issue with appropriate detail, don't use a link with no new information and an non-descriptive title.

Without any more information, there's nothing to do. We already believe we've fixed it. You're welcome to make a PR if this is something that is important to you.

**Comment by zhangchunlin** [comment]
Submitted issue #2512 as your requirement.
