### ISSUE TITLE
`test_exclude_patterns` fails when run tests without installing it

### ISSUE THREAD

**Issue by catap** [pallets/werkzeug#2516]
Let assume that I have a working copy of werkzeug in `/opt/local/var/macports/build/_Users_catap_src_macports-ports_python_py-werkzeug/py38-werkzeug/work/Werkzeug-2.2.` which is kind of default path to build it under MacPorts.

When I run `py.test-3.8 -o addopts="-m 'not dev_server'"` it fails on `test_exclude_patterns` because `sys.prefix` is `/opt/local/Library/Frameworks/Python.framework/Versions/3.8` and `find(set(), set())` returns a set which contains tons of path which starts from `/opt/local/var/macports/build/...`

**Comment by davidism** [comment]
The only supported way to run the tests is installed in a virtualenv. Use `tox -e py` to run the tests.
