### ISSUE TITLE
Custom NumberConverter no longer worked as expect after 2.2.0

### ISSUE THREAD

**Issue by ringsaturn** [pallets/werkzeug#2518]
Same codes work well under 2.1.2 but fail under >=2.2.0. I create a repo to run diff version test cases: https://github.com/ringsaturn/werkzeug-converts-debug

Minimal sample:

`test_converts.py`

```py
from unittest import TestCase, main

from werkzeug import routing as r


class TestConverts(TestCase):

    def test_custom_converts(self):
        try:
            from werkzeug.routing.converters import NumberConverter
        except:
            from werkzeug.routing import NumberConverter

        class FloatConverter(NumberConverter):
            """FloatConverter.
            Copy from werkzeug and replace regex.
            """

            regex = r"-?\d+(\.\d+)?"
            num_convert = float
            part_isolating = True

            def __init__(
                self,
                map,
                min=None,
                max=None,
                signed: bool = False,
            ) -> None:
                super().__init__(map, min=min, max=max, signed=signed)  # type: ignore

        map = r.Map(
            [
                r.Rule(
                    "/foo-lnglat/<float(signed=True):lng>,<float(signed=True):lat>",
                    endpoint="foo-lnglat",
                ),
            ],
            converters={"float": FloatConverter},
        )

        adapter = map.bind("example.co", "/")

        assert adapter.match("/foo-lnglat/116.12,39.34") == (
            "foo-lnglat",
            {"lng": 116.12, "lat": 39.34},
        )


if __name__ == "__main__":
    main()
```

The test case passed under 2.1.2, failed under 2.2.0

Failed output:

```
>       assert adapter.match("/foo-lnglat/116.12,39.34") == (
            "foo-lnglat",
            {"lng": 116.12, "lat": 39.34},
        )
E       AssertionError: assert ('foo-lnglat'...lng': 116.12}) == ('foo-lnglat'...lng': 116.12})
E         At index 1 diff: {'lng': 116.12, 'lat': 0.12} != {'lng': 116.12, 'lat': 39.34}
E         Use -v to get more diff
```

Seems similar with #2510 

Environment:

- Python version: 3.8.14
- Werkzeug version: 2.1.2, >=2.2.0

**Comment by davidism** [comment]
Please include a minimal reproducible example in the issue itself, not as a separate link.

**Comment by ringsaturn** [comment]
> Please include a minimal reproducible example in the issue itself, not as a separate link.

I have update issue with a simple test case.

**Comment by davidism** [comment]
What's custom about your converter?

**Comment by ringsaturn** [comment]
The same converter could parse `116.12,39.34` to `{'lng': 116.12, 'lat': 39.34}`, but failed under 2.2.0 which return `{'lng': 116.12, 'lat': 0.12}`.

The custom converter is just a copy cat from https://stackoverflow.com/a/20640550 without any further changed.

**Comment by davidism** [comment]
You need to _tell_ me what's actually different, not just say "compare it to this code somewhere else." When you report an issue, be sure to give as much detail as possible _in the issue_.

**Comment by ringsaturn** [comment]
> You need to _tell_ me what's actually different, not just say "compare it to this code somewhere else." When you report an issue, be sure to give as much detail as possible _in the issue_.

The "actually differen" is the second param `lat` which should be `39.34` and now is output as `0.12`.

**Comment by davidism** [comment]
Not about the result, about the code.

**Comment by davidism** [comment]
Use a non-capturing group by adding `?:` to the start of the decimal matching part:

```regex
-?\d+(?:\.\d+)?
```
