### ISSUE TITLE
send_file's Content-Disposition filename* is ignored in Chrome and Safari, when download_name is unicode with a brace

### ISSUE THREAD

**Issue by vasa-chi** [pallets/werkzeug#2529]
My test code looks like this:

```python
@app.get('/file')
def return_file():
    return send_file(BytesIO(b"test"), download_name="(тест.txt")
```

Notice the `(` in `download_name`. Currently response headers look like this:
```
Content-Disposition: attachment; filename="("; filename*="UTF-8''(%D1%82%D0%B5%D1%81%D1%82"
```

Firefox uses `filename*` and downloads file with intended name (`(тест.txt`). Both Chrome (106.0.5249.103) and macOS Safari (16.0 (17614.1.25.9.10, 17614)) download files with name `(`.

Both opening and closing braces in download_name cause this behaviour.

Environment:

- Python version: 3.9
- Flask version: 2.2.2

**Comment by runderwood** [comment]
This appears to be owing to the way Werkzeug's header construction code [quotes options in headers](https://github.com/pallets/werkzeug/blob/a3005e6acda7246fe0a684c71921bf4882b4ba1c/src/werkzeug/http.py#L193).

This is the behavior now with the filename above ("(тест.txt")::

```
Content-Disposition: attachment; filename="(.txt"; filename*="UTF-8''(%D1%82%D0%B5%D1%81%D1%82.txt"
```

But without the quotes, as below, the downloads work in Firefox and Chrome:

```
Content-Disposition: attachment; filename="(.txt"; filename*=UTF-8''(%D1%82%D0%B5%D1%81%D1%82.txt
```

It looks like Firefox allows the double quotes around the encoded filename option in the `Content-Disposition` header. But other browsers handle this differently.

Reading over [RFC 5987](https://datatracker.ietf.org/doc/html/rfc8187#section-3.2.1), there's no mention of quoting these values. Maybe this has been interpreted by some to mean the value for `filename` attributes ought to not be quoted? 

Firefox and Chrome both work fine **without the quotes**. 

Currently, Werkzeug adds [double quotes in `quote_header_value`](https://github.com/pallets/werkzeug/blob/a3005e6acda7246fe0a684c71921bf4882b4ba1c/src/werkzeug/http.py#L213) in [`http.py`](https://github.com/pallets/werkzeug/blob/a3005e6acda7246fe0a684c71921bf4882b4ba1c/src/werkzeug/http.py) without making any distinctions regarding which header is being constructed.

**Comment by davidism** [comment]
Report this bug to Chromium. Header option values can be enclosed in quotes.

**Comment by runderwood** [comment]
I don't know that it's that straightforward. The [RFC](https://datatracker.ietf.org/doc/html/rfc5987#section-3.2) doesn't show quotes in `ext-parameter` in the definition (and the succeeding document doesn't seem to override it). But maybe I'm misreading it (though it would explain why implementations vary across browsers).

I think it could theoretically be handled reasonably well based on the `Content-Disposition` header name. Annoying, but possibly more conformant (depending on the reading of the RFC).

**Comment by davidism** [comment]
You'd presumably look at the earlier RFC that defines options in general and shows that quotes are accepted.

**Comment by runderwood** [comment]
The grammar extends the `parameter` element to allow `ext-value` as well as `value`. The latter permits `token` or `quoted-string`. But `ext-value` does not include `quoted-string`:

```
ext-value = charset  "'" [ language ] "'" value-chars
```

There's no mention of quotes. This is to be set against the plain `value` defnition:

```
value = token / quoted-string
``` 

It seems plausible to me that this might be interpreted to indicate extended parameters such as those we're interested here are **not** to be quoted.

It would require a lot of testing to make sure a change to extended parameter handling improves things rather than creates problems. But, for what it's worth, my initial tests showed that non-quoted extended parameters work with **more** browsers, not fewer.

I guess I could look at the browser parser implementations to confirm. But if it's something folks don't think worth delving into at the moment, I'll step back.

**Comment by davidism** [comment]
Thanks for looking into the RFCs, it's not easy :sweat_smile: Happy to review a PR.

**Comment by pgjones** [comment]
Fixed by https://github.com/pallets/werkzeug/commit/97547cc6825e7bfdc9c08b9a99b21d979b891602
