### ISSUE TITLE
Werkzeug hangs when using ssl_context while decoding the https request

### ISSUE THREAD

**Issue by Ircama** [pallets/werkzeug#2530]
Same issue as [here](https://github.com/pallets/flask/issues/4841).

Simplest sample program:

```python
from werkzeug import run_simple, Request, Response
import socket
import sys

if len(sys.argv) == 2 and sys.argv[1].isnumeric():
    socket.setdefaulttimeout(int(sys.argv[1]))

@Request.application
def application(request):
    return Response("Hello World!")

run_simple('0.0.0.0', 5001, application, ssl_context="adhoc")
```

Attack client:

```python
from telnetlib import Telnet

hostname = '...'
port = 5001

while True:
    try:
        with Telnet(hostname, port) as tn:
            tn.read_some()
    except Exception:
        pass
```

Test steps:

- Run the test Werkzeug program (without arguments)
- Run the attack program concurrently
- Test the web server with a browser (https://...:5001): the request hangs
- If, e.g., 5 is used as an argument to the Werkzeug program, each request might be processed after 5 seconds

Environment:

- Python version: 3.10.6
- Werkzeug version: 2.2.2

**Comment by davidism** [comment]
I can't reproduce this issue. The browser does not hang. The telnet code hangs because `read_some` blocks if no data is available, and you haven't sent a request first.
