### ISSUE TITLE
There is no Host header validation according to RFC 1034/1035

### ISSUE THREAD

**Issue by bbangjooo** [pallets/werkzeug#2540]
For now, `get_host` in [sansio/utils.py](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/sansio/utils.py#L56) has only `trusted_hosts` validation which throws SecurityError when host value is not in the given trusted host list. I think not only this validation, but also host value itself validation is required according to [RFC 1034](https://www.rfc-editor.org/rfc/rfc1035.html) like:
```python
def get_host(
    scheme: str,
    host_header: t.Optional[str],
    server: t.Optional[t.Tuple[str, t.Optional[int]]] = None,
    trusted_hosts: t.Optional[t.Iterable[str]] = None,
) -> str:
   
    host_validation_re = re.compile(r"^([a-z0-9.-]+|\[[a-f0-9]*:[a-f0-9\.:]+\])(:[0-9]+)?$") # New
    ...
    
    if host_validation_re.match(host) is None: # New
        raise SecurityError(f"Host {host!r} is not valid according to RFC 1034/1035") # New

    if trusted_hosts is not None:
        if not host_is_trusted(host, trusted_hosts):
            raise SecurityError(f"Host {host!r} is not trusted.")
    return host
```

**Comment by pgjones** [comment]
I'm not sure if this is a framework or server responsibility. Looks as if Django doesn't do this validation, https://github.com/django/django/blob/6220c445c40a6a7f4d442de8bde2628346153963/django/http/request.py#L143.

**Comment by davidism** [comment]
Yeah, I'm not sure this makes sense here. Also, I'm uncomfortable adding a new regex with because there are performance implications.

**Comment by bbangjooo** [comment]
@pgjones  Thanks for opinion. I found that Django has that validation in `split_domain_port` function which is used in `get_host`. Please see here:
[](https://github.com/django/django/blob/6220c445c40a6a7f4d442de8bde2628346153963/django/http/request.py#L684).
@davidism That's good point. I think that Django implement their host validation logic by using `_lazy_regex_compile`. Please see here:
[](https://github.com/django/django/blob/6220c445c40a6a7f4d442de8bde2628346153963/django/utils/regex_helper.py#L342
)

**Comment by davidism** [comment]
I'm referring to the safety of the regex, not its compilation.

**Comment by bbangjooo** [comment]
I agree with you. I forgot that there are weird domains which are not caught easily by regex, such as IDN.

**Comment by davidism** [comment]
Looking at the referenced RFCs 1034 and 1035, I don't see any mention of validation. Additionally, these RFCs don't appear to be part of the HTTP spec. RFC 9110 (HTTP) does not mention validation either, although it does mention checking if it is trusted.
