### ISSUE TITLE
EnumConverter

### ISSUE THREAD

**Issue by TrilceAC** [pallets/werkzeug#2547]
Hi,

In a project that I am working on, I found convenient to create a converter for Enums like those defined at `werkzeug/routing/converters.py`. This converter allows to convert back and forth between enum values and url parameters by means of the enum names. I find this convenient to save some parsing and just getting valid and validated values from urls, and standard url generation from variables bind to an enum value.

`EnumConverter` is somehow an `AnyConverter` and in fact, I have implemented inheriting from `AnyConverter`.

## Example using Flask

Suppose that I have the following enum:

```python
class TriggerType(enum.Flag):
    """Represent a Trigger."""

    TBP = enum.auto()
    TAP = enum.auto()
    TAV = enum.auto()
    PH = enum.auto()
    ALL = TBP | TAP | TAV | PH

```

And I want a route with one of its parameters being the value of the enum. Something like:

```python
@bp.route('/count/<trigger>')
def count(trigger):
    pass
```

With current converters one could use the `AnyConverter`, explicitly listing all possible values. One also has to handle the given URL parameter to get the proper type:

```python
@bp.route('/count/<any(TBP, TAP, TAV, ALL):trigger_name>')
def count(trigger_name):
    trigger = getattr(TriggerType, trigger_name)
    pass
```

and of course, when the URL is rendered, the enum value has to be converted to the proper string:

```python
url_for('.count', trigger_name=TriggerType.TAP.name)
```

With `EnumConverter` that I have implemented this can be done automatically in both directions.

```python
@bp.route('/count/<enum(my.enum.module, TriggerType):trigger>')
def count(trigger, filename):
    pass
```

```python
url_for('.count', trigger=TriggerType.TAP)
```

If the maintainers find interesting this converter, we can discuss some details and I can prepare pull request.

**Comment by davidism** [comment]
I don't think I want to add this to Werkzeug, there's too many opinions to deal with.

* Does the the URL have the name or the value of the member, or either? If either can match, which is used when building? What if one member's name is the same as another's value, which order are they matched?
* URLs usually look cleaner as lowercase, but member names are usually uppercase. Should only uppercase be generated, but both cases be accepted? What if there's mixed case in the name?
* When generating the URL, should it accept a name or a member, or both? Using enum members would be annoying in templates, you'd need to inject every enum you might use into every template context.

An specific implementation isn't particularly complicated, and it's intended that projects will write converters specific to their needs.

```python
from werkzeug.routing import BaseConverter, ValidationError
from pkgutil import resolve_name

class EnumConverter(BaseConverter):
    def __init__(self, map: Map, name: str) -> None:
        super().__init__(map)
        self.enum = resolve_name(name)

    def to_python(self, value: str) -> t.Any:
        try:
            return self.enum[value]  # match on names
            # use self.enum(value) to match on values instead
        except KeyError as e:
            raise ValidationError from e

    def to_url(self, value: t.Any) -> str:
        if isinstance(value, self.enum):
            return value.name
        
        return self.enum[value].name
```

**Comment by ThiefMaster** [comment]
Another point for the "too many opinions": In URLs you usually want dashes, but enum members are underscores. Should those be replaced or not?
