### ISSUE TITLE
Watchdog reloader - CPU usage during idle

### ISSUE THREAD

**Issue by martinsvoboda** [pallets/werkzeug#2548]
WatchdogReloader traversing paths everytime reload interval elapsed (default 1s). I can't test it on different platforms, but on Apple Silicon with Docker this cause significant CPU usage during idle (in my project 5% according to docker stats)

https://github.com/pallets/werkzeug/blob/3115aa6a6276939f5fd6efa46282e0256ff21f1a/src/werkzeug/_reloader.py#L353-L358

However, I think this behaviour doesn't make sense. Registration process should be done only once and then reloader should wait for watchdog events. After moving self.run_step() before the loop, cpu usage drops almost to zero and reloading working as expected.

Environment:

- Python version: 3.9.8
- Werkzeug version: 2.2.2

**Comment by davidism** [comment]
I think this is trying to account for changes to `sys.path` or new imports. However, as far as I can tell it would be really hard to accomplish that without intersecting with already watched paths, and it doesn't particularly make sense to modify `sys.path` from within the app anyway. I'll move it and see if anyone reports that the reloader missed something.

**Comment by davidism** [comment]
Although, I don't see the same rise in CPU use that you do, my example app sits at 0%, with a bump to 0.7% every 10 seconds or so.

**Comment by martinsvoboda** [comment]
I don't know your test environment. Probably it can be more significant when combining Docker on Apple Sillicon if the code is shared using bind mount.
