### ISSUE TITLE
Multipart/form-data custom headers overwritten in pytest environment

### ISSUE THREAD

**Issue by errogtr** [pallets/werkzeug#2549]
### Description

When sending a multipart/form-data requests with custom headers, these are completely overwritten by default values when running tests using `pytest`. By _custom header_ I mean any additional field present in a single part request, so that the payload is  formatted as
```
...
----------------------BOUNDARY
Content-Disposition: form-data; name="<name>"; filename="<filename>"
<custom_header_key>: <custom_header_value>

content
----------------------BOUNDARY 
...
```

If a request is sent to a running Flask app the headers are correctly caught inside `Flask.request.files` and everything works fine. However, if a Flask test client is used, the additional headers are lost during the request. 

### Minimal working example

A working example of this issue can be found [in this repository](https://github.com/errogtr/multipart_test) - please refer to the README file for a more detailed description.

### Fix proposal
I was actually able to isolate the problem to [this line](https://github.com/pallets/werkzeug/blob/3115aa6a6276939f5fd6efa46282e0256ff21f1a/src/werkzeug/test.py#L110) in the `werkzeug/test.py` module. I think that a possibile fix may be substituting the aforementioned line with something like

```
headers = value.headers
headers.update([("Content-Type", content_type)])
```

and I verified that this solve my issue and does not break the anything in the test suite of this project.

### Environment:

- Python version: 3.9
- Werkzeug version: 2.2.2

**Comment by pgjones** [comment]
Fixed by #2554
