### ISSUE TITLE
Etymology on https://werkzeug.palletsprojects.com/en/2.2.x/

### ISSUE THREAD

**Issue by qyanu** [pallets/werkzeug#2555]
Hi,

you *do* know, that "zeug" is actually an old german word (dropped out of use, only remained as part of some compound words) for "Ausrüstung" and thus the translation "zeug=>stuff" presented on the webpage is kind of non-correct?

"zeug => equipment" would be more correct.

For example, there is also the word "Zeughaus" which, is *not* a hous full of arbitrary items (*stuff*), but distinctly specifies a house full of (military) *equiment*.

cheers,
Max

**Comment by aenglander** [comment]
Closing
