### ISSUE TITLE
LimitedStream not respecting `read` contract of RawIOBase.

### ISSUE THREAD

**Issue by thrau** [pallets/werkzeug#2558]
In the `read` implementation of `LimitedStream`, `self._read` refers to a read method of an underlying RawIOBase stream, and is called here:
https://github.com/pallets/werkzeug/blob/3115aa6a6276939f5fd6efa46282e0256ff21f1a/src/werkzeug/wsgi.py#L957-L963

[According to the contract of RawIOBase](https://docs.python.org/3/library/io.html#io.RawIOBase.read), `read` can return fewer bytes than passed in the `size` argument:
>  Fewer than size bytes may be returned if the operating system call returns fewer than size bytes.

This does not however mean that the underlying stream won't return more bytes when read is called again (size is an upper bound). Raising an error on the condition in line 962`if to_read and len(read) != to_read` breaks the contract of IO.read.

To add some context: This is a pretty significant problem for our [server implementation in LocalStack](https://github.com/localstack/localstack/blob/1b92e61427f15306f32348bc2da6a29314e708fa/localstack/http/asgi.py#L113-L117) that builds on Hypercorn, where we expose an `ASGIReceiveCallable` as a readable stream and plug it into Werkzeug. Our stream behaves according to `IO.read`, but Werkzeug will raise unexpected `ClientDisconnect` errors, even though there is still data in the stream.

It seems that the condition could be safely removed, or at least weakened to `if to_read and not len(read)`, which would indicate an unexpected EOF.

Environment:

- Python version: 3.10
- Werkzeug version: 2.2.2, but the code has been affected for a while: https://github.com/pallets/werkzeug/commit/b677ecc9e089a2251f800d9ff26548eb3040d884

**Comment by davidism** [comment]
Fixed more thoroughly by #2620
