### ISSUE TITLE
reloader exlude_patterns behavior differs for WatchdogReloaderLoop and StatReloaderLoop

### ISSUE THREAD

**Issue by robnagler** [pallets/werkzeug#2561]
Setting `exclude_patterns` to an absolute path, e.g. `/home/me/bar/*`, works fine with StatReloaderLoop, and fails to exclude paths with WatchdogReloaderLoop. The root cause is that WatchdogReloaderLoop uses `watchdog` which relies on `pathlib.PurePath.match` and StatReloaderLoop relies on `fnmatch.  Here's a simple demonstration:

```py
import fnmatch
assert fnmatch.fnmatch("/foo/bar/baz", "/foo/*")

import pathlib
assert pathlib.PurePosixPath("/foo/bar/baz").match("/foo/*"), "FAIL"
```

Pathlib's behavior is too strict for this particularly problem, since it matches from the right for relative paths and exact matches for absolute paths. fnmatch finds first match from the left.

The workaround is to disable the watchdog by passing `reloader_type="stat"` to `run_simple`. 

Environment:

- Python version: 3.7.2
- Werkzeug version: 2.0.3

**Comment by davidism** [comment]
This sounds like a bug report for Watchdog, not Werkzeug.

**Comment by robnagler** [comment]
You want to at least document the problem. It was tricky to track down.
