### ISSUE TITLE
send_file should support range request with io.BufferedReader

### ISSUE THREAD

**Issue by kwismann** [pallets/werkzeug#2566]
When using send_file, passing an open file path as io.BufferedReader, range headers are not supported.
Do you see this as a possible feature?
 
Using below code, will show Range request in the http header is ignored:
```
file = open(filename, "rb")
return send_file(file, download_name=filename, as_attachment=True)
```
This is due to the below code.
https://github.com/pallets/werkzeug/blob/3115aa6a6276939f5fd6efa46282e0256ff21f1a/src/werkzeug/utils.py#L428-L444

When size is not set (line 441) the following line 504, rv.content_length, is skipped and range is not reported back to the browser as being supported and the complete file is send
https://github.com/pallets/werkzeug/blob/3115aa6a6276939f5fd6efa46282e0256ff21f1a/src/werkzeug/utils.py#L503-L504

My suggestion would be to add something like this:
```
        stat = os.stat(path)
        size = stat.st_size
        mtime = stat.st_mtime
    else:
        file = path_or_file
        stat = os.fstat(file.fileno())
        size = stat.st_size
        mtime = stat.st_mtime
```
I have done some testing with above code and it seems to work fine.
NB! This is obviously not a complete test and the added code would need to be refactored properly into utils.py.

Environment:

- Python version: 3.8.10
- Werkzeug version: 2.1.2

**Comment by kwismann** [comment]
Actually there is a more elegant solution to this and as far as I can see with no impact on the rest of the codebase.
https://github.com/pallets/werkzeug/blob/main/src/werkzeug/utils.py#L492-L493
If you add this, it is fixed with only very few lines:

```
        elif isinstance(file, io.BytesIO):
            size = file.getbuffer().nbytes
        elif isinstance(file, io.BufferedIOBase):
            stat = os.fstat(file.fileno())
            size = stat.st_size
```

**Comment by davidism** [comment]
`BufferedIOBase` isn't guaranteed to represent a file on disk, so you can't rely on `fileno` or `stat` working. The docs already discuss why:

> The first argument can be a file path or a file-like object. Paths are preferred in most cases because Werkzeug can manage the file and get extra information from the path. Passing a file-like object requires that the file is opened in binary mode, and is mostly useful when building a file in memory with `io.BytesIO`.
