### ISSUE TITLE
Further explanation about license using

### ISSUE THREAD

**Issue by Ashley123456789** [pallets/werkzeug#2569]
When I **import** werkzeug as a third-party dependency, 

- Should I comply with the LICENSE.rst (i.e., BSD 3-Clause)? Is the **import** action considered as **Redistribution and use** in the LICENSE.rst text?
- Do I need to pay attention to **license compatibility**, i.e., can I claim a  **less strict license** than BSD 3-Clause for my projects?

**Comment by ThiefMaster** [comment]
IANAL but the clauses in the license are not relevant for regular end users who just import and use Werkzeug. It's not a viral license like GPL.
