### ISSUE TITLE
Running the development server in the background with the reloader enabled stops the process

### ISSUE THREAD

**Issue by noah-weingarden** [pallets/werkzeug#2571]
Running the development server with a Flask application as a background process causes the process to be immediately stopped, but only when using the reloader. Without the reloader, the process runs normally in the background.

To replicate, create a Flask app and run it either with `werkzeug.serving.run_simple`, `Flask.Flask.run`, or the Flask CLI. Pass `use_reloader=True` if using the first option or enable debug mode if using either of the others. For example:

```python
from flask import Flask
from werkzeug.serving import run_simple

app = Flask(__name__)

@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"

if __name__ == "__main__":
    run_simple("localhost", 8000, app, use_reloader=True)
```

Run the module in the background:

```console
python test.py &
```

Press enter, and see:

```console
[1]+  Stopped                 python test.py
```

Using `bg` afterward has no effect:

```console
$ bg %1
[1]+ python test.py &

[1]+  Stopped                 python test.py
```

If `use_reloader` is instead set to `False`, then `python test.py &` works correctly, with the process running in the background and no stop signal.

I believe this behavior is a result of `werkzeug._reloader.ensure_echo_on`. This function sets the terminal to echo mode if it's currently disabled, which it is if the process is running in the background. Doing this triggers a `SIGTTOU` signal, which stops the process.

I don't think that the reloader ought to make a difference concerning whether or not it's possible to run the development server as a background process. Even redirecting stdout doesn't avoid the problem; only redirecting stdin does, since that causes `ensure_echo_on` to return early.

I understand that `ensure_echo_on` was added to handle a bug where code reloading during a PDB session breaks terminal input (see #1317/#1318), so I don't necessarily suggest removing that function. Can we just ignore `SIGTTOU` from inside of it? (I'll make a PR for that preemptively since it's such a simple change.) 

Environment:

- Python version: 3.10
- Werkzeug version: 2.2.2
- OS: Ubuntu 22.04

**Comment by davidism** [comment]
The development server is meant for development, not production. Running a process in the background sounds like something you'd do in production. I'm fine with that not working, especially with the reloader which _definitely_ shouldn't be run in production.

**Comment by noah-weingarden** [comment]
My use case is that I wish to run end-to-end tests with a testing framework that depends on the server already running, [Cypress](https://www.cypress.io/). It's convenient to have the server running in the background in this context, and it certainly makes sense to use a development server. I also can't think of any disadvantage to ignoring `SIGTTOU` during the specific system call that triggers it.

**Comment by davidism** [comment]
You shouldn't run the reloader during tests, you should be testing a fixed version of the code.

**Comment by noah-weingarden** [comment]
Why? What if I find that, for example, my front-end code makes an API request that triggers an internal server error, and I want to make a change to the server followed by running the test again without having to manually restart the server?

**Comment by davidism** [comment]
Have your test process manage running the app, stopping it when the tests end, and then it requires no manual background process.

**Comment by noah-weingarden** [comment]
That's reasonable, but it seems to me like a matter of personal preference. I can think of other cases where it might be helpful to run the development server as a background process, like if you're using microservices, where one Flask app is a REST API and another is a front-end server. Some people might like to run the REST API in the background while running the front-end server in the foreground. In that case, you'd still want to have the reloader in order to debug issues with the REST API.

**Comment by davidism** [comment]
If they're only developing the frontend, then why would the backend reload? And if it's a background task, how would they see logs about any errors in the backend, to know to fix them and then trigger a reload?

I'm not particularly convinced by the reasons presented here, so I don't plan to make backgrounding the dev server with the reloader a feature at this time.

**Comment by noah-weingarden** [comment]
> If they're only developing the frontend, then why would the backend reload?

They could discover an issue with the backend while working on the frontend, and then modify the backend accordingly.

> And if it's a background task, how would they see logs about any errors in the backend, to know to fix them and then trigger a reload?

By logging to a file.

> I don't plan to make backgrounding the dev server with the reloader a feature at this time.

Just to be clear, have you looked at #2572 yet? It's an extremely simple fix and there doesn't seem to be any disadvantage to merging it from what I can tell.

**Comment by davidism** [comment]
The disadvantage is that it enables backgrounding the dev server reloader, which as I've stated in multiple ways now isn't a good idea. Technical reasons aren't the only reasons to approve or reject PRs. I'm sorry, it's hard to hear "no" to a feature request, but no.

**Comment by noah-weingarden** [comment]
I don't consider this a feature request: I consider it a bugfix. There's nothing in the documentation that suggests running the development server in the background should be impossible, and I really think it's a common practice, even in development. Django clearly agrees with me, at least. That said, I respect your decision, and thank you for all your work in maintaining these great projects.
