### ISSUE TITLE
Tutorial unclear - what is reversing?

### ISSUE THREAD

**Issue by mdavis-xyz** [pallets/werkzeug#2576]
I was following [the tutorial](https://werkzeug.palletsprojects.com/en/2.2.x/tutorial/). There are a few mentions of "reversing" a URL.

> We could also use this to automatically reverse the URL, but that’s not what we will do in this tutorial.

I don't understand what this means.

It sounds like it's talking about taking the URL string, and reversing it.

```
>>> url = 'https://github.com'
>>> url[::-1]
'moc.buhtig//:sptth'
```

I don't see the point of that. So I don't think that's it.

Is it saying that you could use a `Rule` for each submitted URL to redirect the `short_id` to the long URL, instead of doing the redis lookup? If so, perhaps `reverse` is not the clearest word. Can we say `lookup` or `redirect`?

Then later on it says:

> We bind the URL map to the current environment and get back a `URLAdapter`.

Do we get a `URLAdapter`?
When I [search the docs for `URLAdapter`](https://werkzeug.palletsprojects.com/en/2.2.x/search/?q=URLAdapter), the only result is the tutorial.
[The docs for `bind_to_environ`](https://werkzeug.palletsprojects.com/en/2.2.x/routing/#werkzeug.routing.Map.bind_to_environ) say it returns a [`MapAdapter`](https://werkzeug.palletsprojects.com/en/2.2.x/routing/#werkzeug.routing.MapAdapter).

**Comment by davidism** [comment]
Matching and building are the reverse of each other.

**Comment by mdavis-xyz** [comment]
Why did you close this?

As it is today, I think the tutorial is not clear to the target audience, and the `URLAdapter` part is incorrect.
Note that I raised this ticket not to get personal support, but because I think someone (possibly me) should write a PR to modify the tutorial to make it clear.  

Can you confirm whether the `URLAdapter` part is correct or incorrect? What is that class? Does it exist? Why does it not match what the docs say `bind_to_environ` returns? Should I write a PR to change `URLAdapter` to `MapAdapter`?

What does `building` mean in this context? The tutorial doesn't mention that word.
I just looked up [`MapAdapter.build`](https://werkzeug.palletsprojects.com/en/2.2.x/routing/#werkzeug.routing.MapAdapter.build), which is a method not mentioned in the tutorial, of a class not mentioned in the tutorial. I still don't understand how that is relevant to the shortly tutorial.
