### ISSUE TITLE
reloader can use `sys.orig_argv` to get exact command

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#2589]
[`sys.orig_argv`](https://docs.python.org/3/library/sys.html#sys.orig_argv), added in Python 3.10, contains the exact command line used to start the `python` command. It does not modify `-m name` into `/path/to/name.py`, and keeps arguments like `-X dev`. The reloader can use this instead of all the reconstructing it does right now.

**Comment by davidism** [comment]
This would also happen to fix #2588, where `poetry run` creates a `python -c 'import...'` command (somewhat incorrectly, but still). There's no way for the existing code to work with this, `sys.argv` only sees `"-c"`, not the rest of the command.

**Comment by delucca** [comment]
@davidism thanks for all your work!

After this PR is released, I assume I can simply update Flask and it will allow me to use Poetry even if they insist in not fixing the unexpected mutation of sys.argv?
