### ISSUE TITLE
`send_file` filenames with spaces break in Chrome

### ISSUE THREAD

**Issue by georgthegreat** [pallets/werkzeug#2598]
I use `flask.send_file()` for serving pdf files from the historical dance bibliography website hosted at bib.hda.org.ru
In order to achieve human-readable filenames, I invoke the method as follows:
```
return flask.send_file(
    pdf_full_path,
    as_attachment=True,
    download_name=basename
)
```

It turns out that the most recent version of Google Chrome does not parses `filename*` properly if the name contains spaces.

I. e. if you try downloading the file from [here](https://bib.hda.org.ru/books/yatskovsky_1891) by clicking to URL link, you will get `[1891, ru] В. Ф. Яцковский - 100 фигур мазурки (RASL+RSL copy).pdf` in Firefox, but only `[1891` (without any filename extension) in Chrome (reproduced in 110.0.5481.

It looks like Flask returns correct header according to an [MDN page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition), so this looks like a bug in Chrome to me.

Could you, please, take a look and confirm if it is on Chrome side?

Environment:

- Python version: 3.10.4
- Flask version: 2.2.3

**Comment by davidism** [comment]
`filename*` isn't wrapped in quotes, the `''` is part of the extended name syntax. That filename appears to be encoded correctly to me, there are no unquoted spaces in the name.

As part of #2406, I'm reviewing which characters we quote in various places, and this works correctly on my branch. It looks like we weren't being strict enough in `filename*`, and should have used RFC 5987 `attr-char` characters as safe.

**Comment by davidism** [comment]
See https://github.com/pallets/werkzeug/issues/2601 for the more general issue.
