### ISSUE TITLE
Stop escaping non-reserved characters in URLs

### ISSUE THREAD

**Issue by artursoler** [pallets/werkzeug#262]
Currently, only alphanumeric characters plus "_.-" are marked as always safe. As defined in [URL RFC 1738](http://www.ietf.org/rfc/rfc1738.txt) a few more characters are allowed and thus should be included in _always_safe in urls.py.

> Thus, only alphanumerics, the special characters "$-_.+!*'(),", and reserved characters used for their reserved purposes may be used unencoded within a URL.

**Comment by Parakleta** [comment]
This fix should also have been applied to the IRI/URI conversion functions in the same file, as IRIs have the same sub-delims definition.  Should I open this as a new issue?

**Comment by jeffwidman** [comment]
If you think this is still problem, then yes, please open a new issue. Otherwise your comment will just get lost in the noise.
