### ISSUE TITLE
NumberConverter not being exposed

### ISSUE THREAD

**Issue by noiseunion** [pallets/werkzeug#2624]
## The Problem

All routing converters are being exposed as expected in `routing/__init__.py` with the exception of the `NumberConverter`

## How to replicate

Try and reference the `NumberConverter` as `werkzeug.routing.NumberConverter`

Raises:
```python
AttributeError: module 'werkzeug.routing' has no attribute 'NumberConverter'
```

## What should happen

No exception should be raised.  It should find the `NumberConverter` class.

Environment:

- Python version: 3.10.9
- Werkzeug version: 2.2.3

**Comment by noiseunion** [comment]
Hey @davidism - thanks for replying.

This is a breaking change in the 2.2.x branch as it was publicly available pre 2.2.x - I don't see this change in the change log, but maybe I missed it.

**Comment by davidism** [comment]
Everything in Python is "publicly available". However, being able to import it doesn't make it a public API. Public APIs are present in the online documentation.

**Comment by davidism** [comment]
Additionally, 2.2 is a feature release, so it can change compared to 2.1.

**Comment by noiseunion** [comment]
I realize that everything is "public", but you have created a breaking change for other libraries using Werkzeug, which is typically NOT something you do in a minor release.  

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated.

Anyway, I get that the point.  thanks for responding.

**Comment by davidism** [comment]
We're not semver. Just because semver said that its pattern is X.Y.Z doesn't mean every project using X.Y.Z follows semver. See also: Python.

**Comment by noiseunion** [comment]
all good - thanks!  😄
