### ISSUE TITLE
OSError on reload when running Werkzeug server with vs code debugger

### ISSUE THREAD

**Issue by sergehauri** [pallets/werkzeug#2627]
Since werkzeug 2.2.3, running a Flask app in vs code raises the following Exception when reloading the app:

```
Exception in thread Thread-6 (serve_forever):
Traceback (most recent call last):
  File "C:\Users\TAAHASE0\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\TAAHASE0\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\TAAHASE0\dev\projects\werkzeugtest\venv\lib\site-packages\werkzeug\serving.py", line 766, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "C:\Users\TAAHASE0\AppData\Local\Programs\Python\Python310\lib\socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "C:\Users\TAAHASE0\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 324, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\TAAHASE0\AppData\Local\Programs\Python\Python310\lib\selectors.py", line 315, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

With werkzeug 2.2.2, this doesn't happen.

### How to reproduce
A simple flask app (a single app.py file):
```
from flask import Flask

app = Flask(__name__)
```

The following launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Flask",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "app.py",
                "FLASK_DEBUG": "1"
            },
            "args": [
                "run",
                "--no-debugger"
            ],
            "jinja": true,
            "justMyCode": true
        }
    ]
}
```

Running this app with vs code runs the following command:
`(venv) PS C:\Users\TAAHASE0\dev\projects\werkzeugtest>  c:; cd 'c:\Users\TAAHASE0\dev\projects\werkzeugtest'; & 'c:\Users\TAAHASE0\dev\projects\werkzeugtest\venv\Scripts\python.exe' 'c:\Users\TAAHASE0\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '50758' '--' '-m' 'flask' 'run' '--no-debugger'`

Saving the app.py file causes the app to reload:
` * Detected change in 'C:\\Users\\TAAHASE0\\dev\\projects\\werkzeugtest\\app.py', reloading`

which leads to the mentioned Exception and stack trace.

Running the flask app directly from the terminal does not cause this behavior, it reloads the app without error:
```
(venv) PS C:\Users\TAAHASE0\dev\projects\werkzeugtest> flask run --debug --no-debugger
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Detected change in 'C:\\Users\\TAAHASE0\\dev\\projects\\werkzeugtest\\app.py', reloading
 * Restarting with stat
```

I've traced the error to this change: https://github.com/pallets/werkzeug/pull/2517

Specifically to serving.py lines 1058-1067, `srv.server_close()` in the finally block. This try-finally block was not there in 2.2.2, and reverting this part "fixes" the issue.

### Versions
Python 3.10.0
VS Code 1.77.0
VS Code Python Extension v2023.6.0

Python packages:
```click==8.1.3
colorama==0.4.6
Flask==2.2.3
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.2
Werkzeug==2.2.3```

**Comment by davidism** [comment]
> Running the flask app directly from the terminal does not cause this behavior, it reloads the app without error

Then this should be reported to the VS Code and/or VS Code Python teams.

The change was deliberate, as the detailed PR you linked explains. We want to ensure the server closes its resources properly.
