### ISSUE TITLE
Stream argument to ProfilerMiddleware is not typed hinted correctly

### ISSUE THREAD

**Issue by fnork** [pallets/werkzeug#2642]
The profiler middleware `src/werkzeug/middleware/profiler.py:80` documentation and implementation states that the argument `stream` can be set to `None` to disable output.
 
However the type hints specifies `stream: t.IO[str] = sys.stdout,` which is inconsistent with the documentation and the implementation.

To replicate the issue run a type hint aware validator against something initiating a `ProfilerMiddleware` with the `stream` argument set to `None`:
```
ProfilerMiddleware(
    app,
    stream=None
)
```
It will cause an error stating that `None` is not an acceptable value for `stream`.

It's a minor and easy fix that I'm happy to provide a PR for if deemed acceptable with the proposed change:
```
stream: t.Union[t.IO[str], None] = sys.stdout,
```

Environment:

- Python version: 3.10
- Werkzeug version: 2.2.3

**Comment by davidism** [comment]
Happy to review a PR

**Comment by fnork** [comment]
PR submitted.

The build is erroring on `Tests / 3.12-dev (pull_request)` with `warnings.warn("onerror argument is deprecated, use onexc instead"` which seems to be unrelated, but it's still a failure. Is that a know issue or do you have any action points for me?

**Comment by fnork** [comment]
I followed the `CONTRIBUTING.rst` guidelines.
