### ISSUE TITLE
multipart/$custom+form-data

### ISSUE THREAD

**Issue by dwt** [pallets/werkzeug#2650]
A Request with the content-type `multipart/$custom+form-data` is not parsed as multipart/form-data.

To replicate this, make a request with a custom mime type like that.

Example:
```python
import io
import json

from utils.testing import FlaskTestCase

class PostDokumentInputTest(FlaskTestCase):

    def test_send(self):
        headers = {"Content-Type": "multipart/x.company.schema+form-data"}

        metadaten = {
            "foo": "bar"
        }

        response = self.client.post("/dokumente/input", data={
            "metadaten": json.dumps(metadaten),
            "dokument": (io.BytesIO(b"73_document"), "test.pdf")
        }, headers=headers)

        assert 200 == response.status_code
```

I would expect this to be parsed as multipart-form-data.

Environment:

- Python version: '3.11.3 (main, Apr  5 2023, 22:33:13) [GCC 10.2.1 20210110]'
- Werkzeug version: 2.2.3

I would be willing to get a pull request going to switch to some regex or prefix/suffix parsing to support extended mime types here.

BUT - is that something you want, think is missing here?

**Comment by davidism** [comment]
But it's not form data, it's _some_ data with an unknown content type. You could use middleware to fix the type, but you should probably address why you're not getting the valid type.
