### ISSUE TITLE
Enable option to parse forms from infinite streams using `parse_form_data`

### ISSUE THREAD

**Issue by haciMMicah** [pallets/werkzeug#2651]
This feature would enable parsing infinite streams using the short-hand `formparser.parse_form_data` function rather than having to
use the `formparser.FormDataParser` class directly. This can be accomplished simply by replicating the optional `safe_fallback` flag from the `formparser.get_input_stream` function into the `parse_from_environ` method and `formparser.parse_form_data` function

This would also allow parsing infinite streams using the `parse_from_environ` directly with the `FormDataParser` class.

Parsing forms from infinite streams can already be done by directly using the `parse` method but it would be nice if the shorthand could be used.

I recently came across a use case for parsing form streams where the true "Content-Length" is unknown when attempting to parse a multipart/form-data request where the entire request body was `gzip` compressed. This format is currently being used by Google's Crashpad in order to reduce crash dump reporting transmission size. The true content-length can be known by first decompressing the entire request, but for large files that can be very inefficient. I managed to get this working by passing in a `GzipFile` stream since it implements the typical `io.BytesIO` like interface but I was surprised that I could not use the short-hand `parse_form_data` function to do so since `parse_from_environ` only calls `get_input_stream` with the `environ` arg which subsequently sets the input stream to an empty `io.BytesIO` object as the `safe_fallback` arg defaults to `True`. This change would allow something like this...
```
with gzip.GzipFile(fileobj=request_input_stream) as gz_stream:
   env = {
      "wsgi.input: gz_stream",
      "REQUEST_METHOD": "POST",
      "CONTENT_TYPE": content_type,
   }
   stream, form, files = formparser.parse_form_data(env, safe_fallback=False)
```
I have this implemented in my own fork, but was wondering what the sentiment would be in adding it to the upstream. I understand that parsing from infinite streams can be a DoS risk, but since this is already allowed I figured it should be an option in the short-hand version as well.

**Comment by davidism** [comment]
Thanks for pointing out that `parse_form_data` is a public API, I had overlooked it in #2620 (enforcing content length limits consistently), and can update it similarly. That said, I'd prefer not to enable more uses of the `formparser` module directly, as it needs a broad refactor.

In Werkzeug 2.3, you will be able to set `request.max_content_length` for a given request to set a large max length. For example, setting it to 1000000000 to allow up to 1GB of data. That's a safer bet than allowing truly infinite streams.

You can allow your request to have an infinite stream using a sublcass. However, see #2620 and related discussions for why this is not a safe idea in most cases.

```python
from werkzeug import request
from werkzeug.utils import cached_property
from werkzeug.wsgi import get_input_stream

class InfiniteStreamRequest(Request):
    @cached_property
    def stream(self):
        return get_input_stream(
            self.environ,
            safe_fallback=False,
            max_content_length=self.max_content_length
        )
```

**Comment by haciMMicah** [comment]
Thanks for your response! So is the currently recommended way to handle unknown "Content-Length" form requests by subclassing the Request class and returning a stream with a `max_content_length` set and `safe_fallback=False` rather than directly using `formparser`? Or will this only work in >= 2.3? That should work fine for my use case as I should just be able to pass in the `GzipFile` obj into the `environ`

**Comment by davidism** [comment]
If you have a server that properly terminates requests, then you don't need to do anything, it already works. Gunicorn, uwsgi, waitress, and mod_wsgi for example.
