### ISSUE TITLE
support scrypt, deprecate basic hash methods

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#2654]
Scrypt provides much stronger security than PBKDF2. It also has the advantage of not needing to update parameters as often. It is in the standard library. @alex and @reaperhulk recommended `n=2**15, r=8, p=1` for parameters.

Additionally, insecure/basic methods need to be deprecated. Currently, the `plain` method is allowed, which just returns the password as-is. Additionally, plain hashes are supported, rather than always requiring a KDF, and any hash provided by `hashlib` is supported. Deprecate everything except `scrypt` and `pbkdf2`.

If projects notice they are using these old methods, they'll need to implement a migration strategy to upgrade their hashes.

**Comment by davidism** [comment]
`hashlib.scrypt` is not available on PyPy: https://foss.heptapod.net/pypy/pypy/-/issues/3921 For now, I'll continue to use pbkdf2 as the default.

**Comment by homeworkprod** [comment]
Thanks a lot, @davidism!
