### ISSUE TITLE
request.files access became slower

### ISSUE THREAD

**Issue by Amihaeseisergiu** [pallets/werkzeug#2658]
The access to `request.files['file']` became slower when I upgraded to Werkzeug 2.3. A 12.1 MB file used to take a couple of ms, but now it takes about 8 seconds.

```python
from werkzeug import Request, Response, run_simple

@Request.application
def app(request):
    if request.method == "POST":
        return Response(request.files["file"].filename)

    return Response("""<!doctype html>
<meta charset=utf-8>
<form method=post enctype=multipart/form-data>
<input type=file name=file>
<input type=submit>
</form>
""", mimetype="text/html")

run_simple("127.0.0.1", 5000, app)
```

Environment:

- Python version: 3.10
- Werkzeug version: 2.3.0

**Comment by Amihaeseisergiu** [comment]
Seems like the issue is related to the 2.3.0 version of Werkzeug. If I am downgrading both Flask and Werkzeug to 2.2.3 everything works as before.

Seems like only downgrading Flask to 2.2.3 still pulls the 2.3.0 version of Werkzeug. I only had Flask in my `requirements.txt` file, marked as `Flask==2.2.3`, but still ended up with this issue. This is most likely related to pip, but I was expecting the downstream dependencies of Flask's versions to remain the same.

**Comment by davidism** [comment]
> I only had Flask in my requirements.txt

When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates.

**Comment by davidism** [comment]
Yep, looks like the #2639 introduced a slowdown. Testing on 082e0e5b9c01fa3178ac0153413f082616f10914 is noticeably slower than the commit before it, 6425dbfd0d33a9ed198391838438a0659cfb3368.
