### ISSUE TITLE
Call to untyped function "get" in typed context

### ISSUE THREAD

**Issue by toomore** [pallets/werkzeug#2660]
When upgrading to version `2.3.1` and running typing check using mypy, the following error occurs:
> Call to untyped function "get" in typed context  [no-untyped-call]

The "get" function is `request.headers.get('X-SSL-SESSION-ID')`.

Environment:

- Python version: 3.11
- Flask version:
  - 2.2.3 -> 2.2.4
  - 2.2.3 -> 2.3.1

**Comment by davidism** [comment]
Could use help on a PR for this one, I'm not sure why the typing is wrong now.

**Comment by kgutwin** [comment]
I ran into this issue myself, and tracked it down -- the typing didn't change, what happened is that the `.pyi` files inside `werkzeug/datastructures` are not being included in the release package for Werkzeug 2.3.0. The way I tested this was:

```bash
% python3.10 -m venv venv
% . venv/bin/activate
% python -m pip install werkzeug==2.3.0
% ls -l venv/lib/python3.10/site-packages/werkzeug/datastructures
total 248
-rw-r--r--   1 kgutwin  staff   1900 Apr 26 14:24 __init__.py
drwxr-xr-x  13 kgutwin  staff    416 Apr 26 14:24 __pycache__
-rw-r--r--   1 kgutwin  staff  10670 Apr 26 14:24 accept.py
-rw-r--r--   1 kgutwin  staff  15446 Apr 26 14:24 auth.py
-rw-r--r--   1 kgutwin  staff   6043 Apr 26 14:24 cache_control.py
-rw-r--r--   1 kgutwin  staff   3244 Apr 26 14:24 csp.py
-rw-r--r--   1 kgutwin  staff   2913 Apr 26 14:24 etag.py
-rw-r--r--   1 kgutwin  staff   6076 Apr 26 14:24 file_storage.py
-rw-r--r--   1 kgutwin  staff  18882 Apr 26 14:24 headers.py
-rw-r--r--   1 kgutwin  staff   5337 Apr 26 14:24 mixins.py
-rw-r--r--   1 kgutwin  staff   5669 Apr 26 14:24 range.py
-rw-r--r--   1 kgutwin  staff  31761 Apr 26 14:24 structures.py
```

**Comment by davidism** [comment]
Thanks for finding that! We moved to a package and submodules for `datastructures`, but forgot to update `MANIFEST.in`.

**Comment by RonnyPfannschmidt** [comment]
@davidism i took note that the pyproject.toml change doesnt seem to have passed over the include package data options, i suspect that may be related

**Comment by davidism** [comment]
I think `include_package_data` should be true by default when using `pyproject.toml` with setuptools, but I'll check.

**Comment by davidism** [comment]
In the `pyproject.toml` tab, it says:

> ```
> # By default, include-package-data is true in pyproject.toml, so you do
> # NOT have to specify this line.
> ```

**Comment by toomore** [comment]
@davidism Thanks, and thanks all~

**Comment by exhuma** [comment]
> When upgrading to version 2.3.1

Should this not be 2.3.0? I am currently on 2.3.0 and I get the same error, and 2.3.1 is not on pypi
