### ISSUE TITLE
cannot read data due to `max_content_length`

### ISSUE THREAD

**Issue by basrieter** [pallets/werkzeug#2668]
I have a Flask api that sets MAX_CONTENT_LENGTH to 2MB. With Werkzeug 2.3.0/2.3.1 this causes the reading of `request.data` (or `request.get_data()` to freeze. This happens in my Windows development environment using `flask run`. Not when running in Gunicorn under Linux.

This might be a result of https://github.com/pallets/werkzeug/commit/4f7048e7a31752142f18eefeccd49acc42a89e31

## To replicate

Install Flask:

```
pip install flask
```

For me this installs:

* blinker==1.6.2
* click==8.1.3
* colorama==0.4.6
* Flask==2.3.1
* importlib-metadata==6.6.0
* itsdangerous==2.1.2
* Jinja2==3.1.2
* MarkupSafe==2.1.2
* Werkzeug==2.3.1
* zipp==3.15.0

Create a simple Flask-app:
```
from flask import Flask, jsonify, request

app = Flask("server", static_url_path="")
app.config["MAX_CONTENT_LENGTH"] = 2 * 1000 * 1000


@app.get("/api/test")
def get_roles():
    r = request
    print(r.get_data())
    return jsonify(True)
```

Run it:

```
 flask run
```

Then browse to http://127.0.0.1:5000/api/test. This will not result in a response. 

It should response with "true" as a result. 

If  `app.config["MAX_CONTENT_LENGTH"] = 2 * 1000 * 1000` is removed. It all works as expected. 

## Environment

- OS: Windows 10/11 (Verified on 2 different systems)
- Python version:  Python 3.8 / 3.9
- Werkzeug version: 2.3.0/2.3.1

**Comment by davidism** [comment]
Why are you reading `request.data` in a GET request? That's incorrect.

**Comment by basrieter** [comment]
> Why are you reading `request.data` in a GET request? That's incorrect.

Even the `request.get_data()` fails

**Comment by davidism** [comment]
Same question, why are you reading data in a GET request?

Also, please stop editing the title.

**Comment by davidism** [comment]
You are (or a library is) asking for data when none was sent. There's no way to distinguish between "no data, no content length" and "streaming data, no content length". If `max_content_length` is set, it means "read up to this limit if there is no content length". The browser isn't sending anything, so the read keeps waiting until it times out.

**Comment by davidism** [comment]
And it's not reading more than the configured length. It's not reading anything, because nothing is sent. The problem is the ambiguity of requesting data when there is no data, compared to requesting streaming data. It's not possible to tell the two cases apart.

**Comment by basrieter** [comment]
I just pointing out the change in behaviour between the two versions, but also between the different hosting/running options. 

I already replace the component that was the `get_data()` on every request and cause my blockage.

**Comment by basrieter** [comment]
Thanks for your effort and keep up the good work for open source software.
