### ISSUE TITLE
Mapping Error, all requests return 405

### ISSUE THREAD

**Issue by gus4rs** [pallets/werkzeug#2676]
```python
from klein import run, route

@route('/', methods=['GET'])
def do_post(request):
    return "hello"

run("localhost", 8080)
```

This stopped working from werkzeug ```2.3.0``` onwards

**Comment by davidism** [comment]
When opening an issue against Werkzeug, please provide a minimal example using Werkzeug only.

**Comment by gus4rs** [comment]
Dude, really? You don't want to put any effort at all? 😄

Anyway, in case you're still interested in having this issue fixed, it is literally a 2min task to run the sample inside a venv:

```
python3 -m venv repro
source repro/bin/activate
pip install klein==20.6.0
python app.py 
```

Finally
```
curl http://localhost:8080
```

You will get 405 error, because the version of werkzeug pulled is ```2.3.2```

If you downgrade it to ```2.2.0``` with ```pip install wekzeug==2.2.0``` and re-run the app, it works!

**Comment by pgjones** [comment]
This is an issue for klein, please open on their repository.
