### ISSUE TITLE
No path by default in set_cookie()

### ISSUE THREAD

**Issue by novns** [pallets/werkzeug#2679]
The new behavior of set_cookie() is not documented and not mentioned in the Changes log.

set_cookie() does not set path to '/' by default anymore and "per default it will span the whole domain" in the documentation is not correct.

The commit: https://github.com/pallets/werkzeug/commit/eb363e4fad9ebc333cb69fc83ae45b3a46fe82ce

Environment:

- Python version: 3.10.10
- Flask version: 2.3.1

**Comment by davidism** [comment]
> not mentioned in the Changes log.

You need to look at the changelog for Werkzeug for changes in Werkzeug.
