### ISSUE TITLE
Query strings parsing behaviour change

### ISSUE THREAD

**Issue by gubenkoved** [pallets/werkzeug#2689]
Since 2.3.0 version arguments parsing behaviour has changed in backward incompatible way.

Here is simple repro based on the "getting started" app:

```
from werkzeug.wrappers import Request, Response

@Request.application
def application(request):
    print('url: %r' % request.url)
    print('args: %r' % request.args)
    return Response('Hello, World!')


if __name__ == '__main__':
    from werkzeug.serving import run_simple
    run_simple('localhost', 4000, application)
```

```
curl "localhost:4000/?test=foo:ASC;bar:DESC"
```

On 2.2.3 version we get the following results:
```
url: 'http://localhost:4000/?test=foo:ASC;bar:DESC'
args: ImmutableMultiDict([('test', 'foo:ASC;bar:DESC')])
127.0.0.1 - - [02/May/2023 12:33:25] "GET /?test=foo:ASC;bar:DESC HTTP/1.1" 200 -
```

Since 2.3.0 it results with following:
```
url: 'http://localhost:4000/?test=foo:ASC;bar:DESC'
args: ImmutableMultiDict([('test', 'foo:ASC'), ('bar:DESC', '')])
127.0.0.1 - - [02/May/2023 12:34:05] "GET /?test=foo:ASC;bar:DESC HTTP/1.1" 200 -
```

The problem is in the query string parsing logic -- notice how `test` variable only has `foo:ASC` as its value.

Environment:

- Python version: 3.8.0
- Werkzeug version: 2.3.0

**Comment by davidism** [comment]
Hmm, looks like Python < 3.10 allowed both `&` and the old `;` as separators: https://docs.python.org/3/library/urllib.parse.html#urllib.parse.parse_qs. Best way to fix this is to upgrade to 3.10, but I'll figure it out.

**Comment by davidism** [comment]
Python 3.8.8, 3.9.2, and >=3.10.0 changed `urllib.parse_qs` to only treat `&` as a separator rather than `;`. I think the answer here is going to be that you need to update Python to the latest patch release, regardless of version.

**Comment by davidism** [comment]
It looks like all of those Python releases were security fixes, so if your OS is not including them then you need to report that immediately to your OS's security team.
