### ISSUE TITLE
Dropping OIDC_access_token header breaking authentication behind reverseproxy

### ISSUE THREAD

**Issue by DrakezulsMinimalism** [pallets/werkzeug#2703]
Apache HTTPD plugin uses headers with underscores that are now dropped, thus our dev's cannot use authentication anymore.

How to reproduce this bug:
1. Start any webserver based on werkzeug >2.3.0
2. Send request with headers, at least one of which includes an underscore
3. See that the underscore header is dropped.

This is based on https://github.com/pallets/werkzeug/blame/main/src/werkzeug/serving.py#L206
- We are using a reverse proxy for authentication both, in production and development.
- We are using a WSGI server in production, but werkzeug/flask development during development
- The reverse proxy injects this header itself and doesn't allow it to be passed by the original request of the client, however, the header cannot be modified by us, as it comes from the authentication library.

Expected behavior:
Do not drop headers with underscore, or add an allow-list of expected headers (?) or a flag to skip this check

Environment:
- Python version: 3.10
- Werkzeug version: >2.3.0
- httpd + mod_auth_openidc, see https://github.com/OpenIDC/mod_auth_openidc/wiki/Access-Tokens-and-Refresh-Tokens

**Comment by ThiefMaster** [comment]
Sounds like this should be fixed in mod_auth_openidc tbh... but some way to whitelist headers could indeed be useful, even though the whole concept of putting underscores in header names which usually use dashes seems like a bad idea

**Comment by ThiefMaster** [comment]
Searching for "underscores" in the mod_auth_openidc repo pointed me to https://github.com/OpenIDC/mod_auth_openidc/issues/365#issuecomment-393867445 among some other discussions. So maybe you can use that module to rewrite the header names?

**Comment by DrakezulsMinimalism** [comment]
Thanks for the ultra fast response(s) ... seems I missed that while searching for the header name and a way to configure it.
I'll give it a try.

@davidism If HTTPD would sanitize the incoming request (i.e. replace _ in headers) and then inject it's own (bad) underscored-header, this would not be an insecure setup IMO, but I agree on the usual implications ... and it would not be feasible in a multi-level proxy setup then either.

Thanks both, I'll revert back shortly and document the fix, if any.
