### ISSUE TITLE
new deprecation warnings in Python 3.12

### ISSUE THREAD

**Issue by tonybaloney** [pallets/werkzeug#2704]
Starting flask in Python 3.12 raises warnings of deprecations in Python 3.14 within Werkzeug

```default
/Users/anthonyshaw/projects/cpython/.venv-312/lib/python3.12/site-packages/werkzeug/routing/rules.py:751: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  parts = parts or [ast.Str("")]
/Users/anthonyshaw/projects/cpython/.venv-312/lib/python3.12/site-packages/werkzeug/routing/rules.py:748: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  _convert(elem) if is_dynamic else ast.Str(s=elem)
/Users/anthonyshaw/projects/cpython/Lib/ast.py:587: DeprecationWarning: Attribute s is deprecated and will be removed in Python 3.14; use value instead
  return Constant(*args, **kwargs)
/Users/anthonyshaw/projects/cpython/.venv-312/lib/python3.12/site-packages/werkzeug/routing/rules.py:755: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  if isinstance(p, ast.Str) and isinstance(ret[-1], ast.Str):
/Users/anthonyshaw/projects/cpython/.venv-312/lib/python3.12/site-packages/werkzeug/routing/rules.py:756: DeprecationWarning: Attribute s is deprecated and will be removed in Python 3.14; use value instead
  ret[-1] = ast.Str(ret[-1].s + p.s)
/Users/anthonyshaw/projects/cpython/.venv-312/lib/python3.12/site-packages/werkzeug/routing/rules.py:756: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  ret[-1] = ast.Str(ret[-1].s + p.s)
```

For example:

https://github.com/pallets/werkzeug/blob/76b049dd45fd072fb62a54bccc0e8d513b03f4d8/src/werkzeug/routing/rules.py#L757

The documentation states "Changed in version 3.8: Class [ast.Constant](https://docs.python.org/3/library/ast.html#ast.Constant) is now used for all constants." so I don't know if the `ast.Str` conditions are even working in versions 3.8+.

Considering Werkzeug just dropped support for Python 3.7, the rules code could be refactored to use the new type without breaking compatibility

Environment:

- Python version: 3.12a1
- Werkzeug version: 2.2.3

**Comment by davidism** [comment]
Got confused for a second because I was seeing the errors after fixing our uses. It's because pytest still has the issue internally as well: https://github.com/pytest-dev/pytest/issues/10977

**Comment by davidism** [comment]
A few other 3.12 things came up:

* AST `node.value` instead of `node.s`
* `importlib.util.find_spec` instead of `pkgutil.find_loader`
