### ISSUE TITLE
EnvironBuilder fails on certain non-conformant form input

### ISSUE THREAD

**Issue by kgutwin** [pallets/werkzeug#2706]
Fuzz testing on my application using Schemathesis raised a strange and difficult-to-reproduce error, which typically looked like this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kgutwin/github/werkzeug/src/werkzeug/test.py", line 719, in get_environ
    input_stream, content_length, boundary = stream_encode_multipart(
  File "/Users/kgutwin/github/werkzeug/src/werkzeug/test.py", line 128, in stream_encode_multipart
    write_binary(encoder.send_event(Field(name=key, headers=headers)))
  File "/Users/kgutwin/github/werkzeug/src/werkzeug/sansio/multipart.py", line 313, in send_event
    raise ValueError(f"Cannot generate {event} in state: {self.state}")
ValueError: Cannot generate Field(name='baz', headers=Headers([('Content-Type', 'application/octet-stream')])) in state: State.DATA_START
```

I traced this down to Schemathesis generating a request with form data containing multiple dicts. The above traceback can be reproduced as follows:

```python
from werkzeug import test
builder = test.EnvironBuilder(
    method="POST", 
    path="/foo", 
    headers={"Content-Type": "multipart/form-data"}, 
    data={'foo': 'bar', "bar": {}, "baz": {}}
)
builder.get_environ()
```

Reviewing the [documentation on EnvironBuilder](https://werkzeug.palletsprojects.com/en/2.3.x/test/#werkzeug.test.EnvironBuilder), it appears that the data parameter expects a dict with values of either string, tuple, or file-like object, so providing a dict as a form value is not expected to be valid input.

The reason that dicts trigger this behavior is that the processing of the data parameter in the EnvironBuilder constructor takes the same path for dict values as it does for tuple values and file-like values:

```python
for key, value in _iter_data(data):
    if isinstance(value, (tuple, dict)) or hasattr(value, "read"):
        self._add_file_from_data(key, value)
    else:
        self.form.setlistdefault(key).append(value)
```

However, `_add_file_from_data()` only expects tuples or `t.IO[bytes]` instances as its input, which ultimately causes `stream_encode_multipart()` to get lost when building the multipart form stream. My guess is that the intention was to allow dict values in order to allow names to the arguments when creating files, but that was never fully implemented.

I was going to submit a simple PR for a change to the above code block to get the code to reflect the documentation's description of expected input:

```python
for key, value in _iter_data(data):
    if isinstance(value, tuple) or hasattr(value, "read"):
        self._add_file_from_data(key, value)
    elif isinstance(value, str):
        self.form.setlistdefault(key).append(value)
   else:
        raise ValueError("data values must be string, tuple, or file-like")
```

However, this change causes existing test cases in the test suite to fail, like this one:

```python
    def test_delete_requests_with_form():
        @Request.application
        def test_app(request):
            return Response(request.form.get("x", None))
    
        client = Client(test_app)
>       resp = client.delete("/", data={"x": 42})
```

So now I'm concerned that making the input check more stringent could cause downstream applications or test suites to start failing, perhaps unnecessarily.

My question is, which path is preferred? If the form data input should be permissive, then fixing the path that causes the original exception should be straightforward, and the documentation may want to be updated to suit. Or, should the code reflect the expectations in the documentation, raising ValueError on any invalid input?

Environment:

- Python version: 3.10.10
- Werkzeug version: 2.3.4

**Comment by davidism** [comment]
I don't really see the point in fixing this. The fuzzer should be manipulating the data for consumption _by your application_ not fuzzing the input to Werkzeug's test runnner. Fairly sure fuzzers have ways to configure them to not fuzz certain things, such as "always create valid input for the test runner, but fuzz the strings".

**Comment by kgutwin** [comment]
Sorry about the confusion. My concern is less towards bad behavior by fuzzers (I agree, that's a fuzzer problem) but more that the Werkzeug docs don't align to its code. 

In your opinion, should `EnvironBuilder` accept `data` input in the form of a dict, or any other type other than "string, tuple, or file-like"? 
* If so, the docs should be updated (and the special case behavior that was caught by the fuzzer should be fixed).
* Otherwise, the code should raise ValueError when invalid input is provided, which will require updating some test cases that are currently passing dicts as data.

**Comment by davidism** [comment]
The docs and type annotations already correctly describe how `EnvironBuilder(data=...)` works.

https://werkzeug.palletsprojects.com/en/2.3.x/test/#request-body
https://werkzeug.palletsprojects.com/en/2.3.x/test/#werkzeug.test.EnvironBuilder

```python
data: None | (t.IO[bytes] | str | bytes | t.Mapping[str, t.Any]) = None
```
