### ISSUE TITLE
stat reloader crashes while running in pycharm debugger

### ISSUE THREAD

**Issue by KTBL-MaximilianKugler** [pallets/werkzeug#2707]
After updating from Flask 2.2.2 (using Werkzeug 2.2.2) to Flask 2.3.2 (using Werkzeug 2.3.4), my Flask application is no longer able to run with pycharm's debugger attached in case stat reloader is enabled. The first reload attempt will instantly crash the entire running python process.

Assume bootstrapping a Flask app like this

`app.run(host='127.0.0.1', port=5050, debug=True, use_reloader=True)`

from within pycharm using its debugger will result in the following command line 

`<full path to python.exe> "C:\Program Files\JetBrains\PyCharm 2022.1\plugins\python\helpers\pydev\pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 55150 --file <full path to start script creating the Flask app>`

after the first change is detected by stats reloader, process immediately crashes with the following output

```
INFO     werkzeug  * Restarting with stat
<full path to python.exe>: can't open file 'C:\\Program': [Errno 2] No such file or directory

Process finished with exit code 2
```

After tracking down the changes that happened in Werkzeug between 2.2.2 and 2.3.4, the responsible part seems to be the introduction of sys.orig_argv as discussed in https://github.com/pallets/werkzeug/issues/2589, which is used from Python 3.10 and above in order to derive the originating command line (including all parameters) in order to to be able to precisely restart the process as it has been originally started. The relevant changes seems to be done here https://github.com/pallets/werkzeug/commit/51b8402ec419b7afdc098cbd37953c8e125df10c

Unfortunately in my case the path to pycharm's debugger script contains whitespaces ("C:\Program Files") and since it is not correctly quoted before command line execution from stat reloader above exception occurs. Since I installed pycharm in the default location of Windows, I assume that this might happen to others as well?!

Looking at the implementation I am not really sure where to do the proper quoting/handling of command line parameters in _reloader.py or whether it is wise at all for Werkzeug to try and restart the entire debugger process by the reloader using sys.orig_argv in this scenario (which was not the case with 2.2.2 -> here only the acual Flask app related process was restarted and it worked pretty well). At least as a workaround I simply set use_reloader=False to stop the reloader from crashing and was thereby able to continue to use pycharm's debugger after updating to Flask 2.3.2.

Environment:

- Python version: 3.10
- Werkzeug version: 2.3.4 (Flask 2.3.2)
- PyCharm 2022.1.2

**Comment by davidism** [comment]
> it is not correctly quoted before command line execution from stat reloader.

The reloader isn't required to do any quoting, `subprocess.call` accepts a list of arguments to be used as-is for starting a process, it doesn't require shell quoting.

If `sys.orig_argv` isn't correct, then that's a bug that must be reported with a minimal reproducible example to Python. Or perhaps it's an issue with either the pydev debugger or PyCharm's use of it, in which case it should be reported to them.

**Comment by davidism** [comment]
It does seem like pydevd or PyCharm aren't doing the right thing, so this should be reported to them. Printing out the result from `_get_args_for_reloading()` shows the correct values on Windows even when there's a space in a path.

**Comment by davidism** [comment]
I also can't reproduce this on Linux, spaces in paths are handled correctly there, and `sys.orig_argv` looks the same, so perhaps something they're doing for Windows is interpreting arguments incorrectly.

**Comment by davidism** [comment]
Looks like it was reported to PyCharm here: https://youtrack.jetbrains.com/issue/PY-60819/FLASKDEBUG1-breaks-debugger-when-Python-PyCharm-installation-path-has-spaces

Click the "thumbs up" icon next to the issue title to vote for the issue and increase its priority.
