### ISSUE TITLE
AttributeError on query string parsing with `args` method incorrectly using `decode`

### ISSUE THREAD

**Issue by fmigneault** [pallets/werkzeug#2710]
# Describe how to replicate the bug.

Since https://github.com/pallets/werkzeug/commit/47cf613252064cf9456b91604d2dddddcca7726d (`>=2.3.0`), the `request.args` property causes `AttributeError("'str' object has no attribute 'decode'")`. This is because the query string is already unicode, not bytes.

Basically, perform any request and call `request.args` to obtain the query string arguments as mapping. This will cause the `AttributeError`.

```python
req.query_string = {str} 'version=1.0.0&request=Execute&service=WPS&identifier=WpsPackageDockerAppTest'
req.args = {AttributeError}AttributeError("'str' object has no attribute 'decode'")
```

The commit (47cf613252064cf9456b91604d2dddddcca7726d) that introduced this problem added the `decode` part that was not employed before. Either way, the `url_charset` for which is was added has already been deprecated, and would not have worked as intended unless  `query_string` was stored as bytes. 

Environment:

- Python version: 3.10.10
- Werkzeug version: 2.3.x

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided. Be sure to include a minimal reproducible example when reporting an issue.

**Comment by davidism** [comment]
```python
from werkzeug import Request, Response, run_simple

@Request.application
def app(request: Request) -> Response:
    return Response(str(request.args))

run_simple("127.0.0.1", 5000, app)
```

Navigating to `http://127.0.0.1:5000/?version=1.0.0&request=Execute&service=WPS&identifier=WpsPackageDockerAppTest` returns the expected parsed data without raising an `AttributeError`.

**Comment by fmigneault** [comment]
If using an application that passes around the request already prepared in the right format because it itself created the request object, it is normal that it doesn't raise. In my situation, the `werkzeug` request had to be modified due to some problematic internal query string parameters handling when integrating it with other plugins and handlers, which themselves use a similar `query_string` property, but actually as a string, not bytes.

The value was set using (over simplified below, but it could be defined either by string or bytes depending on the handler):
`request.query_string = "version=1.0.0&request=Execute&service=WPS&identifier=WpsPackageDockerAppTest"`

Because `werkzeug.urls.url_decode` was used before, which lead eventually to: 

https://github.com/pallets/werkzeug/blob/76b049dd45fd072fb62a54bccc0e8d513b03f4d8/src/werkzeug/urls.py#L1122-L1123

... it did not matter whether the string was passed as `bytes` or `str`. 
The error arises now because the `decode` is performed preemptively.

**Comment by davidism** [comment]
Modifying `request.query_string` is not particularly "public", it's not a documented API. But if you are going to do it anyway then it is typed as `bytes` so you need to conform to that. The type annotations have not changed. And really, you should modify `environ` using middleware (and conform to the WSGI encoding rules in that case).
