### ISSUE TITLE
Unable to set cross-domain cookie

### ISSUE THREAD

**Issue by davidt99** [pallets/werkzeug#2722]
Since version 2.3.x, I can't set a cross-domain cookie.

Calling `dump_cookies`with a domain that starts with a dot `.` (cross-domain) like ".example.com" will always result in a cookie without a dot.
I tracked the change to this https://github.com/pallets/werkzeug/commit/cf0102d6443e936f95b21b69e3deb65028d6fe3b commit. The code always `lstrip` and dots.

Here is a test method that can be added to testing [file](https://github.com/pallets/werkzeug/blob/main/tests/test_http.py):
```python
def test_cookie_domain_cross_domain(self):
    val = http.dump_cookie("foo", "bar", domain=".foo.com")
    assert val == "foo=bar; Domain=.foo.com; Path=/"
```

Environment:

- Python version: 3.11
- Werkzeug version: 2.3.4

**Comment by davidism** [comment]
Setting the domain at all makes it cross domain. A leading dot is ignored according to the modern specification and browsers follow that.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

> Setting the domain will make the cookie available to it, as well as to all its subdomains.
>
> If omitted, this attribute defaults to the host of the current document URL, not including subdomains.
>
> Contrary to earlier specifications, leading dots in domain names (.example.com) are ignored.

https://httpwg.org/specs/rfc6265.html#sane-domain

> Note that a leading %x2E ("."), if present, is ignored even though that character is not permitted
