### ISSUE TITLE
Routing Error does not indicate the string which has an issue

### ISSUE THREAD

**Issue by TheGreatAlgo** [pallets/werkzeug#2749]
Issue: Currently having the problem of `urls must start with a leading slash` found in the `rules.py`. Cannot figure out which url is the issue. 

Replicate: Have an incorrect url

Expected: Indicate what the incorrect url is.

**Comment by ThiefMaster** [comment]
Please do not open issues for such simple improvements. A PR is more than enough.

**Comment by TheGreatAlgo** [comment]
my bad, was just following recommendations listed when opening a pr

**Comment by ThiefMaster** [comment]
that's meant for bigger developments so people don't waste time for something we're never going to merge
