### ISSUE TITLE
Option to allow headers with underscores in development server

### ISSUE THREAD

**Issue by hayd** [pallets/werkzeug#2781]
Prior to https://github.com/pallets/werkzeug/pull/2622 headers with underscores were not ignored in the development server.

Our production WSGI server does not ignore these headers, and unfortunately for legacy reasons we must support them.

Prior to werkzeug 2.3 we were able to replicate this behavior in our unit tests (using the development server). It would be great to continue to be able to do going forward with something like [nginx's underscores_in_headers](https://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers).

**Comment by davidism** [comment]
You can use any production WSGI server during development, if the development server does not support a feature you need.

**Comment by hayd** [comment]
True. To confirm there's no possibility of accepting a PR to support this?
