### ISSUE TITLE
Regression issue with PathConverter?

### ISSUE THREAD

**Issue by CrashLaker** [pallets/werkzeug#2783]
Hi all,

I used to use the following code to regex match any route on my flask application.
https://stackoverflow.com/questions/24000729/flask-route-using-path-with-leading-slash

here's a sample code
```python
from flask import Flask, request, jsonify, json, abort, redirect, url_for, render_template
from werkzeug.routing import PathConverter

class EverythingConverter(PathConverter):
    regex = '.*?'

app = Flask(__name__, template_folder='template')
app.url_map.converters['everything'] = EverythingConverter

@app.route('/<everything:path>', methods=['GET', 'POST'])
def main(path=""):
    return path

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=9009)
```
when browsing for example `:9009/foo/bar` it would return `foo/bar`

I can reproduce this on
`Flask==2.0.3`
`werkzeug==2.0.3`

but this doesn't work on `werkzeug==2.3.7`

i'm not sure this is related to the changes on slash behavior.

can anyone help me?

regards,c.

**Comment by pgjones** [comment]
You need to mark your custom converter as not [part isolating](https://werkzeug.palletsprojects.com/en/2.3.x/routing/#custom-converters),
```python
class EverythingConverter(PathConverter):
    regex = '.*?'
    part_isolating = False
```

See also https://github.com/pallets/werkzeug/pull/2784
