### ISSUE TITLE
The `Aborter` class does not set the `code` attribute on the exception it raises if it receives a `Response`

### ISSUE THREAD

**Issue by lkk7** [pallets/werkzeug#2793]
**Bug:**
The `Aborter` class does not set the `code` attribute on the exception it raises, if it receives a `Response`. This issue does not occur if an int is passed.
This part:
```python
        if isinstance(code, Response):
            raise HTTPException(response=code)
```
Creates a `HTTPException`, but doesn't set it's `code`, which might be used by other libraries (e.g. flask-restx)

**A minimal reproducible example:**
Modify the test `test_proxy_exception` in `tests/tests_exceptions.py` to actually check if the HTTPException has the correct code:
```python
def test_proxy_exception():
    orig_resp = Response("Hello World", status=200)
    with pytest.raises(exceptions.HTTPException) as excinfo:
        exceptions.abort(orig_resp)
    resp = excinfo.value.get_response({})
    assert excinfo.value.code == 200 # <--------- This fails
    assert resp is orig_resp
    assert resp.get_data() == b"Hello World"
```

**Expected behavior:**
The test passes.

**Environment:**
- Python version: 3.11
- Werkzeug version: 3.0.0 and earlier

**Comment by davidism** [comment]
This is intentional. You are creating the response, you can already set it's code.

**Comment by lkk7** [comment]
Understood 😄

**Comment by lkk7** [comment]
@davidism  But why shouldn't the exception have the same code as the response? Especially if it's an explicit field in HTTPException made for that.

**Comment by lkk7** [comment]
Sorry to spam you with messages, just the last clarification: 
The aborter raises a `HTTPException`. It doesn't set the status code.
Another library handles the `HTTPException`. It tries to access `e.code` and errors out.

Do you suggest to use `e.reponse.status_code` instead of that? I get it. It may be confusing, but if that's the decision, I'll go with a PR for the other library
