### ISSUE TITLE
Aliases for url_decode and url_encode for backwards compatibility

### ISSUE THREAD

**Issue by Nixellion** [pallets/werkzeug#2802]
I'd like to propose a change that can potentially restore backwards compatibility with a large number of projects that rely on `werkzeug` and import it's `url_encode` and `url_decode` functions, projects like flask-login.

I propose adding simple aliases from `url_en\decode` to equal `urllib.parse` functions in a form of simple variables or wrapper functions that will also display a deprecation warning to urge people to fix their code.

Here's an example of one approach, these two lines could be simply added at the end or beginning of `werkzeug.urls`:

```python
url_decode = unqoute
url_encode = urlencode
```

As a test I've already implemented this change by monkey_patching werkzeug.urls in my own projects, and it "fixes" incompatibility with other projects like flask-login:

```python
# region Patch werkzeug
import werkzeug.urls
werkzeug.urls.url_decode = werkzeug.urls.unquote
werkzeug.urls.url_encode = werkzeug.urls.urlencode
# endregion
```

**Comment by ThiefMaster** [comment]
Not all those functions are *exact* drop-ins. For example, url_split had a .host, while urlsplit's return value has .hostname

**Comment by davidism** [comment]
You can read in great detail why the changes were made in https://github.com/pallets/werkzeug/issues/2600, https://github.com/pallets/werkzeug/issues/2406, and https://github.com/pallets/werkzeug/pull/2608. Our previous implementation was a copy/modification from ancient versions of Python. Replacing them provides better performance and security through Python itself. Before being removed, they all showed deprecation warnings first.

**Comment by Nixellion** [comment]
@ThiefMaster That may be so, but from what I can see majority of other tools and flask extensions used only those two.

@davidism I understand why the changes were made, and I was not suggesting to keep old implementations, merely the naming alias. This should not be affecting performance in any way.
