### ISSUE TITLE
A new converter to match any text including slashes and newlines

### ISSUE THREAD

**Issue by alexprengere** [pallets/werkzeug#2803]
I am developing a Flask application where I support a url allowing for input text:

```python
app = Flask(__name__)

@app.route("/text/<message>")
def index_with_text(message):
    ...
```

In my case the `message` can be a XML message, so it can have forward slashes (`%2F`)and encoded newlines (`%0A`).
The default url routing makes it so forward slashes are excluded from `message`, so I tried using `<path:message>`.
Unfortunately this does not work, as newlines now break the routing.
Diving into Werkzeug internals for both converters:

* `BaseConverter` uses `regex = "[^/]+"`
* `PathConverter` uses `regex = "[^/].*?"`

In Unix, newlines are possible in filenames, so one could argue that the `PathConverter` behavior should also capture newlines.
For my application I just created a new converter:

```python
from werkzeug.routing import BaseConverter

class MsgConverter(BaseConverter):
    regex = r"[^/][\s\S]*?"  # \s\S means anything including newlines
    part_isolating = False

app.url_map.converters["msg"] = MsgConverter
```

This left me wondering about two things:

* should `PathConverter` be tweaked as to allow for newlines?
* if not, should a new converter be added to cover this use case of "any text"?

Thanks a lot!

**Comment by ThiefMaster** [comment]
IMHO linebreaks have no place in a URL... I strongly suggest using POST data for this.

Also, you can write your own converter if you REALLY need this. It's certainly not something that makes sense upstream.
