### ISSUE TITLE
ImportError: cannot import name 'url_encode' from 'werkzeug.urls' on 3.0.1

### ISSUE THREAD

**Issue by GavBurke** [pallets/werkzeug#2807]
Describe how to replicate the bug.

Upgrade from 2.2.3 of werkzeug to 3.0.1 (maybe even 3.0.0) and see you can no longer import url_encode 

Environment:

- Python version: 3.9
- Werkzeug version: 3.0.1

**Comment by ThiefMaster** [comment]
You need to read changelogs before updating, even more so in case of major version bumps (even though we don't really do semver)... Those utils have been deprecated for some months (you should test your code w/ DeprecationWarnings enabled) and removed in 3.0.
