### ISSUE TITLE
Werzueg's full_path implementation always appends '?', even when the query string is empty.

### ISSUE THREAD

**Issue by naumanahmedkhan** [pallets/werkzeug#2816]
Werzueg's full_path implementation always appends '?', even when the query string is empty.

The issue can be replicated by using flask API in python with Werzueg and use the request.full_path function with empty query string.
The url should be the same and no ? should be appended at the end of the url. 

Environment:

- Python version: 3.11.4
- Werkzeug version: 3.0.1

**Comment by RonnyPfannschmidt** [comment]
The addition is intentional to denote query Parameters

**Comment by naumanahmedkhan** [comment]
It is appending ? at the end even though there are no query parameters present.

**Comment by RonnyPfannschmidt** [comment]
Exactly, this explicitly indicates that the query Parameters where included in the value to avoid confusion between the case where the parameters where split

**Comment by davidism** [comment]
An empty query is equivalent to no query part. The URL is valid and does not change meaning with an empty query. It does represent the _full_ URL. If you want a value without it, you can override `Request.full_path` or do `request.full_path.removesuffix("?")`.
