### ISSUE TITLE
incorrect documentation for MultiDict.items()

### ISSUE THREAD

**Issue by lmaddox** [pallets/werkzeug#2817]
documentation (https://werkzeug.palletsprojects.com/en/3.0.x/datastructures/#werkzeug.datastructures.MultiDict) is wrong.

"""
items(multi=False)
Return an iterator of (key, value) pairs.

Parameters:
multi – If set to True the iterator returned will have a pair for each value of each key. Otherwise it will only contain pairs for the first value of each key.
""""

steps to reproduce:

```
└─$ python  
Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import multidict
>>> m = multidict.MultiDict()
>>> m.items(multi=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: MultiDict.items() takes no keyword arguments
```

**Comment by davidism** [comment]
You imported `multidict`. That's a different package than `werkzeug`.
