### ISSUE TITLE
Update runtime dependencies

### ISSUE THREAD

**Issue by alperak** [pallets/werkzeug#2851]
Hi, I'm working on Yocto and list all of the modules that had to be installed before WerkZeug would import successfully. Accordingly to this, the dependencies variable in pyproject.toml needs to be updated.

ModuleNotFoundError: No module named 'json'
ModuleNotFoundError: No module named 'logging' 
ModuleNotFoundError: No module named 'dataclasses'
ModuleNotFoundError: No module named 'zipfile'

The Python standard library has been split into some subpackages for Yocto, so we don't have to install the whole stdlib if it's not needed.

**Comment by ThiefMaster** [comment]
we're not going to list stdlib modules in there... install_requires is for external dependencies
