### ISSUE TITLE
Random "ssl.SSLEOFError: EOF occurred in violation of protocol" when handling HTTP 206

### ISSUE THREAD

**Issue by xuancong84** [pallets/werkzeug#2852]
I am hosting the Python Flask server on Raspberry Pi 4 (Linux arm64) and accessing the server from Ubuntu/Debian (Linux amd64).
Hosting website using HTTP (`app.run(host='0.0.0.0', port=port)`) works but if I use HTTPS (`app.run(host='0.0.0.0', port=port, ssl_context='adhoc')`), the following error occurs randomly only on **HTTP 206 requests** (HTTP Ranged Get Request).

```
192.168.50.30 - - [20/Feb/2024 09:46:45] "GET /files/foreign/Belki%20Üstümüzden%20Bir%20Kuş%20Geçer.mp4 HTTP/1.1" 206 -
Error on request:
Traceback (most recent call last):
  File "/home/xuancong/miniconda3/lib/python3.10/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/xuancong/miniconda3/lib/python3.10/site-packages/werkzeug/serving.py", line 326, in execute
    write(data)
  File "/home/xuancong/miniconda3/lib/python3.10/site-packages/werkzeug/serving.py", line 301, in write
    self.wfile.write(data)
  File "/home/xuancong/miniconda3/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
  File "/home/xuancong/miniconda3/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/home/xuancong/miniconda3/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2426)
192.168.50.30 - - [20/Feb/2024 09:46:45] "GET /files/foreign/Belki%20Üstümüzden%20Bir%20Kuş%20Geçer.mp4 HTTP/1.1" 206 -
192.168.50.30 - - [20/Feb/2024 09:46:45] "GET /files/foreign/Belki%20Üstümüzden%20Bir%20Kuş%20Geçer.mp4 HTTP/1.1" 206 -
```

So is the bug in Python SSL or werkzeug? I am using the latest version Flask and werkzeug up to today. Thanks!

**Comment by davidism** [comment]
This appears to be an issue with ssl, given where the error is coming from. Werkzeug isn't doing anything special here.

That said, you must never use the development server to deploy to production. It is not secure, stable, or efficient. See https://flask.palletsprojects.com/deploying/

**Comment by xuancong84** [comment]
> This appears to be an issue with ssl, given where the error is coming from. Werkzeug isn't doing anything special here.
> 

Yup, from the stacktrace, it seems so. But consider the fact that this only happens on HTTP 206 request but not others, I don't think it is SSL library issue because at SSL level, it does not really distinguish between HTTP 206 or otherwise.
