### ISSUE TITLE
TLS connection not properly closed

### ISSUE THREAD

**Issue by phoebusm** [pallets/werkzeug#2868]
I am testing `moto` with `werkzeug` for some S3 connection test. The client uses `libcurl` as the backend.
During the test, I encountered error
`OpenSSL SSL_read: Connection closed abruptly, errno 0 (Fatal because this is a curl debug build)`
which in https://github.com/curl/curl/blob/fd1260d492f9fb4d16c5abd22a58de959f49dcf8/lib/vtls/openssl.c#L4759, suggests `close_notify` was not sent before the end of the session.
I have found some [discussion](https://security.stackexchange.com/questions/82028/ssl-tls-is-a-server-always-required-to-respond-to-a-close-notify) online regarding this matter and it suggests `close_notify` should be sent.

```
werkzeug.run_simple(
            "0.0.0.0",
            port,
            _HostDispatcherApplication(create_backend_app, service="s3"),
            threaded=True,
            ssl_context=(cert_file, key_file) if cert_file and key_file else None,
        )
```

`close_notify` sent at the end of the session

Environment:

- Python version: 3.10
- Werkzeug version: 3.0.1

**Comment by davidism** [comment]
Werkzeug is a basic wrapper around Python's built-in `http.server`, you'll want to report that to them with a minimal reproducible example.
