### ISSUE TITLE
`TypeConversionDict.pop` could pop with type

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [pallets/werkzeug#2883]
TypeConversionDict provides a `type` argument for the `get` method, but does not do the same for `pop`. Currently this is the way to do a typed pop:

```python
d = TypeConversionDict(foo='99', bar='baz')
v = d.get('foo', type=int)
if v is not None:
     d.pop('foo')
reveal_type(v)  # int | None
```

I propose:

```python
d = TypeConversionDict(foo='99', bar='baz')
v = d.pop('foo', type=int)  # currently this does not work
reveal_type(v)  # int | None
```

Implementation suggestion:

```python
  def pop(self, key, default=_missing, type=None):
      value = self.get(key, default, type)
      if value is _missing:
          raise KeyError(key)
      del self[key]
      return value
```

I'm using `_missing` to correct reproduce the behaviour of pop, and re-using `self.get` sice we don't want the item to be pop-ed if the type-conversion fails (yes??. i guess that's the tricky bit, no?)

**Comment by davidism** [comment]
After discussing it with other maintainers, we don't want to accept the additional complexity right now, when Werkzeug itself won't use it. Thanks for working on this.

**Comment by MarcinKonowalczyk** [comment]
Cool. No worries! Thanks for considering! :))
