### ISSUE TITLE
replace pytest-xprocess

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#2906]
Pytest-xprocess has been really helpful to running our dev server tests. But we're not doing anything super complicated, and its API may be adding complexity. And it causes a bunch of resource warnings when pytest ends (luckily these don't count as errors).

I think I had seen a project from @pamelafox that used plain `multiprocessing` or `subprocess` to manage a live server directly. See about switching our tests to something like that.

**Comment by pamelafox** [comment]
I think this is the one you're thinking of:
https://github.com/Azure-Samples/azure-flask-postgres-flexible-aca/blob/main/src/tests/local/conftest.py

I believe its now finally working on the Windows test runner, that was what
we were trying to fix last time I worked on that project.
