### ISSUE TITLE
Doesn't work on FUSE file systems

### ISSUE THREAD

**Issue by LittleLightLittleFire** [pallets/werkzeug#2950]
Run reloader on any FUSE filesystem.
FUSE does not support inotify, the current implementation defaults to 'auto' which defaults to 'inotify' when `watchdog.observes` exists (https://github.com/pallets/werkzeug/blob/main/src/werkzeug/_reloader.py#L405)

Needs a switch to force 'auto' to 'stat' mode, possibly via environmental variables so that it can be user controlled.

Environment:

- Python version: all
- Werkzeug version: all

**Comment by davidism** [comment]
`run_simple(..., reloader_type="stat")`
