### ISSUE TITLE
inline type annotations for datastructures

### ISSUE THREAD

**Issue by davidism** [pallets/werkzeug#2970]
Currently we have a bunch of `.pyi` files with the annotations, because Python <= 3.8 didn't support generic `list` and `dict` subclassing. Now that we support >= 3.9, we should be able to move all the annotations into the Python code and remove the stubs.

**Comment by sgaynetdinov** [comment]
@davidism Hi, is this task available?

**Comment by davidism** [comment]
I'm currently most of the way through it, thanks for offering though!
