### ISSUE TITLE
Receiving 413 - RequestEntityTooLarge response

### ISSUE THREAD

**Issue by decarmona** [pallets/werkzeug#2999]
Hello!

I've been using Flask v3.0.0 with Werkzeug v3.0.6 

I recently updated to Flask 3.0.3 which the update came with Werkzeug 3.1.2 but now one of my endpoints (responsible for uploading files) suddenly started responding with 413 RequestEntityTooLarge.

- Originally, MAX_CONTENT_LENGTH at Flask was left unset. Tried setting it to a higher value but the issue persists.
- Only happens with files larger than 100 KB.
- Downgraded Werkzeug to v3.0.6 and the issue was gone/fixed.

Thank you guys for your amazing support! <3

Environment:

- Python version: 3.11.10
- Werkzeug version: 3.1.2

**Comment by davidism** [comment]
Be sure to include a minimal reproducible example when reporting an issue. I can't reproduce this issue with the information provided. Uploading a file > 100kb (or > 1GB) does not raise an error. Perhaps you're seeing the new default `max_form_memory_size` introduced in #2964, but that deals with non-file fields only.
