### ISSUE TITLE
Secret key rotation with SecureCookie sessions

### ISSUE THREAD

**Issue by foresto** [pallets/werkzeug#31]
One of the shortcomings I've found in every existing python web session library is that they don't support secret key rotation.  It's one of the best ways I know of to protect against brute force and hash algorithm attacks, so I've been looking into implementing it with Werkzeug SecureCookie (and Flask sessions).  Getting my web application to periodically generate a new secret key seems easy enough.  The tricky part is getting the securecookie code to manage multiple keys properly.  I think it would have to work something like this:
1. Keep a list (or ring buffer) of secret keys instead of just one.
2. When signing a cookie, use the newest key that's at least a few minutes old.
   (Don't use brand new keys because other web server instances might not have them yet.)
3. When validating a signed cookie, try every key in the list.
   (In case a new key was added after the cookie was last signed.)
4. Allow the web application to periodically rotate the keys, adding a new one and deleting the oldest one.

I looked into implementing this behavior in a SecureCookie subclass, but it looks like the hmac-related code is pretty well entwined with the other code in serialize() and unserialize(), making it a little difficult to do cleanly.  (Especially item 3: validating against multiple keys.)  Would you consider breaking the signing and validation code into separate methods, in such a way that key rotation would be easy to implement?

If it worked well, perhaps key rotation could even become a standard feature in SecureCookie.  (That would be reason enough for some of us to use it instead of the various other web session libraries available for python.)

**Comment by BabakMN** [comment]
Is there any updates on this topic? If someone provides some guidance I may be able to contribute a patch.

**Comment by rohitchormale** [comment]
any update on this ?

**Comment by davidism** [comment]
If anyone's interested in this, it's probably reasonable to implement it on top of itsdangerous, which is what Werkzeug's implementation should switch to anyway.
