### ISSUE TITLE
adopt a middleware?

### ISSUE THREAD

**Issue by ThomasWaldmann** [pallets/werkzeug#35]
http://hg.moinmo.in/moin/2.0-dev/file/tip/contrib/wsgi/

maybe some stuff from there could be useful in werkzeug (or at least the ideas):

- profiling
- proxy (done differently than in werkzeug)

If it was in werkzeug, I could get rid of it there and maybe some other people would find it useful, too.

**Comment by RonnyPfannschmidt** [comment]
in accordance with #4 this should probably be closed
