### ISSUE TITLE
non-latin urls

### ISSUE THREAD

**Issue by anna-hope** [pallets/werkzeug#374]
I encountered this bug while using the latest sprint code from Flask, but I assume it's Werkzeug-level.

If I register a URL that has non-latin characters (particularly, cyrillic), it doesn't work. The request seems to invariably go for ÑÐµÑÑ, whatever that is (not cyrillic), and therefore result in a 404 or something of the sort.

I've been staring at what I think might be relevant pieces of code, but I can't nail it down to where the issue might be.

In Python 2, if there is a route of the form /someurl/<name> where 'name' is cyrillic, it fetches the correct page. In Python 3, it gives me a 404.

I've also checked and found out that registering non-latin routes at top level (/некий-урл) crashes the Python 2 instance of Werkzeug completely, whereas the Python 3 instance doesn't register non-latin view functions at all (but doesn't crash).

**Comment by a0c** [comment]
Hi all!
I've an issue similar to this one, with non-latin URLs, which I have [posted](https://www.odoo.com/forum/help-1/question/non-ascii-unicode-cyrillic-url-on-website-106812) on Odoo's Help Forum.
Can you give me a hint on why non-latin URLs are failing on the werkzeug level?

#### FIX?
As far as I could debug it, it seems that [wsgi_decoding_dance() method](https://github.com/pallets/werkzeug/blob/master/werkzeug/_compat.py#L97) should look similar to [wsgi_encoding_dance() method](https://github.com/pallets/werkzeug/blob/master/werkzeug/_compat.py#L100) and should have this check at the beginning of it:
```python
        if isinstance(s, unicode):
            return s
```
