### ISSUE TITLE
SharedDataMiddleware does not support unicode paths

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/werkzeug#379]
The static file serving currently does not support unicode paths on either 2.x or 3.x but it fails in different ways.  On Python 3 it lacks the WSGI encoding dance and on 2.x it hopes the URL encoding is the FS encoding.

**Comment by davidism** [comment]
I can't reproduce this issue. I created a file called `実験.txt` and used the following app:

```python
from werkzeug.exceptions import NotFound
from werkzeug.middleware.shared_data import SharedDataMiddleware

@Request.application
def app(request):
    return NotFound()

app = SharedDataMiddleware(app, {"/static": ""})
```

```
python -m werkzeug.serving example:app
```

Navigating to `https://127.0.0.1:5000/static/実験.txt` correctly served the file with Python 2 and Python 3.
