### ISSUE TITLE
Test client incorrectly follows redirects with a non-root base_url

### ISSUE THREAD

**Issue by SimonSapin** [pallets/werkzeug#382]
Hi,

When using the test client with `follow_redirects=True` and a `base_url` that has a non-root path, the client makes redirected requests with the base path includes once too many times. Test case:

```
from flask import Flask, redirect, url_for, abort

app = Flask(__name__)

@app.route('/create/')
def create():
    return 'create'

@app.route('/edit/')
def edit():
    return redirect(url_for('create'))

@app.route('/<path:path>')
def catch_all(path):
    print(path)
    abort(404)

print(app.test_client().get(
    '/edit/', base_url='/not-root/', follow_redirects=True))
```

Output:

```
not-root/create/
<Response streamed [404 NOT FOUND]>
```

Expected output: a single line with a 200 response.

**Comment by untitaker** [comment]
Looked into this and think it's a design flaw -- postponing.

**Comment by byeskille** [comment]
What is the status of this?
Is it possible to solve? Or maybe there is a simple workaround in some cases?

I think I am experiencing this in the same way as described in the issue [SimonSapin/Frozen-Flask#34](https://github.com/SimonSapin/Frozen-Flask/issues/34)

I have forked the flask app [pulse](https://github.com/18F/pulse) with [additions](https://github.com/robbi5/pulse) from @robbi5 

When running [the script](https://github.com/byeskille/pulse/blob/norway/freeze.py) utilizing [`flask_frozen` ](https://github.com/SimonSapin/Frozen-Flask)it runs just fine if the `base_url` is the root of the domain.

When I add a subdirectory it fails in just the same way as described by @mblayman in [Frozen-Flask#34](https://github.com/SimonSapin/Frozen-Flask/issues/34) with 404´s.
See: https://gist.github.com/byeskille/e55e81b73174c2df8671b9054284781e

**Comment by untitaker** [comment]
This is absolutely a bug, but nobody has offered a bugfix yet...

**Comment by honzajavorek** [comment]
If I'm to provide a patch, could someone guide me through a bit? What would be needed to be done?
