### ISSUE TITLE
POSTing to a GET endpoint may trigger an unexpected redirect when another rule also matches the url

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/werkzeug#397]
I have route for `/foo/<path:bla>/` and one for `/foo/<xyz>/foobar`. The latter is more specific and thus the first rule only matches if the second rule did not match.

However, when sending a POST request to the second url I get a slash-adding redirect triggered by the first rule instead of the expected 405 error.

Demo: https://gist.github.com/ThiefMaster/5806003

**Comment by edk0** [comment]
The testcase behaves correctly now.
