### ISSUE TITLE
Remove unnecessary crud from werkzeug.contrib

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/werkzeug#4]
Some things ended up in contrib that really shouldn't have been there.

**Comment by untitaker** [comment]
I wonder if we should move even more modules into separate packages, even though they are directly relevant to Werkzeug.

An example would be `werkzeug.urls`: A general-purpose backport of `urllib.parse` is extremely useful outside of Werkzeug's context, and it'd be very useful to have potentially more maintainers on it who are otherwise not interested in using Flask or Werkzeug.

**Comment by RonnyPfannschmidt** [comment]
i like the idea, but it needs some preparation and thougts

**Comment by asteinlein** [comment]
I could be interested in helping out here, but would obviously need some decisions being made here. One idea would be extract some parts to external packages, i.e. `werkzeug.contrib.cache` to `werkzeug-cache` or some such, middlewares to `werkzeug-middleware`, etc.

We could for instance include these packages as dependencies in Werkzeug for a while and alias them in their existing locations for backwards compatibility, while emitting deprecation warnings about their future removals.

**Comment by RonnyPfannschmidt** [comment]
sounds like a good plan to me, @mitsuhiko @untitaker do you agree?

in case the others agree i propose providing @asteinlein with a repo under pallets for werkzeug-cache as a starting point and using werkzeug_cache as potential module name

**Comment by untitaker** [comment]
Agreed! Will set up a repo later.

IIRC somebody already forked Werkzeug's profiler middleware into a new package.
We should seek collaboration from that person.

**Comment by asteinlein** [comment]
IMO we should have one repo with a collection of useful middlewares, i.e. a
werkzeug-middleware, since many use cases are useful to provide defaults
for. Having multiple repos for different middlewares seems overkill to me.

Just my 2c though. :)

**Comment by untitaker** [comment]
Middlewares will require more discussion, what ones to keep in Werkzeug and what not.

The things that IMO definetly can be factored out are:

* cache
* atom
* fixers
* profiler

**Comment by untitaker** [comment]
Let's start with `cache`: https://github.com/pallets/werkzeug-cache

@asteinlein I've added you as a collaborator to werkzeug-cache, @RonnyPfannschmidt you're a member anyway.

**Comment by untitaker** [comment]
Oh, I forgot that `werkzeug.locals` is a candidate as well!

**Comment by davidism** [comment]
`werkzeug.contrib.wrappers` contains some interesting request/response mixins.  At least `ProtobufRequestMixin` should probably go.  The rest should move into `werkzeug.wrappers`.  I'm already doing this for `JSONRequestMixin`.  (It might be a good idea to split `wrappers` into two moduels, `request` and `response`.)

**Comment by mitsuhiko** [comment]
+1 on these:

* move local into a repo
* move cache into a repo
* find a solution for contrib wrappers

-1 on urls

Two reasons for this: a) i don't want to start having tiny dependencies everywhere. This is a huge maintenance hurdle and I keep learning this over and over at Sentry. Secondly because it's not even an entirely correct implementation of URLs.

**Comment by untitaker** [comment]
@mitsuhiko I was proposing `urls` because I once needed something that behaves the same on both Py2 and Py3 and didn't want to depend on a WSGI library for that.

**Comment by lepture** [comment]
@untitaker why the repo (https://github.com/pallets/werkzeug-cache) is deleted?

**Comment by untitaker** [comment]
@lepture i cannot remember but i think the transition was not properly coordinated, people still submitted PRs

**Comment by lepture** [comment]
@untitaker I'm closing issues related to cache. https://github.com/pallets/werkzeug/issues/1249

I'll make a separated repo in next week.

**Comment by lepture** [comment]
Created https://github.com/pallets/cachelib

**Comment by davidism** [comment]
I added cards for all the `contrib` code to https://github.com/pallets/werkzeug/projects/2

**Comment by davidism** [comment]
I didn't add a card for `werkzeug.local` because it's not in `contrib`, although we may still want to extract it eventually.

**Comment by davidism** [comment]
Things I marked as "discuss":

- [ ] `wrappers.RoutingArgsRequestMixin` - seems to be a spec that was never adopted, although it almost matches Flask, which sets `Request.view_args` during route matching.
- [ ] `wrappers.ReverseSlashBehaviorRequestMixin` - not sure when this would be used, seems like other code in Werkzeug is handling leading and trailing slashes
- [ ] `fixers.PathInfoFromRequestUriFix` - is this still a problem with Windows? Is CGI on Windows Apache something we need to keep a fixer for?
- [ ] `fixers.HeaderRewriterFix` - not sure if this is worth maintaining. It's pretty straightforward for an app to implement exactly what they need, with more nuance than this gives. The examples (removing Date, adding X-Powered-By`) both seem to be bad practice (mandatory header, fingerprinting information).

**Comment by davidism** [comment]
Marking this for 0.15 to deprecate everything that needs to be. We can have a separate task to remove deprecated code for 1.0, which will include more than this.
