### ISSUE TITLE
Response.age mishandled as datetime instead of int (or timedelta)

### ISSUE THREAD

**Issue by cvrebert** [pallets/werkzeug#408]
Environment:

```
Flask==0.10.1
Werkzeug==0.9.1
```

Test case:

``` py
#/usr/bin/env python2.7
from flask import Flask, Response

app = Flask(__name__)

@app.route('/')
def root():
    resp = Response()
    resp.age = 42
    return resp

if __name__ == "__main__":
    client = app.test_client()
    resp = client.get('/')
    print "age property:", resp.age
    print "Age header:", resp.headers['Age']
```

Result:

```
age property: 1970-01-01 00:00:42
Age header: Thu, 01 Jan 1970 00:00:42 GMT
```

Expected `42` instead in both cases (though personally I'd optimally prefer `timedelta(seconds=42)` in the former case).
[The HTTP spec says (in part; emphasis added):](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)

> The Age response-header field conveys the sender's estimate of the **amount of time** since the response (or its revalidation) was generated at the origin server.
> `age-value = delta-seconds`
> Age values are **non-negative decimal integers**, representing time in seconds.

**Comment by untitaker** [comment]
Will be fixed in 1.0.
