### ISSUE TITLE
is_resource_modified() should work for methods besides GET

### ISSUE THREAD

**Issue by zhangchunlin** [pallets/werkzeug#409]
https://github.com/pallets/werkzeug/blob/5444a6f2c373064bb138447af0be2d72e0fa6b86/werkzeug/http.py#L893-L894

If the request method is post, but I want to return a different file every time, then this should not return false.

**Comment by untitaker** [comment]
@davidism I think that was my intention but I am not sure if that's a good idea anymore.

**Comment by untitaker** [comment]
My edit looks like I saw an issue with it and just postponed the decisioo to 1.0 without really knowing what to do

**Comment by davidism** [comment]
As far as I can tell from the RFC the change to check `is_resource_modified` on all methods would have been correct. Setting the headers only happens on GET, but responding to them them can happen with any method.
