### ISSUE TITLE
~30% Performance Hit on 0.8.3 -> 0.9.4

### ISSUE THREAD

**Issue by Julian** [pallets/werkzeug#429]
Hey.

Haven't really tracked this down or even looked at your diff between these versions, but I'm reporting it ahead of time since I'm not sure I'll have time to do that.

We have a fairly simple service (~1ms response times for endpoints), and in a quick upgrade to 0.9.4 saw a ~30% slowdown on response time and ~10% increase in CPU usage.

Guessing this is due to some additional string handlings somewhere, I know that was one thing you were talking about recently. Not sure there's an actual issue, but bringing it up just in case. For us this was quite significant.

**Comment by alanhamlett** [comment]
Is this using the packaged dev server? If yes, then it could be related to the stat reloader and #682

**Comment by untitaker** [comment]
The Python 3 port occured far before the new reloader. I don't think this is related.
