### ISSUE TITLE
LanguageAccept.best_match() - better fallback

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/werkzeug#450]
```
>>> parse_accept_header('en-us', LanguageAccept).best_match(['en', 'de'])
>>> parse_accept_header('en', LanguageAccept).best_match(['en-us', 'de'])
```

Both those calls return `None`. I'm not sure if there's a RFC specifying the behaviour for this but shouldn't a territory-less language _always_ work if there's no exact match available? I.e. if the client specified `en-us`, `en` would be fine and more important, if the client specified `en` and the server just knows `en-us` that one should be used.

This is important in cases like the following one: There's an application using Flask-Babel which has english as its native language (i.e. hardcoded) because it's nice to keep code in english and a translation, e.g. german. That language is the default language though (because the main audience of the site speaks german). However, if a client sends an Accept-Languages for `en` (or any  `en-*`) the english "translation" should be used. But without specifying `en` and all `en-*` language codes when calling `best_match()` it will return `None` (or `de` depending on the passed arguments) instead - even though the user's header clearly says he prefers english.

**Comment by lassecph** [comment]
I had problems matching various german accept_languages, foreinstance de-de, de-at. This seems to work for me (all de-de or de-at will be 'de'):

`@babel.localeselector
    def get_locale():
        locale = request.cookies.get('locale')

        if not locale:
            for lang in request.accept_languages.values():
                if lang[:2] in ['de', 'en']:
                    locale = lang[:2]
                    break

        if not locale:
            locale = 'en'

        g.locale = locale
        return locale`

**Comment by lafrech** [comment]
> Babel has a function negotiate_locale which does exactly what I'm suggesting here.
> 
> ```
> @babel.localeselector
> def get_current_locale():
>     preferred = [x.replace('-', '_') for x in request.accept_languages.values()]
>     return negotiate_locale(preferred, AVAILABLE_LOCALES)
> ```

I'm not sure this covers every cases.

If my application defines locales as lang_territory and the browser sends a request as lang_territory where only lang matches:

```py
from babel import negotiate_locale
AVAILABLE_LOCALES = ['en_US', 'de_DE']
negotiate_locale(['en_EN'], AVAILABLE_LOCALES)  # returns None
```

Isn't this the typical use case?

Or am I missing something?

**Comment by arthurwhite** [comment]
> This leaves out matching based on quality though. So this solution isn't technically correct. I'm not really sure whether it is preferred for the fix to be in werkzeug or in babel. best_match does do quality matching, but babel doesn't. — @budlight

No, the @ThiefMaster snippet is correct as an [`Accept`](https://github.com/pallets/werkzeug/blob/b7c88324054e99c1a8bf124173c3ab3c14cebc28/werkzeug/datastructures.py#L1601) object is automatically sorted by quality (from 1 to 0) so [`negotiate_locale`](https://github.com/python-babel/babel/blob/ead6ed984fee9019b94700068f553223ad30b012/babel/core.py#L979) tries to match the most preferred first.

@lafrech
Your case also must work. But it's a Babel issue.

**Comment by kramred** [comment]
Just stumbled upon this behaviour and thought/think it is a bug, tracked it down to the 
`class LanguageAccept(Accept):` in datastructures.py
where it should be `return _locale_delim_re.split(language.lower())[0]` with the **`[0]`** added inside
`
def _value_matches(self, value, item):
  def _normalize(language):
`
Will add more info later, see [this gist](https://gist.github.com/kramred/b25a0eda206f83a8f07f0a289cdfacd1) for testing

**Comment by arthurwhite** [comment]
I already have submitted a PR for this issue: https://github.com/pallets/werkzeug/pull/1020.

As we see, almost 4 years later, this issue is still open… Meanwhile, Node.js with the [i18n](https://github.com/mashpie/i18n-node) module continues to handles the job perfectly. ⌛️

**Comment by TimotheeJeannin** [comment]
Any updates on this ?

**Comment by lepture** [comment]
I thought https://github.com/pallets/werkzeug/pull/1065 has done the work. cc @ThiefMaster

**Comment by chivalry** [comment]
I've submitted a PR for this, would love to get feedback.

https://github.com/pallets/werkzeug/pull/1507

**Comment by Dreamsorcerer** [comment]
The negotiate_locale() workaround doesn't even work as expected by this thread. e.g.
`negotiate_locale(('en',), ('en_gb', 'de'))`
Returns None. The original example with en_us only works due to it being an alias for en in the default kwargs.
