### ISSUE TITLE
Reloader, python -m, and sys.path

### ISSUE THREAD

**Issue by SimonSapin** [pallets/werkzeug#461]
See https://github.com/Kozea/WeasyPrint/issues/133

What’s going on is:
- `python -m weasyprint.navigator` is run
- `[sys.executable] + sys.argv` is `['…/python', '…/weasyprint/navigator.py']`
- The reloader spawns a subprocess that way
- The child process does not have `-m`, so Python add’s the .py file’s parent directory to `sys.path`
- Werkzeug tries to import stdlib’s `html.entities`
- This incorrectly imports `weasyprint/html.py`
- Stuff breaks

Nobody here is doing anything obviously wrong. How do you suggest dealing with this situation? What do you think of having `…/weasyprint/navigator.py` (which is expected to be mostly used with `python -m`) remove its parent directory from `sys.path` if it’s there?

**Comment by waynew** [comment]
I just came across this bug myself. I expected the `-m` flag to be present in `sys.argv`, but it most definitely isn't.

Is there any kind of workaround for this?

**Comment by untitaker** [comment]
Yes, one is presented in https://github.com/mitsuhiko/flask/issues/1246

On 9 July 2015 15:08:30 CEST, Wayne Werner <notifications@github.com> wrote:
>I just came across this bug myself. I expected the `-m` flag to be
>present in `sys.argv`, but it most definitely isn't.
>
>Is there any kind of workaround for this?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/werkzeug/issues/461#issuecomment-119955695

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by martijnvermaat** [comment]
I have a similar issue, where relative imports fail because the reloader executes the module as a non-package:

```
$ python -m myapp.entrypoints.website
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "/tmp/myapp/entrypoints/website.py", line 9, in <module>
    from . import mymodule
ValueError: Attempted relative import in non-package
```

Using the comments from @untitaker, in Python < 3.3 we can detect if `python -m` was used (only then is `__loader__` defined) and force the reloader to also use it by resetting `sys.argv`:

```python
try:
    sys.argv = ['-m', __loader__.fullname] + sys.argv[1:]
except NameError:
    pass
```

But this is quite a hacky workaround (and only for Python < 3.3).

**Comment by untitaker** [comment]
I think I tried to fix this with __loader__ once, but it showed vastly
different behavior from 2 to 3.

**Comment by asarch** [comment]
Sadly,

$ python -m werkzeug.serving weasyprint.navigator:app --reload --debug
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 45, in <module>
    from ._compat import PY2
ValueError: Attempted relative import in non-package

**Comment by RonnyPfannschmidt** [comment]
This bug of python can't be fixed propperly with python, so I suggest to provide a console-script

**Comment by mvolfik** [comment]
Any change in this? Just ran into this issue... (Python 3.6)

**Comment by thpica** [comment]
I managed to get around the issue by doing something like:
```sh
PYTHONPATH=$PWD python -m myapp.entrypoints.website
```
