### ISSUE TITLE
ProxyFix does not work behind an AWS ELB with healthchecks

### ISSUE THREAD

**Issue by moodh** [pallets/werkzeug#464]
The ProxyFix middleware requires an argument that defines the amount of proxies in front of the application.

If you run the setup AWS ELB > NGINX > For example flask you would want the argument num_proxies=1. However if you point the health check to the same URL it will not have the correct headers and report the instance as crashed (with an exception since the proxy is out of range).

I wrote my own ProxyFix for now, and I suppose this is somewhat of an edge case but I thought I'd report it just the same. :)

**Comment by lipis** [comment]
It just hit us straight in the eye! Since this looks like it's not fixed yet.. @moodh do you still have that fix lying around somewhere?
