### ISSUE TITLE
Building urls with host_matching Map does not produce host based URLs

### ISSUE THREAD

**Issue by sharoonthomas** [pallets/werkzeug#488]
``` python

>>> from werkzeug import routing as r
>>> m = r.Map([
...   r.Rule('/', endpoint='index', host='www.domain.com'),
...   r.Rule('/', endpoint='index', host='my.domain.com'),
... ], host_matching=True)
>>> www = m.bind('www.domain.com')
>>> my = m.bind('my.domain.com')
>>> www.match('/')
('index', {})
>>> my.match('/')
('index', {})
```

When building

``` python
>>> www.build('index')
'/'
>>> my.build('index')
'http://www.domain.com/'
```

**Comment by aenglander** [comment]
There are two viable solutions to this issue that I can surmise and I am looking for feedback on the most appropriate option.

1. Do not allow the same endpoint value to be used for two routes. I would propose a `ValueError` to be raised when it occurs.
2. Check for and favor a host match for all rules that match the endpoint in a build call.
