### ISSUE TITLE
Resource Warning in unit tests

### ISSUE THREAD

**Issue by rawrgulmuffins** [pallets/werkzeug#513]
Cloned Werkzeug just a little bit ago and ran run-tests.py and saw these pop up.
Reported Error:

```
/Users/alord/flask/werkzeug/werkzeug/werkzeug/wsgi.py:802: ResourceWarning:   
unclosed file <_io.FileIO name=5 mode='rb+'> iter = chain((first_item,), _iter)

/Users/happy/flask/werkzeug/werkzeug/werkzeug/http.py:332: ResourceWarning: 
unclosed file <_io.FileIO name=5 mode='rb+'> extra = dict(parts)
```

Environment Information:
OS X 10.8.5 (12F45)
XTools
Python3.4
WerkZeug (cloned Today, I believe that makes it 0.10Dev but unsure)

**Comment by ramschmaerchen** [comment]
Still there, bug might be flask related:
```bash
Python 3.5.2
Flask==0.11.1
```
```python
# unittest
def setUp(self):
    self.app = frontend.app.test_client()
def test_sass_route(self):
    page = self.app.get("static/foo.css")
    self.assertEqual(page.status_code, 200)
```
```bash
# unittest output
test_css_route (tests.router.AssetRoutingTest) ... Python.framework/Versions/3.5/lib/python3.5/unittest/case.py:600: ResourceWarning: unclosed file <_io.BufferedReader name='static/foo.css'>
  testMethod()
__ok__
```

Test runs successfully and OS file access output suggests the file gets closed __before__ the python application quits.

**Comment by jab** [comment]
I'm fixing a bug on latest master and seeing this in a test I'm adding. Any known workarounds?

**Comment by ramschmaerchen** [comment]
I decided to use "ignore" as workaround ;)

**Comment by davidism** [comment]
This is very old and I can't reproduce it. I know people are reporting that this is still happening, if you have a concrete test case *with Werkzeug* (or from its tests), please open a new issue with exact details.
