### ISSUE TITLE
Proposed small changes to server shutdown

### ISSUE THREAD

**Issue by r1chardj0n3s** [pallets/werkzeug#519]
We've run into a problem where the Flask server we run in the background of our test suite isn't being shut down cleanly between tests. To reliably cleanly shut it down I have added a call to server_close() in werkzeug's BaseWSGIServer implementation at the end of serve_forever.

This means that the socket is explicitly closed immediately rather than eventually implicitly. In a fast-running test suite, it often won't be closed before the next test attempts to open the socket.

An additional potential improvement could be to also invoke the shutdown() method on the socketserver BaseServer, rather than poke at the private variable _BaseServer__shutdown_request directly. That method has some additional thread safety built in which may prove useful. This is up for debate though, so I'll only address the main problem in my initial PR.

**Comment by davidism** [comment]
Looked into this a bit, it seems that `server.shutdown()` only works if `threaded=True`. It waits for `serve_forever` loop to set an event, which means it deadlocks if run from the same thread. Given that it doesn't seem to have any issues right now, I'm going to leave it as-is.
