### ISSUE TITLE
Wrong Location when doing a redirect behind a Proxy.

### ISSUE THREAD

**Issue by vaab** [pallets/werkzeug#540]
Hi,

When I'm proxying an application served by werkzeug, this application issues a redirect. In the code the redirect is asked for "/". But werkzeug will fill this URL wrongly: it'll use the X-FORWARDED-HOST as the real host. By doing this it'll do the reverse proxy's job of rewritting the url. And of course, as it is not his job, werkzeug doesn't do it right. It forgets the eventual subdirs.

The result is that I can't ProxyReverse any werkzeug application that should live in a subdirectory in my main frontend.

**More information**

I have frontend apache host ``www.frontend.com``, which receives the HTTP requests. It's configured to proxy (pass the requests) to a werkzeug application on host ``internal-application.intranet`` when you hit the subdirectory "abc".

So when hitting: http://www.frontend.com/abc 
The requests should be proxied internally to ``http://internal-application.intranet``. This last one is running werkzeug.

When the application issues a redirect, let me explicit the scenario to be clear:
```
Client - ask for https://www.frontend.com/abc/file
    --> www.frontend.com (Proxy) 
        | www.frontend.com - ask for http://internal-application.intranet/file
        |    --> internal-application.intranet
        |        |  wants to redirect, so send back a redirect with header:
        |        |      Location: http://internal-application.intranet/other-file
        |    <--
        | www.frontend.com - receive the redirect, parses 'Location' header, 
        |     and replace instances of 'http://internal-application.intranet'
        |     by 'https://www.frontend.com/abc' : it take cares of:
        |       1 - protocol: http -> https
        |       2 - host: 'internal-application.intranet' -> 'www.frontend.com'
        |       3 - subdir: '/' -> 'abc/'
    <--
Client - receives a correct redirect that will work
```

So the header 'Location' is usually rewritten on-the-fly by the proxy before sending it the client. For instance: when it detects the pattern "http://internal-application.intranet" in the ``Location`` header, it'll change it to ``https://www.frontend.com/abc``.

But this doesn't work because werkzeug uses some information provided by the proxy to do some sort of a replacement of the ``Location`` header. But I don't think it should. As a result, when it issues a redirect, it doesn't send ``Location: http://internal-application.intranet`` as it should, but ``Location: http://www.frontend.com``: it replaces the HOST, but notice that it misses the subdirectory (and there are also issue with the protocol).

I don't think that werkzeug should do these changes, and it should rely on the proxy mecanism to do it's job.

**Diagnosis**

Then werkzeug in file ``werkzeug/wrapper.py`` in line 1110 will replace a partial location (as "/")  by the full one (as "http://myhost.com/"). Here are the lines:

```
                ...
                current_url = get_current_url(environ, root_only=True)
                if isinstance(current_url, text_type):
                    current_url = iri_to_uri(current_url)
                location = url_join(current_url, location)
                ...
```

So it calls ``get_current_url``, which in turn will ask for the host url thanks to ``get_host``.

And ``get_host`` will  use ``HTTP_X_FORWARDED_HOST`` instead of legit information:

```

def get_host(environ, trusted_hosts=None):
    """Return the real host for the given WSGI environment.  This takes care
    of the `X-Forwarded-Host` header.  Optionally it verifies that the host
    is in a list of trusted hosts.  If the host is not in there it will raise
    a :exc:`~werkzeug.exceptions.SecurityError`.

    :param environ: the WSGI environment to get the host of.
    :param trusted_hosts: a list of trusted hosts, see :func:`host_is_trusted`
                          for more information.
    """
    if 'HTTP_X_FORWARDED_HOST' in environ:
        rv = environ['HTTP_X_FORWARDED_HOST'].split(',')[0].strip()
    elif 'HTTP_HOST' in environ:
        rv = environ['HTTP_HOST']
    ...
```

I've commented these two lines to test, used ``tcpdump`` to check content of packets between proxy and application, and all seems right : the redirect finaly works fine.

If anything is wrong in my understanding of this, please tell me. If NOT using ``HTTP_X_FORWARDED_HOST`` in ``get_host`` is the way to go, tell me, I'll fix it and send you a PR. I'd like to gather some review on my analysis before sending a PR, and there might be a lot of good reason of wanting to keep this mecanism working.

Thanks for you comments.

**Comment by GatorPython** [comment]
Are you certain this is a werkzeug problem and not a problem with whatever server you're using? I'm thinking this may be a server issue that is not exactly the result of anything on the werkzeug end.

I am experiencing a similar issue with my application sitting behind a reverse proxy. I believe our issues are one in the same in kind. The frontend server is running Microsoft IIS. For whatever reason, I believe it is **_IIS_** that is rewriting the location in the response header.

For example, I have in my Flask application the following:

```
@app.route("/test")
def redirect_test():
    return redirect("http://google.com")
```

This application sits behind a reverse proxy such that `http://frontend.com/myapp/test` reverse proxies to `http://my-internal-server:8080/test` and hits the above route.

If I access the application through the frontend server, I get the following response headers:

```
Location:http://frontend.com
Server:Microsoft-IIS/7.5
```

If access the routedirectly at `http://my-internal-server:8080/test` I'm correctly redirected to Google.com  and the headers read as follows:
```
Location:http://google.com
Server:Werkzeug/0.11.10 Python/3.5.2
```

The conclusion I've drawn is that the problem domain lies in the server handling the reverse proxy. In my specific case, it's the default rewrite behavior of the ARR/urlrewrite modules in IIS. Thusly, I don't believe there's any changes that can be made in the werkzeug code that will address this problem.

**Comment by davidism** [comment]
This is more than likely a config issue (either with the HTTP or WSGI headers), not an issue with Werkzeug.  Configure the proper proxy headers and apply the `ProxyFix` middleware.
