### ISSUE TITLE
Colorized werkzeug terminal output

### ISSUE THREAD

**Issue by Frozenball** [pallets/werkzeug#553]
I believe the console output of werkzeug could use some color. For example, when a traceback is printed to terminal, it could be colored as red for better visual inspection.

**Comment by tuukkamustonen** [comment]
There's at least https://github.com/borntyping/python-colorlog which can be initialized simply enough, so simple colorization (by level) could be added without too much effort (conditionally - enable if package is available, disable if not).

**Comment by davidism** [comment]
Closing as it seems like it would be better handled by logging-related libraries.
