### ISSUE TITLE
werkzeug.serving.run_simple does not handle SIGTERM correctly

### ISSUE THREAD

**Issue by masklinn** [pallets/werkzeug#58]
When the process receives `SIGTERM`, it should shut down and exit, with as few operations as possible and without printing anything.

A `werkzeug.serving.run_simple` process receiving `SIGTERM` generally result in a return code of 141 (symptom of an un/mishandled `SIGPIPE`), and when using the reloader the process goes zombie (it has to be killed manually, as the port stays bound).

Adding a signal handler for `SIGTERM` which simply invokes `sys.exit(0)` is sufficient to fix the issue (in that there is no more misbehavior of the process), but I am not sure it's the actually correct fix.

**Comment by drewdogg** [comment]
I ran into this same problem in Flask with debug mode (use_debugger=True).  However, I see a return code of 0 on the "parent" process.  Without debug mode enabled, SIGTERM works fine and the process exits with code 143.  Python 2.7.5.

**Comment by zyv** [comment]
Got hit by this bug as well, in my case `docker stop` was sending `SIGTERM` to werkzeug-powered server (moto), but server ignored and then docker killed it with `SIGKILL` resulting into a non-zero exit code.

The workaround was to specify `SIGINT` (Ctrl+C) as a preferred stop signal in Dockerfile (`STOPSIGNAL SIGINT`), after that the containers shut down cleanly.

**Comment by AGausmann** [comment]
I have the same problem while running a Flask app inside of Docker; however, `STOPSIGNAL SIGINT` is still not enough to stop the container. I have to use `SIGKILL`.

**Comment by aenglander** [comment]
I cannot recreate the issue. I have tried this with the official Python container with the 2.7 and 3.7 tag. I used the following Dockerfile:

```docker
FROM python:2.7

WORKDIR /usr/src/app

RUN pip install click \
                werkzeug \
                sqlalchemy \
                jinja2

COPY . .

RUN python manage-shorty.py initdb

ENTRYPOINT ["python"]

CMD ["manage-shorty.py", "runserver"]
```

I would then run the container in interactive mode and cancel with:

```bash
$ docker run -it --name werkzeug-example werkzeug-examples
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
 * Restarting with stat
^C
```

Running `docker ps` showed it exited with `0`:

```bash
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                      PORTS               NAMES
8c708ea4ef77        werkzeug-examples   "python manage-short…"   About a minute ago   Exited (0) 58 seconds ago                       werkzeug-example
```

Running the container and stopping with `docker stop  werkzeug-example` also exits with `0`. 

Here is the result of Docker Version on the computer I ran these commands:
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Can you provide an example which can reproduce the issue you are experiencing?

**Comment by aenglander** [comment]
Until we can get a reproducible scenario, I will close this as it cannot be reproduced in the latest version of Docker and Werkzeug.
