### ISSUE TITLE
Import Python 3 related decisions from sprint repo into docs

### ISSUE THREAD

**Issue by untitaker** [pallets/werkzeug#588]
For porting Werkzeug to Python 3, [we had a sprint](https://github.com/mitsuhiko/pocoo-sprint-18052013). The `werkzeug.rst` in the linked repository contains crucial information on which string types should be chosen for representing headers, URIs, IRIs etc. Maybe it's just me, but even now i sometimes take a look back into that repo when working on `werkzeug.urls`.

Therefore i think we should import at least parts of `werkzeug.rst` into the documentation. The current location is too isolated for such design decisions.

**Comment by davidism** [comment]
I'm not sure where this would go in the docs, and I think it's somewhat moot at this point given the maturity of compat as well as the pending EOL for Python 2.
