### ISSUE TITLE
get_host will use X-Forwarded-Host by default

### ISSUE THREAD

**Issue by danielrichman** [pallets/werkzeug#609]
Here: https://github.com/mitsuhiko/werkzeug/blob/cbd049d88727936173386d2e80bb5ffa51fedd6e/werkzeug/wsgi.py#L141

I don't think that this is a safe default.
When using flask it gives any client the ability to set an arbitrary hostname in `request.url`.

This surprised me, since http://werkzeug.pocoo.org/docs/0.9/contrib/fixers/#werkzeug.contrib.fixers.ProxyFix exists to explicitly enable support for these headers (`X-Forwarded-For`, `X-Forwarded-Host`, ...).

And I think that this is misleading: http://werkzeug.pocoo.org/docs/0.9/wrappers/#werkzeug.wrappers.BaseRequest.trusted_hosts since a web server must not only “not route invalid hosts to the application”, but it must also delete any foreign `X-Forwarded-Host` headers.

**Comment by untitaker** [comment]
Removing blocker label because the fix is breaking backwards-compat.

**Comment by danielrichman** [comment]
Could you at least fix the documentation here https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/wrappers.py#L191 to mention that *both*

 - a webserver should manually be set up to not route invalid hosts to the application
 - a webserver should clear the `X-Forwarded-Host` header if it does not use it

...and we can discuss whether or not this is a sane default behaviour or not later?

**Comment by untitaker** [comment]
I think we should document this in the docstring of get_host and refer to it in this param's docstring. What do you think?

Also, if you have concrete ideas about the wording, patches welcome! :)

**Comment by danielrichman** [comment]
Do you think that the documentation for the `host`, `url`, ... properties of `BaseRequest` should refer to `trusted_hosts`?

**Comment by untitaker** [comment]
I have no opinion or idea about this at all... I find it hard to predict how users will read your documentation.

**Comment by danielrichman** [comment]
https://github.com/danielrichman/werkzeug/compare/trusted-hosts-docs ?

**Comment by untitaker** [comment]
Yeah looks great! I merged your changes for now, and hopefully we'll be able to figure out something better for 1.0. Thanks, not only for the patch, but for bringing this issue up @danielrichman!

**Comment by danielrichman** [comment]
Okay, so: the current documentation correctly describes the current behaviour, however, I believe this issue should stay open since I do not think that using *X-Forwarded-Host* is a sensible default.

To summarise arguments so far:

@mitsuhiko (correctly) says
> The way the system works is this: the server has two sources for where the host can come from: the X-Forwarded-Host and the Host header. Both of which can be modified by the client. If you have a proxy in front you can sanitize them.

I argue that this violates the principle of least surprise.

 - I do not think the typical person would think about or expect werkzeug to use *X-Forwarded-Host* by default.
 - The fact that the old documentation read "this is the recommended setup as a webserver should manually be set up to not route invalid hosts to the application" lends weight to my claim that most people wouldn't think of this---even you guys didn't!
 - Setting up the web server to "not route invalid hosts to the application" is quite a common thing to do, whereas sanitising *X-Forwarded-Host* is not(?).
 - The typical proxy simply passes on the *Host* header unmodified; it has no need for *X-Forwarded-Host*.
 - Moreover, while the need for *X-Forwarded-For* is obvious; you only need *X-Forwarded-Host* in [weird cases](http://stackoverflow.com/questions/19084340/real-life-usage-of-the-x-forwarded-host-header)?
 - The fact that [fixers.ProxyFix](http://werkzeug.pocoo.org/docs/0.9/contrib/fixers/#werkzeug.contrib.fixers.ProxyFix) exists implies that one has to specifically enable support for *X-Forwarded-** headers, which *is* the case for *X-Forwarded-For*, etc., but *is not* the case for *-Host*.
 - In fact, ProxyFix itself will read the *X-Forwarded-Host* header (as well as the others) and overwrite the *Host* header! That is, the feature "use *X-Forwarded-Host*" is implemented twice.

Miscellaneous

 - Backwards compat: would you not expect someone that needs this header to be using *ProxyFix* anyway, for *X-Forwarded-For*, etc.?
 - This has been discussed before in #540 and #371. Above, I provide arguments that this is not a sensible default. These two issues go one further: they provide examples where the current *X-Forwarded-Host* behaviour actually breaks things. In both it is suggested that this should be the job of *ProxyFix* only.

**Comment by untitaker** [comment]
>I believe this issue should stay open since I do not think that using X-Forwarded-Host is a sensible default.

I did not close it! I just postponed it to version ``1.0``, because at this version we're allowed to make compatibility-breaking changes.

>would you not expect someone that needs this header to be using ProxyFix anyway, for X-Forwarded-For, etc.?

I can imagine that developers don't do anything if the current behavior seems to "work".

Thanks for the summary.

**Comment by davidism** [comment]
@untitaker I have marked this as a blocker. We should fix this in the next feature release. Waiting for 1.0 is too long. People should be using `ProxyFix` for this behavior.

**Comment by ThiefMaster** [comment]
:+1: for not doing any implicit HTTP_X_FORWARDED overrides and having people use ProxyFix for it

**Comment by thewilkybarkid** [comment]
> I argue that this violates the principle of least surprise.

Yep, we've just been surprised to find this is the case.
