### ISSUE TITLE
Python 3.2 support required

### ISSUE THREAD

**Issue by kyegupov** [pallets/werkzeug#63]
Python version 3.2 finally resolves the long-standing issue of Unicode support in WSGI headers (PEP 3333). Thus, it is now possible (and desirable) to port Werkzeug to Python 3 and embrace the future.

See also: http://docs.python.org/dev/whatsnew/3.2.html

**Comment by jayvdb** [comment]
It would be nice to clearly state that 3.2 wont ever be supported, in a front page somewhere.

I see http://werkzeug.pocoo.org/ says "Supports Python 2.6, 2.7 and 3.3." , which should be "Supports Python 2.6, 2.7 and 3.3+."

And maybe explicitly fail on cpython 3.2 during setup.py by using `u'...'` in setup.py .. as I believe that is the main problem with supporting 3.2 - all `u'...'` would need to be removed (and `unicode_literals` added), which is a lot of churn for little benefit.

**Comment by untitaker** [comment]
@jayvdb This will be resolved in the upcoming rewrite of the websites for Werkzeug/Flask/Jinja.
