### ISSUE TITLE
newstr in python2 causes bad headers (i.g. "key: b'value'\r\n\r\n")

### ISSUE THREAD

**Issue by touilleMan** [pallets/werkzeug#704]
see: https://github.com/mitsuhiko/werkzeug/blob/70d0abb28e17241136535420e06071325c1d57e5/werkzeug/datastructures.py#L1194

``` python
    def to_wsgi_list(self):
        [...]
        if PY2:
            return [(to_native(k), v.encode('latin1')) for k, v in self]
        return list(self)
[...]
    def __str__(self):
        """Returns formatted headers suitable for HTTP transmission."""
        strs = []
        for key, value in self.to_wsgi_list():
            strs.append('%s: %s' % (key, value))
        strs.append('\r\n')
        return '\r\n'.join(strs)
```

In case we use `newstr` (i.g. `from builtins import str`) in our code this code break:

``` python
>>> from werkzeug import Headers
>>> str(werkzeug.Headers({'key': 'value'}))
'key: value\r\n\r\n'
>>> from builtins import str
>>> str(werkzeug.Headers({'key': str('value')}))
"key: b'value'\r\n\r\n"
```

`newstr` get enocoded into a `newbytes` which `__str__` method display in a `b'<actual_string>'` style.

A solution would be to do manual concatenation to prevent the use of `__str__`:

``` python
strs.append(key + value`)
```

**Comment by untitaker** [comment]
Please mention that this is by a third-party package. I'd suggest that python-future is broken in that regard, and not Werkzeug.

**Comment by davidism** [comment]
I can't reproduce the issue.
