### ISSUE TITLE
Control-C doesn't work during reloader sleep

### ISSUE THREAD

**Issue by untitaker** [pallets/werkzeug#711]
https://github.com/mitsuhiko/flask/issues/1373#issuecomment-83229953

Not sure how fixable this is.

**Comment by spideynn** [comment]
@untitaker It seems that this is a Windows only issue, but you could do a shorter sleep interval ex.
```python
for i in range(60):
    sleep(1)
```

**Comment by untitaker** [comment]
I've found this issue: http://bugs.python.org/issue581232

But it seems that this was supposed to be fixed a long time ago?

**Comment by davidism** [comment]
In years of using Flask and Werkzeug, with Watchdog and stat reloaders, on Linux and Windows, I've never encountered this issue. Is there any more information on reproducing it?
