### ISSUE TITLE
Stat reloader tries to import six's lazy module

### ISSUE THREAD

**Issue by ya-mouse** [pallets/werkzeug#717]
I have problem with stat reloader. With version 0.10 if I run this simple app:

``` python
from flask import Flask
import requests
app = Flask(__name__)
@app.route('/')
def index():
     return 'Index'
app.run(debug=True, host='127.0.0.1')
```

then I've got the following traceback:

```
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    app.run(debug = True, host='127.0.0.1')
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 622, in run_simple
    reloader_type)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/_reloader.py", line 269, in run_with_reloader
    reloader.run()
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/_reloader.py", line 159, in run
    for filename in chain(_iter_module_files(), self.extra_files):
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/_reloader.py", line 70, in _iter_module_files
    for package_path in getattr(module, '__path__', ()):
  File "/usr/lib/python3/dist-packages/six.py", line 116, in __getattr__
    _module = self._resolve()
  File "/usr/lib/python3/dist-packages/six.py", line 105, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/six.py", line 76, in _import_module
    __import__(name)
ImportError: No module named 'tkinter'
```

If I downgrade to 0.9 or remove "import requests" everything would be fine.

Newer Werkzeug version tries to get __ path __ attribute from six.MovedModule instance (mapping for "tkinter.commondialog").
Not all values in sys.modules are real modules.

**Comment by untitaker** [comment]
Then this should fail with 0.9 too, because 0.9 iterates through sys.modules in a similar manner (accessing file instead of path).

How does watchdog behave? Also, please try out #715, for the stat reloader it restores the old behavior.

**Comment by untitaker** [comment]
BTW I think this is ultimatively a six issue. Werkzeug should definetly be more tolerant against these kind of things, but it can't prepare against all kinds of magic.

**Comment by ya-mouse** [comment]
From my point of view, If application has already started, then some lazy modules (like a six-moved) might not be used at all. So, for the manual modules' import we have to put "straw" under the Werkzeug.

**Comment by untitaker** [comment]
`sys.modules` contains modules that have been imported, so they are used by definition (and import error should've been raised until then)

**Comment by ya-mouse** [comment]
I've never experience a problem with "requests" module. Regarding to the [six' source](https://bitbucket.org/gutworth/six/src/c996ed1dc0064f45e691f1664d06001ae07fff00/six.py#cl-117) this is a true lazy module that is only resolved per request.
There are a lot of [modules](https://bitbucket.org/gutworth/six/src/c996ed1dc0064f45e691f1664d06001ae07fff00/six.py#cl-235) including "tkinter and "winreg" (fixed in the referenced commit). The Werkzeug tries to resolve *all* lazy modules.

**Comment by untitaker** [comment]
How should Werkzeug be able to detect such modules?

**Comment by ya-mouse** [comment]
Just catch ImportError. I don't think that previously successfull module import should fail on re-import again. So, ImportError may occur only on non-existent lazy module.

**Comment by davidism** [comment]
I can't reproduce this issue. I tried `git bisect` to find when it was fixed, and I couldn't reproduce the issue at any point.
