### ISSUE TITLE
Incorrect rule matched given two rules, one with a variable and suffix, another with two variables

### ISSUE THREAD

**Issue by abramclark** [pallets/werkzeug#727]
There are two rules, the first one matching "/&lt;owner_name&gt;:Stuff" and the second matching "/&lt;owner_name&gt;:&lt;label_name&gt;". A request for "/fooman:Stuff" is matched by the second route, instead of the first as expected.

A workaround as suggested by ronny on #pocoo is to change the first route to match "/&lt;owner_name&gt;:&lt;any(Stuff):foo&gt;"

**Comment by skyline75489** [comment]
Looks like a duplicate of #185

**Comment by davidism** [comment]
Also reported at pallets/flask#1265.
