### ISSUE TITLE
ident_func when running within gunicorn+gaiohttp

### ISSUE THREAD

**Issue by urbaniak** [pallets/werkzeug#730]
`LocalManager.ident_func` should be set to `asyncio.Task.current_task` when running under gunicorn+gaiohttp.

Currently if we're running with gaiohttp the LocalManager mixes the context of different tasks :(

Have no idea how to properly implement the detection if we're running under eventlet (under python3) or asyncio, just hacked my own greenlet module which returns the proper task id.

**Comment by RonnyPfannschmidt** [comment]
the default is only aware of greenlets/threads, its unclear how to deal with something more complex

LocalManager can be given a custom ident function in the constructor, but its unclear how to determine the deployment situation

**Comment by urbaniak** [comment]
Maybe we can combine all available task identifiers?

Something like that:

    identifiers = []

    try:
        from greenlet import getcurrent
        identifiers.append(getcurrent)
    except ImportError:
        pass

    try:
        from thread import get_ident
        identifiers.append(get_ident)
    except ImportError:
        pass

    try:
        from asyncio.Task import current_task
        identifiers.append(current_task)
    except ImportError:
        pass


    def identifier():
        return "".join([str(i()) for i in identifiers])

**Comment by untitaker** [comment]
I don't like the performance implications of that.

I suppose if e.g. `greenlet.getcurrent` raises an exception if greenlet is not used, we could pop it from identifiers, and that could improve performance a bit again, but there's still some penalty left.

**Comment by untitaker** [comment]
I wonder if we could use `threading.active_count` to determine whether to disable the usage of `threading.get_ident`, and if the other libs support something similar.

**Comment by urbaniak** [comment]
Similar thing can be achieved by using `asyncio.get_event_loop().is_running()` on asyncio.

**Comment by urbaniak** [comment]
Any chances to get that one resolved somehow?

We can determine which eventloop is used just once at the startup, that won't cause any performance issues.

**Comment by davidism** [comment]
Rolling this into #1322
