### ISSUE TITLE
JSONRequestMixin tries to call json.loads() on bytes if simplejson is not available under Python 3

### ISSUE THREAD

**Issue by underyx** [pallets/werkzeug#731]
Throws an exception that the stdlib `json.loads` needs `str`, not `bytes` such as `request.data`.

**Comment by untitaker** [comment]
This is definetly a bug, but I think we'll either remove JSONRequestMixin in future versions of Werkzeug in favor of Flask's implementation. Whether Flask's implementation should be moved to Werkzeug is worth discussing though.

**Comment by davidism** [comment]
@untitaker thoughts on moving `flask.Request.get_json` over?  I'm sure there's a way to do it while still supporting Flask's decoder.

**Comment by untitaker** [comment]
We eventually should kill one of those, agreed!

**Comment by davidism** [comment]
Why are we allowing a property here, but arguing against it in Flask?

**Comment by untitaker** [comment]
I'd say it's because Armin actually uses the latter. :P

On 4 June 2016 22:49:02 CEST, David Lord <notifications@github.com> wrote:
>Why are we allowing a property here, but arguing against it in Flask?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/werkzeug/issues/731#issuecomment-223777523

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
