### ISSUE TITLE
Why set the default value of path_info=None while it cannot be?

### ISSUE THREAD

**Issue by zhaoguixu** [pallets/werkzeug#740]
As stated in issue  #440, #857

``` python
def test_mapadapterpath_info_is_none(self):
        m = r.Map([])
        ma = m.bind('example.org', path_info=None)
        m.match(return_rule=True)   #==========> it will crash
```

I just inspect the code and have a question why set the default value of path_info as None when it cannot be?

``` python
def match(self, path_info=None, method=None, return_rule=False,
                query_args=None):
        ...
def bind(self, server_name, script_name=None, subdomain=None,
             url_scheme='http', default_method='GET', path_info=None,
             query_args=None):
        ...
```

**Comment by RonnyPfannschmidt** [comment]
it can be given either in bind or match,

it has to be given in at least one, the one in match overriding the one given in bind

**Comment by zhaoguixu** [comment]
As I think, it would be better to give a friendly raise when both None happened instead of a rough AttributeError confusing the user.

**Comment by RonnyPfannschmidt** [comment]
i tested based on your example in a python shell an got a 404,
maybe i needs a rule to trigger the behavior

are you up for creating a small pull request including a test and fix?

**Comment by zhaoguixu** [comment]
There is a typo in the test. 
```python
def test_mapadapterpath_info_is_none(self):
    m = r.Map([])
    ma = m.bind('example.org', path_info=None)
    ma.match(return_rule=True)   #==========> it will crash
```
...
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 1382, in match
    self.subdomain, path_info.lstrip('/'))
AttributeError: 'NoneType' object has no attribute 'lstrip'

In the PR, I just set the root path as the default when both bind and match are None.

**Comment by untitaker** [comment]
@zhaoguixu You sent this PR to the wrong repository.

**Comment by zhaoguixu** [comment]
So where is the right repo? Feel free to merge it if necessary.

**Comment by untitaker** [comment]
You sent the PR against your own fork...

On 9 September 2015 13:07:36 CEST, Zhaogui <notifications@github.com> wrote:
>So where is the right repo? Feel free to merge it if necessary.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/werkzeug/issues/740#issuecomment-138877228

-- 
Sent from my phone. Please excuse my brevity.
