### ISSUE TITLE
Empty response when manually manipulating response with unicodecsv/csv

### ISSUE THREAD

**Issue by pyskell** [pallets/werkzeug#754]
This may be related to (https://github.com/mitsuhiko/flask/issues/1286), but I'm not 100% sure (as only the internal content of the file is utf-8 encoded). Apologies if it is.

The issue is that the following code works with runserver and gunicorn, returning the header in CSV format. However, it returns a completely empty file with runserver_plus w/ Werkzeug:

```
def export_list_to_csv(request):

    response = HttpResponse(content_type='text/csv',)
    response['Content-Disposition'] = 'attachment; filename="my_product_list.csv"'

    writer = unicodecsv.writer(response)

    headers = ["name", "description", "website", "price", "creation_date"]

    writer.writerow(headers)

    return response
```

**Comment by untitaker** [comment]
Well, does the log show the error message mentioned in that issue? Have you tried removing runserver-plus and using Werkzeug's server directly?

On 4 August 2015 18:43:10 CEST, h-core <notifications@github.com> wrote:
>This may be related to
>(https://github.com/mitsuhiko/flask/issues/1286), but I'm not 100% sure
>(as only the internal content of the file is utf-8 encoded). Apologies
>if it is.
>
>The issue is that the following code works with runserver and gunicorn,
>returning the header in CSV format. However, it returns a completely
>empty file with runserver_plus w/ Werkzeug:
>
>
>    def export_list_to_csv(request):
>
>        response = HttpResponse(content_type='text/csv',)
>response['Content-Disposition'] = 'attachment;
>filename="my_product_list.csv"'
>
>        writer = unicodecsv.writer(response)
>
> headers = ["name", "description", "website", "price", "creation_date"]
>
>        writer.writerow(headers)
>
>        return response
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/werkzeug/issues/754

-- 
Sent from my phone. Please excuse my brevity.

**Comment by davidism** [comment]
Closing due to age and not enough info.
