### ISSUE TITLE
print warning when server_name and cur_server_name don't match

### ISSUE THREAD

**Issue by Alexis-benoist** [pallets/werkzeug#760]
If the server name is misconfigured, the `subdomain` is `'<invalid>'` and no warning is printed.

https://github.com/pallets/werkzeug/blob/d637320cd174eec5cc1baa3aa3412bd5390e9442/werkzeug/routing.py#L1302

An improvement could be to print a warning if the names don't match, instead of just returning 404 errors for all pages.

**Comment by guyskk** [comment]
+1

**Comment by jlark** [comment]
+1

**Comment by npdoty** [comment]
I just spent multiple days trying to debug a Flask application that returned 404s for every request with no indication as to why the routes weren't being matched. It would help troubleshooting enormously if there were a visible warning when this mismatch occurs.

**Comment by WCICS** [comment]
I had the same issue. This should probably be an error, but there must _atleast_ be a warning, as otherwise we have to dig through werkzeug source code just to find out that we have a config issue.
