### ISSUE TITLE
Fix documentation theming

### ISSUE THREAD

**Issue by untitaker** [pallets/werkzeug#761]

**Comment by untitaker** [comment]
Two options:

* Just fall back to default, online doc builder overrides `conf.py`.
* Factor out theme into third-party package (https://github.com/pocoo/pocoo-sphinx-themes), depend on that, fallback to default

**Comment by rkuska** [comment]
Any update on this one?

**Comment by davidism** [comment]
This is fixed, we moved to pallets-sphinx-themes and will soon be building on Read the Docs.
