### ISSUE TITLE
Testsuite documentation in contributing.rst is not up to date

### ISSUE THREAD

**Issue by jaapz** [pallets/werkzeug#769]
The documentation says the minimal requirement for running the testsuite is `py.test`, which is not true. If only `py.test` is installed, running the tests fails because `requests` is imported but not installed.

**Comment by jaapz** [comment]
Also `pytest-xprocess` is used in the test, which is not documented.

**Comment by grahamlyons** [comment]
Could you open a pull request with the fixes required?

**Comment by simenheg** [comment]
It seems that this was fixed in April this year by 16fdd66c0dc8cfd6e6ec6c90569ba4f667f8b536. The mention of `pytest-xprocess` is added in https://github.com/pallets/werkzeug/pull/1169.
