### ISSUE TITLE
strict_slashes route option applied to wrong endpoints

### ISSUE THREAD

**Issue by jtallieu** [pallets/werkzeug#773]
When attempting to match a rule, `Rule.match()` triggers the `RequestSlash()` exception immediately.  Other routes with the same rule (but different methods) are not considered.  The first matched rule's strict_slashes option is used although, the request could be for a different method.

For example:

If I have:

```
route_base = '/hooks'

@app.route('/<id_>/', methods=["GET"])
    def get(self, id_):
       pass

@app.route('/<id_>', methods=["PUT"], strict_slashes=False)
    def put(self, id_):
       pass

@app.route('/<id_>/', methods=["DELETE"])
    def delete(self, id_):
       pass
```

The map will contain, three Rules `'/hooks/<id_>/', '/hooks/<id_>', '/hooks/<id_>/'`.

If I issue a `PUT /hooks/12345` (no slash) I get the redirect to use the '/' because sometimes the options for the DELETE endpoint are used in `Rule.match()` because it happens to match first.  I expect the `strict_slashes` to be bound to the rule-methods combo.

**Comment by jtallieu** [comment]
Could also be the cause of https://github.com/mitsuhiko/werkzeug/issues/397

**Comment by edk0** [comment]
This no longer happens.
