### ISSUE TITLE
OverflowError when downloading big files

### ISSUE THREAD

**Issue by olilau** [pallets/werkzeug#776]
Hello,

I sometimes get an OverflowError when downloading big files.
I've included the traceback at the end.

It happens with big files. The first one is 4465410157 bytes (4.5 Gb) long and the other is 3670993906 bytes (3.7 Gb) long.
It does not happens every time. Some of my colleagues got that error. I couldn't reproduce it though.

I'm running werkzeug version 0.9.6+dfsg-1 from Debian GNU Linux 8 in a docker container.
Python 2.7.9
My colleagues are using 'wget' to download these files (in case it could help). I've tried with 'curl' and 'wget' but I don't get that error at my end.

Am I doing something wrong ? Or is it an issue in werkzeug ?
If you need anything else, tell me.

Thank you.

In case it could help, I'm also pasting the serve_file method since it originates from that method:

``` python
def serve_file(path):
    range = http.request.httprequest.range
    if range and len(range.ranges) > 1:
        raise NotImplemented("Multiple ranges")
    try:
        archive = open(path, 'rb')
    except IOError, exc:
        if exc.errno == 2:
            raise NotFound("File does not exist")
    archive.seek(0, SEEK_END)
    filesize = archive.tell()
    if not range:
        archive.seek(0)
        return Response(archive, 200, mimetype='application/octet-stream',
                        headers=[
                            ('Content-Length', str(filesize)),
                            ('Content-Disposition',
                             "attachment; filename=\"%s\""
                             % basename(path)),
                        ],
                        direct_passthrough=True)
    else:
        start, stop = range.ranges[0]
        if stop is None:
            stop = filesize
        if start > stop:
            raise RequestedRangeNotSatisfiable()
        archive.seek(start)
        length = stop - start
        if length == 0:
            return Response('', 204)
        response = Response(LimitedStream(archive, length),
                            206, mimetype='application/octet-stream',
                            headers=[
                                ('Content-Length', str(length)),
                                ('Content-Disposition',
                                 "attachment; filename=\"%s\""
                                 % basename(path)),
                            ],
                            direct_passthrough=True)
        response.content_range = \
            ContentRange('bytes', start, stop, filesize)
        return response
```

Traceback:
 444 2015-10-05 05:55:28,106 22421 ERROR upgrade werkzeug: Error on request:
 445 Traceback (most recent call last):
 446   File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
 447     execute(self.server.app)
 448   File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 167, in execute
 449     for data in application_iter:
 450   File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 1044, in **next**
 451     line = self.readline()
 452   File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 1006, in readline
 453     line = self._readline(size)
 454 OverflowError: signed integer is greater than maximum

**Comment by mitsuhiko** [comment]
Can you print the value of size in 1006 readline?

**Comment by olilau** [comment]
Unfortunately no. Last time it happened was on the 5th of October.

**Comment by mitsuhiko** [comment]
This will need more information for me to be able to look into it.

**Comment by olilau** [comment]
I understand. You can close it. I'll reopen it if I have the chance to reproduce it or have more information.

**Comment by olilau** [comment]
@mitsuhiko Can you reopen this issue ?
I can reproduce it.

When the exception is raised, size = 2315817887
I was using "wget --continue" but the same error can also happen without the "--continue" parameter.
With this parameter, size is always equal to 2315817887

Without this parameter, the size is quite random. For example:
2318637466 or 2239564998

I've upgraded werkzeug from 0.9.6 to 0.11.11 but the issue is the same.

Do you need more information ?

**Comment by olilau** [comment]
The file I'm trying to download is 2327155115 bytes
The already download chunk is 11337228 bytes
2327155115 - 11337228 = 2315817887

**Comment by davidism** [comment]
See Flask's `send_file` implementation. You should be using `response.make_conditional(request)` to handle range requests, rather than using `LimitedStream`. `make_conditional` uses a different file wrapper that reads in chunks.

`LimitedStream` also contains the following warning in the docs:

> calls to `readline` and `readlines` are not WSGI compliant because it passes a size argument to the readline methods. Unfortunately the WSGI PEP is not safely implementable without a size argument to `readline` because there is no EOF marker in the stream.  As a result of that the use of `readline` is discouraged.
> 
> For the same reason iterating over the `LimitedStream` is not portable.  It internally calls `readline`.
> 
> We strongly suggest using `read` only or using the `make_line_iter` which safely iterates line-based
> over a WSGI input stream.

**Comment by davidism** [comment]
Related to #265, which asks to move Flask's `send_file` to Werkzeug.

**Comment by olilau** [comment]
Thank you for these recommendations.
