### ISSUE TITLE
Embedded document passed in Client.post is treated as file object

### ISSUE THREAD

**Issue by xiaohan2012** [pallets/werkzeug#791]
I am trying to pass in a embedded object in a post quest but failed.

The code is like this:

> c = Client()
> c.post('url', {'field1': 'value1', 'field2': {'subfield1': 'subvalue2'}})

The code execution makes 'field2' in to `Client._add_file_from_data`, which is this line: 

https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/test.py#L338

**Comment by RonnyPfannschmidt** [comment]
As far as I can tell the code you linked works exactly as intended, what was your expectation??

**Comment by xiaohan2012** [comment]
Oh, sorry for the unclarity.

My usercase is: 

```
 c.post('url', {'username': 'some.user', 'location':  {"city": "Helsinki", "country": "Finland", "address": "blahblah"}}, content_type='application/json')
```

The error is:

```
Traceback (most recent call last):
  File "/home/vagrant/code/petnet/testing.py", line 49, in test_insert
    data=Fixture.person1
  File "/home/vagrant/code/petnet/testing.py", line 17, in post_json
    content_type='application/json').data
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 772, in post
    return self.open(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/flask/testing.py", line 103, in open
    builder = make_test_environ_builder(self.application, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/testing.py", line 34, in make_test_environ_builder
    return EnvironBuilder(path, base_url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 334, in __init__
    self._add_file_from_data(key, value)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/test.py", line 351, in _add_file_from_data
    self.files.add_file(key, **value)
TypeError: add_file() got an unexpected keyword argument 'city'
```

The `location` field should not be treated as a file, but a embedded document.

Am I posting the data in the wrong way?

Thanks

**Comment by xiaohan2012** [comment]
Oh, I think I know the solution now. 

This works for me:

```
import json
 c.post('url', json.dumps({'username': 'some.user', 'location':  {"city": "Helsinki", "country": "Finland", "address": "blahblah"}}), content_type='application/json')
```

**Comment by RonnyPfannschmidt** [comment]
I See, rhats the correct solution, 

perhaps a post_json method would be helpfull.

Do you See something that needs to be done, or do you consider this issue resolved?

**Comment by xiaohan2012** [comment]
It's solved for me. 

If this is a common issue, something like the `post_json` is necessary. 

the `requests` library actually uses `json` parameter in the `post` method. As can be seen in its [soruce code](https://github.com/kennethreitz/requests/blob/master/requests/sessions.py#L511)

**Comment by marthinus-engelbrecht** [comment]
Hi,

Disclaimer: I'm new to python.

I just had a similar issue. My code was: 

``` python
client = Client(app)
data = {
    "jsonrpc": "2.0",
    "method": "App.start",
    "id": "2cca33fe-5588-44f1-a570-7fe3ac0118a0"
}

app_iter, status, headers = client.post('/api', base_url='http://localhost:3333', content_type='application/json', data=data)
```

I kept on getting a parse error from the endpoint due to invalid JSON  

Thanks to @xiaohan2012 I got it right. My code now is: 

``` python
client = Client(app)
data = {
    "jsonrpc": "2.0",
    "method": "App.start",
    "id": "2cca33fe-5588-44f1-a570-7fe3ac0118a0"
}

app_iter, status, headers = client.post('/api', base_url='http://localhost:3333', content_type='application/json', data=json.dumps(data))
```

Is it expected that I convert my `dict` to`JSON` even though I provide `content_type='application/JSON'`? This is not very intuitive and the documentation doesn't explicitly say it. I was stuck on this for a while. Maybe it should say it explicitly?

**Comment by davidism** [comment]
#950 addresses this

The docs don't indicate that it does anything special with data if content_type is set.  It accepts either a string and content_type (json.dumps), or a dict that's converted to form data.
http://werkzeug.pocoo.org/docs/0.11/test/#werkzeug.test.EnvironBuilder

**Comment by aguynamedben** [comment]
FWIW I also found this surprising behavior. Seems like common case with a completely unhelpful error message.
