### ISSUE TITLE
Make debugger PIN_TIME higher/configurable

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/werkzeug#817]
During development - which is really the only place where the debugger should be used - it's pretty annoying to enter the PIN once a day. Why not make the cookie last e.g. a week or allow the lifetime to be configured?

**Comment by mitsuhiko** [comment]
If you know what you're doing you can also disable the PIN check entirely.  You can export `WERKZEUG_DEBUG_PIN=off` and not be bothered any more.

**Comment by davidism** [comment]
I think I'll just leave it as enabled/disabled.
