### ISSUE TITLE
useragents: detecting Microsoft Edge as Chrome

### ISSUE THREAD

**Issue by ghost** [pallets/werkzeug#818]
Python ver. 2.7.9
Werkzeug ver. 0.11.2
(I am using this from Flask, ver. 0.10.1)

The current regex used in useragents.py does not seems to be covering Microsoft Edge's `Edge/` section in the user-agent string. `chrome` is returned for the `browser` key as a result of this.

A few examples of this issue:
- Lumia running Edge (mobile) on Windows Phone 10.0
  - User-agent: `Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; Lumia 640 XL LTE) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586`
  - Result: `"browser": "chrome", "platform": "chromeos"`
- Windows 10 running Edge
  - User-agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240`
  - Result: `"browser": "chrome", "platform": "windows"`

Microsoft's MSDN has a page on some of its browser products' user-agent strings, which can be found [here](https://msdn.microsoft.com/en-us/library/hh869301%28v=vs.85%29.aspx).

edit: fix wrong result pasted.

**Comment by Permafacture** [comment]
Just ran into this.

**Comment by doekman** [comment]
Microsoft Edge is still not listed as a detectable browser. Just got this user-agent string from Edge:

    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
