### ISSUE TITLE
dev server sets wrong HTTP_HOST when path starts with a double slash

### ISSUE THREAD

**Issue by ThiefMaster** [pallets/werkzeug#822]
See https://github.com/mitsuhiko/flask/issues/1639#issuecomment-162305541

    if request_url.netloc:
        environ['HTTP_HOST'] = request_url.netloc

This code was added in 7486573d / #248. Do absolute http requests even make sense except for HTTP proxies?

**Comment by davidism** [comment]
As reported in the linked issue, this can lead to weird behavior.  http://127.0.0.1:5000//google.com will redirect to Google.

**Comment by mitsuhiko** [comment]
That should definitely be fixed.

**Comment by untitaker** [comment]
Perhaps just change `if request_url.netloc` to `if request_url.scheme and request_url.netloc`.

**Comment by RaminFP** [comment]
any update?

**Comment by ThiefMaster** [comment]
It's not even a day since the last comment...

**Comment by RaminFP** [comment]
Ok ! tnx @ThiefMaster

**Comment by untitaker** [comment]
Triaging: blocker bug

**Comment by RaminFP** [comment]
@untitaker  Nice work!!

**Comment by DePierre** [comment]
@untitaker Any update on this open redirect issue?

**Comment by sibeliusseraphini** [comment]
:+1:

**Comment by untitaker** [comment]
Could somebody review #890 and check if I missed something?
