### ISSUE TITLE
Proposal for Live Server Thread

### ISSUE THREAD

**Issue by foxx** [pallets/werkzeug#844]
In situations where you want to run acceptance tests in Python, it can be useful to have the ability to run a WSGI server in a different thread. There is some trickery required to make it work properly, as seen below. 

Can a core maintainer please let me know if this would be considered for merge? If so, I'll put together a fully tested and documented PR.

```python
import socket
import threading
from werkzeug.serving import make_server

class LiveServerThread(threading.Thread):
    """
    Example usage:

    >>> thread = LiveServerThread(host='127.0.0.1', port='0', app=self.app)
    >>> thread.start()
    >>> print(thread.url)
    http://127.0.0.1:55691
    """

    def __init__(self, *args, **kwargs):
        super().__init__()
        self.daemon = True
        self.server = make_server(*args, **kwargs)
  
    @property
    def url(self):
        return "http://{}:{}".format(self.server.server_name, self.server.server_port)
  
    def run(self):
        """Called inside thread once started"""
        self.server.serve_forever()
  
    def stop(self):
        """Called outside thread to shutdown"""
        self.server.shutdown_signal = True
        if self.server and self.is_alive():
            try:
                s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                s.connect(self.server.socket.getsockname()[:2])
                s.send(b'\r\n')
                s.close()
            except IOError:
                import traceback
                traceback.print_exc()
        self.join(5)
```

**Comment by untitaker** [comment]
What exactly is the issue you're experiencing? I use Werkzeug's server without reloader in a separate thread and it seems to work fine.

**Comment by foxx** [comment]
@untitaker There isn't a helper class which exposes any of the above, including soft thread shutdown and URL generation, which is what I included above.

**Comment by untitaker** [comment]
Sorry for responding late -- I don't consider this to be within scope for Werkzeug.

For pytest there already is https://bitbucket.org/pytest-dev/pytest-localserver, for other testing frameworks some other API might be more appropriate.
