### ISSUE TITLE
Add json argument to test.Client.post() 

### ISSUE THREAD

**Issue by jwg4** [pallets/werkzeug#848]
Hi there. I wondered if it would be useful to have an argument `json` for the method `test.Client.post()`. The idea would be that you can pass in a request body in the form of a data structure which gets serialized to JSON. 
You would not be able to set both `data` and `json`, it would simply be a convenience rather than serialize to JSON and then pass in as `data`.
This argument is present in `requests.post()` and one reason it might be nice to have it is that makes it possible to keep testing with the Werkzeug client and live testing/monitoring against a production server using Requests closer together.
I am happy to submit a PR for this, but I wanted to check first in case it is seen as bloaty or not a good idea for some other reason. Thanks!

**Comment by DoWhileGeek** [comment]
I heavily agree with this idea. I was actually skimming issues to see if theres any talk about a json attribute or method planned for the `Response` object, I'm probably going to end up creating an issue for this like you did.

**Comment by DoWhileGeek** [comment]
Also, `Client.put()` should have this argument as well.

**Comment by jeffwidman** [comment]
Related: https://github.com/pallets/flask/pull/1416

**Comment by lynncyrin** [comment]
To expand on the spec above, currently I do

```python
    response = app.post(
        '/snippets',
        data=json.dumps({'text': 'rawr', 'shared': False}),
        content_type='application/json',
    )
```

whereas I would like to do

```python
    response = app.post(
        '/snippets',
        json={'text': 'rawr', 'shared': False},
    )
```

**Comment by lynncyrin** [comment]
Looks like https://github.com/pallets/werkzeug/pull/950 was on the way to getting this done, just needs someone with capacity to finish it!
