### ISSUE TITLE
request.files FileStorage object iterates indefinitely on Python 3

### ISSUE THREAD

**Issue by joshringer** [pallets/werkzeug#849]
When retrieving a file through request.files, attempting to iterate over it will hang as iterator indefinitely produces empty lines after content instead of raising `StopIteration`.

This only occurs on Python 3, Python 2 seems unaffected.
Tested against werkzeug version 0.10.4, also against master 818c27fb5191eb58a40049b61173c6711682cf66, Python 3.5.0 & 2.7.10

Code to reproduce:
```python
from werkzeug.wrappers import Request, Response
from werkzeug.test import Client

@Request.application
def iter_file(request):
    fobj = request.files['testfile']
    lines = [line for line in fobj]  # <-- this will hang on py3
    # fobj produces empty lines after content indefinitely on iteration
    # should be raising StopIteration at end of content
    return Response(b'\n'.join(lines))

client = Client(iter_file)

data = b'\r\n'.join([
    b'--foo',
    b'Content-Disposition: form-data; name="testfile"; filename="atest.txt"',
    b'Content-Type: text/plain',
    b'',
    b'A simple test',
    b'--foo--',
])

response = client.post(
    '/',
    data=data,
    content_type='multipart/form-data; boundary="foo"',
    content_length=len(data)
)  # ==> hang on py3
```

**Comment by joshringer** [comment]
Issue is due to string vs. bytes in python 3 for iter call in FileStorage class.
Fairly sure the following patch is safe. Underlying stream object should iterate over lines anyway, right?

[issue_849.diff.txt](https://github.com/mitsuhiko/werkzeug/files/92074/issue_849.diff.txt)

**Comment by illume** [comment]
There is a related py3 issue in werkzeug.test and file uploads with stream_encode_multipart, write_binary trying to write strings to the streams, when it needs bytes (line 59). Not sure if it's part of this same issue.

I checked the test_datastructures.py and there are basically no tests for FileStorage (they are probably hiding elsewhere).

**Comment by untitaker** [comment]
@joshringer Please file this patch as PR.

@illume Please file a new issue.

**Comment by illume** [comment]
@untitaker Ok. Can you please direct me on where tests for this issue should go? #874 requires a test, and the issue here is basically a test for that. I could also add a test for the issue I described.

**Comment by untitaker** [comment]
@illume Thanks! `test_datastructures` is the correct place.

**Comment by untitaker** [comment]
@illume Though given the example in the OP I'd also accept putting the tests into `test_wrappers`

**Comment by illume** [comment]
Ok. Thanks for the help.

**Comment by untitaker** [comment]
Done by #874
