### ISSUE TITLE
Passing Integers to Test Client in Python 3.4

### ISSUE THREAD

**Issue by badisa** [pallets/werkzeug#852]
Python: 3.3.5/3.4.3
Werkzeug:  0.11.3
Test Runner: Pytest

The following code runs fine under Python 2.7.6:
```
   client = app.test_client()
   with open("/Users/badisa/Downloads/QUERIES/query-86.sdf", 'rb') as dataset:
         params = {
                "name": "Dataset",
                "priority": 5,
                "dataset": (dataset, "file_name"
        }
        response = client.post(
                '/datasets/',
                data=params
       )
       self.assertEqual(200, response.status_code)
```

But in python 3 it raises the following error:

```
string = 'True'

    def write_binary(string):
        stream, total_length, on_disk = _closure
        if on_disk:
            stream.write(string)
        else:
            length = len(string)
            if length + _closure[1] <= threshold:
>               stream.write(string)
E               TypeError: 'str' does not support the buffer interface
```

Reading the error originally I thought I was uploading the file incorrectly, but it seems that by having any value that is an integer causes the TypeError.

Even reading through the [documentation](http://werkzeug.pocoo.org/docs/0.11/test/#testing-api) for the Testing API it doesn't make it clear that only strings are allowed in the dictionary as values besides the File Objects.

**Comment by faisalburhanudin** [comment]
also happened to me,
makes me puzzled for hours.

need better error message .
