### ISSUE TITLE
Wiki30 tutorial disappeared

### ISSUE THREAD

**Issue by leafstorm** [pallets/werkzeug#87]
Since the introduction of the new Werkzeug Web site, the "wiki in 30 minutes" screencast and source code has disappeared. While it is probably a bit out of date, everyone loves screencasts and everyone loves wikis, so it is probably a good idea to make it accessible again (especially since I plan on maybe using it as a base for a new Flask tutorial).

**Comment by davidism** [comment]
Unfortunately I have no idea where this is.
