### ISSUE TITLE
Minor issues in `BaseResponse.set_cookie`

### ISSUE THREAD

**Issue by larsbutler** [pallets/werkzeug#888]
While browsing the [Flask API docs for Response.set_cookie](http://flask.pocoo.org/docs/0.10/api/#flask.Response.set_cookie), I noticed a couple of issues. By quickly skimming through the docs source files, I traced the origin of those docs to `werkzeug`. Here are the issues I found:

1. The keyword parameters `path`, `secure` and `httponly` are not included in the docstring.
2. The `secure` parameter in [BaseResponse.set_cookie](https://github.com/pallets/werkzeug/blob/ff82fa21297294804e8d1c3203074fec4d292d1d/werkzeug/wrappers.py#L995-L996) defaults to `None`, while in [`werkzeug.http.dump_cookie`](https://github.com/pallets/werkzeug/blob/ff82fa21297294804e8d1c3203074fec4d292d1d/werkzeug/http.py#L908-L910), the default value is `False`. `None` doesn't make sense as a default value, since the `Secure` and `HttpOnly` attributes either are or are not present in a cookie; see https://tools.ietf.org/html/rfc6265#page-21. Probably it's technically okay, but there may be a subtle bug here with the `secure=None`. It's worth looking into.

I'm working on a patch to propose a few cleanups/fixes, and I'll submit that shortly.

**Comment by untitaker** [comment]
Fixed by #889 as far as I can tell.

I was suspicious about your change to the `secure` parameter, but as far as I can tell the logic inside `dump_cookie` only depends on the truthyness of that value.
