### ISSUE TITLE
0.11.6 fails to run in debug

### ISSUE THREAD

**Issue by alexa-infra** [pallets/werkzeug#896]
I'm getting the following error after today update:

    File "/local/lib/python3.4/site-packages/werkzeug/debug/__init__.py", line 169, in get_pin_and_cookie_name
       h.update('cookiesalt')
    TypeError: Unicode-objects must be encoded before hashing

Python 3.4.3
Werkzeug 0.11.6
Flask 0.10.1

P.S. 0.11.5 runs just fine

**Comment by SoftpymesAdrian** [comment]
Same here!

**Comment by untitaker** [comment]
Fixed in 0.11.7
