### ISSUE TITLE
Problem with stdout buffering

### ISSUE THREAD

**Issue by jjb** [pallets/werkzeug#917]
Here's a problem that I am experiencing which I don't fully know the cause of. But I'll explain what I know.

When running a Flask app under [heroku local](https://devcenter.heroku.com/articles/heroku-local), my stdout is buffered until I control-c, at which point it is all printed.

This issue describes what I think is the same problem, in this case under supervisord and not heroku local: https://github.com/pallets/flask/issues/1420

Both of the workarounds described in the issue work for me. either

``` python
import sys
import os
sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
```

at the top of my flask application file, or 

```
PYTHONUNBUFFERED=1
```

in my environment.

Someone in the thread vaguely asserts that it's werkzeug's fault and points out this line of code: https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/_reloader.py#L96

Let me know if you would like me to provide a minimal demonstration of the bug.

**Comment by untitaker** [comment]
I suppose you are referring to https://github.com/pallets/flask/issues/1420#issuecomment-89769748, but I don't think this problem is fixable.

**Comment by jjb** [comment]
@untitaker why? A limitation at what level?

**Comment by untitaker** [comment]
I don't know a way to get the arguments passed to the Python interpreter, within Python.

**Comment by kennethreitz** [comment]
I don't believe `PYTHONUNBUFFERED` solves this problem at all, actually. At least, not in my experimentation. Python will not, under any circumstances, automatically flush once it writes a full line to stdout/err, like every other language I know of. 

That has historically been the problem with many third-party wrapper tools (Foreman, etc). 

It's possible the source of this issue is unrelated though, as I've been told node-foreman's scanning exhibits more proper behavior with stdout streams from Python applications.

**Comment by jjb** [comment]
fwiw: in my setup it solves my problem very consistently on multiple apps

**Comment by untitaker** [comment]
@kennethreitz Maybe foreman fakes a TTY, I don't know. But `PYTHONUNBUFFERED` and `-u` definetly disable stdout buffering (at least in my tests).

**Comment by kennethreitz** [comment]
Is flushing not a thing when buffering is taken out of the equation?

It's been many years since I've experimented with this — it was when I was trying to replicate pexpect's functionality into a subprocess module "for humans" wrapper.

**Comment by untitaker** [comment]
>Is flushing not a thing when buffering is taken out of the equation?

Yes, I think so.

There appear to be more stdio buffers than Python's internal one BTW, but I really have no idea.

**Comment by kennethreitz** [comment]
> There appear to be more stdio buffers than Python's internal one BTW, but I really have no idea.

That was my impression — that there was another layer of buffering *somewhere* within the system, and that a stdout.flush() is simply required if a simplistic (potentially lazy?) line scanning method is being used in the parent application.

**Comment by davidism** [comment]
This no longer seems to be an issue. I created a basic app with `run_simple(..., use_reloader=True)`, and `heroku local` printed all output as it occurred.

I know you're using `heroku local` and not actually deploying, but unless you're using a different procfile in production that uses Gunicorn, your current configuration is not safe. You should not be running the development server, with or without the reloader, in production.
