### ISSUE TITLE
MemcacheCache argument timeout doesn't work right

### ISSUE THREAD

**Issue by BMan-L** [pallets/werkzeug#921]
cache = MemcachedCache(['127.0.0.1:11211'])                                                                                                                          
    cache.set("key", "value", timeout = 10)
    while True:
        print cache.get("key")
        time.sleep(1)

this code output:
value
value
value
value
None
None
None
None
None
....

I check the code in contrib.cache.MemcacheCache.
found that "timeout = self._normalize_timeout(timeout)" in method "set"
is that necessary?

**Comment by untitaker** [comment]
If I remember correctly, memcached takes an absolute time as timeout (as opposed to other caching backends for Werkzeug), so we need to add it to the current time in that function.

No idea how you're getting the behavior you see. How long does cache.get itself take?

**Comment by BMan-L** [comment]
cache.get() take almost no time because in the same host.
i try replace "cache = MemcachedCache(['127.0.0.1:11211'])" with  "cache = memcache.Client(['127.0.0.1:11211'])" than it work right.

the api for memcached is python-memcached-1.57

**Comment by untitaker** [comment]
Hmm.

* `python-memcached` doesn't seem to do anything fancy to the timeout param: https://github.com/linsomniac/python-memcached/blob/master/memcache.py#L983
* The memcached protocol implies that our implementation is correct: https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L163

I don't think it's a bug in Werkzeug (or even anywhere else) TBH. Technically memcached doesn't guarantee that the key is preserved until the timeout.

**Comment by untitaker** [comment]
BTW the example script you give at the top gives the correct output for me. You sure you're not launching the test script against a "busy" instance?

**Comment by BMan-L** [comment]
i'm not sure....but i'm sure that it output one line per second yesterday, if i set timeout <= 5, it output None in first line. Today i try again to run this script and it work right now, confusing...

**Comment by untitaker** [comment]
Do you mind if I close this issue again until you figure out a solution?

**Comment by BMan-L** [comment]
No, not at all.
