### ISSUE TITLE
Built-in web server vulnerable to memory exaustion

### ISSUE THREAD

**Issue by spanezz** [pallets/werkzeug#936]
Werkzeug's internal HTTP server is not enforcing a maximum line length for the http request line, and is vulnerable to memory exaustion attacks. I'm attaching two scripts that can be used to 
[reproduce](https://github.com/pallets/werkzeug/files/275966/reproduce.zip) the problem.

Run this in one terminal:
```
        $ ulimit -v 3048576
        $ python3 flaskapp.py
         * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
         * Restarting with stat
```
and on another terminal:
```
        $ ./breakit
```
flaskapp.py will die with this MemoryError when the ulimit kicks in:
```
        Exception happened during processing of request from ('127.0.0.1', 53928)
        Traceback (most recent call last):
          File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
            self.process_request(request, client_address)
          File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
            self.finish_request(request, client_address)
          File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
            self.RequestHandlerClass(request, client_address, self)
          File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
            self.handle()
          File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 203, in handle
            rv = BaseHTTPRequestHandler.handle(self)
          File "/usr/lib/python3.5/http/server.py", line 422, in handle
            self.handle_one_request()
          File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 234, in handle_one_request
            self.raw_requestline = self.rfile.readline()
        MemoryError
```
To see the source of the error, compare this code in
`/usr/lib/python3/dist-packages/werkzeug/serving.py`:
```py
    def handle_one_request(self):
        """Handle a single HTTP request."""
        self.raw_requestline = self.rfile.readline()
        if not self.raw_requestline:
            self.close_connection = 1
        elif self.parse_request():
            return self.run_wsgi()
```
With its equivalent code in `/usr/lib/python3.5/http/server.py`:
```py
    def handle_one_request(self):
        """Handle a single HTTP request.

        You normally don't need to override this method; see the class
        __doc__ string for information on how to handle specific HTTP
        commands such as GET and POST.

        """
        try:
            self.raw_requestline = self.rfile.readline(65537)
            if len(self.raw_requestline) > 65536:
                self.requestline = ''
                self.request_version = ''
                self.command = ''
                self.send_error(HTTPStatus.REQUEST_URI_TOO_LONG)
                return
            if not self.raw_requestline:
                self.close_connection = True
                return
            if not self.parse_request():
                # An error code has been sent, just exit
                return
            mname = 'do_' + self.command
            if not hasattr(self, mname):
                self.send_error(
                    HTTPStatus.NOT_IMPLEMENTED,
                    "Unsupported method (%r)" % self.command)
                return
            method = getattr(self, mname)
            method()
            self.wfile.flush() #actually send the response if not already done.
        except socket.timeout as e:
            #a read or a write timed out.  Discard this connection
            self.log_error("Request timed out: %r", e)
            self.close_connection = True
            return
```

From private conversation, I understand that the built-in server is not supposed to be exposed to the internet, and that security vulnerabilities in it are not considered a priority. I would then suggest to change the [quickstart documentation](http://flask.pocoo.org/docs/0.10/quickstart/#public-server) to not only explicitly warning against `debug=True`, but also to explicitly warning that no effort should be expected of keeping the built-in server free of security vulnerability.

Likewise, [the tutorial](http://flask.pocoo.org/docs/0.10/tutorial/setup/#tutorial-setup) should probably mention that the built-in server is not expected to be safe to use and is supposed to be used only for development.

**Comment by untitaker** [comment]
You're filing a suggestion for Flask's docs against Werkzeug's issue tracker.

Also, I think this is sufficient: http://flask.pocoo.org/docs/dev/deploying/#deployment

**Comment by spanezz** [comment]
That, or a bug in werkzeug, or both, your choice.

**Comment by untitaker** [comment]
The Werkzeug server is already vulnerable to every imaginable kind of DoS. That's not on purpose, but it keeps the code simple, so I guess it is at least known by the author.

We'd be happy to add a note to the docs, but I'm somewhat wary of overloading the quickstart.

**Comment by mitsuhiko** [comment]
I'm going to close this. There is plenty more that is wrong with that server. It's for development purposes only.
