### ISSUE TITLE
SubdomainDispatcherMiddleware?

### ISSUE THREAD

**Issue by asteinlein** [pallets/werkzeug#939]
Werkzeug already has `DispatcherMiddleware` that works on paths. How about providing a built-in `SubdomainDispatcherMiddleware` for similar simple cases?

This seems like such a common case that a default would be useful, IMHO. I'm doing this already, so I can provide a PR if there is interest.

**Comment by untitaker** [comment]
Werkzeug currently contains a lot of very specific things that are only tangentially WSGI-related in `werkzeug.contrib`. The plan is to get rid of as many as possible, and put them into their own packages.

While middlewares are not only in `contrib` and are more closely related to WSGI than e.g `werkzeug.contrib.cache`, there are infinitely many "generally useful" middlewares that one could write and include in Werkzeug.

I'm not claiming that your middleware idea is a bad one! But at the moment I don't think that Werkzeug should "gain weight", so to speak.

**Comment by asteinlein** [comment]
Yes, I see your point and the intention of slimming Werkzeug. However, having `DispatcherMiddleware` not even in `werkzeug.contrib`, but actually in "core" `werkzeug.wsgi`, doesn't seem ideal to me, given the plan you mention to even move stuff out of `contrib`. Has there been any discussion of moving that out of core?

As for `contrib`, has there been made any specific plans of how splitting `contrib` stuff into separate packages will work? I could be interested helping out gathering useful middleware somewhere, if this plan is going to move forward.

**Comment by untitaker** [comment]
It's been agreed upon, but no real planning or action: https://github.com/pallets/werkzeug/issues/4

**Comment by asteinlein** [comment]
Ah, good. Closing this based on your feedback, thanks.
