### ISSUE TITLE
MultiDict.setlist() with empty input causes weird errors

### ISSUE THREAD

**Issue by houseofsuns** [pallets/werkzeug#944]
First an example:

<pre>
>>> from werkzeug.datastructures import MultiDict
>>> d = MultiDict()
>>> d.setlist('a', [])
>>> d['a']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/site-packages/werkzeug/datastructures.py", line 401, in __getitem__
    return dict.__getitem__(self, key)[0]
IndexError: list index out of range
>>> 
</pre>

It's pretty much useless to do this, but it should throw an error on the setlist call not on the lookup.

**Comment by alexpantyukhin** [comment]
I think that it would be good to raise `BadRequestKeyError`  there https://github.com/pallets/werkzeug/blob/master/werkzeug/datastructures.py#L401 when the list of values is empty also.

**Comment by davidism** [comment]
This appears to be fixed.
