### ISSUE TITLE
Request#get_data(as_text=True) does not work with Content-Type/charset

### ISSUE THREAD

**Issue by momijiame** [pallets/werkzeug#947]
The followings are related tickets.
https://github.com/pallets/werkzeug/issues/233
https://github.com/pallets/werkzeug/issues/909
The fundamental cause is same.
Request#charset member is always set UTF-8 now.

The above have been triggering another issue.

Request#get_data(as_text=True) does not work with Content-Type/charset.
Since the method is using Request#charset.
Regardless of the request contains Content-Type header with charset, Content-Body is always decoded by UTF-8.
https://github.com/pallets/werkzeug/blob/0.11.10/werkzeug/wrappers.py#L481

In Flask, Request#get_json() handles appropriately.
Since the method uses Request#mimetype_params['charset'] instead of Request#charset.
https://github.com/pallets/flask/blob/0.11.1/flask/wrappers.py#L150-L154

This is my workaround.

``` python
data = request.get_data()
charset = request.mimetype_params.get('charset') or 'UTF-8'
decoded_data = data.decode(charset, 'replace')
```

The above is instead of this.

``` python
decoded_data = request.get_data(as_text=True)
```

IMHO, Request#get_data() can be fixed in spite of related tickets by using Request#mimetype_params['charset'] instead of Request#charset.

(Reproduction)

1 - Make a encoded file with EUC-JP

```
$ cat << 'EOF' > greeting.txt
こんにちは
EOF
$ nkf -e greeting.txt > greeting.euc.txt
$ nkf --guess greeting.euc.txt
EUC-JP (LF)
```

2 - Make and run a example source

```
$ cat << 'EOF' > getdata1.py 
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Flask
from flask import request

app = Flask(__name__)


@app.route('/', methods=['POST'])
def post():
    return request.get_data(as_text=True)
EOF
$ export FLASK_APP=getdata1.py
$ flask run                   
 * Serving Flask app "getdata1"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

3 - Request which included Content-Type/charset (Garbled characters)

```
$ curl -X POST -H "Content-Type: text/plain; charset=EUC-JP" -d @greeting.euc.txt http://localhost:5000
����ˤ���
```

[EUC-JP characters] -> (UTF-8 decode) -> [Python unicode object] -> (UTF-8 encode) -> [UTF-8 characters (Garbled)]

(Workaround)

1 - Make and run a example source

```
$ cat << 'EOF' > getdata2.py 
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Flask
from flask import request

app = Flask(__name__)


@app.route('/', methods=['POST'])
def post():
    data = request.get_data()
    charset = request.mimetype_params.get('charset') or 'UTF-8'
    return data.decode(charset, 'replace')
EOF
$ export FLASK_APP=getdata2.py
$ flask run
 * Serving Flask app "getdata2"
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

2 - Request which included Content-Type/charset (Okay)

```
$ curl -X POST -H "Content-Type: text/plain; charset=EUC-JP" -d @greeting.euc.txt http://localhost:5000
こんにちは
```

[EUC-JP characters] -> (EUC-JP decode) -> [Python unicode object] -> (UTF-8 encode) -> [UTF-8 characters]

(My environment)

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.5
BuildVersion:   15F34
$ python --version
Python 3.5.1
$ echo $LANG
ja_JP.UTF-8
$ pip list | egrep -i "(flask|werkzeug)"
Flask (0.11)
Werkzeug (0.11.10)
```

**Comment by davidism** [comment]
This is intentional: https://github.com/pallets/werkzeug/issues/909#issuecomment-365578698. We cannot trust a user-supplied codec because Python has no way to tell us if a codec name is a standard text encoding or a Python-specific / custom registered codec (for example, "zip"). If you're willing to take that risk, you can mix in `contrib.wrappers.DynamicCharsetRequestMixin` to your `Request` class, or do something similar with your own list of good codecs.
