### ISSUE TITLE
wrappers.Response should have proper json support

### ISSUE THREAD

**Issue by DoWhileGeek** [pallets/werkzeug#948]
I use the `Requests` library as my goto http library, its fantastic, and makes working with json a breeze. You can imagine the jarring halt when writing tests for `Flask` and having none of those niceties with the werkzeug test client, or `wrapper.Response` objects.

#848 covers the test client `json` argument, In this issue I propose a mixin to add a `json()` method for `wrapper.Response`.

If no one is opposed, I will try and carve out some time for a mixin PR.

**Comment by untitaker** [comment]
Sorry for responding so late.

In https://github.com/pallets/werkzeug/blob/master/werkzeug/contrib/wrappers.py there is already a JSONMixin. As part of #4 it should be merged with Flask's somehow.
