### ISSUE TITLE
Allow CombinedMultiDict.copy()

### ISSUE THREAD

**Issue by Yajo** [pallets/werkzeug#951]
`CombinedMultiDict` is immutable, but does not have a `.copy()` method to get a mutable copy from it. It would be quite useful.

**Comment by nateprewitt** [comment]
I believe you may be looking for the [`.to_dict()`](https://github.com/pallets/werkzeug/blob/ff82fa21297294804e8d1c3203074fec4d292d1d/werkzeug/datastructures.py#L1434) method, which will return a standard python dictionary with the `CombinedMultiDict` contents.

**Comment by Yajo** [comment]
Well I was thinking on getting a mutable MultiDict, with all its api

**Comment by nateprewitt** [comment]
Would passing the returned dictionary to an instantiation of `MultiDict` work for your use case? Otherwise, you'd end up writing `.copy()`/`.to_dict()` methods for every possible output type.

e.g.

```
 foo = MultiDict([('foo', 'bar')])
 baz = MultiDict([('baz', 'qux')])

 immut_dict = CombinedMultiDict([foo, baz])
 mut_dict = MultiDict(immut_dict.to_dict()) 
```

**Comment by davidism** [comment]
`copied_multidict = MultiDict(original_multidict)`

If it was implemented, I'd expect `ImmutableMultiDict.copy` to return another `ImmutableMultiDict`, not sure how useful that would be.

**Comment by Yajo** [comment]
Yes, that would work indeed. Or creating a `MultiDict` and updating it with the others instead of creating a `CombinedMultiDict` directly. My suggestion was just for an enhacement to allow to do that more easily, just like with `ImmutableMultiDict`, but you can close it if you consider it not necessary.

**Comment by davidism** [comment]
It's not clear what the behavior should be. `Combined` is a view of other dicts, what it returns changes as the underlying dicts change. Making a copy would break that expectation. Then again, the current `copy` seems pretty useless. I'm leaning towards changing to `return MultiDict(self)`, but I'll wait a bit.
