### ISSUE TITLE
Werkzeug prints ready message to stdout before it's ready to accept connections

### ISSUE THREAD

**Issue by crdoconnor** [pallets/werkzeug#957]
I have a script which detects via stdout epoll trigger that django runserver_plus is ready to connect to (listening for "Development server is running at http://127.0.0.1:8000/") and then connects directly to the server. I currently have to put a sleep in to get it to work. It seems to take about 50-150ms for it to be ready.

Version of python is 3.4.3, Werkzeug==0.11.10.

**Comment by remram44** [comment]
This looks like a django-extensions issue.

In runserver_plus.py, the message is printed [line 265](https://github.com/django-extensions/django-extensions/blob/af9f78c5935b61afaaadd2a989df2bddfab58f0b/django_extensions/management/commands/runserver_plus.py#L265), then werkzeug.run_simple() is called [line 330](https://github.com/django-extensions/django-extensions/blob/af9f78c5935b61afaaadd2a989df2bddfab58f0b/django_extensions/management/commands/runserver_plus.py#L330).

**Comment by remram44** [comment]
On the other hand, printing this message once werkzeug is ready would require some kind of hook in run_simple() that is called once server is created and before it enters handling loop.

**Comment by untitaker** [comment]
This issue is unfixable, Python's stdlib doesn't provide any APIs for that. There was a similar issue maybe one year ago.

**Comment by remram44** [comment]
It seems to me that @crdoconnor just needs the message printed after listen() but before accept(), so between `make_server()` and `serve_forever()` would do. I'm not sure what more support from stdlib is needed?

**Comment by untitaker** [comment]
Ah I see, in that case it would probably make sense to override `serve_forever` to log the "Listening..." message.

**Comment by davidism** [comment]
I'm not clear what else can change here. The code emits the message after `make_server` (`listen`) and before `serve_forever` as described. But this was the case before this issue was opened.

**Comment by remram44** [comment]
I can verify that the message "Running on http://127.0.0.1:5000/" is now shown after the `listen()` call :+1:

**Comment by davidism** [comment]
Thanks for verifying, I'll close this.
