### ISSUE TITLE
Mindless action in MultiPartParser constructor

### ISSUE THREAD

**Issue by vit1251** [pallets/werkzeug#963]
```python
class MultiPartParser(object):
    def __init__(self, ...):
        self.stream_factory = stream_factory
        ...
        if stream_factory is None:
            stream_factory = default_stream_factory
````

Most likely it occurred after refactoring.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pallets/werkzeug/blob/2e9f5c0d0c1c36b612f6797c00f8c6ac3ba7b1db/werkzeug/formparser.py#L287

good find

**Comment by RonnyPfannschmidt** [comment]
i think there should be a short discussion on how to handle those then someone new can pick it up and make things nice as a first contribution

@mitsuhiko  @untitaker - i would like to see a change of such uses from the if/else to single line statements like `self.foo = default_foo if foo is None else Foo`

if you agree its something a beginner can easily tackle as first contribution

**Comment by alexpantyukhin** [comment]
@RonnyPfannschmidt I think this way it would be good to have the same approach for `self.cls` also ) https://github.com/pallets/werkzeug/blob/2e9f5c0d0c1c36b612f6797c00f8c6ac3ba7b1db/werkzeug/formparser.py#L297
