### ISSUE TITLE
%-encoded / gets included in wrong <path:...> parameter

### ISSUE THREAD

**Issue by mavjop** [pallets/werkzeug#971]
(I reported this in the Flask issue tracker, and @davidism said it should be reported against Werkzeug. He also said he thought it was reported already, but I haven't been able to find an issue precisely matching this problem. If it is in fact a duplicate of another problem, of course feel free to merge my report or close it and let me know the issue # or URL of the issue this duplicates.)

Problem description:

> In a URL with two path:... type arguments (both need to accept URL-path-encoded data) next to each other, a %2F (encoded /) gets included in the wrong parameter.

Versions:

> Python 2.7.11
> Flask 0.11
> Werkzeug 0.11.10

Request URL:
`http://localhost:5000/api/v1/entry/foo.com/%2Fbar%2Fbaz/block/12345/get`

Result:
`{"this_is_a_test": "XXX this is test code, not a real thing", "path": "bar/baz", "name": "foo.com/"}`

That is:

> name: foo.com/
> path: bar/baz

Expected Result:
`{"this_is_a_test": "XXX this is test code, not a real thing", "path": "/bar/baz", "name": "foo.com"}`

That is:

> name: foo.com
> path: /bar/baz

The code:

```
# The special modifier "path" as in "<path:somevariablename>" means
# "somevariablename" may be URL path encoded data.
@app.route('/api/v1/entry/<path:name>/get')
@app.route('/api/v1/entry/<path:name>/<path:path>/get')
def get_entry(name, path=None, methods=['GET']):
    name = urllib.unquote(name)

    if path is not None:
        path = urllib.unquote(path)

    return json.dumps({
        'this_is_a_test': 'XXX this is test code, not a real thing',
        'name': name,
        'path': path,
    })
```

**Comment by mavjop** [comment]
(For reference, the issue I posted in the Flask issue tracker was https://github.com/pallets/flask/issues/1972.)

**Comment by edk0** [comment]
`<path>` accepts all slashes, not just encoded ones. It can't tell the difference between `%2F` and `/` by design of WSGI.
