### ISSUE TITLE
Add libmc support

### ISSUE THREAD

**Issue by dongweiming** [pallets/werkzeug#982]
[Libmc](https://github.com/douban/libmc) is now the fastest Memcached client implementation, powering all web traffics in [douban.com](http://www.alexa.com/siteinfo/douban.com). I want add libmc support to `werkzeug.contrib.cache.MemcachedCache`

@untitaker @mitsuhiko, What do you think of this?

**Comment by untitaker** [comment]
Totally fine by me, however I'd also like to modify the tests such that all memcached clients are tested (not just one like it is right now).

**Comment by dongweiming** [comment]
@untitaker ok. I had prepared a PR: https://github.com/pallets/werkzeug/pull/981

**Comment by dongweiming** [comment]
When refactoring the test for memcached clients, I can help you do something fo libmc

**Comment by untitaker** [comment]
I took a look at the code and realized it is quite a lot of effort to properly refactor this:

* If we keep adding new libraries, we should remove the library-specific logic from the testsuite. Currently we have a try-except chain in `contrib.cache`, **as well as** the testsuite itself.
* All libraries should be tested. This requires a lot of new test environments, no idea how to express that in tox elegantly.

**Comment by davidism** [comment]
Moved refactor discussion to new issue. Merged the corresponding request since a refactor is out of scope for that.
